// scripts/write-version.mjs
// 单一版本真相源：读取仓库根 version.json，构建期生成：
//   - src/version.ts      （前端 APP_VERSION，被 SettingsView 读取）
//   - native/version.h     （native APP_VER_STR / APP_VER_MAJOR/MINOR/PATCH，被 main.cpp 与 app.rc 引用）
// 通过 pnpm 的 prebuild / predev 生命周期自动触发；也可单独 `node scripts/write-version.mjs`。
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(resolve(root, 'version.json'), 'utf8'));
const v = String(pkg.version || '0.0.0');
const parts = v.split('.').map((n) => parseInt(n, 10) || 0);
const major = parts[0] || 0;
const minor = parts[1] || 0;
const patch = parts[2] || 0;

// 前端
mkdirSync(resolve(root, 'src'), { recursive: true });
writeFileSync(
  resolve(root, 'src/version.ts'),
  `// AUTO-GENERATED by scripts/write-version.mjs — 不要手动编辑\n` +
    `export const APP_VERSION = ${JSON.stringify(v)};\n`
);

// native 头（供 main.cpp 与 app.rc 引用）
mkdirSync(resolve(root, 'native'), { recursive: true });
writeFileSync(
  resolve(root, 'native/version.h'),
  `// AUTO-GENERATED by scripts/write-version.mjs — 不要手动编辑\n` +
    `#pragma once\n` +
    `#define APP_VER_STR "${v}"\n` +
    `#define APP_VER_MAJOR ${major}\n` +
    `#define APP_VER_MINOR ${minor}\n` +
    `#define APP_VER_PATCH ${patch}\n`
);

console.log(`[write-version] APP_VERSION = ${v}`);
