#include "custom_steam_library_test_runtime.h"
#include <iostream>
static void check(bool ok,const char* why){if(!ok)throw std::runtime_error(why);}
static void mustFail(const std::function<void()>& f){bool bad=false;try{f();}catch(const std::exception&){bad=true;}check(bad,"Expected controlled failure");}
static json record(int requested=620,int canonical=620,const std::string& type="game",const std::string& name="Portal 2"){
    return {{std::to_string(requested),{{"success",true},{"data",{{"steam_appid",canonical},{"name",name},{"type",type}}}}}};
}
static HttpResponse payload(const json& doc){const auto t=doc.dump();return {200,{},std::vector<unsigned char>(t.begin(),t.end())};}
static std::vector<unsigned char> png(const fs::path& path,int width=600,int height=900){
    (void)artworkInspectionGdiPlusToken();fs::create_directories(path.parent_path());Gdiplus::Bitmap image(width,height,PixelFormat32bppARGB);Gdiplus::Graphics g(&image);g.Clear(Gdiplus::Color(255,30,60,90));check(image.Save(path.c_str(),&pngEncoderClsid(),nullptr)==Gdiplus::Ok,"Fixture PNG save failed");return readBinaryFile(path);
}
int wmain(int argc,wchar_t** argv){try{
    check(argc==2||argc==3,"Pass fresh Build fixture root and optional Steam evidence root");const auto root=fs::absolute(argv[1]);
    const auto build=fs::absolute(fs::path(__FILE__).parent_path()/L".."/L".."/L".."/L"Build").lexically_normal();
    check(canonicalPathKey(root).starts_with(canonicalPathKey(build)+"\\")&&!fs::exists(root),"Unsafe/reused fixture root");fs::create_directories(root);
    // Avoid live DNS / local transparent accelerator probes, including on a
    // machine with Steam accelerator Hosts mappings. Actual policy is tested
    // with a deterministic direct route and a fail-closed raw HTTP backend.
    g_steamAcceleratorStatus.checked=true;g_steamAcceleratorStatus.state="fixture-direct";
    for(const auto* host:{"store.steampowered.com","steamstore-a.akamaihd.net","api.steampowered.com","shared.steamstatic.com","cdn.cloudflare.steamstatic.com"})g_steamAcceleratorStatus.localHostCache[host]=false;
    json cases=json::array();
    auto test=[&](const char* name,const std::function<void(const fs::path&)>& action){const auto p=root/std::to_wstring(cases.size());fs::create_directories(p);g_workerDataRoot=p/L"data";g_fastMetadataMode=false;artworkTestTransport={};selftestMoveFault={};
        try{action(p);cases.push_back({{"name",name},{"passed",true}});}catch(const std::exception& e){cases.push_back({{"name",name},{"passed",false},{"error",e.what()}});}artworkTestTransport={};selftestMoveFault={};};
    test("steam-exact-valid-appdetails",[](const auto&){auto r=steamDetailsRecord(record(),620);check(r.requestedAppId==620&&r.canonicalAppId==620&&r.type=="game","Valid Steam record rejected");});
    for(const auto& pair:std::vector<std::pair<std::string,json>>{{"null",nullptr},{"array",json::array()},{"string","error"},{"number",42},{"empty-object",json::object()},{"unrelated-app",record(570,570,"game","Dota 2")},{"failed-app",{{"620",{{"success",false}}}}},{"data-null",{{"620",{{"success",true},{"data",nullptr}}}}},{"envelope-array",{{"620",json::array()}}}}){
        const auto name="steam-rejects-"+pair.first;test(name.c_str(),[&](const auto&){mustFail([&]{steamDetailsRecord(pair.second,620);});});}
    for(const auto& bad:std::vector<json>{nullptr,"true",1,0,json::array(),json::object()})test("steam-success-type-is-strict",[&](const auto&){auto r=record();r["620"]["success"]=bad;mustFail([&]{steamDetailsRecord(r,620);});});
    for(const auto& bad:std::vector<json>{nullptr,"620",0,-1,620.5,18446744073709551615ull,json::object()})test("steam-canonical-id-type-and-range",[&](const auto&){auto r=record();r["620"]["data"]["steam_appid"]=bad;mustFail([&]{steamDetailsRecord(r,620);});});
    test("steam-missing-id-not-filled-from-request",[](const auto&){auto r=record();r["620"]["data"].erase("steam_appid");mustFail([&]{steamDetailsRecord(r,620);});});
    for(const auto* key:{"name","type"})for(const auto& bad:std::vector<json>{nullptr,12,json::array(),""})test("steam-title-and-content-type-are-strict",[&](const auto&){auto r=record();r["620"]["data"][key]=bad;mustFail([&]{steamDetailsRecord(r,620);});});
    for(const auto* type:{"dlc","demo","tool","music","soundtrack"})test("steam-related-content-is-not-coerced-to-game",[&](const auto&){auto r=steamDetailsRecord(record(620,620,type),620);check(r.type==type&&r.type!="game","Related content became base game");});
    test("steam-alias-requires-independent-canonical-query",[](const auto&){int requests=0;artworkTestTransport=[&](const auto&,const auto&,const auto& url,const auto&){++requests;return payload(url.find("appids=621")!=std::string::npos?record(621,621):record(620,621));};json log=json::array();auto r=fetchSteamDetails(620,log);check(requests==2&&r.canonicalAppId==621&&r.requestedAppId==620&&fs::exists(steamDetailsCachePath(621))&&!fs::exists(steamDetailsCachePath(620)),"Alias not verified independently");});
    test("steam-alias-canonical-title-disagreement-rejected",[](const auto&){artworkTestTransport=[](const auto&,const auto&,const auto& url,const auto&){return payload(url.find("appids=621")!=std::string::npos?record(621,621,"game","Other Game"):record(620,621));};json log=json::array();mustFail([&]{fetchSteamDetails(620,log);});check(!fs::exists(steamDetailsCachePath(621)),"Unverified alias cached");});
    test("steam-alias-cycle-rejected",[](const auto&){artworkTestTransport=[](const auto&,const auto&,const auto& url,const auto&){return payload(url.find("appids=621")!=std::string::npos?record(621,620):record(620,621));};json log=json::array();mustFail([&]{fetchSteamDetails(620,log);});});
    test("steam-alias-failed-canonical-query-rejected",[](const auto&){artworkTestTransport=[](const auto&,const auto&,const auto& url,const auto&){return url.find("appids=621")!=std::string::npos?HttpResponse{404}:payload(record(620,621));};json log=json::array();mustFail([&]{fetchSteamDetails(620,log);});});
    test("steam-cache-invalid-canonical-is-cache-miss",[](const auto&){writeJsonAtomic(steamDetailsCachePath(620),{{"schemaVersion",1},{"steamAppId",620},{"fetchedAt",unixTimeMs()},{"data",record(620,621)["620"]["data"]}});uint64_t at=0;check(!loadSteamDetailsCache(620,at),"Mismatched cache accepted");});
    test("steam-cache-corrupt-json-is-cache-miss",[](const auto&){const auto p=steamDetailsCachePath(620);writeAtomic(p,{'{'});uint64_t at=0;check(!loadSteamDetailsCache(620,at),"Broken JSON cache accepted");});
    test("steam-cache-null-fetched-at-is-cache-miss",[](const auto&){writeJsonAtomic(steamDetailsCachePath(620),{{"schemaVersion",1},{"steamAppId",620},{"fetchedAt",nullptr},{"data",record()["620"]["data"]}});uint64_t at=0;check(!loadSteamDetailsCache(620,at),"Invalid timestamp accepted");});
    test("steam-cache-future-timestamp-is-not-used",[](const auto&){writeJsonAtomic(steamDetailsCachePath(620),{{"schemaVersion",1},{"steamAppId",620},{"fetchedAt",unixTimeMs()+60000},{"data",record()["620"]["data"]}});int calls=0;artworkTestTransport=[&](const auto&,const auto&,const auto&,const auto&){++calls;return payload(record());};json log=json::array();fetchSteamDetails(620,log);check(calls==1,"Future cache granted hit");});
    test("steam-cache-valid-hit-does-not-contact-network",[](const auto&){saveSteamDetailsCache(steamDetailsRecord(record(),620));json log=json::array();auto r=fetchSteamDetails(620,log);check(r.canonicalAppId==620&&log.size()==1&&log[0]["cacheHit"]==true,"Valid cache not used");});
    auto sequence=[&](const std::vector<HttpResponse>& responses,json& log,size_t max=1000){size_t index=0;artworkTestTransport=[&,index](const auto&,const auto&,const auto&,const auto&)mutable{const auto n=(std::min)(index++,responses.size()-1);return responses[n];};return httpRequestWithRetry("fixture","GET","https://fixture.invalid/test",L"",{},max,false,"",&log);};
    test("http-429-then-success-uses-production-retry-policy",[&](const auto&){json log=json::array();auto r=sequence({HttpResponse{429},payload(record())},log);check(r.status==200&&log.size()==2&&log[0]["reconnectScheduled"]==true,"429 not retried");});
    test("http-empty-503-then-success",[&](const auto&){json log=json::array();auto r=sequence({HttpResponse{503},payload(record())},log);check(r.status==200&&log.size()==2,"503 not retried");});
    test("http-persistent-503-is-bounded",[&](const auto&){json log=json::array();auto r=sequence({HttpResponse{503}},log);check(r.status==503&&log.size()==HTTP_MAX_ATTEMPTS,"503 retry unbounded");});
    test("http-404-is-not-retried",[&](const auto&){json log=json::array();auto r=sequence({HttpResponse{404}},log);check(r.status==404&&log.size()==1,"404 needlessly retried");});
    test("http-retry-after-respected-and-capped",[&](const auto&){json log=json::array();auto response=HttpResponse{429};response.retryAfterMs=2000;auto r=sequence({response,payload(record())},log);check(r.status==200&&log[0]["retryDelayMs"].get<int>()>=2000,"Retry-After ignored");check(parseRetryAfterMs(L"9999999999999999999999999")==HTTP_MAX_RETRY_AFTER_MS&&parseRetryAfterMs(L"bad")==0&&parseRetryAfterMs(L"-2")==0&&parseRetryAfterMs(L"2")==2000,"Retry-After parse invalid");});
    test("http-transport-timeout-retry-and-success",[](const auto&){int count=0;artworkTestTransport=[&](const auto&,const auto&,const auto&,const auto&){if(++count==1)throw HttpTransportError("fixture timeout",ERROR_WINHTTP_TIMEOUT,true);return payload(record());};json log=json::array();auto r=httpRequestWithRetry("fixture","GET","https://fixture.invalid/test",L"",{},1000,false,"",&log);check(r.status==200&&count==2&&log[0]["win32Error"]==ERROR_WINHTTP_TIMEOUT,"Transport retry bypassed");});
    test("http-invalid-data-fails-without-retry",[](const auto&){int count=0;artworkTestTransport=[&](const auto&,const auto&,const auto&,const auto&)->HttpResponse{++count;throw HttpTransportError("fixture invalid",ERROR_INVALID_DATA,false);};json log=json::array();mustFail([&]{httpRequestWithRetry("fixture","GET","https://fixture.invalid/test",L"",{},1000,false,"",&log);});check(count==1,"Permanent transport fault retried");});
    test("http-content-length-over-limit-rejected",[&](const auto&){json log=json::array();auto r=HttpResponse{200};r.expectedBytes=1001;mustFail([&]{sequence({r},log);});check(log.size()==1,"Oversized declaration retried");});
    test("http-actual-body-over-limit-rejected",[&](const auto&){json log=json::array();auto r=HttpResponse{200};r.body.resize(1001);mustFail([&]{sequence({r},log);});});
    test("http-200-html-is-not-json",[](const auto&){artworkTestTransport=[](const auto&,const auto&,const auto&,const auto&){std::string s="<html>Steam error</html>";return HttpResponse{200,{},std::vector<unsigned char>(s.begin(),s.end())};};json log=json::array();mustFail([&]{getJson("https://fixture.invalid/test","fixture",&log);});});
    test("http-200-empty-json-is-not-success",[](const auto&){artworkTestTransport=[](const auto&,const auto&,const auto&,const auto&){return HttpResponse{200};};json log=json::array();mustFail([&]{getJson("https://fixture.invalid/test","fixture",&log);});});
    test("fixture-raw-http-is-forbidden",[](const auto&){mustFail([]{httpRequest("GET","https://store.steampowered.com/",L"",{},1000,false,"",GetTickCount64()+1000);});});
    test("image-real-png-decodes",[](const auto& p){auto b=png(p/L"valid.png");auto i=inspectImage(b);check(i&&i->width==600&&i->height==900,"Valid PNG rejected");});
    test("image-header-only-png-rejected",[](const auto& p){auto b=png(p/L"valid.png");b.resize(24);check(!inspectImage(b),"Header-only fake image accepted");});
    test("image-truncated-png-rejected",[](const auto& p){auto b=png(p/L"valid.png");b.resize(45);check(!inspectImage(b),"Truncated image accepted");});
    test("image-html-with-jpg-extension-rejected",[](const auto&){std::string s="<html>200 OK</html>";check(!inspectImage(std::vector<unsigned char>(s.begin(),s.end())),"HTML accepted as artwork");});
    test("image-decompression-bomb-header-rejected",[](const auto& p){auto b=png(p/L"valid.png");b[16]=0x7f;b[17]=0xff;b[18]=0xff;b[19]=0xff;check(!inspectImage(b),"Huge dimensions accepted");});
    test("image-minimal-jpeg-sof-is-not-decodable",[](const auto&){std::vector<unsigned char> b={0xff,0xd8,0xff,0xc0,0,17,8,3,0x84,2,0x58,3,1,0x11,0,2,0x11,0,3,0x11,0,0xff,0xd9};check(!inspectImage(b),"SOF without pixels accepted");});
    test("image-real-hero-ratio-and-resolution",[](const auto& p){auto b=png(p/L"hero.png",3840,1240);auto i=inspectImage(b);check(i&&i->width==3840&&i->height==1240,"Steam official full hero shape rejected");});
    test("atomic-write-transient-denial-keeps-and-retries",[](const auto& p){const auto target=p/L"config.json";writeAtomic(target,{'o','l','d'});int attempts=0;selftestMoveFault=[&](const auto&,const auto& to){return to==target.wstring()&&++attempts<=2?ERROR_ACCESS_DENIED:0;};writeAtomic(target,{'n','e','w'});check(attempts==3&&readBinaryFile(target)==std::vector<unsigned char>({'n','e','w'}),"Worker atomic retry failed");});
    test("atomic-write-disk-fault-keeps-original",[](const auto& p){const auto target=p/L"config.json";writeAtomic(target,{'o','l','d'});selftestMoveFault=[&](const auto&,const auto& to){return to==target.wstring()?ERROR_DISK_FULL:0;};mustFail([&]{writeAtomic(target,{'n','e','w'});});check(readBinaryFile(target)==std::vector<unsigned char>({'o','l','d'}),"Original lost on disk fault");for(const auto& e:fs::directory_iterator(p))check(e.path().filename().wstring().find(L".yeman-tmp-")==std::wstring::npos,"Staging file leaked");});
    test("steam-200-external-redirect-cannot-grant-identity",[](const auto&){artworkTestTransport=[](const auto&,const auto&,const auto&,const auto&){auto r=payload(record());r.finalUrl="https://untrusted.invalid/api/appdetails?appids=620";return r;};json log=json::array();mustFail([&]{fetchSteamDetails(620,log);});check(!fs::exists(steamDetailsCachePath(620)),"External redirect cached as Steam authority");});
    test("steam-final-url-rejects-downgrade-and-host-lookalikes",[](const auto&){for(const auto* url:{"http://store.steampowered.com/api/appdetails","https://store.steampowered.com.untrusted.invalid/api/appdetails","https://store.steampowered.com/error","https://untrusted.invalid/api/appdetails"})check(!trustedSteamMetadataFinalUrl("https://store.steampowered.com/api/appdetails?appids=620",url),"Untrusted URL accepted");check(trustedSteamMetadataFinalUrl("https://store.steampowered.com/api/appdetails?appids=620","https://store.steampowered.com/api/appdetails?appids=620"),"Official Steam URL rejected");});
    test("random-malformed-appdetails-1000-combinations-never-verify",[](const auto&){const std::vector<json> bad={nullptr,0,"",json::array(),json::object()};for(int i=0;i<1000;++i){auto r=record();if(i%3==0)r["620"]["success"]=bad[(i/3)%bad.size()];else if(i%3==1)r["620"]["data"]["steam_appid"]=bad[(i/3)%bad.size()];else r["620"]["data"]["type"]=bad[(i/3)%bad.size()];try{steamDetailsRecord(r,620);}catch(...){continue;}throw std::runtime_error("Malformed combination accepted at i="+std::to_string(i)+" value="+r.dump());}});
    test("atomic-write-and-read-beyond-max-path",[](const auto& p){auto dir=p;for(int i=0;i<8;++i)dir/=L"long-artwork-metadata-fixture-012345";const auto target=dir/L"manifest.json";check(target.wstring().size()>300,"Long-path fixture too short");writeJsonAtomic(target,{{"ok",true},{"id",620}});const auto b=readBinaryFile(target);check(json::parse(b.begin(),b.end())["id"]==620,"Long-path JSON did not roundtrip");writeJsonAtomic(target,{{"ok",true},{"id",570}});const auto replaced=readBinaryFile(target);check(json::parse(replaced.begin(),replaced.end())["id"]==570,"Long-path replacement failed");});
    test("io-path-supports-long-unc-without-changing-persisted-path",[](const auto&){const auto original=fs::path(L"\\\\server\\share")/std::wstring(260,L'a')/L"image.png";const auto result=custom_steam_library::ioPath(original).wstring();check(result.starts_with(L"\\\\?\\UNC\\server\\share\\"),"UNC IO prefix malformed");check(!original.wstring().starts_with(L"\\\\?\\"),"Original persisted path was mutated");});
    if(argc==3){const auto evidence=fs::path(argv[2]);for(const int id:{620,570})test("live-captured-steam-appdetails-parses",[&](const auto&){const auto b=readBinaryFile(evidence/(L"app-"+std::to_wstring(id)+L".json"));auto r=steamDetailsRecord(json::parse(b.begin(),b.end()),id);check(r.canonicalAppId==id&&r.type=="game","Real Steam sample rejected");});test("live-captured-steam-invalid-app-is-rejected",[&](const auto&){const auto b=readBinaryFile(evidence/L"app-999999999.json");mustFail([&]{steamDetailsRecord(json::parse(b.begin(),b.end()),999999999);});});}

    test("builtin-steam-tool-rejected-before-network-or-cache",[](const auto&){
        int calls=0;artworkTestTransport=[&](const auto&,const auto&,const auto&,const auto&)->HttpResponse{++calls;return payload(record(228980,228980,"game","Steamworks Common Redistributables"));};
        json attempts=json::array();mustFail([&]{fetchSteamDetails(228980,attempts);});check(calls==0&&attempts.empty(),"Excluded tool started network");
    });
    test("builtin-steam-tool-forged-game-record-rejected",[](const auto&){
        mustFail([&]{steamDetailsRecord(record(228980,228980,"game","Renamed Tool"),228980);});
        mustFail([&]{steamDetailsRecord(record(620,228980,"game","Renamed Tool"),620);});
        mustFail([&]{steamDetailsRecord(record(620,620,"game","Steamworks Common Redistributables"),620);});
    });
    test("builtin-steam-tool-old-verified-identity-is-denied",[](const auto&){
        json match={{"appId",228980},{"primaryProvider","steam"},{"identityStatus","verified"},{"steamVerificationStatus","steam-verified"},{"resolverVersion",STEAM_RESOLVER_VERSION}};
        check(!custom_steam_library::verifiedSteamIdentityMatch(match),"Cached tool is verified game");
        match["appId"]=620;check(custom_steam_library::verifiedSteamIdentityMatch(match),"Real cached game rejected");
    });
    size_t failures=0;for(const auto& t:cases)if(!t["passed"].get<bool>())++failures;json report={{"allPassed",failures==0},{"caseCount",cases.size()},{"failedCount",failures},{"cases",cases},{"realSteamFilesModified",false},{"liveNetworkUsedByFixtures",false}};selftestMoveFault={};writeJsonAtomic(root/L"summary.json",report);std::cout<<report.dump(2)<<"\n";return failures?1:0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}
