#include <functional>
#include "custom_steam_library_storage_isolation.h"
#define wWinMain hostMainUnusedInSelftest
#include "../native/custom-steam-library/workspace_host.cpp"
#undef wWinMain
#include <iostream>
static void require(bool value,const char* why){if(!value)throw std::runtime_error(why);}
static void writeFixtureJson(const fs::path& p, const json& value){writeJsonWithLocalBackup(p,value,false);}
static void fixtureFile(const fs::path& p){fs::create_directories(p.parent_path());std::ofstream stream(p,std::ios::binary);stream<<"fixture; local only";}
int wmain(int argc,wchar_t** argv){
    try{
        require(argc==2,"Pass a new Build fixture root");const auto root=fs::absolute(argv[1]);
        const auto build=fs::absolute(fs::path(__FILE__).parent_path()/L".."/L".."/L".."/L"Build").lexically_normal();
        auto rootText=normalizedPathKey(root),buildText=normalizedPathKey(build);
        if(buildText.back()!=L'\\')buildText+=L"\\";
        require(rootText.starts_with(buildText)&&!fs::exists(root),"Unsafe/reused fixture root");fs::create_directories(root);
        json cases=json::array();
        auto test=[&](const char* name,const std::function<void()>& action){try{action();cases.push_back({{"name",name},{"passed",true}});}catch(const std::exception& e){cases.push_back({{"name",name},{"passed",false},{"error",e.what()}});}};
        g_dataRoot=root/L"data";const auto exe=root/L"Game"/L"Game.exe";fixtureFile(exe);
        const auto tall=g_dataRoot/L"artwork"/L"game"/L"tall.png",longCover=g_dataRoot/L"artwork"/L"game"/L"long.png",hero=g_dataRoot/L"artwork"/L"game"/L"hero.png";
        for(const auto& p:{tall,longCover,hero})fixtureFile(p);
        const auto manifestPath=tall.parent_path()/L"manifest.json";
        json manifest={{"exe",toUtf8(exe.wstring())},{"ok",false},{"successCount",0},{"match",{{"appId",nullptr},{"igdbId",7},{"primaryProvider","playnite-igdb"},{"identityStatus","metadata-verified"},{"contentRelation",nullptr}}},{"artwork",json::array({{{"type","tall"},{"ok",true},{"portableFile",toUtf8(tall.wstring())},{"provider","playnite-igdb"}},{{"type","long"},{"ok",true},{"portableFile",toUtf8(longCover.wstring())},{"provider","baidu-image"}},{{"type","hero"},{"ok",true},{"portableFile",toUtf8(hero.wstring())},{"provider","playnite-igdb"}}})}};
        writeFixtureJson(manifestPath,manifest);
        json plan={{"items",json::array({{{"primaryExecutable",toUtf8(exe.wstring())},{"status","needs-steam-verification"}}})}};
        json snapshot={{"library",{{"games",json::array({{{"primaryExecutable",toUtf8(exe.wstring())},{"gameDirectory",toUtf8(exe.parent_path().wstring())},{"directoryName","Fixture Game"},{"status","ready"}}})}}},{"manualOverrides",{{"items",json::object()}}}};
        test("missing-manifest-link-is-recovered-without-steamid",[&]{auto p=plan;attachArtworkPreviews(p);require(p["items"][0]["artworkPreview"].size()==3,"Portable artwork not attached");require(p["items"][0]["artworkManifest"]==toUtf8(manifestPath.wstring()),"Manifest link not repaired");});
        test("igdb-baidu-preview-is-independent-of-top-level-count",[&]{auto p=plan;attachArtworkPreviews(p);require(p["items"][0]["artworkPreview"]["long"]["provider"]=="baidu-image","Baidu preview hidden");});
        test("visual-complete-is-not-steam-identity",[&]{auto p=buildLocalSteamPlanSnapshot(snapshot);attachArtworkPreviews(p);require(p["items"][0]["status"]=="waiting-steam-verification","Visual result granted import-ready identity");require(p["summary"]["readyToAdd"]==0,"No-ID automatically importable");require(p["items"][0]["artworkPreview"].size()==3,"Waiting item has no images");});
        const auto manualCover=g_dataRoot/L"artwork"/L"overrides"/L"cover.png";fixtureFile(manualCover);
        const json overrides={{"items",{{toUtf8(exe.wstring()),{{"cover",{{"file",toUtf8(manualCover.wstring())}}},{"artworkProtection",{{"cover","manual"}}}}}}}};
        test("one-manual-slot-does-not-skip-game-queue",[&]{require(!manualArtworkProtected(overrides,toUtf8(exe.wstring())),"Partial manual edit blocks automatic queue");});
        test("missing-manual-file-does-not-lock-queue",[&]{auto o=overrides;o["items"][toUtf8(exe.wstring())]["cover"]["file"]=toUtf8((root/L"missing.png").wstring());require(!manualArtworkProtected(o,toUtf8(exe.wstring())),"Missing manual file blocks automatic queue");});
        test("manual-preview-wins-only-own-slot",[&]{writeFixtureJson(g_dataRoot/L"config"/L"manual-overrides.json",overrides);auto p=plan;attachArtworkPreviews(p);const auto a=p["items"][0]["artworkPreview"];require(a["tall"]["source"]=="manual"&&a["long"]["source"]=="automatic"&&a["hero"]["source"]=="automatic","Slot priority is not independent");});
        test("deleted-slot-does-not-show-stale-auto-image",[&]{auto o=overrides;o["items"][toUtf8(exe.wstring())]["artworkProtection"]["cover"]="deleted";writeFixtureJson(g_dataRoot/L"config"/L"manual-overrides.json",o);auto p=plan;attachArtworkPreviews(p);require(!p["items"][0]["artworkPreview"].contains("tall")&&p["items"][0]["artworkPreview"].contains("hero"),"Deleted slot reappeared");});
        test("deleted-slots-stop-auto-retry-but-remain-empty",[&]{auto a=hostArtworkReadiness(manifest,{{"artworkProtection",{{"cover","deleted"}}}});require(!a["tall"].get<bool>()&&a["automaticSlotsComplete"].get<bool>(),"Deleted slot repeatedly scheduled");});
        test("all-explicit-deletions-protect-all-slots",[&]{json o={{"items",{{toUtf8(exe.wstring()),{{"artworkProtection",{{"cover","deleted"},{"long","deleted"},{"wallpaper","deleted"}}}}}}}};require(manualArtworkProtected(o,toUtf8(exe.wstring())),"Full manual opt-out not protected");});
        test("unverified-steam-number-is-not-identity-authority",[&]{auto m=manifest;m["match"]={{"appId",77},{"primaryProvider","steam"},{"steamVerificationStatus",nullptr}};writeFixtureJson(manifestPath,m);auto p=buildLocalSteamPlanSnapshot(snapshot);require(p["summary"]["readyToAdd"]==0,"Unverified AppID granted readiness");writeFixtureJson(manifestPath,manifest);});
        test("bad-manifest-link-cannot-attach-another-game",[&]{auto p=plan;const auto other=g_dataRoot/L"artwork"/L"other"/L"manifest.json";auto m=manifest;m["exe"]=toUtf8((root/L"Other"/L"Game.exe").wstring());writeFixtureJson(other,m);p["items"][0]["artworkManifest"]=toUtf8(other.wstring());attachArtworkPreviews(p);require(p["items"][0]["artworkManifest"]==toUtf8(manifestPath.wstring()),"Wrong game's manifest accepted");});
        test("manual-only-readiness-works-without-manifest",[&]{const auto a=hostArtworkReadiness(json::object(),{{"cover",{{"file",toUtf8(tall.wstring())}}},{"wallpaper",{{"file",toUtf8(hero.wstring())}}}});require(a["minimumComplete"].get<bool>(),"Manual-only images need manifest");});
        const json joined={{"gameDirectory",toUtf8(exe.parent_path().wstring())},{"primaryExecutable",toUtf8(exe.wstring())},{"status","already-in-steam"},{"shortAppId","2388972698"},{"suggestedName","My Custom Shortcut"},{"existingSteamArtwork",{{"hero",toUtf8(hero.wstring())}}}};
        const json ownership={{"libraryState",toUtf8((g_dataRoot/L"state"/L"library-scan.json").wstring())},{"items",json::array({joined})}};
        test("artwork-refresh-retains-joined-shortcut-entire-row",[&]{auto p=buildLocalSteamPlanSnapshot(snapshot,ownership);require(p["items"][0]==joined,"Joined shortcut was reverified or lost grid/identity");require(p["summary"]["alreadyInSteam"]==1&&p["summary"]["needsSteamVerification"]==0,"Joined summary moved to needs-processing");require(steamPlanItemAlreadyOwned(p["items"][0]),"Automatic queue would scrape joined game");});
        test("advisory-scan-classification-cannot-demote-owned-shortcut",[&]{auto s=snapshot;s["library"]["games"][0]["status"]="unrecognized-tool";s["library"]["games"][0]["contentType"]="non-game";const auto p=buildLocalSteamPlanSnapshot(s,ownership);require(p["items"][0]==joined&&p["summary"]["alreadyInSteam"]==1,"Advisory PE classification demoted an owned shortcut");});
        test("added-shortcut-without-store-id-stays-owned",[&]{auto o=ownership;o["items"][0]["status"]="added-to-steam";const auto p=buildLocalSteamPlanSnapshot(snapshot,o);require(p["items"][0]["status"]=="added-to-steam","No-ID added shortcut lost ownership");});
        test("mixed-refresh-keeps-joined-and-applies-new-artwork",[&]{auto s=snapshot;auto other=s["library"]["games"][0];other["gameDirectory"]=toUtf8((root/L"Other").wstring());other["primaryExecutable"]=toUtf8((root/L"Other"/L"Other.exe").wstring());fixtureFile(root/L"Other"/L"Other.exe");s["library"]["games"].push_back(other);auto p=buildLocalSteamPlanSnapshot(s,ownership);attachArtworkPreviews(p);require(p["items"][0]["status"]=="already-in-steam"&&p["items"][0]["artworkPreview"].contains("hero"),"Mixed refresh moved joined game or hid artwork");require(!steamPlanItemAlreadyOwned(p["items"][1]),"Ownership leaked to another game");});
        test("authoritative-shortcut-removal-is-not-sticky",[&]{auto o=ownership;o["items"]=json::array();const auto p=buildLocalSteamPlanSnapshot(snapshot,o);require(!steamPlanItemAlreadyOwned(p["items"][0]),"Removed shortcut remained joined forever");});
        test("changed-primary-exe-does-not-inherit-shortcut-ownership",[&]{auto s=snapshot;s["library"]["games"][0]["primaryExecutable"]=toUtf8((exe.parent_path()/L"New.exe").wstring());fixtureFile(exe.parent_path()/L"New.exe");const auto p=buildLocalSteamPlanSnapshot(s,ownership);require(!steamPlanItemAlreadyOwned(p["items"][0]),"Different EXE inherited ownership");});
        test("different-directory-or-library-does-not-inherit-ownership",[&]{auto o=ownership;o["items"][0]["gameDirectory"]=toUtf8(root.wstring());require(!steamPlanItemAlreadyOwned(buildLocalSteamPlanSnapshot(snapshot,o)["items"][0]),"Directory ownership leaked");o=ownership;o["libraryState"]=toUtf8((root/L"foreign"/L"library-scan.json").wstring());require(!steamPlanItemAlreadyOwned(buildLocalSteamPlanSnapshot(snapshot,o)["items"][0]),"Foreign library ownership leaked");});
        test("native-steam-games-remain-excluded-in-artwork-refresh",[&]{auto s=snapshot;s["library"]["games"][0]["steamNative"]=true;s["library"]["games"][0]["nativeSteamAppId"]=620;auto p=buildLocalSteamPlanSnapshot(s,ownership);require(steamPlanItemAlreadyOwned(p["items"][0])&&p["items"][0]["steamNative"].get<bool>(),"Native exclusion lost");});
        test("artwork-slot-wait-does-not-exhaust-provider-budget",[&]{using Clock=ScrapeGameTimeBudget::Clock;const auto now=Clock::time_point{};ScrapeGameTimeBudget b(now);b.suspend(now+std::chrono::seconds(90));b.suspend(now+std::chrono::seconds(100));b.resume(now+std::chrono::seconds(690));require(b.remaining(now+std::chrono::seconds(690))==210000,"Queue wait charged to provider budget");require(b.remaining(now+std::chrono::seconds(800))==100000,"Work budget was reset");b.suspend(now+std::chrono::seconds(900));b.resume(now+std::chrono::seconds(1900));require(b.remaining(now+std::chrono::seconds(1900))==0,"Idle wait revived exhausted budget");});
        test("cancelled-artwork-slot-waiters-exit-without-another-worker-notification",[&]{std::mutex mutex;std::condition_variable cv;int active=4;std::atomic<bool> cancelled{false},jobCancelled{false};std::atomic<int> returned{0};std::vector<std::thread> waiters;for(int i=0;i<12;++i)waiters.emplace_back([&]{if(!acquireScrapeArtworkSlot(mutex,cv,active,4,cancelled,jobCancelled))++returned;});Sleep(40);jobCancelled=true;for(auto& waiter:waiters)waiter.join();require(returned==12&&active==4,"Cancelled waiters acquired slots or remained asleep");});

        const auto grid=root/L"Steam"/L"userdata"/L"fixture"/L"config"/L"grid";
        for(const auto* stem:{L"4000000000p",L"4000000000",L"4000000000_hero"})fixtureFile(grid/(std::wstring(stem)+L".png"));
        auto gridGame=joined;gridGame["primaryExecutable"]=toUtf8((root/L"GridGame"/L"Game.exe").wstring());gridGame["gameDirectory"]=toUtf8((root/L"GridGame").wstring());gridGame["shortAppId"]="4000000000";gridGame["gridDirectory"]=toUtf8(grid.wstring());gridGame["accountId"]="fixture";gridGame.erase("artworkManifest");gridGame.erase("artworkPreview");
        test("all-advisory-refreshes-retain-steam-grid-images",[&]{json p={{"items",json::array({gridGame})}};for(int i=0;i<8;++i){attachWorkspaceArtwork(p,json::object());require(p["items"][0]["artworkPreview"].size()==3,"Advisory refresh blanked Steam artwork");for(const auto* type:{"tall","long","hero"})require(p["items"][0]["artworkPreview"][type]["provider"]=="steam-grid-existing","Wrong preview provider");}});
        test("temporarily-unreadable-steam-grid-retains-local-cache",[&]{auto g=gridGame;g["gridDirectory"]=toUtf8((root/L"UnavailableGrid").wstring());json p={{"items",json::array({g})}};attachWorkspaceArtwork(p,json::object());require(p["items"][0]["artworkPreview"].size()==3,"Unavailable Steam grid hid cached images");});
        test("manual-deletion-blocks-grid-and-cached-artwork",[&]{const auto overrideFile=g_dataRoot/L"config"/L"manual-overrides.json";const auto before=readJson(overrideFile,json::object());writeFixtureJson(overrideFile,{{"items",{{jsonStringOr(gridGame,"primaryExecutable"),{{"artworkProtection",{{"cover","deleted"},{"long","deleted"},{"wallpaper","deleted"}}}}}}}});json p={{"items",json::array({gridGame})}};attachWorkspaceArtwork(p,json::object());require(!p["items"][0].contains("artworkPreview"),"Deleted slot resurrected from Steam grid");writeFixtureJson(overrideFile,before);});
        test("duplicate-exe-plan-has-one-row-and-retains-nested-ownership",[&]{auto s=snapshot;auto nested=s["library"]["games"][0];nested["gameDirectory"]=toUtf8((exe.parent_path()/L"bin").wstring());s["library"]["games"].push_back(nested);auto o=ownership;o["items"][0]["gameDirectory"]=nested["gameDirectory"];const auto p=buildLocalSteamPlanSnapshot(s,o);require(p["items"].size()==1&&steamPlanItemAlreadyOwned(p["items"][0]),"Deduplication lost existing nested shortcut ownership");});


        writeFixtureJson(g_dataRoot/L"config"/L"manual-overrides.json",overrides);
        const json verified={{"appId",4012810},{"storefrontAppId",4012810},{"formalName","STEINS;GATE RE:BOOT"},{"identityStatus","verified"},{"steamVerificationStatus","steam-verified"},{"primaryProvider","steam"},{"resolverVersion","steam-official-fuzzy-global-v4"}};
        const auto identityResult=root/L"identity-output"/L"manifest.json";writeFixtureJson(identityResult,{{"exe",toUtf8(exe.wstring())},{"match",verified},{"metadata",{{"releaseDate","2026-08-19"}}}});
        test("metadata-only-verified-identity-survives-persistence-and-old-visual-manifest",[&]{persistResolvedIdentityCache(identityResult);auto s=snapshot;attachResolvedIdentityCache(s);const auto key=toUtf8(normalizedPathKey(exe));require(s["resolvedIdentities"][key]["steamVerificationStatus"]=="steam-verified","Verified status lost from persisted identity index");const auto p=buildLocalSteamPlanSnapshot(s);require(p["items"][0]["status"]=="ready-to-add"&&p["items"][0]["steamStoreAppId"]==4012810,"Old visual/IGDB manifest masked verified Steam identity");attachWorkspaceArtwork(s["steamPlan"]=p,json::object());require(s["steamPlan"]["items"][0]["artworkPreview"].size()==3,"Applying identity erased existing images");});
        test("visual-only-followup-cannot-demote-verified-identity-cache",[&]{persistResolvedIdentityCache(manifestPath);auto s=snapshot;attachResolvedIdentityCache(s);require(buildLocalSteamPlanSnapshot(s)["items"][0]["status"]=="ready-to-add","Weaker visual result overwrote verified cache");});
        test("manual-id-clear-wins-over-cached-verified-identity",[&]{auto s=snapshot;attachResolvedIdentityCache(s);s["manualOverrides"]={{"items",{{toUtf8(exe.wstring()),{{"idCleared",true}}}}}};const auto p=buildLocalSteamPlanSnapshot(s);require(p["items"][0]["status"]=="waiting-steam-verification"&&!p["items"][0].contains("steamStoreAppId"),"Manual ID deletion was undone by identity cache");});
        test("unverified-numeric-candidate-never-promotes-ready",[&]{auto s=snapshot;auto candidate=verified;candidate["identityStatus"]="unverified";candidate["steamVerificationStatus"]="network-pending";s["resolvedIdentities"]={{toUtf8(normalizedPathKey(exe)),candidate}};require(buildLocalSteamPlanSnapshot(s)["items"][0]["status"]=="waiting-steam-verification","Numeric candidate was granted verified identity");});

        size_t failures=0;for(const auto& t:cases)if(!t["passed"].get<bool>())++failures;
        json report={{"allPassed",failures==0},{"caseCount",cases.size()},{"failedCount",failures},{"cases",cases},{"realSteamFilesModified",false}};writeFixtureJson(root/L"summary.json",report);std::cout<<report.dump(2)<<"\n";return failures?1:0;
    }catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}
}
