// Exact production helper + pinned native TabsHook + pinned DFL patch stack, inert React only.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {execFileSync} from 'node:child_process';import {createRequire} from 'node:module';import {root,task} from './fixtures/decky_task_paths.mjs';
const require=createRequire(path.join(root,'package.json')),{transformSync}=require('esbuild');
const evalTs=(source,extra={})=>{const module={exports:{}};vm.runInNewContext(transformSync(source,{loader:'tsx',format:'cjs',jsxFactory:'SP_REACT.createElement'}).code,{module,exports:module.exports,WeakMap,WeakSet,WeakRef,console:{debug(){}},...extra});return module.exports;};
const archive='G:/YeManCC-Work/Archives/Steam-QAM-YMCC-Wishlist-20261009';
const patcher=evalTs(execFileSync('tar',['-xOf',archive+'/downloads/decky--ui--4.12.1.tgz','package/src/utils/patcher.ts'],{encoding:'utf8'}));
const {installConsoleTab:install,YMCC_CONSOLE_TAB_ID:id}=evalTs(fs.readFileSync(path.join(root,'decky-plugin/src/qamPlacement.ts'),'utf8'));
const ui={...patcher,QuickAccessTab:{Decky:999,Notifications:0},ErrorBoundary:'Boundary'},cases=[];const check=(name,fn)=>{fn();cases.push(name);};
function fixture(){const host={},content={type:'Content',oneMirror:true},react={createElement:(type,props,...children)=>({type,props:{...props,children:children.length===1?children[0]:children}})};
 const file=archive+'/sources/SteamDeckHomebrew--decky-loader/decky-loader-75563316f9119ee7e36be7f43885be65e877fad0/frontend/src/tabs-hook.tsx';
 const Native=evalTs(fs.readFileSync(file,'utf8'),{window:host,SP_REACT:react,require:name=>name==='@decky/ui'?ui:name==='./logger'?{__esModule:true,default:class{log(){}debug(){}}}:{QuickAccessVisibleStateProvider:'Provider'}}).default;
 const hook=new Native();hook.add({id:999,title:'Decky',content:{deckyHome:true},icon:'plug'});return {host,hook,content,make:()=>[{key:0},{key:3},{key:4},{key:5},{key:7},{key:6}]};}
check('dedicated Console exists before notification, original Decky home stays last; only one owned content element',()=>{const f=fixture(),handle=install(ui,f.host,f.content,'Y'),tabs=f.make();assert.equal(handle.active,true);f.hook.render(tabs,true);assert.deepEqual(tabs.map(t=>t.key),[id,0,3,4,5,7,6,999]);assert.equal(tabs[0].title,'YMCC 控制台');assert.equal(tabs[0].panel.props.children.props.children,f.content);handle.dispose();});
check('repeat render of one reused native array never accumulates multiple owned console panels',()=>{const f=fixture(),h=install(ui,f.host,f.content,'Y'),tabs=f.make();for(let i=0;i<8;i++){f.hook.render(tabs,true);assert.equal(tabs.filter(t=>t.key===id).length,1);}h.dispose();assert.equal(tabs.filter(t=>t.key===id).length,0);});
check('normal render/visibility callbacks are retained with no duplicate registration or client',()=>{const f=fixture(),h=install(ui,f.host,f.content,'Y'),tabs=f.make();f.hook.render(tabs,true);let seen=0;tabs[0].qAMVisibilitySetter=v=>{assert.equal(v,false);seen++;};f.hook.render(tabs,false);assert.equal(tabs.filter(t=>t.key===id).length,1);assert.equal(seen,1);h.dispose();});
check('unload removes own registration and own tab, restores exact original home and render function',()=>{const f=fixture(),before=f.hook.render,h=install(ui,f.host,f.content,'Y'),tabs=f.make();f.hook.render(tabs,true);h.dispose();h.dispose();assert.equal(f.hook.render,before);assert.deepEqual(tabs.map(t=>t.key),[0,3,4,5,7,6,999]);assert.equal(f.hook.tabs.length,1);f.hook.render(tabs,true);assert.equal(tabs.filter(t=>t.key===999).length,1);});
check('existing foreign registrations preserve their identity and order',()=>{const f=fixture();f.hook.add({id:101,content:{foreign:true}});const h=install(ui,f.host,f.content,'Y'),tabs=f.make();f.hook.render(tabs,true);assert.deepEqual(tabs.map(t=>t.key),[id,0,3,4,5,7,6,999,101]);h.dispose();assert.equal(f.hook.tabs[1].id,101);});
check('second install / id collision fail closed without stealing someone else tab',()=>{const f=fixture(),h=install(ui,f.host,f.content,'Y');assert.equal(install(ui,f.host,f.content,'Y').active,false);h.dispose();f.hook.add({id,content:{foreign:true}});assert.equal(install(ui,f.host,f.content,'Y').active,false);assert.equal(f.hook.tabs.length,2);});
check('unsupported Loader or patch API leaves default plugin-list fallback available',()=>{for(const api of [{}, {...ui,QuickAccessTab:{Decky:42,Notifications:0}}]){const f=fixture(),h=install(api,f.host,f.content,'Y');assert.equal(h.active,false);assert.equal(f.hook.tabs.length,1);h.dispose();}});
check('patches before and after ours are retained on unload',()=>{const f=fixture();let count=0;const a=patcher.afterPatch(f.hook,'render',(_,r)=>{count++;return r;}),h=install(ui,f.host,f.content,'Y'),b=patcher.afterPatch(f.hook,'render',(_,r)=>{count++;return r;});f.hook.render(f.make(),true);h.dispose();f.hook.render(f.make(),true);assert.equal(count,4);assert.equal(a.hasUnpatched,false);assert.equal(b.hasUnpatched,false);b.unpatch();a.unpatch();});
check('bounded live receipts fail closed and fully unwind, never leave partial framework-tab arrays',()=>{const f=fixture(),h=install(ui,f.host,f.content,'Y'),arrays=Array.from({length:33},()=>f.make());for(const a of arrays)f.hook.render(a,true);assert.equal(h.active,false);assert.equal(f.hook.tabs.length,1);for(const a of arrays){assert.equal(a.filter(t=>t.key===id).length,0);f.hook.render(a,true);assert.equal(a.filter(t=>t.key===999).length,1);}h.dispose();});
check('factory returns no second Content when direct tab is installed, a labeled fallback when not',()=>{const source=fs.readFileSync(path.join(root,'decky-plugin/src/index.tsx'),'utf8');assert.match(source,/content: placement.active \? null : directContent/);assert.match(source,/installConsoleTab\(DFL, window, directContent, consoleIcon\)/);assert.match(source,/name: 'YMCC 控制台'/);});
check('same-count reused native array refreshes the current plugin owner/provider, not the previous content',()=>{const f=fixture(),a=install(ui,f.host,f.content,'Y'),tabs=f.make();f.hook.render(tabs,true);const oldHome=tabs.find(t=>t.key===999),replacement={type:'NewContent',oneMirror:true};f.hook.removeById(id);const b=install(ui,f.host,replacement,'Y');assert.equal(b.active,true);f.hook.render(tabs,true);const own=tabs.find(t=>t.key===id);assert.equal(own.panel.props.children.props.children,replacement);assert.equal(tabs.find(t=>t.key===999),oldHome);assert.equal(tabs.filter(t=>t.key===999).length,1);a.dispose();assert.equal(f.hook.tabs.find(t=>t.id===id)?.content,replacement);f.hook.render(tabs,true);assert.equal(tabs.find(t=>t.key===id).panel.props.children.props.children,replacement);b.dispose();});
check('reinstall after normal unload fills only the missing own tab without duplicating the native Decky home',()=>{const f=fixture(),a=install(ui,f.host,f.content,'Y'),tabs=f.make();f.hook.render(tabs,true);a.dispose();const oldHome=tabs.find(t=>t.key===999),replacement={type:'NewContent',oneMirror:true},b=install(ui,f.host,replacement,'Y');for(let i=0;i<6;i++){f.hook.render(tabs,true);assert.equal(tabs.filter(t=>t.key===id).length,1);assert.equal(tabs.filter(t=>t.key===999).length,1);assert.equal(tabs.find(t=>t.key===999),oldHome);assert.equal(tabs.find(t=>t.key===id).panel.props.children.props.children,replacement);}b.dispose();});
const report={project:'YMCC 控制台',stage:'Mainline19',cases:cases.length,results:cases,exactProductionHelper:true,exactNativeTabsHook:true,exactDflPatchStack:true,actualSteam:false,extraMirrorClients:0,newRuntimeTimers:0,configWrites:0,hardwareWrites:0};fs.writeFileSync(path.join(task,'validation/MAINLINE19-QAM-PLACEMENT.json'),JSON.stringify(report,null,2));console.log(`Direct console contracts passed: ${cases.length}`);
