// Exact production host, relay, original stores and adapters; memory-only IO.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {root,task} from './fixtures/decky_task_paths.mjs';import {load,seed,profile,main} from './fixtures/decky_game_memory_store.mjs';import {createMirrorHostFixture} from './fixtures/decky_mirror_host_fixture.mjs';
const runId='d'.repeat(32),peer={connection:'1',runId},cases=[];let sequence=0;
const flush=async()=>{for(let i=0;i<200;i++)await Promise.resolve();};
async function fixture(initial){const f=await createMirrorHostFixture({initial});f.ready();f.read=async()=>{f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'snapshot',runId}});await flush();return f.replies.at(-1).message.snapshot;};f.edit=async(command,field,value,expected)=>{const s=expected??await f.read(),n=++sequence;f.emit('deckySidebar.mirrorRequest',{...peer,request:{command,runId,clientId:'newcontrols',id:'newcontrols:'+n,sequence:n,generation:s.generation,revision:s.revision,identity:command==='frame.setField'?s.game?.identity??'':undefined,args:{field,value}}});await flush();return f.replies.findLast(r=>r.message.id==='newcontrols:'+n)?.message;};return f;}
async function check(name,fn){await fn();cases.push(name);}
await check('FPS snapshot reads independent pair rather than performance-combination legacy 60/30',async()=>{const f=await fixture(),s=await f.read();assert.equal(s.frames.pair.ac.fps,120);assert.equal(s.frames.pair.dc.fps,60);assert.equal(s.frames.dedicated,false);assert.equal(s.actions.frames,true);assert.equal(f.counts.frameApplies,0);assert.equal(f.counts.saves,0);assert.ok(!JSON.stringify(s).includes('controlAdmission'));f.stop();});
await check('first FPS edit creates whole original EXE profile, independent RTSS pair, original owner application',async()=>{const f=await fixture(),before=structuredClone(f.state.schedule);const r=await f.edit('frame.setField','acFps','90');assert.equal(r.ok,true);assert.equal(r.result.saved,true);assert.equal(r.result.applied,true);assert.equal(f.counts.frameApplies,1);const raw=f.memory.raw();assert.equal(raw.rtss['game.exe'].acFps,90);assert.equal(raw.rtss['game.exe'].dcFps,60);assert.equal(raw.entries['game.exe'].padPersona,'steamdeck');assert.equal(raw.entries['game.exe'].gyroOverride,'off');assert.equal(raw.entries['game.exe'].enabled,true);assert.deepEqual(f.state.schedule,before);assert.equal((await f.read()).frames.dedicated,true);assert.equal(f.counts.touchpadSaves,0);f.stop();});
await check('existing RTSS record and opaque EXE snapshots are preserved when FPS changes',async()=>{const data=seed();data.entries['game.exe']={...profile(),padPersona:'elite',gyroOverride:'racing',gyroPreset:'racing'};data.rtss['game.exe']={enabled:true,acFps:90,dcFps:35,acCeiling:120,dcCeiling:60};const f=await fixture(data),before=structuredClone(f.memory.view().entries['game.exe']);assert.equal((await f.edit('frame.setField','acFps','100')).ok,true);const raw=f.memory.raw();assert.deepEqual(raw.entries['game.exe'],before);assert.equal(raw.rtss['game.exe'].dcFps,35);assert.equal(raw.rtss['other.exe'].acFps,50);assert.equal(raw.rtss['other.exe'].dcFps,30);f.stop();});
await check('AC/DC power source displays one editable side; old side command rejected with zero saves',async()=>{const f=await fixture();f.state.powerSource='dc';f.powerChanged();const s=await f.read();assert.equal((await f.edit('frame.setField','acFps','90',s)).ok,false);assert.equal(f.counts.saves,0);assert.equal((await f.edit('frame.setField','dcFps','45')).ok,true);assert.equal(f.memory.raw().rtss['game.exe'].dcFps,45);assert.equal(f.memory.raw().rtss['game.exe'].acFps,120);f.stop();});
await check('no-game global frame edit keeps DC and all EXE data untouched',async()=>{const f=await fixture();f.state.game=null;f.gameChanged();const s=await f.read();assert.equal(s.actions.game,false);assert.equal(s.actions.frames,true);assert.equal((await f.edit('frame.setField','acFps','95')).ok,true);assert.equal(f.counts.globalFrameSaves,1);assert.equal(f.counts.saves,0);assert.deepEqual(f.memory.raw().entries,{});assert.equal(f.state.globalFrames.dc.fps,60);assert.equal((await f.read()).frames.pair.ac.fps,95);f.stop();});
await check('unlimited ceiling preserves remembered FPS, and enable ceiling follows the original clamp semantics',async()=>{const f=await fixture();await f.edit('frame.setField','acFps','95');await f.edit('frame.setField','acCeiling','0');let s=await f.read();assert.equal(s.frames.pair.ac.fps,0);assert.equal(s.frames.pair.ac.lastFps,95);assert.equal((await f.edit('frame.setField','acFps','80')).ok,false);await f.edit('frame.setField','acCeiling','60');s=await f.read();assert.equal(s.frames.pair.ac.fps,60);assert.equal(s.frames.pair.ac.ceiling,60);assert.equal(s.frames.pair.dc.fps,60);f.stop();});
await check('invalid/unsupported frame values fail before save or original RTSS owner',async()=>{const f=await fixture();for(const [field,value]of [['acFps','NaN'],['acFps','19'],['acFps','301'],['acFps','90.1'],['acFps','090'],['acCeiling','45'],['exe','x']])assert.equal((await f.edit('frame.setField',field,value)).ok,false);assert.equal(f.counts.saves,0);assert.equal(f.counts.frameApplies,0);f.stop();});
await check('FPS save is truthful when original limiter application fails: saved pending, not applied',async()=>{const f=await fixture();f.state.frameApplyResult=false;const r=await f.edit('frame.setField','acFps','90');assert.equal(r.result.saved,true);assert.equal(r.result.applied,false);assert.equal(r.result.pending,true);assert.equal(f.memory.raw().rtss['game.exe'].acFps,90);f.stop();});
await check('frame private source races reject silent RTSS/global changes after snapshot',async()=>{for(const mode of ['rtss','global']){const f=await fixture(),s=await f.read();if(mode==='rtss'){const raw=f.memory.raw();raw.rtss['game.exe']={enabled:true,acFps:80,dcFps:45};f.memory.documents.set(main,JSON.stringify(raw));}else f.state.globalFrames.ac.fps=100;assert.equal((await f.edit('frame.setField','acFps','90',s)).ok,false);assert.equal(f.counts.saves,0);assert.equal(f.counts.frameApplies,0);f.stop();}});
await check('frame target identity/shared lock/power generation gates reject before mutation',async()=>{for(const mode of ['identity','lock','power','generation']){const f=await fixture(),s=await f.read();let release;if(mode==='identity')f.state.game.processCreated='reuse';if(mode==='lock')release=f.memory.lock.tryAcquireQuickAction('original-frame-editor');if(mode==='power')f.state.power.phase='pending';if(mode==='generation')f.state.power.generation++;assert.equal((await f.edit('frame.setField','acFps','90',s)).ok,false);assert.equal(f.counts.saves,0);release?.();f.stop();}});
await check('touchpad snapshot contains four global primary dropdowns plus original conditional mappings',async()=>{const f=await fixture(),s=await f.read();for(const field of ['layout','summonPosition','specialMask','rearMask'])assert.ok(s.touchpads.fields[field]);assert.equal(s.touchpads.persona,'steamdeck');assert.equal(s.touchpads.fields.layout.value,'dual');assert.equal(s.touchpads.fields.leftMode.choices[0].data,'steamdeck');assert.equal(f.counts.touchpadSaves,0);f.stop();});
await check('global touchpad changes never create EXE records, even while confirmed game is present',async()=>{const f=await fixture();const r=await f.edit('touchpad.setField','layout','single');assert.equal(r.ok,true);assert.equal(f.state.touchpads.enabled,true);assert.equal(f.state.touchpads.layout,'single');assert.deepEqual(f.memory.raw().entries,{});assert.deepEqual(f.memory.raw().rtss,{});assert.equal(f.counts.saves,0);assert.equal(f.counts.globalFrameSaves,0);assert.equal((await f.read()).touchpads.fields.singleMode.supported,true);f.stop();});
await check('summon/special/rear dropdowns preserve original mask and enabled linkage',async()=>{const f=await fixture();for(const [field,value]of [['summonPosition','right'],['specialMask','1'],['rearMask','10']])assert.equal((await f.edit('touchpad.setField',field,value)).ok,true);assert.equal(f.state.touchpads.summonEnabled,true);assert.equal(f.state.touchpads.specialEnabled,true);assert.equal(f.state.touchpads.rearEnabled,true);assert.equal(f.state.touchpads.rearMask,10);await f.edit('touchpad.setField','rearMask','0');assert.equal(f.state.touchpads.rearEnabled,false);assert.equal(f.state.touchpads.scale,100);assert.equal(f.state.touchpads.transparency,80);f.stop();});
await check('touchpads available with no confirmed game, independent of disabled game actions',async()=>{const f=await fixture();f.state.game=null;f.gameChanged();const s=await f.read();assert.equal(s.actions.touchpads,true);assert.equal(s.actions.game,false);assert.equal((await f.edit('touchpad.setField','summonPosition','left')).ok,true);assert.equal(f.counts.touchpadSaves,1);assert.equal(f.counts.saves,0);f.stop();});
await check('touchpads use global persona, not current dedicated input override',async()=>{const data=seed();data.entries['game.exe']={...profile(),padPersona:'elite',gyroOverride:'off'};const f=await fixture(data);assert.equal((await f.read()).touchpads.persona,'steamdeck');await f.edit('touchpad.setField','rearMask','5');assert.equal(f.state.touchpads.persona,'steamdeck');assert.equal(f.memory.raw().entries['game.exe'].padPersona,'elite');assert.equal(f.counts.saves,0);f.stop();});
await check('global persona switch and silent touch configuration source races reject old menu',async()=>{for(const mode of ['persona','config']){const f=await fixture(),s=await f.read();if(mode==='persona')f.state.input.outputTarget.persona='elite';else f.state.touchpads.scale=150;assert.equal((await f.edit('touchpad.setField','rearMask','5',s)).ok,false);assert.equal(f.counts.touchpadSaves,0);f.stop();}});
await check('PS/native mapping disabled when host unavailable; entering layout falls back exactly as original page',async()=>{const f=await fixture();f.state.input.outputTarget={persona:'dualsense-edge',buttonMappingEnabled:true};Object.assign(f.state.touchpads,{layout:'off',singleMode:'dualsense',leftMode:'dualsense',rightMode:'dualsense',ps5Available:false});const s=await f.read();assert.equal(s.touchpads.fields.leftMode.choices.find(o=>o.data==='dualsense').disabled,true);assert.equal((await f.edit('touchpad.setField','layout','dual')).ok,true);assert.equal(f.state.touchpads.leftMode,'wasd');assert.equal(f.state.touchpads.rightMode,'mouse');assert.equal((await f.edit('touchpad.setField','leftMode','dualsense')).ok,false);f.stop();});
await check('touchpad layout-off/single rejects hidden left-right and invalid invented mask values',async()=>{const f=await fixture();await f.edit('touchpad.setField','layout','single');for(const[field,value]of [['leftMode','wasd'],['rearMask','11'],['specialMask','99'],['singleMode','steamdeck'],['exe','game.exe']])assert.equal((await f.edit('touchpad.setField',field,value)).ok,false);assert.equal(f.counts.touchpadSaves,1);f.stop();});
await check('touchpad source ignores volatile counters but includes durable config and capability gates',async()=>{const f=await fixture(),s=await f.read();Object.assign(f.state.touchpads,{events:888,repaints:999,visible:true});assert.equal((await f.edit('touchpad.setField','rearMask','5',s)).ok,true);f.stop();});
await check('touchpad original owner failed save is not reported applied and does not write EXE data',async()=>{const f=await fixture();f.state.touchError=true;const r=await f.edit('touchpad.setField','summonPosition','left');assert.equal(r.ok,false);assert.equal(f.state.touchpads.summonPosition,'off');assert.equal(f.counts.saves,0);assert.equal(f.memory.lock.isQuickActionBusy(),false);f.stop();});
await check('touchpad lock and pending power protect source save, no new timers/retries',async()=>{for(const mode of ['lock','power']){const f=await fixture(),s=await f.read();let release;if(mode==='lock')release=f.memory.lock.tryAcquireQuickAction('original-touchpad');else f.state.power.phase='pending';assert.equal((await f.edit('touchpad.setField','summonPosition','left',s)).ok,false);assert.equal(f.counts.touchpadSaves,0);release?.();f.stop();}});
fs.writeFileSync(path.join(task,'validation/MAINLINE23-FRAME-TOUCHPAD.json'),JSON.stringify({cases:cases.length,results:cases,productionHostRelayAdapters:true,originalStore:true,independentFrameModel:true,touchpadsGlobalOnly:true,realConfigWrites:0,hardwareWrites:0},null,2));console.log('Frame/touchpad PASS '+cases.length);
