// Exact host, authenticated relay and production adapters; original memory store.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {task} from './fixtures/decky_task_paths.mjs';import {createMirrorHostFixture} from './fixtures/decky_mirror_host_fixture.mjs';import {seed,profile} from './fixtures/decky_game_memory_store.mjs';
const runId='c'.repeat(32),peer={connection:'1',runId},cases=[];let id=0;
const flush=async()=>{for(let i=0;i<150;i++)await Promise.resolve();};
async function fixture(initial){const f=await createMirrorHostFixture({initial});f.ready();f.read=async()=>{f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'snapshot',runId}});await flush();return f.replies.at(-1).message.snapshot;};f.edit=async(field,value,expected)=>{const snap=expected??await f.read();f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'game.setField',runId,clientId:'actions',id:'actions:'+ ++id,sequence:id,generation:snap.generation,revision:snap.revision,identity:snap.game.identity,args:{field,value}}});await flush();return f.replies.findLast(r=>r.message.id==='actions:'+id)?.message;};return f;}
async function check(name,fn){await fn();cases.push(name);}
await check('default global display sentinels are disabled; fake client cannot write them',async()=>{const f=await fixture();const snap=await f.read();assert.equal(snap.game.fields.padPersona.choices.find(c=>c.data==='follow').disabled,true);assert.equal(snap.game.fields.acMode.choices.find(c=>c.data==='follow').disabled,true);assert.equal((await f.edit('padPersona','follow')).ok,false);assert.equal(f.counts.saves,0);f.stop();});
await check('first dedicated edit freezes both AC/DC plus whole input selection once in the original EXE record',async()=>{const f=await fixture();f.state.gyroDefaults.enabled=true;f.state.gyroDefaults.preset='racing';await f.read();const reply=await f.edit('corePolicyMode','only-big');assert.equal(reply.ok,true);assert.equal(f.counts.saves,1);const e=f.memory.raw().entries['game.exe'];assert.equal(e.enabled,true);assert.equal(e.acMode,'balanced');assert.equal(e.dcMode,'eco');assert.ok(e.ac&&e.dc);assert.equal(e.padPersona,'steamdeck');assert.equal(e.gyroOverride,'racing');assert.equal(e.gyroPreset,'racing');assert.equal(e.corePolicyMode,'only-big');const snap=await f.read();assert.ok(!snap.game.fields.padPersona.choices.some(c=>c.data==='follow'));assert.ok(!snap.game.fields.acMode.choices.some(c=>c.data==='follow'));f.stop();});
await check('dedicated snapshot stops following subsequent global persona/gyro choices',async()=>{const f=await fixture();await f.edit('acMode','performance');f.state.gyroDefaults={...f.state.gyroDefaults,padPersona:'elite',enabled:true,preset:'steam',source:'new-global'};f.emit('input.shortcutRuntime',{});await flush();const s=await f.read();assert.equal(s.game.fields.padPersona.value,'steamdeck');assert.equal(s.game.fields.gyroEnabled.value,'off');assert.equal(s.game.fields.gyroPreset.value,'fps');f.stop();});
await check('reading old inherited records never migrates them; next explicit edit materializes them',async()=>{const data=seed();data.entries['game.exe']=profile();const f=await fixture(data);const before=JSON.stringify(f.memory.raw());await f.read();assert.equal(JSON.stringify(f.memory.raw()),before);await f.edit('dcMode','extreme');const e=f.memory.raw().entries['game.exe'];assert.equal(e.padPersona,'steamdeck');assert.equal(e.gyroOverride,'off');assert.equal(f.counts.saves,1);f.stop();});
await check('same displayed first core default explicitly activates and remembers the full EXE profile once',async()=>{const f=await fixture(),s=await f.read();assert.equal(s.game.fields.corePolicyMode.value,'big-small');assert.equal(s.game.fields.corePolicyMode.inherited,true);assert.equal((await f.edit('corePolicyMode','big-small',s)).result.saved,true);const e=f.memory.raw().entries['game.exe'];assert.equal(e.padPersona,'steamdeck');assert.equal(e.gyroOverride,'off');assert.ok(e.ac&&e.dc);assert.equal(e.enabled,true);const next=await f.read();assert.equal(next.game.fields.corePolicyMode.inherited,false);assert.equal((await f.edit('corePolicyMode','big-small',next)).result.saved,false);assert.equal(f.counts.saves,1);f.stop();});
await check('inactive explicit records expose same-value selection as activation instead of global or no-op',async()=>{const data=seed();data.entries['game.exe']={...profile(),enabled:false,padPersona:'elite',gyroOverride:'racing',gyroPreset:'racing',corePolicyMode:'only-big',corePolicyEnabled:true};const f=await fixture(data),s=await f.read();for(const field of ['corePolicyMode','padPersona','gyroPreset'])assert.equal(s.game.fields[field].inherited,true);assert.equal((await f.edit('padPersona','elite',s)).result.saved,true);assert.equal(f.memory.raw().entries['game.exe'].enabled,true);assert.equal((await f.read()).game.fields.padPersona.inherited,false);f.stop();});
await check('duplicate gyro switch still freezes an inherited pad before becoming a true no-op',async()=>{const data=seed();data.entries['game.exe']={...profile(),gyroOverride:'fps',gyroPreset:'fps'};const f=await fixture(data);const reply=await f.edit('gyroEnabled','on');assert.equal(reply.result.saved,true);assert.equal(f.memory.raw().entries['game.exe'].padPersona,'steamdeck');assert.equal(f.memory.raw().entries['game.exe'].gyroOverride,'fps');assert.equal((await f.edit('gyroEnabled','on')).result.saved,false);assert.equal(f.counts.saves,1);f.stop();});
await check('native-pad dormant gyro reset does not repeatedly require global input migration',async()=>{const data=seed();data.entries['game.exe']={...profile(),padPersona:'disabled',gyroOverride:'follow',corePolicyMode:'big-small',corePolicyEnabled:true};const f=await fixture(data),s=await f.read();assert.equal(s.game.fields.corePolicyMode.inherited,false);assert.equal((await f.edit('padPersona','disabled',s)).result.saved,false);assert.equal(f.counts.saves,0);f.stop();});
await check('switching native pad back to virtual cannot reactivate its dormant follow gyro inheritance',async()=>{const data=seed();data.entries['game.exe']={...profile(),padPersona:'disabled',gyroOverride:'follow',gyroPreset:'racing'};const f=await fixture(data),s=await f.read();assert.equal((await f.edit('padPersona','elite',s)).result.saved,true);const e=f.memory.raw().entries['game.exe'];assert.equal(e.padPersona,'elite');assert.equal(e.gyroOverride,'off');assert.equal(e.gyroPreset,'fps');const updated=await f.read();assert.equal(updated.game.fields.padPersona.inherited,false);assert.equal(updated.game.fields.gyroPreset.inherited,false);f.stop();});
await check('global input source changed while snapshot admission is old cannot be silently frozen',async()=>{const f=await fixture(),snap=await f.read();f.state.gyroDefaults.source='changed-without-event';const result=await f.edit('acMode','performance',snap);assert.equal(result.ok,false);assert.equal(f.counts.saves,0);f.stop();});
await check('live speed uses original owner with no dedicated store save or fan changes',async()=>{const f=await fixture();assert.equal((await f.read()).game.fields.speedFactor.value,'1');let reply=await f.edit('speedFactor','1.5');assert.equal(reply.ok,true);assert.equal(reply.result.applied,true);assert.equal(reply.result.saved,false);assert.equal(f.counts.speedApply,1);assert.equal(f.counts.saves,0);assert.equal((await f.read()).game.fields.speedFactor.value,'1.5');reply=await f.edit('speedFactor','1');assert.equal(reply.ok,true);assert.equal(f.counts.speedClear,1);assert.equal((await f.read()).game.fields.speedFactor.value,'1');assert.deepEqual(f.memory.raw().entries,{});f.stop();});
await check('repeat speed is a no-op; invalid/global factors reject before original owner',async()=>{const f=await fixture();await f.edit('speedFactor','1.5');await f.edit('speedFactor','1.5');assert.equal(f.counts.speedApply,1);for(const bad of ['NaN','0','16','1.50','follow'])assert.equal((await f.edit('speedFactor',bad)).ok,false);assert.equal(f.counts.speedApply,1);f.stop();});
await check('unsafe fallback is reported as not applied, never success or persisted',async()=>{const f=await fixture();f.state.speedResult={ok:true,safeFallback:true,skipped:true,reason:'stale_target',msgs:['kept at 1x']};const reply=await f.edit('speedFactor','2');assert.equal(reply.ok,true);assert.equal(reply.result.applied,false);assert.equal(reply.result.saved,false);assert.equal(f.state.speed,null);f.stop();});
await check('speed rejects old process identity, shared original lock and pending power',async()=>{for(const mode of ['identity','lock','power']){const f=await fixture(),snap=await f.read();let release;if(mode==='identity')f.state.game.processCreated='reused';if(mode==='lock')release=f.memory.lock.tryAcquireQuickAction('original-panel');if(mode==='power')f.state.power.phase='pending';assert.equal((await f.edit('speedFactor','2',snap)).ok,false);assert.equal(f.counts.speedApply,0);release?.();f.stop();}});
await check('speed session source races and cross-game speed state never become the displayed factor',async()=>{const f=await fixture(),snap=await f.read();f.state.speed={pid:999,processCreated:'other',factor:8,enabled:true};assert.equal((await f.edit('speedFactor','2',snap)).ok,false);assert.equal(f.counts.speedApply,0);assert.equal((await f.read()).game.fields.speedFactor.value,'1');f.stop();});
await check('original Minecraft compatibility guard disables widget and rejects synthetic mutations',async()=>{const f=await fixture();f.state.game.name='javaw.exe';f.gameChanged();await flush();assert.equal((await f.read()).game.fields.speedFactor.supported,false);assert.equal((await f.edit('speedFactor','2')).ok,false);assert.equal(f.counts.speedApply,0);f.stop();});
fs.writeFileSync(path.join(task,'validation/MAINLINE22-ACTIONS.json'),JSON.stringify({cases:cases.length,results:cases,productionHostRelayAdapters:true,originalStore:true,realConfigWrites:0,hardwareWrites:0},null,2));console.log('Console22 actions PASS '+cases.length);
