import { task } from './fixtures/decky_task_paths.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { createRequire } from 'node:module';
const root=path.resolve(import.meta.dirname,'..');const require=createRequire(path.join(root,'package.json'));const {transformSync}=require('esbuild');
function load(relative){const module={exports:{}};vm.runInNewContext(transformSync(fs.readFileSync(path.join(root,relative),'utf8'),{loader:'ts',format:'cjs'}).code,{module,exports:module.exports,structuredClone,queueMicrotask,require:name=>{if(name==='../../decky-plugin/src/steamRunningContext')return load('decky-plugin/src/steamRunningContext.ts');throw new Error('Unexpected dependency');}});return module.exports;}
const {ReadOnlyMirrorRelay}=load('src/bridge/deckyMirrorRelay.ts');const {createFanMirrorActions}=load('src/bridge/deckyFanActions.ts');
const cases=[];async function check(name,fn){await fn();cases.push({name,status:'passed'});}const flush=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
function deferred(){let resolve,reject;const promise=new Promise((y,n)=>{resolve=y;reject=n;});return {promise,resolve,reject};}
const runId='a'.repeat(32);const peer={connection:'1',runId,connected:true};
function request(sequence=1,overrides={}){return {...peer,request:{command:'fan.setEnabled',runId,id:`client:${sequence}`,clientId:'client',sequence,generation:1,revision:1,args:{enabled:true},...overrides}};}
function relayFixture(overrides={}){const replies=[];const effects=[];let invalidate;
 const relay=new ReadOnlyMirrorRelay({read:async()=>({generation:1,ready:true,game:{label:'A',identity:'a.exe:101:A',fields:{}},fan:{supported:true,enabled:false,preset:'balanced',canToggle:true,choices:[]},actions:{fan:true,game:false}}),observe:fn=>{invalidate=fn;return()=>{};},reply:async(connection,message)=>{replies.push(message);return true;},execute:async(...args)=>{effects.push(args);return {saved:false,applied:true,notice:'original-owner-ack'};},...overrides});
 return {relay,replies,effects,invalidate:()=>invalidate(),open:()=>relay.request({...peer,request:{command:'snapshot',runId}})};}
await check('valid action invokes exactly one existing action boundary',async()=>{const f=relayFixture();await f.open();await f.relay.request(request());assert.equal(f.effects.length,1);assert.equal(f.replies.find(r=>r.type==='reply').ok,true);f.relay.dispose();});
await check('duplicate receipt reuses reply even after source revision changes',async()=>{const f=relayFixture();await f.open();await f.relay.request(request());await flush();await f.relay.request(request());assert.equal(f.effects.length,1);assert.equal(f.replies.filter(r=>r.type==='reply').length,2);f.relay.dispose();});
await check('same request ID with altered args cannot execute again',async()=>{const f=relayFixture();await f.open();await f.relay.request(request());await f.relay.request(request(1,{args:{enabled:false}}));assert.equal(f.effects.length,1);assert.match(f.replies.filter(r=>r.type==='reply').at(-1).error,/不同操作/);f.relay.dispose();});
await check('concurrent exact duplicate waits same in-flight result',async()=>{const pending=deferred();let effects=0;const f=relayFixture({execute:async()=>{effects++;await pending.promise;return {saved:false,applied:true,notice:'ack'};}});await f.open();const a=f.relay.request(request());await flush();const b=f.relay.request(request());pending.resolve();await Promise.all([a,b]);assert.equal(effects,1);assert.equal(f.replies.filter(r=>r.type==='reply').length,2);f.relay.dispose();});
await check('different command while pending fails busy without hardware call',async()=>{const pending=deferred();let effects=0;const f=relayFixture({execute:async()=>{effects++;await pending.promise;return {saved:false,applied:true,notice:'ack'};}});await f.open();const a=f.relay.request(request());await flush();await f.relay.request(request(2,{args:{enabled:false}}));assert.equal(effects,1);assert.match(f.replies.filter(r=>r.type==='reply').at(-1).error,/正在执行/);pending.resolve();await a;f.relay.dispose();});
await check('stale revision fails closed',async()=>{const f=relayFixture();await f.open();await f.relay.request(request(1,{revision:0}));assert.equal(f.effects.length,0);assert.match(f.replies.filter(r=>r.type==='reply').at(-1).error,/状态已变化/);f.relay.dispose();});
await check('stale power generation fails closed',async()=>{const f=relayFixture();await f.open();await f.relay.request(request(1,{generation:2}));assert.equal(f.effects.length,0);f.relay.dispose();});
await check('game operations remain disabled, not silently reduced to global',async()=>{const f=relayFixture();await f.open();await f.relay.request(request(1,{command:'game.setField',identity:'a.exe:101:A',args:{field:'acMode',value:'eco'}}));assert.equal(f.effects.length,0);assert.match(f.replies.filter(r=>r.type==='reply').at(-1).error,/尚未接线/);f.relay.dispose();});
await check('invalid sequence/client identity fails closed',async()=>{const f=relayFixture();await f.open();for(const packet of [{sequence:NaN},{clientId:'bad:client'},{id:'wrong-id'},{sequence:0},{args:[]}])await f.relay.request(request(1,packet));assert.equal(f.effects.length,0);f.relay.dispose();});
await check('unknown packet fields and raw fan curve rejected before receipt storage',async()=>{const f=relayFixture();await f.open();for(const packet of [{extra:'ignored?'},{args:{enabled:true,nodes:[]}},{args:{preset:'soft',nodes:[]},command:'fan.setPreset'}])await f.relay.request(request(1,packet));assert.equal(f.effects.length,0);f.relay.dispose();});
await check('oversize mutable request cannot amplify receipt memory',async()=>{const f=relayFixture();await f.open();await f.relay.request(request(1,{identity:'x'.repeat(3000)}));assert.equal(f.effects.length,0);assert.match(f.replies.filter(r=>r.type==='reply').at(-1).error,/请求过大/);f.relay.dispose();});
await check('request argument value frozen before awaited source read',async()=>{const read=deferred();const f=relayFixture({read:()=>read.promise});f.relay.connected(peer);const packet=request();const task=f.relay.request(packet);packet.request.args.enabled=false;read.resolve({generation:1,ready:true,game:null,fan:{supported:true,enabled:false,preset:'balanced',canToggle:true,choices:[]},actions:{fan:true,game:false}});await task;assert.equal(f.effects[0][1].enabled,true);f.relay.dispose();});
await check('peer detach during accepted action never publishes to new peer',async()=>{const pending=deferred();const f=relayFixture({execute:async(_c,_a,context)=>{await pending.promise;context.checkpoint();return {saved:false,applied:true,notice:'ack'};}});await f.open();const task=f.relay.request(request());await flush();f.relay.connected({...peer,connected:false});f.relay.connected({...peer,connection:'2'});pending.resolve();await task;assert.equal(f.replies.filter(r=>r.type==='reply').length,0);f.relay.dispose();});
await check('failed action is cached and cannot retry its side effects',async()=>{let effects=0;const f=relayFixture({execute:async()=>{effects++;throw new Error('mock owner failed');}});await f.open();await f.relay.request(request());await f.relay.request(request());assert.equal(effects,1);assert.ok(f.replies.filter(r=>r.type==='reply').every(r=>r.ok===false));f.relay.dispose();});
await check('old evicted request cannot replay due to sequence high-water mark',async()=>{const f=relayFixture();await f.open();for(let sequence=1;sequence<=35;sequence++){const snap=f.replies.filter(r=>r.type==='snapshot').at(-1).snapshot;await f.relay.request(request(sequence,{revision:snap.revision}));await flush();}const before=f.effects.length;await f.relay.request(request());assert.equal(f.effects.length,before);assert.match(f.replies.filter(r=>r.type==='reply').at(-1).error,/已处理或过期/);f.relay.dispose();});

const savedCurves={soft:[{tempC:0,dutyPercent:9},{tempC:40,dutyPercent:15},{tempC:70,dutyPercent:30},{tempC:100,dutyPercent:70}],balanced:[{tempC:0,dutyPercent:18},{tempC:40,dutyPercent:25},{tempC:70,dutyPercent:50},{tempC:100,dutyPercent:90}],aggressive:[{tempC:0,dutyPercent:27},{tempC:40,dutyPercent:35},{tempC:70,dutyPercent:80},{tempC:100,dutyPercent:100}]};
function fanFixture(overrides={}){const calls=[];const saved=[];const displays=[];const values={active:false,preset:'balanced',feature:true,busy:false,power:{generation:1,phase:'ready',hardwareWritesAllowed:true},duty:0};
 const owner={hasControlIntent:false,controlReady:false,state:'awaiting-control',recoveryActive:false,start:async args=>{calls.push(['start',args]);return {allowed:true,writeReady:true};},apply:async nodes=>{calls.push(['apply',structuredClone(nodes)]);owner.hasControlIntent=true;owner.controlReady=true;owner.state='ready';return {state:'Ready'};},applyPreset:async(preset,nodes)=>{calls.push(['preset',preset,structuredClone(nodes)]);owner.hasControlIntent=true;owner.controlReady=true;owner.state='ready';return {state:'Ready'};},disable:async()=>{calls.push(['disable']);owner.hasControlIntent=false;owner.controlReady=false;owner.state='awaiting-control';return {state:'AwaitingControl'};}};
 const deps={owner,enabled:()=>values.active,currentPreset:()=>values.preset,curve:preset=>structuredClone(savedCurves[preset]),save:async(nodes,preset)=>{saved.push({nodes:structuredClone(nodes),preset});values.preset=preset;},updateActive:active=>{values.active=active;},updateDuty:duty=>{values.duty=duty;},power:async()=>values.power,featureAllowed:()=>values.feature,uiBusy:()=>values.busy,display:value=>displays.push(value),...overrides};
 const action=createFanMirrorActions(deps);const context={generation:1,checkpoint:()=>{}};return {action,calls,saved,displays,values,owner,deps,context};}
await check('off-state preset saves existing curve without starting owner',async()=>{const f=fanFixture();const result=await f.action.execute('fan.setPreset',{preset:'soft'},f.context);assert.equal(result.saved,true);assert.equal(result.applied,false);assert.equal(f.calls.length,0);assert.deepEqual(f.saved[0].nodes,savedCurves.soft);assert.equal(f.values.active,false);});
await check('enable uses original owner start and apply of existing current curve',async()=>{const f=fanFixture();const result=await f.action.execute('fan.setEnabled',{enabled:true},f.context);assert.deepEqual(f.calls.map(c=>c[0]),['start','apply']);assert.deepEqual(f.calls[1][1],savedCurves.balanced);assert.equal(f.values.active,true);assert.equal(result.applied,true);assert.equal(f.saved.length,0);});
await check('active preset uses start and applyPreset, no new enable or lease owner',async()=>{const f=fanFixture();f.values.active=true;await f.action.execute('fan.setPreset',{preset:'aggressive'},f.context);assert.deepEqual(f.calls.map(c=>c[0]),['start','preset']);assert.equal(f.calls[1][1],'aggressive');assert.deepEqual(f.calls[1][2],savedCurves.aggressive);});
await check('off uses original disable and resets presentation only',async()=>{const f=fanFixture();f.values.active=true;await f.action.execute('fan.setEnabled',{enabled:false},f.context);assert.deepEqual(f.calls.map(c=>c[0]),['disable']);assert.equal(f.values.active,false);assert.equal(f.values.duty,0);assert.equal(f.saved.length,0);});
await check('already-enabled live original owner avoids repeat start/apply',async()=>{const f=fanFixture();f.values.active=true;f.owner.hasControlIntent=true;f.owner.controlReady=true;f.owner.state='ready';await f.action.execute('fan.setEnabled',{enabled:true},f.context);assert.equal(f.calls.length,0);});
await check('invalid preset/curve payload rejected before writes',async()=>{const f=fanFixture();await assert.rejects(f.action.execute('fan.setPreset',{preset:'soft',nodes:[]},f.context),/INVALID_PRESET/);await assert.rejects(f.action.execute('fan.setPreset',{preset:'new'},f.context),/INVALID_PRESET/);assert.equal(f.saved.length,0);assert.equal(f.calls.length,0);});
await check('cached active without original owner intent/readiness invokes original start/apply rather than fake no-op',async()=>{const f=fanFixture();f.values.active=true;await f.action.execute('fan.setEnabled',{enabled:true},f.context);assert.deepEqual(f.calls.map(call=>call[0]),['start','apply']);});
await check('feature gate false never reads power/starts owner',async()=>{const f=fanFixture();f.values.feature=false;await assert.rejects(f.action.execute('fan.setEnabled',{enabled:true},f.context),/NOT_ENABLED/);assert.equal(f.calls.length,0);});
await check('original view busy/editing rejects new mirror operation',async()=>{const f=fanFixture();f.values.busy=true;await assert.rejects(f.action.execute('fan.setEnabled',{enabled:true},f.context),/BUSY/);assert.equal(f.calls.length,0);});
await check('power transition never saves/applies',async()=>{const f=fanFixture();f.values.power.phase='resuming';await assert.rejects(f.action.execute('fan.setPreset',{preset:'soft'},f.context),/POWER_NOT_READY/);assert.equal(f.saved.length,0);assert.equal(f.calls.length,0);});
await check('sleep generation change after start prevents hardware apply',async()=>{const f=fanFixture();f.owner.start=async()=>{f.values.power.generation=2;return {allowed:true,writeReady:true};};await assert.rejects(f.action.execute('fan.setEnabled',{enabled:true},f.context),/POWER_NOT_READY/);assert.equal(f.calls.length,0);assert.equal(f.values.active,false);});
await check('capability refusal has no hardware write or global active fake success',async()=>{const f=fanFixture();f.owner.start=async()=>({allowed:false,writeReady:false});await assert.rejects(f.action.execute('fan.setEnabled',{enabled:true},f.context),/CAPABILITY_NOT_READY/);assert.equal(f.values.active,false);assert.equal(f.calls.length,0);});
await check('save rejection prevents hardware start',async()=>{const f=fanFixture({save:async()=>{throw new Error('mock save failed');}});f.values.active=true;await assert.rejects(f.action.execute('fan.setPreset',{preset:'soft'},f.context),/mock save/);assert.equal(f.calls.length,0);});
await check('curve selection frozen across awaited save',async()=>{const pending=deferred();const mutable=structuredClone(savedCurves.soft);const f=fanFixture({curve:()=>mutable,save:()=>pending.promise});f.values.active=true;const task=f.action.execute('fan.setPreset',{preset:'soft'},f.context);await flush();mutable[0].dutyPercent=99;pending.resolve();await task;assert.equal(f.calls[1][2][0].dutyPercent,9);});
await check('owner failure preserves its recovery intent, no new retry loop',async()=>{const f=fanFixture();f.owner.apply=async()=>{f.owner.recoveryActive=true;throw new Error('mock recovery pending');};const result=await f.action.execute('fan.setEnabled',{enabled:true},f.context);assert.equal(result.pending,true);assert.equal(result.applied,false);assert.equal(f.values.active,true);assert.equal(f.calls.length,1);});
await check('preset apply failure reports failure, keeps saved preset',async()=>{const f=fanFixture();f.values.active=true;f.owner.applyPreset=async()=>{throw new Error('mock failed');};await assert.rejects(f.action.execute('fan.setPreset',{preset:'soft'},f.context),/mock failed/);assert.equal(f.values.preset,'soft');assert.equal(f.values.active,false);assert.equal(f.values.duty,0);});
await check('disable failure cancels presentation intent but never reports OEM success',async()=>{const f=fanFixture();f.values.active=true;f.owner.disable=async()=>{throw new Error('mock restore unconfirmed');};await assert.rejects(f.action.execute('fan.setEnabled',{enabled:false},f.context),/unconfirmed/);assert.equal(f.values.active,false);assert.equal(f.values.duty,0);assert.match(f.displays.at(-1).notice,/未确认/);});
await check('active preset startup failure does not falsely keep control acknowledged',async()=>{const f=fanFixture();f.values.active=true;f.owner.start=async()=>{throw new Error('mock host unavailable');};await assert.rejects(f.action.execute('fan.setPreset',{preset:'soft'},f.context),/unavailable/);assert.equal(f.values.preset,'soft');assert.equal(f.values.active,false);assert.equal(f.saved.length,1);});
await check('original handshake capability observation reused before enable',async()=>{const gates=[];const f=fanFixture({observeCapability:async allowed=>gates.push(allowed)});await f.action.execute('fan.setEnabled',{enabled:true},f.context);assert.deepEqual(gates,[true]);});
await check('second fan command cannot overlap owner work',async()=>{const pending=deferred();const f=fanFixture();f.owner.apply=()=>pending.promise;const first=f.action.execute('fan.setEnabled',{enabled:true},f.context);await flush();await assert.rejects(f.action.execute('fan.setEnabled',{enabled:false},f.context),/BUSY/);pending.resolve({state:'Ready'});await first;});

await check('slow original fan start is acknowledged as ON intent immediately, no mirror timeout or false hardware readiness',async()=>{const f=fanFixture(),start=deferred();f.owner.start=async()=>{f.calls.push(['start']);return start.promise;};const r=await f.action.request('fan.setEnabled',{enabled:true},f.context);assert.equal(r.pending,true);assert.equal(r.applied,false);assert.equal(f.values.active,true);assert.equal(f.displays.at(-1).pending,true);await flush();assert.equal(f.calls.length,1);assert.equal((await f.action.request('fan.setEnabled',{enabled:true},f.context)).pending,true);assert.equal(f.calls.length,1);start.resolve({allowed:true,writeReady:false});await flush();assert.deepEqual(f.calls.map(c=>c[0]),['start','apply']);assert.equal(f.displays.at(-1).pending,false);assert.equal(f.values.active,true);});
await check('pending fan accepts newest saved preset without a second startup or blocking other mirror controls',async()=>{const f=fanFixture(),start=deferred();f.owner.start=async()=>{f.calls.push(['start']);return start.promise;};await f.action.request('fan.setEnabled',{enabled:true},f.context);await flush();for(const preset of ['soft','aggressive']){const r=await f.action.request('fan.setPreset',{preset},f.context);assert.equal(r.pending,true);assert.equal(r.saved,true);}assert.equal(f.calls.length,1);start.resolve({allowed:true,writeReady:false});await flush();assert.deepEqual(f.calls.map(c=>c[0]),['start','preset']);assert.equal(f.calls[1][1],'aggressive');assert.deepEqual(f.calls[1][2],savedCurves.aggressive);assert.equal(f.values.active,true);});
await check('explicit OFF cancels waiting startup, late ready cannot turn it back on or apply a stale curve',async()=>{const f=fanFixture(),start=deferred();f.owner.start=async()=>{f.calls.push(['start']);return start.promise;};await f.action.request('fan.setEnabled',{enabled:true},f.context);await flush();await f.action.request('fan.setEnabled',{enabled:false},f.context);assert.equal(f.values.active,false);start.resolve({allowed:true,writeReady:true});await flush();assert.deepEqual(f.calls.map(c=>c[0]),['start','disable']);assert.equal(f.values.active,false);assert.equal(f.displays.at(-1).active,false);});
await check('real owner startup failure is reported without silently reverting the registered ON intent',async()=>{const f=fanFixture();f.owner.start=async()=>{throw Error('original owner reported unavailable');};const r=await f.action.request('fan.setEnabled',{enabled:true},f.context);assert.equal(r.pending,true);await flush();assert.equal(f.values.active,true);assert.equal(f.displays.at(-1).active,true);assert.match(f.displays.at(-1).notice,/尚未确认/);assert.equal(f.displays.at(-1).pending,false);assert.equal(f.calls.length,0);});
await check('closing the mirror owner suppresses late startup receipts without any new writer or retry',async()=>{const f=fanFixture(),start=deferred();f.owner.start=()=>start.promise;await f.action.request('fan.setEnabled',{enabled:true},f.context);await flush();const count=f.displays.length;f.action.stop();start.resolve({allowed:true,writeReady:true});await flush();assert.equal(f.displays.length,count);assert.equal(f.calls.length,0);});
await check('peer lifetime is not a hardware deadline after accepted fan intent; initial power admission still protects writes',async()=>{const f=fanFixture(),start=deferred();let live=true;f.context.checkpoint=()=>{if(!live)throw Error('peer closed');};f.owner.start=()=>start.promise;await f.action.request('fan.setEnabled',{enabled:true},f.context);live=false;start.resolve({allowed:true,writeReady:true});await flush();assert.equal(f.values.active,true);assert.equal(f.calls[0][0],'apply');const blocked=fanFixture();blocked.values.power.phase='pending';await assert.rejects(blocked.action.request('fan.setEnabled',{enabled:true},blocked.context),/POWER_NOT_READY/);assert.equal(blocked.values.active,false);});


await check('slow explicit OFF also acknowledges cancellation without waiting for OEM release or falsely claiming it completed',async()=>{const f=fanFixture(),release=deferred();f.values.active=true;f.owner.disable=async()=>{f.calls.push(['disable']);await release.promise;f.owner.hasControlIntent=false;return {state:'AwaitingControl'};};const result=await f.action.request('fan.setEnabled',{enabled:false},f.context);assert.equal(result.pending,true);assert.equal(result.applied,false);assert.equal(f.values.active,false);await flush();assert.equal(f.calls.length,1);release.resolve();await flush();assert.equal(f.values.active,false);assert.match(f.displays.at(-1).notice,/关闭/);});
const expression=fs.readFileSync(path.join(root,'src/views/FanView.vue'),'utf8').replace(/\r\n/g,'\n');const original=fs.readFileSync(path.join(task,'validation/mainline15-preimage/src/views/FanView.vue'),'utf8').replace(/\r\n/g,'\n');
await check('all original FanView business source preserved outside marked observation addition',()=>{const stripped=expression.replace("\nimport { onFanMirrorDisplay, registerFanMirrorUiBlocker, notifyFanMirrorUiGate } from '@/bridge/deckyFanDisplay';",'').replace(/\/\/ YMCC Decky sidebar: observation-only additions; original business functions remain unchanged\.[\s\S]*?onUnmounted\(\(\) => \{ stopFanMirrorBlocker\(\); stopFanMirrorDisplay\(\); \}\);\n/,'');assert.equal(stripped.replace(/\r\n/g,'\n'),original.replace(/\r\n/g,'\n').replace(/^\uFEFF/,''));});
await check('original suspended owner with cached active/readiness cannot report applied no-op',async()=>{const f=fanFixture();f.values.active=true;f.owner.hasControlIntent=true;f.owner.controlReady=true;f.owner.state='suspended';await f.action.execute('fan.setEnabled',{enabled:true},f.context);assert.deepEqual(f.calls.map(call=>call[0]),['start','apply']);});
fs.writeFileSync(path.resolve(task,'validation/MIRROR-MUTATION-SELFTEST.json'),JSON.stringify({project:'YMCC Decky 侧边栏',cases:cases.length,results:cases,realHardware:false,userConfigWrites:false,originalFanLogicPreserved:true},null,2));console.log(`Mutation/fan mirror tests passed: ${cases.length}`);
