import { task } from './fixtures/decky_task_paths.mjs';
// Server-side admission must be private and tied to the exact public revision.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {root,load} from './fixtures/decky_game_memory_store.mjs';
const steam=load(fs.readFileSync(path.join(root,'decky-plugin/src/steamRunningContext.ts'),'utf8'));const {ReadOnlyMirrorRelay}=load(fs.readFileSync(path.join(root,'src/bridge/deckyMirrorRelay.ts'),'utf8'),{'../../decky-plugin/src/steamRunningContext':steam});
const runId='a'.repeat(32),peer={connection:'1',runId,connected:true};const flush=async()=>{for(let i=0;i<80;i++)await Promise.resolve();},defer=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
function fixture(){const state={admission:{entry:'private-original-entry',schedule:'private-original-schedule'},captures:[],replies:[]};let override;
 const relay=new ReadOnlyMirrorRelay({read:async()=>({gameAdmission:state.admission,generation:1,ready:true,actions:{game:true,fan:false},game:{label:'Game',identity:'fixture-game',fields:{}},fan:{supported:false,enabled:false,preset:'',choices:[]}}),observe:()=>()=>{},reply:async(_c,message)=>{state.replies.push(message);return true;},execute:async(command,args,context)=>{state.captures.push({command,args,context});if(override)return override(context);return {saved:true,applied:false,notice:'original save admitted'};}});
 const open=()=>relay.request({...peer,request:{command:'snapshot',runId}});const packet=(sequence=1,more={})=>({...peer,request:{command:'game.setField',runId,id:'private:'+sequence,clientId:'private',sequence,generation:1,revision:1,identity:'fixture-game',args:{field:'acMode',value:'performance'},...more}});
 return {relay,state,open,packet,setExecute:value=>override=value};}
const cases=[];async function check(name,fn){await fn();cases.push(name);}
await check('private admission is absent from JSON reply/public snapshot, not a client-visible profile copy',async()=>{const f=fixture();await f.open();const snapshot=f.state.replies[0].snapshot;assert.ok(!Object.hasOwn(snapshot,'gameAdmission'));assert.ok(!JSON.stringify(f.state.replies).includes('private-original'));assert.equal(snapshot.game.identity,'fixture-game');f.relay.dispose();});
await check('accepted public revision passes its private admission to action only',async()=>{const f=fixture();await f.open();await f.relay.request(f.packet());const context=f.state.captures[0].context;assert.equal(context.gameAdmission.entry,'private-original-entry');assert.equal(context.gameAdmission.schedule,'private-original-schedule');assert.equal(context.gameIdentity,'fixture-game');assert.ok(!JSON.stringify(f.state.replies).includes('private-original'));f.relay.dispose();});
await check('provider mutation after snapshot cannot change the private copy associated with that revision',async()=>{const f=fixture();await f.open();f.state.admission.entry='mutated-provider-reference';await f.relay.request(f.packet());assert.equal(f.state.captures[0].context.gameAdmission.entry,'private-original-entry');f.relay.dispose();});
await check('client cannot inject or renew server admission through packet/argument extras',async()=>{const f=fixture();await f.open();for(const packet of [f.packet(1,{gameAdmission:{entry:'injected',schedule:'injected'}}),f.packet(2,{args:{field:'acMode',value:'performance',gameAdmission:{entry:'injected'}}})])await f.relay.request(packet);assert.equal(f.state.captures.length,0);assert.ok(f.state.replies.filter(message=>message.type==='reply').every(message=>message.ok===false));f.relay.dispose();});
await check('new source read binds new private admission to new revision; old request cannot borrow it',async()=>{const f=fixture();await f.open();f.state.admission={entry:'new-private',schedule:'new-preset'};f.relay.invalidate();await flush();assert.equal(f.state.replies.filter(message=>message.type==='snapshot').at(-1).snapshot.revision,2);await f.relay.request(f.packet());assert.equal(f.state.captures.length,0);await f.relay.request(f.packet(2,{revision:2}));assert.equal(f.state.captures[0].context.gameAdmission.entry,'new-private');f.relay.dispose();});
await check('source changes while an accepted action is pending cannot renew its captured private data',async()=>{const f=fixture(),gate=defer();f.setExecute(async context=>{await gate.promise;assert.equal(context.gameAdmission.entry,'private-original-entry');return {saved:false,applied:false,notice:'checked original captured source'};});await f.open();const action=f.relay.request(f.packet());await flush();f.state.admission={entry:'later-source',schedule:'later-presets'};f.relay.invalidate();gate.resolve();await action;await flush();assert.equal(f.state.captures.length,1);f.relay.dispose();});
await check('source conflict yields specific no-save/refresh/no-retry message, not a fake hardware outcome',async()=>{const f=fixture();f.setExecute(async()=>{throw new Error('GAME_MIRROR_SOURCE_CHANGED');});await f.open();await f.relay.request(f.packet());const reply=f.state.replies.find(message=>message.type==='reply');assert.equal(reply.ok,false);assert.match(reply.error,/未保存.*更新.*不自动重试/);assert.equal(reply.result,undefined);f.relay.dispose();});
await check('deduplicated source-conflict receipt does not retry a changed file or reacquire business owner',async()=>{const f=fixture();f.setExecute(async()=>{throw new Error('GAME_MIRROR_SOURCE_CHANGED');});await f.open();const packet=f.packet();await f.relay.request(packet);await flush();f.state.admission={entry:'new',schedule:'new'};await f.relay.request(packet);assert.equal(f.state.captures.length,1);assert.equal(f.state.replies.filter(message=>message.type==='reply').length,2);f.relay.dispose();});
const record={project:'YMCC Decky 侧边栏',stage:'Implementation11',cases:cases.length,results:cases,exactProductionRelay:true,privateAdmissionOnWire:false,publicClientSchemaChanged:false,businessFiles:0,hardware:0};fs.writeFileSync(path.resolve(task,'validation/PRIVATE-ADMISSION-IMPLEMENTATION11.json'),JSON.stringify(record,null,2));console.log(`Server-private admission checks passed: ${cases.length}`);
