import { task } from './fixtures/decky_task_paths.mjs';
// Complete unchanged original GameCustom store with a shared memory-only fs.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {root,fixture,base,profile,seed,gamePolicyKey,main,backup} from './fixtures/decky_game_memory_store.mjs';
const cases=[];const evidence=[];
async function check(name,action){const result=await action();cases.push(name);if(result)evidence.push({name,...result});}
const plain=value=>JSON.parse(JSON.stringify(value));
const deferred=()=>{let resolve;const promise=new Promise(done=>{resolve=done;});return {promise,resolve};};
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
await check('valid old document loads without migration, new file or business writes',async()=>{const f=fixture();const value=await f.store.loadGameCustomConfig();assert.equal(value.entries['game.exe'].acMode,'balanced');assert.equal(f.stats().fakeWrites,0);assert.equal(f.documents.size,1);return f.stats();});
await check('Steam and non-Steam observations reach the same remembered EXE entry',async()=>{const f=fixture();const value=await f.store.loadGameCustomConfig();const a=gamePolicyKey({path:'C:/Games/Game.exe',steamAppId:'480'}),b=gamePolicyKey({path:'C:/Games/Game.exe'});assert.equal(a,b);assert.equal(value.entries[a].acMode,value.entries[b].acMode);assert.deepEqual(Object.keys(value.entries).sort(),['game.exe','other.exe']);});
await check('normal old EXE edit uses original atomic main/backup paths only',async()=>{const f=fixture();const value=await f.store.loadGameCustomConfig();value.entries['game.exe'].acMode='performance';await f.store.saveGameCustomConfig(value);assert.equal(f.raw().entries['game.exe'].acMode,'performance');assert.deepEqual([...f.documents.keys()].sort(),[main,backup].sort());assert.ok(f.calls.every(call=>call[1]===main||call[1]===backup));assert.ok(!Object.hasOwn(f.raw().entries['game.exe'],'steamAppId'));return f.stats();});
await check('RTSS-only map and other EXE profiles remain unchanged after the edit',async()=>{const initial=seed(),f=fixture(initial),value=await f.store.loadGameCustomConfig();const priorRtss=plain(value.rtss);value.entries['game.exe'].dcMode='performance';await f.store.saveGameCustomConfig(value);assert.deepEqual(f.raw().rtss,priorRtss);assert.deepEqual(f.raw().entries['other.exe'],plain(value.entries['other.exe']));});
await check('original writer retains opaque top/entry fields already on disk',async()=>{const initial=seed();initial.opaque={flag:'keep'};initial.entries['game.exe'].vendorFuture={number:'18446744073709551615'};const f=fixture(initial),value=await f.store.loadGameCustomConfig();assert.equal(value.entries['game.exe'].vendorFuture,undefined);value.entries['game.exe'].acMode='extreme';await f.store.saveGameCustomConfig(value);assert.deepEqual(f.raw().opaque,initial.opaque);assert.deepEqual(f.raw().entries['game.exe'].vendorFuture,initial.entries['game.exe'].vendorFuture);});
await check('existing mixed-case names normalize exactly as before, not to SteamID',async()=>{const initial=seed();initial.entries={'Game.EXE':profile(18),'game.exe':profile(32)};const f=fixture(initial),value=await f.store.loadGameCustomConfig();assert.deepEqual(Object.keys(value.entries),['game.exe']);assert.equal(value.entries['game.exe'].ac.tdpMax,18);});
await check('old snapshots survive a load/save without invented dynamic inheritance',async()=>{const initial=seed();delete initial.entries['game.exe'].acMode;delete initial.entries['game.exe'].dcMode;initial.entries['game.exe'].ac.tdpMax=27;const f=fixture(initial),value=await f.store.loadGameCustomConfig();await f.store.saveGameCustomConfig(value);assert.equal(f.raw().entries['game.exe'].ac.tdpMax,27);assert.ok(!Object.hasOwn(f.raw().entries['game.exe'],'acMode'));assert.ok(!Object.hasOwn(f.raw().entries['game.exe'],'inheritAc'));});
await check('disabled old entry stays disabled across an original store edit',async()=>{const initial=seed();initial.entries['game.exe'].enabled=false;const f=fixture(initial),value=await f.store.loadGameCustomConfig();value.entries['game.exe'].acMode='performance';await f.store.saveGameCustomConfig(value);assert.equal(f.raw().entries['game.exe'].enabled,false);});
await check('failed save neither publishes a new cache nor blocks the next save',async()=>{const f=fixture(),value=await f.store.loadGameCustomConfig();value.entries['game.exe'].acMode='extreme';f.failNext();await assert.rejects(f.store.saveGameCustomConfig(value),/memory-only write failure/);assert.equal(f.store.getGameCustomConfig().entries['game.exe'].acMode,'balanced');assert.equal(f.stats().notifications,0);await f.store.saveGameCustomConfig(value);assert.equal(f.store.getGameCustomConfig().entries['game.exe'].acMode,'extreme');assert.equal(f.stats().notifications,1);});
await check('load waits for the pending original save queue and reads committed state',async()=>{const f=fixture(),value=await f.store.loadGameCustomConfig(),gate=deferred();value.entries['game.exe'].acMode='performance';f.holdNext(gate.promise);const save=f.store.saveGameCustomConfig(value);await flush();let loaded=false;const load=f.store.loadGameCustomConfig().then(value=>{loaded=true;return value;});await flush();assert.equal(loaded,false);gate.resolve();await save;assert.equal((await load).entries['game.exe'].acMode,'performance');});
await check('original listeners receive detached snapshots; reader mutation cannot change cache',async()=>{const f=fixture(),value=await f.store.loadGameCustomConfig();f.store.onGameCustomConfigChanged(snapshot=>{snapshot.entries['game.exe'].acMode='eco';});await f.store.saveGameCustomConfig(value);const cached=f.store.getGameCustomConfig();cached.entries['game.exe'].acMode='extreme';assert.equal(f.store.getGameCustomConfig().entries['game.exe'].acMode,'balanced');});
await check('expected boundary: original whole-document save serializes but does not merge stale known maps',async()=>{const f=fixture(),one=await f.store.loadGameCustomConfig(),two=structuredClone(one);one.entries['game.exe'].acMode='performance';two.entries['other.exe'].acMode='extreme';await Promise.all([f.store.saveGameCustomConfig(one),f.store.saveGameCustomConfig(two)]);assert.equal(f.raw().entries['game.exe'].acMode,'balanced');assert.equal(f.raw().entries['other.exe'].acMode,'extreme');return {characterization:'Stale full-document replacement reproduced; future mirror must read fresh after acquiring original shared lock, not patch old snapshots',bugFixedInOriginalStore:false};});
await check('prep recipe: original shared lock refuses overlap with the original panel',async()=>{const f=fixture(),release=f.lock.tryAcquireQuickAction('top-custom-profile-select-mode');assert.ok(release);assert.equal(f.lock.tryAcquireQuickAction('decky-game-mirror'),null);assert.equal(f.stats().fakeWrites,0);release();const acquired=f.lock.tryAcquireQuickAction('decky-game-mirror');assert.ok(acquired);acquired();assert.equal(f.lock.isQuickActionBusy(),false);});
await check('prep recipe: fresh original load under shared lock preserves the preceding panel change',async()=>{const f=fixture(),panel=await f.store.loadGameCustomConfig();panel.entries['other.exe'].acMode='extreme';await f.store.saveGameCustomConfig(panel);const release=f.lock.tryAcquireQuickAction('decky-game-mirror');assert.ok(release);try{const fresh=await f.store.loadGameCustomConfig();fresh.entries['game.exe'].acMode='performance';await f.store.saveGameCustomConfig(fresh);}finally{release();}assert.equal(f.raw().entries['other.exe'].acMode,'extreme');assert.equal(f.raw().entries['game.exe'].acMode,'performance');});
await check('EXE deletion remains durable; no Steam mapping or unified section revives it',async()=>{const f=fixture(),value=await f.store.loadGameCustomConfig();delete value.entries['game.exe'];await f.store.saveGameCustomConfig(value);assert.equal((await f.store.loadGameCustomConfig()).entries['game.exe'],undefined);assert.equal(f.raw().entries['game.exe'],undefined);});
const record={project:'YMCC Decky 侧边栏',stage:process.argv.includes('--stage14')?'Implementation14':process.argv.includes('--stage13')?'Implementation13':process.argv.includes('--stage12')?'Implementation12':process.argv.includes('--stage11')?'Implementation11':process.argv.includes('--stage09')?'Implementation09':'Implementation08',dateHongKong:'2026-10-09',cases:cases.length,results:cases,evidence,completeOriginalStoreExecuted:true,originalSharedLockExecuted:true,originalMergeAndSnapshotExecuted:true,storeFileReadInHost:'source only',realBusinessFileReads:0,realBusinessFileWrites:0,hardwareCalls:0,nativeCalls:0,originalModelEdited:false,steamIdPersisted:false,deliveryDependencyChanges:0,gameWriteAdapterWired:false};
fs.writeFileSync(path.resolve(task,process.argv.includes('--stage14')?'validation/GAME-STORE-MEMORY-IMPLEMENTATION14.json':process.argv.includes('--stage13')?'validation/GAME-STORE-MEMORY-IMPLEMENTATION13.json':process.argv.includes('--stage12')?'validation/GAME-STORE-MEMORY-IMPLEMENTATION12.json':process.argv.includes('--stage11')?'validation/GAME-STORE-MEMORY-IMPLEMENTATION11.json':process.argv.includes('--stage09')?'validation/GAME-STORE-MEMORY-IMPLEMENTATION09.json':'validation/GAME-STORE-MEMORY-IMPLEMENTATION08.json'),JSON.stringify(record,null,2));
console.log(`Original EXE store memory-only tests passed: ${cases.length}`);
