// Exact local anchored component, not a desktop-only native position assumption.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {createRequire} from 'node:module';import {root,task} from './fixtures/decky_task_paths.mjs';
const require=createRequire(path.join(root,'package.json')),{transformSync}=require('esbuild'),source=fs.readFileSync(path.join(root,'decky-plugin/src/AnchoredDropdown.tsx'),'utf8');
const refs=[{current:{querySelector:()=>({focus:()=>optionFocus++}),querySelectorAll:()=>options,ownerDocument:{visibilityState:'visible',get activeElement(){return active;}}}},{current:{element:{focus:()=>triggerFocus++}}},{current:false}];let ri=0,optionFocus=0,triggerFocus=0,active=null,opened=0,cancelled=0,changes=[];const effects=[],options=[0,1,2].map(index=>({focus:()=>active=options[index]}));
const react={createElement:(type,props,...children)=>({type,props,children}),useRef:()=>refs[ri++],useEffect:fn=>effects.push(fn)},DFL={DropdownItem:'DropdownItem',Focusable:'Focusable'},module={exports:{}};
vm.runInNewContext(transformSync(source,{loader:'tsx',format:'cjs',jsxFactory:'SP_REACT.createElement'}).code,{module,exports:module.exports,SP_REACT:react,DFL});
const props={label:'core',selectedOption:'a',rgOptions:[{data:'a',label:'first'},{data:'b',label:'last'},{data:'follow',label:'global',disabled:true}],disabled:false,opened:false,onMenuWillOpen:show=>{opened++;show();return false;},onCancel:()=>cancelled++,onChange:choice=>changes.push(choice.data)};
const render=()=>{ri=0;effects.length=0;return module.exports.AnchoredDropdown(props);};const cases=[];const check=(name,fn)=>{fn();cases.push(name);};
check('native trigger intercept always returns false: centered Steam menu is never called',()=>{const tree=render(),trigger=tree.children[0];assert.equal(trigger.props.controlled,true);assert.equal(trigger.props.onMenuWillOpen(),false);assert.equal(opened,1);assert.equal(tree.children[1],false);});
check('list is a child immediately after trigger, native focusable option order preserved',()=>{props.opened=true;const tree=render(),list=tree.children[1];assert.equal(list.props.role,'listbox');assert.equal(list.props['flow-children'],'column');assert.deepEqual(Array.from(list.children[0],n=>n.children[0]),['first','last','global']);assert.equal(list.children[0][2].props.focusable,false);effects.forEach(fn=>fn());assert.equal(optionFocus,1);});
check('cancelled dropdown returns focus to its own original native trigger',()=>{props.opened=false;render();effects.forEach(fn=>fn());assert.equal(triggerFocus,1);});
check('Escape and Steam B cancellation are consumed within the QAM list',()=>{props.opened=true;let stopped=0;const tree=render(),event={key:'Escape',preventDefault:()=>stopped++,stopPropagation:()=>stopped++};tree.props.onKeyDownCapture(event);assert.equal(cancelled,1);tree.children[1].props.onCancel(event);assert.equal(cancelled,2);assert.equal(stopped,4);});
check('keyboard Home/End and arrows focus available options without auto-applying a value',()=>{const tree=render();const event=key=>({key,preventDefault(){},stopPropagation(){}});tree.props.onKeyDownCapture(event('Home'));assert.equal(active,options[0]);tree.props.onKeyDownCapture(event('ArrowDown'));assert.equal(active,options[1]);tree.props.onKeyDownCapture(event('End'));assert.equal(active,options[2]);assert.equal(changes.length,0);});
check('disabled global choice cannot activate; explicit option delegates one selected data',()=>{const list=render().children[1];list.children[0][2].props.onActivate();assert.equal(changes.length,0);list.children[0][1].props.onActivate();assert.deepEqual(changes,['b']);});
fs.writeFileSync(path.join(task,'validation/MAINLINE22-ANCHORED-DROPDOWN.json'),JSON.stringify({cases:cases.length,results:cases,productionComponent:true,actualSteamFocus:false,hardwareWrites:0},null,2));console.log('Anchored dropdown PASS '+cases.length);
