import { task } from './fixtures/decky_task_paths.mjs';
// Windows native broker -> exact production host/relay/actions -> original
// memory-backed store. Steam/WebView/device IPC remain explicitly out of scope.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';
import {root,load,main} from './fixtures/decky_game_memory_store.mjs';import {createMirrorHostFixture} from './fixtures/decky_mirror_host_fixture.mjs';import {SocketAdapter,awaitState,deferred,bounded} from './fixtures/decky_native_transport.mjs';
const steam=load(fs.readFileSync(path.join(root,'decky-plugin/src/steamRunningContext.ts'),'utf8'));
const {MirrorClient}=load(fs.readFileSync(path.join(root,'decky-plugin/src/mirrorClient.ts'),'utf8'),{'./steamRunningContext':steam});
const file=path.resolve(task,'Build/decky-sidebar-broker-test.exe');
const child=spawn(file,['--serve-relay-fixture'],{windowsHide:true,stdio:['pipe','pipe','pipe']});let stderr='',buffer='',host,client,attachWait=null,requested=0;const sockets=[],cases=[];
child.stderr.on('data',data=>stderr+=String(data));const terminal=new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',(code,signal)=>resolve({code,signal}));});const boot=deferred(),summary=deferred();
child.stdout.on('data',data=>{buffer+=data;for(;;){const end=buffer.indexOf('\n');if(end<0)break;const line=buffer.slice(0,end).trim();buffer=buffer.slice(end+1);if(!line)continue;try{const event=JSON.parse(line);if(event.endpoint)boot.resolve(event);else if(event.type==='peer')host?.emit('deckySidebar.mirrorPeer',event);else if(event.type==='request'){requested++;host?.emit('deckySidebar.mirrorRequest',event);}else if(event.type==='attach')attachWait?.resolve(event);else if(event.endpointReleased)summary.resolve(event);}catch(error){summary.reject(error);}}});
const flush=async()=>{for(let i=0;i<80;i++)await Promise.resolve();};
async function waitObserverGone(){const until=Date.now()+1500;while(Date.now()<until){if(host.observerStats().watchers===0)return;await new Promise(resolve=>setTimeout(resolve,15));}throw new Error('Host observer detach deadline');}
try{
 const bootstrap=await bounded(boot.promise,'native bootstrap');
 host=await createMirrorHostFixture({invoke:async(command,args)=>{if(command==='deckySidebar.mirrorReply'){child.stdin.write(JSON.stringify(args)+'\n');return true;}if(command==='deckySidebar.mirrorAttach'){attachWait=deferred();child.stdin.write('attach\n');const task=attachWait;return bounded(task.promise,'native host attach').finally(()=>{if(attachWait===task)attachWait=null;});}throw new Error('Unexpected native operation '+command);}});
 host.ready();await flush();
 client=new MirrorClient({bootstrap:()=>bootstrap,socket:url=>{const socket=new SocketAdapter(url);sockets.push(socket);return socket;},schedule:(fn,delay)=>setTimeout(fn,delay),cancel:clearTimeout,clientId:'actual-host-pipeline',steam:()=>({availability:'observed',appId:'480',runningCount:1})});
 client.setVisible(true);const first=await awaitState(client,state=>state.connected&&state.snapshot?.ready);
 assert.equal(first.snapshot.actions.game,true);assert.equal(first.snapshot.game.fields.corePolicyMode.value,'big-small');assert.equal(first.snapshot.game.fields.acMode.value,'follow');assert.equal(first.snapshot.steam.appId,'480');assert.ok(!first.notice.includes('默认核心'));assert.equal(host.counts.saves,0);assert.equal(host.counts.power,1);assert.equal(host.counts.capabilities,1);cases.push('real Windows native broker and production Client consume exact production host snapshot/defaults with zero saves');
 const edits=[['acMode','performance'],['dcMode','extreme'],['corePolicyMode','only-small'],['hyperThreadPolicy','off'],['padPersona','elite'],['gyroOverride','fps']];
 let firstPacket;
 for(const [field,value] of edits){const result=await client.mutate('game.setField',{field,value});assert.equal(result.saved,true);assert.equal(result.applied,false);assert.equal(result.pending,true);await awaitState(client,state=>state.snapshot?.game?.fields[field].value===value);if(!firstPacket)firstPacket=sockets[0].sent.find(packet=>packet.command==='game.setField');}
 assert.equal(host.counts.saves,6);assert.equal(host.memory.raw().entries['game.exe'].enabled,true);assert.equal(host.counts.joyxoff,0);assert.equal(host.counts.fanSaves,0);cases.push('all six dropdown fields pass Client/native/host/adapter/original store without a second hardware owner');
 let priorSaves=host.counts.saves;const receipt=deferred();const packet=firstPacket;sockets[0].addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.type==='reply'&&message.id===packet.id)receipt.resolve(message);});sockets[0].send(JSON.stringify(packet));assert.equal((await bounded(receipt.promise,'cached game ACK')).ok,true);assert.equal(host.counts.saves,priorSaves);cases.push('original receipt cache prevents duplicate save after lost ACK across the complete host pipeline');
 const changed=host.memory.raw();changed.entries['game.exe'].corePolicyMode='all';changed.entries['game.exe'].corePolicyEnabled=true;host.memory.documents.set(main,JSON.stringify(changed));
 await assert.rejects(client.mutate('game.setField',{field:'acMode',value:'eco'}),/原方案已变化/);assert.equal(host.counts.saves,priorSaves);await awaitState(client,state=>state.snapshot?.game?.fields.corePolicyMode.value==='all');
 assert.equal(host.memory.raw().entries['game.exe'].acMode,'performance');assert.equal(host.memory.lock.isQuickActionBusy(),false);cases.push('silent original-file policy change is rejected without saving, then exact host refreshes before a new explicit intent');
 assert.ok(!Object.hasOwn(client.snapshot().snapshot,'gameAdmission'));assert.ok(sockets.every(socket=>socket.sent.every(packet=>!Object.hasOwn(packet,'gameAdmission'))));cases.push('private admission never crosses production native/plugin wire or requires a new public client field');
 const safe=await client.mutate('game.setField',{field:'acMode',value:'eco'});assert.equal(safe.saved,true);await awaitState(client,state=>state.snapshot?.game?.fields.acMode.value==='eco');assert.equal(host.memory.raw().entries['game.exe'].corePolicyMode,'all');priorSaves=host.counts.saves;
 const old=client.snapshot().snapshot;host.state.power={...host.state.power,generation:2,phase:'pending',hardwareWritesAllowed:false};host.powerChanged(true);await awaitState(client,state=>state.snapshot?.generation===2&&!state.snapshot.ready);await assert.rejects(client.mutate('game.setField',{field:'acMode',value:'eco'}));assert.equal(host.counts.saves,priorSaves);cases.push('committed host pending-power snapshot disables mutations before original settings IO');
 client.setVisible(false);await waitObserverGone();const counts=structuredClone(host.counts);host.state.power={...host.state.power,phase:'ready',hardwareWritesAllowed:true};host.powerChanged();host.scheduleChanged();await flush();assert.equal(host.counts.power,counts.power);assert.equal(host.counts.schedule,counts.schedule);cases.push('hidden QAM disconnects exact host observers; power/config events add zero reads while hidden');
 client.setVisible(true);const reopened=await awaitState(client,state=>state.connected&&state.snapshot?.ready&&state.snapshot.generation===2);assert.equal(reopened.snapshot.game.fields.acMode.value,'eco');assert.equal(host.counts.saves,priorSaves);cases.push('reopen binds existing native transport and exact host with fresh generation and remembered EXE settings');
 host.stop();host.start();host.ready();const remounted=await awaitState(client,state=>state.snapshot?.revision>reopened.snapshot.revision);assert.equal(remounted.snapshot.game.fields.gyroOverride.value,'fps');assert.equal(sockets.length,2);cases.push('host renderer remount uses actual native mirrorAttach revision without opening another socket or losing EXE memory');
 host.state.game={...host.state.game,pid:202,processCreated:'987654321',name:'Offline.exe',title:'Offline',path:'D:/GOG/Offline.exe'};host.gameChanged();const nonSteam=await awaitState(client,state=>state.snapshot?.game?.label==='Offline');assert.match(nonSteam.snapshot.game.identity,/offline\.exe/);assert.equal(nonSteam.snapshot.game.fields.acMode.value,'follow');await client.mutate('game.setField',{field:'acMode',value:'balanced'});await awaitState(client,state=>state.snapshot?.game?.fields.acMode.value==='balanced');assert.equal(host.memory.raw().entries['offline.exe'].enabled,true);assert.equal(host.memory.raw().entries['game.exe'].acMode,'eco');assert.ok(!Object.hasOwn(host.memory.raw().entries['offline.exe'],'steamAppId'));cases.push('new non-Steam EXE uses same host map even when Steam AppID observation remains present');
 host.state.game=null;host.gameChanged();await awaitState(client,state=>state.connected&&state.snapshot?.game===null);assert.equal(client.snapshot().snapshot.actions.game,false);assert.equal(client.snapshot().snapshot.actions.fan,true);cases.push('no confirmed game closes game actions without shutting down the global fan mirror');
 client.setVisible(false);await waitObserverGone();client.dispose();host.stop();child.stdin.end('stop\n');const native=await bounded(summary.promise,'native stop summary'),exit=await bounded(terminal,'native broker exit');assert.equal(exit.code,0);assert.equal(native.activeAfterStop,false);assert.equal(native.endpointReleased,true);assert.deepEqual(host.observerStats(),{ipc:0,game:0,schedule:0,fan:0,watchers:0});cases.push('all original host observers, client sockets and native broker handles released on shutdown');
 const report={project:'YMCC Decky 侧边栏',stage:process.argv.includes('--stage14')?'Implementation14':process.argv.includes('--stage13')?'Implementation13':process.argv.includes('--stage12')?'Implementation12':process.argv.includes('--stage11')?'Implementation11':'Implementation10',dateHongKong:'2026-10-09',cases:cases.length,results:cases,platform:process.platform,status:'passed',actualNativeBroker:true,productionClient:true,exactProductionHost:true,productionRelayAndAdapters:true,originalStoreAndLock:true,hostCounts:host.counts,memoryStoreStats:host.memory.stats(),nativeSummary:native,requested,actualWebView:false,actualSteam:false,physicalHardwareWrites:0,realBusinessConfigWrites:0,actualJoyxoffOperations:0};fs.writeFileSync(path.resolve(task,process.argv.includes('--stage14')?'validation/MIRROR-HOST-NATIVE-PIPELINE-IMPLEMENTATION14.json':process.argv.includes('--stage13')?'validation/MIRROR-HOST-NATIVE-PIPELINE-IMPLEMENTATION13.json':process.argv.includes('--stage12')?'validation/MIRROR-HOST-NATIVE-PIPELINE-IMPLEMENTATION12.json':process.argv.includes('--stage11')?'validation/MIRROR-HOST-NATIVE-PIPELINE-IMPLEMENTATION11.json':'validation/MIRROR-HOST-NATIVE-PIPELINE-IMPLEMENTATION10.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(error){client?.dispose();host?.stop();for(const socket of sockets)socket.close();if(!child.stdin.destroyed)child.stdin.end('stop\n');await bounded(terminal,'failure broker cleanup').catch(()=>child.kill());throw new Error(`${error.stack}; stderr=${stderr}; counts=${JSON.stringify(host?.counts)}`);}
