// Exact client -> relay -> host -> fan/global adapters. External IO is memory only.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {root,task} from './fixtures/decky_task_paths.mjs';import {load} from './fixtures/decky_game_memory_store.mjs';import {createMirrorHostFixture} from './fixtures/decky_mirror_host_fixture.mjs';
const {MirrorClient}=load(fs.readFileSync(path.join(root,'decky-plugin/src/mirrorClient.ts'),'utf8'),{'./steamRunningContext':load(fs.readFileSync(path.join(root,'decky-plugin/src/steamRunningContext.ts'),'utf8'))});
const flush=async()=>{for(let i=0;i<300;i++)await Promise.resolve();};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const results=[];async function check(name,run){await run();results.push(name);}
async function fixture(options={}){
 const start=deferred(),apply=deferred(),calls=[],fan={active:false,preset:'balanced'},timers=new Map();let counter=0,now=0,host;
 const runId='f'.repeat(32),peer={connection:'1',runId};
 const listeners=new Map(),socket={sent:[],addEventListener:(name,fn)=>listeners.set(name,fn),emit:(name,value)=>listeners.get(name)?.({data:typeof value==='string'?value:JSON.stringify(value)}),send:text=>{const request=JSON.parse(text);socket.sent.push(request);host.emit('deckySidebar.mirrorRequest',{...peer,request});},close:()=>listeners.get('close')?.()};
 const life={controlReady:false,state:'starting',hasControlIntent:false,recoveryActive:false,start:async()=>{calls.push('start');return start.promise;},apply:async()=>{calls.push('apply');life.hasControlIntent=true;await apply.promise;life.state='ready';life.controlReady=true;return {state:'Ready'};},applyPreset:async()=>{calls.push('preset');life.hasControlIntent=true;life.state='ready';life.controlReady=true;return {state:'Ready'};},disable:async()=>{calls.push('disable');await options.disableWait;life.hasControlIntent=false;life.controlReady=false;life.state='awaiting-control';return {state:'AwaitingControl'};}};
 const feature={FAN_IMPORT_ENABLED:true,FAN_FORCE_PREVIEW:false,fanFeatureEnabled:{value:true},fanControlActive:{get value(){return fan.active;}},getFanFeatureSettings:()=>({preset:fan.preset}),getFanPresetCurve:()=>[{tempC:0,dutyPercent:0},{tempC:100,dutyPercent:90}],saveFanCurve:async(_,preset)=>{fan.preset=preset;},setFanControlActive:value=>{fan.active=value;},setFanNavigationDuty:()=>{},recordFanHandshake:async()=>{}};
 host=await createMirrorHostFixture({fanOwner:{lifecycle:life,featureBindings:feature,close:async()=>{}},invoke:async(command,args)=>{if(command==='deckySidebar.mirrorAttach')return {connected:false};if(command==='deckySidebar.mirrorReply'){socket.emit('message',args.message);return true;}if(command==='input.shortcutRuntime.clear')return true;throw Error('Unmocked IO '+command);}});
 host.state.game=null;host.state.input.gyroMotion={enabled:false,preset:'fps'};host.ready();
 const client=new MirrorClient({bootstrap:()=>({runId,endpoint:'ws://127.0.0.1:12345/mirror',token:'INERT-TEST-ONLY'}),socket:()=>socket,clientId:'controls34',schedule:(action,delay)=>{timers.set(++counter,{action,due:now+delay});return counter;},cancel:id=>timers.delete(id)});
 client.setVisible(true);socket.emit('open');await flush();
 const advance=async ms=>{now+=ms;for(const[id,t]of[...timers])if(t.due<=now){timers.delete(id);t.action();}await flush();};
 return {host,client,socket,start,apply,life,fan,calls,timers,advance,stop:()=>{client.dispose();host.stop();}};
}
await check('slow fan ON returns real accepted intent, cancels 4s client deadline and publishes pending snapshot without blocking other controls',async()=>{const f=await fixture();const on=f.client.mutate('fan.setEnabled',{enabled:true},f.client.snapshot().snapshot);await flush();const r=await on;assert.equal(r.pending,true);assert.equal(r.applied,false);assert.equal(f.client.snapshot().busy,false);assert.equal(f.client.snapshot().snapshot.fan.enabled,true);assert.equal(f.client.snapshot().snapshot.fan.pending,true);assert.equal(f.client.snapshot().snapshot.fan.supported,false);assert.equal(f.timers.size,0);await f.advance(60000);assert.equal(f.client.snapshot().snapshot.fan.enabled,true);assert.equal(f.calls.filter(c=>c==='start').length,1);assert.equal(f.client.snapshot().connected,true);
 const gyro=f.client.mutate('global.setField',{field:'gyroEnabled',value:'on'},f.client.snapshot().snapshot);await flush();await gyro;assert.equal(f.host.state.input.gyroMotion.enabled,true);assert.equal(f.client.snapshot().snapshot.fan.enabled,true);assert.equal(f.client.snapshot().busy,false);
 f.start.resolve({allowed:true,writeReady:false});await flush();assert.equal(f.client.snapshot().snapshot.fan.pending,true);f.apply.resolve({});await flush();assert.equal(f.client.snapshot().snapshot.fan.pending,false);assert.equal(f.client.snapshot().snapshot.fan.supported,true);assert.equal(f.client.snapshot().snapshot.fan.enabled,true);assert.deepEqual(f.calls,['start','apply']);f.stop();});
await check('pending fan preset remains an interactive save, not a second startup',async()=>{const f=await fixture();const on=f.client.mutate('fan.setEnabled',{enabled:true});await flush();await on;const save=f.client.mutate('fan.setPreset',{preset:'soft'},f.client.snapshot().snapshot);await flush();await save;assert.equal(f.fan.preset,'soft');assert.equal(f.host.counts.fanSaves,1);f.start.resolve({allowed:true,writeReady:false});await flush();assert.deepEqual(f.calls,['start','preset']);assert.equal(f.client.snapshot().snapshot.fan.pending,false);f.stop();});
await check('client explicit OFF cancels pending original startup and ignores its late confirmation',async()=>{const f=await fixture();const on=f.client.mutate('fan.setEnabled',{enabled:true});await flush();await on;const off=f.client.mutate('fan.setEnabled',{enabled:false},f.client.snapshot().snapshot);await flush();await off;f.start.resolve({allowed:true,writeReady:true});await flush();assert.equal(f.fan.active,false);assert.equal(f.client.snapshot().snapshot.fan.enabled,false);assert.deepEqual(f.calls,['start','disable']);f.stop();});

await check('slow OEM release also frees the client and keeps explicit OFF without claiming hardware release',async()=>{const release=deferred(),f=await fixture({disableWait:release.promise});const on=f.client.mutate('fan.setEnabled',{enabled:true});await flush();await on;f.start.resolve({allowed:true,writeReady:true});f.apply.resolve({});await flush();const off=f.client.mutate('fan.setEnabled',{enabled:false},f.client.snapshot().snapshot);await flush();const r=await off;assert.equal(r.pending,true);assert.equal(r.applied,false);assert.equal(f.client.snapshot().busy,false);assert.equal(f.client.snapshot().snapshot.fan.enabled,false);assert.equal(f.life.hasControlIntent,true);await f.advance(60000);assert.equal(f.client.snapshot().snapshot.fan.enabled,false);assert.equal(f.timers.size,0);release.resolve();await flush();assert.equal(f.life.hasControlIntent,false);assert.equal(f.client.snapshot().snapshot.fan.enabled,false);f.stop();});
await check('all four global preset IDs use the original CAS and keep game entries untouched',async()=>{const f=await fixture();const on=f.client.mutate('global.setField',{field:'gyroEnabled',value:'on'});await flush();await on;for(const preset of ['racing','custom','steam','fps']){const p=f.client.mutate('global.setField',{field:'gyroPreset',value:preset},f.client.snapshot().snapshot);await flush();await p;assert.equal(f.host.state.input.gyroMotion.preset,preset);}assert.equal(f.host.counts.saves,0);assert.equal(f.host.counts.inputSaves,5);assert.deepEqual(f.host.memory.raw().entries,{});assert.equal(f.host.state.input.outputTarget.persona,'steamdeck');f.stop();});
fs.writeFileSync(path.join(task,'validation/CONTROLS34-CLIENT-HOST.json'),JSON.stringify({status:'passed',cases:results.length,results,actualProductionClientHostRelay:true,memoryIOOnly:true,realFanOrGyroWrites:0,realConfigurationWrites:0},null,2));console.log('Controls34 client/host PASS '+results.length);
