// Actual Steam/DFL and current native broker; all business owners stay in memory.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {task} from './fixtures/decky_task_paths.mjs';import {targets,connect} from './fixtures/decky_cdp.mjs';
const sessionFile=process.env.YMCC_DECKY_UI_SESSION_FILE;
assert.ok(sessionFile&&path.resolve(sessionFile).startsWith(path.dirname(task)+path.sep),'Explicit current fixture session required');
const session=()=>JSON.parse(fs.readFileSync(sessionFile,'utf8'));
const output=path.join(task,'validation/SIX-MODULES-NATIVE-UI.json');
const report={actualSteam:true,actualNativeBroker:true,actualDflControls:true,businessOwners:'memory',realProductYmcc:false,realConfigWrites:0,hardwareWrites:0,steps:[]};
const save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2)),sleep=ms=>new Promise(r=>setTimeout(r,ms));let c,q;
const read=`(()=>{const p=document.querySelector('.ymcc-decky-sidebar'),r=e=>e.getBoundingClientRect().toJSON(),label=e=>document.getElementById(e.getAttribute('aria-labelledby'))?.innerText,disabled=e=>{if(e.getAttribute('aria-disabled')==='true'||e.classList.contains('Disabled'))return true;let f=e[Object.keys(e).find(k=>k.startsWith('__reactFiber$'))];for(let i=0;f&&i<12;i++,f=f.return)if(typeof f.memoizedProps?.disabled==='boolean')return f.memoizedProps.disabled;return false;};return {modules:Array.from(p?.querySelectorAll('[data-ymcc-module]')||[]).map(e=>e.dataset.ymccModule),panels:document.querySelectorAll('.ymcc-decky-sidebar').length,combos:Array.from(p?.querySelectorAll('[role=combobox]')||[]).map(e=>({label:e.closest('.ymcc-anchored-dropdown')?.innerText.split(String.fromCharCode(10))[0],text:e.innerText,rect:r(e),focus:e===document.activeElement,disabled:disabled(e)})),checks:Array.from(p?.querySelectorAll('[role=checkbox]')||[]).map(e=>({label:label(e),checked:e.getAttribute('aria-checked'),disabled:disabled(e),rect:r(e)})),sliders:Array.from(p?.querySelectorAll('.ymcc-decky-slider')||[]).map(e=>({label:e.innerText.split(String.fromCharCode(10))[0],value:e.querySelector('[role=slider]')?.getAttribute('aria-valuenow'),max:e.querySelector('[role=slider]')?.getAttribute('aria-valuemax'),track:e.querySelector('[class*=SliderTrack]')?r(e.querySelector('[class*=SliderTrack]')):null,rect:r(e),text:e.innerText})),list:p?.querySelector('[role=listbox]')?r(p.querySelector('[role=listbox]')):null,options:Array.from(p?.querySelectorAll('[role=option]')||[]).map(e=>({text:e.innerText,selected:e.getAttribute('aria-selected')==='true',disabled:e.getAttribute('aria-disabled')==='true',rect:r(e)}))};})()`;
async function ui(){return q.evaluate(read,{awaitPromise:false});}
async function poll(predicate){for(let i=0;i<80;i++){const s=await ui();if(predicate(s))return s;await sleep(75);}throw Error('Current native UI condition deadline');}
function modules(s){assert.equal(s.panels,1);assert.deepEqual(s.modules,['tdp','frames','fan','lossless','virtual','touchpads']);}
function count(){return session().mutationRequests?.length||0;}
async function scroll(label,kind='combo'){
 const selector=kind==='combo'?'.ymcc-anchored-dropdown':'.ymcc-decky-slider';
 await q.evaluate(`(()=>{const e=Array.from(document.querySelectorAll(${JSON.stringify(selector)})).find(e=>e.innerText.split(String.fromCharCode(10))[0]===${JSON.stringify(label)});if(!e)throw Error('Missing control');e.scrollIntoView({block:'center',behavior:'instant'});return true;})()`,{awaitPromise:false});
 // Native QAM focus/scroll animation is independent of browser scrollIntoView.
 // Wait for actual geometry rather than clicking a stale hard-coded 100ms sample.
 let last='',stable=0;for(let i=0;i<30;i++){await sleep(75);const s=await ui(),item=(kind==='combo'?s.combos:s.sliders).find(e=>e.label===label),key=JSON.stringify(item?.rect);stable=key===last?stable+1:0;last=key;if(stable>=2)return s;}throw Error('Control bounds did not settle');
}
async function mouse(rect){assert.ok(rect&&rect.top>=0&&rect.bottom<=(await q.evaluate('innerHeight',{awaitPromise:false}))+1,'Only click visible native control');const x=rect.left+rect.width/2,y=rect.top+rect.height/2;for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});}
async function open(label){const s=await scroll(label),item=s.combos.find(e=>e.label===label);assert.ok(!item.disabled,label+' available');await mouse(item.rect);const opened=await poll(s=>!!s.list),trigger=opened.combos.find(e=>e.label===label);assert.ok(opened.list.top>=trigger.rect.bottom-2);assert.ok(Math.abs(opened.list.left-trigger.rect.left)<1);assert.ok(Math.abs(opened.list.width-trigger.rect.width)<1);return opened;}
async function cancel(label){for(const type of ['keyDown','keyUp'])await q.send('Input.dispatchKeyEvent',{type,key:'Escape',code:'Escape',windowsVirtualKeyCode:27});return poll(s=>!s.list&&s.combos.find(e=>e.label===label)?.focus);}
async function choose(label,predicate){const s=await open(label),index=s.options.findIndex((o,i)=>!o.disabled&&predicate(o,i));assert.ok(index>=0,'Selectable original option '+label);const expected=s.options[index].text;await q.evaluate(`document.querySelectorAll('.ymcc-anchored-options [role=option]')[${index}].scrollIntoView({block:'nearest',behavior:'instant'});true`,{awaitPromise:false});await sleep(150);const current=await ui();await mouse(current.options[index].rect);await poll(s=>!s.list&&s.combos.find(e=>e.label===label)?.text===expected);await sleep(150);return expected;}
async function toggle(label,enabled){let e=await q.evaluate(`(()=>{const e=Array.from(document.querySelectorAll('.ymcc-decky-sidebar [role=checkbox]')).find(e=>document.getElementById(e.getAttribute('aria-labelledby'))?.innerText===${JSON.stringify(label)});if(!e)throw Error('Missing toggle');e.scrollIntoView({block:'center',behavior:'instant'});return true;})()`,{awaitPromise:false});await sleep(250);const state=await ui(),item=state.checks.find(e=>e.label===label);assert.ok(item&&!item.disabled);if(item.checked===String(enabled))return;await mouse(item.rect);await poll(s=>s.checks.find(e=>e.label===label)?.checked===String(enabled));await sleep(150);}
async function drag(label,ratio){const s=await scroll(label,'slider'),item=s.sliders.find(e=>e.label===label);assert.ok(item?.track,'Native slider track '+label);const t=item.track,x=t.left+t.width*ratio,y=t.top+t.height/2;for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});await sleep(100);}
async function memory(change){fs.writeFileSync(session().memoryStateRequestPath,JSON.stringify(change));await sleep(200);}
try{
 const start=session();assert.ok(!start.controllerTerminal&&!start.finishedUtc,'Do not test a stopped fixture');assert.ok(start.events.some(e=>e.type==='loader-security'&&e.unelevated===true),'Native source verified non-admin Loader');
 const list=await targets();c=await connect(list.find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);await c.evaluate('DFL.Navigation.OpenQuickAccessMenu(100019);true');await sleep(300);q=await connect((await targets()).find(t=>t.title.startsWith('QuickAccess')).webSocketDebuggerUrl);
 await memory({game:'initial',powerSource:'ac'});const initial=await poll(s=>s.modules.length===6&&s.combos.some(e=>e.label==='核心调度'));modules(initial);assert.ok(initial.combos.every(e=>Math.abs(e.rect.width-initial.combos[0].rect.width)<1));report.initial=initial;report.preExistingMutations=start.mutationRequests||[];save();
 const beforeMenus=count();for(const label of ['屏幕触摸板','YMCC呼出','专用按键','背部按键','锁帧上限','虚拟手柄','核心调度','游戏变速']){const current=(await ui()).combos.find(e=>e.label===label);if(current?.disabled){assert.ok(['专用按键','背部按键'].includes(label),'Only current persona-specific unsupported controls may be disabled');report.steps.push(label+' remains visible and is correctly disabled for the current original controller persona');continue;}await open(label);await cancel(label);assert.equal(count(),beforeMenus,'Cancel must never mutate any owner: '+label);}report.steps.push('Six game modules present; all currently supported menus expand down/aligned, have uniform widths and Escape returns exact trigger without any business write');save();
 const beforeGlobal=session().hostCounts;await memory({game:null});let s=await poll(s=>!s.combos.some(e=>e.label==='核心调度'));modules(s);assert.ok(s.sliders.some(e=>e.label==='交流电方案'));assert.ok(s.combos.some(e=>e.label==='虚拟手柄'&&!e.disabled));assert.ok(s.checks.find(e=>e.label==='LosslessScaling 插帧')?.disabled===true);report.steps.push('No game still retains all six modules: original global TDP/virtual input usable, LS retained with explicit target requirement, touchpads/fan stay global');save();
 const powerBefore=count(),powerApplies=beforeGlobal.globalPowerApplies;await drag('交流电方案',1);await sleep(1000);assert.equal(count(),powerBefore,'No early global TDP write');await drag('交流电方案',0);await sleep(1000);await drag('交流电方案',1);await sleep(2500);assert.equal(count(),powerBefore,'Intermediate selection renews the complete three-second delay');await sleep(700);assert.equal(count(),powerBefore+1);assert.equal(session().mutationRequests.at(-1).command,'global.setField');assert.equal(session().mutationRequests.at(-1).args.field,'acMode');assert.equal(session().hostCounts.globalPowerApplies,powerApplies+1);assert.equal(session().hostCounts.saves,beforeGlobal.saves);report.steps.push('Actual native global TDP changes commit exactly once only three seconds after final selection, through original power queue and native whitelist');save();
 const framesBefore=session().hostCounts;await drag('插电锁帧 AC',.7);await poll(s=>s.sliders.find(e=>e.label==='插电锁帧 AC')?.text.includes('90 FPS'));assert.equal(session().mutationRequests.at(-1).command,'frame.setField');assert.equal(session().mutationRequests.at(-1).args.field,'acFps');assert.equal(session().hostCounts.globalFrameSaves,framesBefore.globalFrameSaves+1);assert.equal(session().hostCounts.saves,framesBefore.saves);report.steps.push('No-game current AC FPS commits its independent global pair through original frame owner, not the power mode or an EXE profile');save();
 await choose('虚拟手柄',o=>!o.selected);assert.equal(session().mutationRequests.at(-1).command,'global.setField');assert.equal(session().mutationRequests.at(-1).args.field,'padPersona');assert.equal(session().hostCounts.inputSaves,beforeGlobal.inputSaves+1);assert.equal(session().hostCounts.saves,beforeGlobal.saves);report.steps.push('Global virtual controller travels through actual native global whitelist and original input CAS; no EXE dedicated write');save();
 await choose('YMCC呼出',o=>!o.selected);assert.equal(session().mutationRequests.at(-1).command,'touchpad.setField');assert.equal(session().hostCounts.saves,beforeGlobal.saves);report.steps.push('Global touchpad control still saves through original touchpad owner with no game');
 await memory({powerSource:'dc'});s=await poll(s=>s.sliders.some(e=>e.label==='电池锁帧 DC'));modules(s);assert.ok(!s.sliders.some(e=>e.label==='插电锁帧 AC'));await memory({powerSource:'ac'});s=await poll(s=>s.sliders.some(e=>e.label==='插电锁帧 AC'));report.steps.push('Actual memory power events switch independent current AC/DC frame and TDP controls without losing modules');
 await memory({game:'initial'});s=await poll(s=>s.combos.some(e=>e.label==='核心调度'));modules(s);report.steps.push('Returning to the confirmed game restores dedicated controls and advanced core/speed/gyro without dropping any primary module');
 if(!(await ui()).combos.find(e=>e.label==='虚拟手柄')?.text.includes('SteamDeck'))await choose('虚拟手柄',o=>/SteamDeck/i.test(o.text));
 await toggle('陀螺仪',true);let presets=await open('陀螺仪预设');assert.equal(presets.options.filter(o=>!o.disabled).length,4,'All four original gyro presets');await cancel('陀螺仪预设');await choose('陀螺仪预设',o=>!o.selected);assert.equal(session().mutationRequests.at(-1).args.field,'gyroPreset');await toggle('陀螺仪',false);report.steps.push('Four gyro presets are present and anchored; actual native selection uses only original dedicated game gyro owner');
 await toggle('风扇控制（全局）',true);assert.equal(session().mutationRequests.at(-1).command,'fan.setEnabled');assert.equal(session().ownerStats.fan.active,true);await toggle('风扇控制（全局）',false);assert.equal(session().ownerStats.fan.active,false);report.steps.push('Native fan switch uses original global fan lifecycle and releases its memory lease normally');
 await toggle('LosslessScaling 插帧',true);assert.equal(session().ownerStats.lossless.running,true);assert.ok(session().ownerStats.lossless.events.includes('original-launch'));await toggle('LosslessScaling 插帧',false);assert.equal(session().ownerStats.lossless.running,false);assert.ok(session().ownerStats.lossless.events.includes('original-normal-close'));assert.equal(session().ownerStats.lossless.realFilesWritten,0);assert.equal(session().ownerStats.lossless.realProcessesStarted,0);report.steps.push('LosslessScaling native toggle starts/stops original one-click owner in memory only, no second profile writer or launcher');save();
 const reopenCount=count();for(let i=0;i<3;i++){await c.evaluate('DFL.Navigation.CloseSideMenus();true');await sleep(150);await c.evaluate('DFL.Navigation.OpenQuickAccessMenu(100019);true');await sleep(200);modules(await ui());}assert.equal(count(),reopenCount,'Hide/reopen never changes business state');
 report.tabs=await q.evaluate(`Array.from(document.querySelectorAll('[role=tab]')).map(e=>{let f=e[Object.keys(e).find(k=>k.startsWith('__reactFiber$'))];for(let i=0;f&&i<20;i++,f=f.return)if(f.key!=null)return String(f.key);return null;})`,{awaitPromise:false});assert.equal(report.tabs.filter(k=>k==='100019').length,1);assert.equal(report.tabs.filter(k=>k==='999').length,1);report.steps.push('Three close/reopen cycles retain one console and one original Decky home, no business mutation');
 report.final=await ui();report.hostCounts=session().hostCounts;report.mutations=session().mutationRequests;report.pass=true;save();console.log('Six-module actual native Steam UI PASS '+report.steps.length);
}catch(error){report.failure=error.stack;report.hostCounts=session().hostCounts;report.mutations=session().mutationRequests;save();throw error;}finally{q?.close();c?.close();}
