// Actual local Steam + DFL input, with explicitly memory-only frame/touchpad owners.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {root,task} from './fixtures/decky_task_paths.mjs';import {targets,connect} from './fixtures/decky_cdp.mjs';
const sessionFile=path.join(task,'validation/'+(process.env.YMCC_DECKY_UI_RUN_NAME||'MAINLINE23-REAL-UI')+'.json'),out=path.join(task,'validation/MAINLINE23-REAL-UI-ACCEPTANCE.json');
const report={actualSteam:true,actualDflControls:true,businessData:'memory fixture',realProductYmcc:false,physicalControllerTested:false,realConfigWrites:0,hardwareWrites:0,steps:[]};
const session=()=>JSON.parse(fs.readFileSync(sessionFile,'utf8')),save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)),sleep=ms=>new Promise(r=>setTimeout(r,ms));let q,c;
const read=`(()=>{const panel=document.querySelector('.ymcc-decky-sidebar'),rect=e=>e.getBoundingClientRect().toJSON();return {panels:document.querySelectorAll('.ymcc-decky-sidebar').length,text:panel?.innerText,combos:Array.from(panel?.querySelectorAll('[role=combobox]')||[]).map(e=>({label:e.closest('.ymcc-anchored-dropdown')?.innerText.split('\\n')[0],text:e.innerText,rect:rect(e),focus:e===document.activeElement})),options:Array.from(panel?.querySelectorAll('[role=option]')||[]).map(e=>({text:e.innerText,rect:rect(e),disabled:e.getAttribute('aria-disabled')})),list:panel?.querySelector('[role=listbox]')?rect(panel.querySelector('[role=listbox]')):null,sliders:Array.from(panel?.querySelectorAll('.ymcc-decky-slider')||[]).map(e=>({label:e.innerText.split('\\n')[0],text:e.innerText,rect:rect(e),value:e.querySelector('[role=slider]')?.getAttribute('aria-valuenow'),track:e.querySelector('.SliderTrack')?rect(e.querySelector('.SliderTrack')):null})),height:innerHeight};})()`;
async function poll(predicate){for(let i=0;i<70;i++){const state=await q.evaluate(read);if(predicate(state))return state;await sleep(100);}throw Error('Actual QAM timeout '+JSON.stringify(await q.evaluate(read)));}
async function mouse(rect){const x=rect.left+rect.width/2,y=rect.top+rect.height/2;assert.ok(y>=0&&y< (await q.evaluate('innerHeight')),'input target must be on-screen');for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});}
async function scroll(label,kind='combo'){await q.evaluate(`(()=>{const nodes=Array.from(document.querySelectorAll(${JSON.stringify(kind==='combo'?'.ymcc-anchored-dropdown':'.ymcc-decky-slider')}));const node=nodes.find(e=>e.innerText.split('\\n')[0]===${JSON.stringify(label)});node?.scrollIntoView({block:'center'});return !!node;})()`);await sleep(100);}
async function open(label){await scroll(label);const state=await q.evaluate(read),combo=state.combos.find(e=>e.label===label);assert.ok(combo,label);await mouse(combo.rect);return poll(s=>!!s.list);}
function down(label,state){const combo=state.combos.find(e=>e.label===label);assert.ok(state.list.top>=combo.rect.bottom-2,'menu expands down '+label);assert.ok(Math.abs(state.list.left-combo.rect.left)<1,'menu aligned left '+label);assert.ok(Math.abs(state.list.right-combo.rect.right)<1,'menu aligned right '+label);}
async function cancel(label){for(const type of ['keyDown','keyUp'])await q.send('Input.dispatchKeyEvent',{type,key:'Escape',code:'Escape',windowsVirtualKeyCode:27});return poll(s=>!s.list&&s.combos.find(e=>e.label===label)?.focus);}
async function choose(label,option){let s=await open(label);down(label,s);const index=s.options.findIndex(e=>e.text===option);assert.ok(index>=0,'option '+option);await q.evaluate(`document.querySelectorAll('.ymcc-anchored-options [role=option]')[${index}].scrollIntoView({block:'nearest'});true`);s=await q.evaluate(read);await mouse(s.options[index].rect);return poll(s=>!s.list&&s.combos.find(e=>e.label===label)?.text===option);}
async function fps(side,ratio,expected){const label=side==='ac'?'插电锁帧 AC':'电池锁帧 DC';await scroll(label,'slider');const s=await q.evaluate(read),track=s.sliders.find(s=>s.label===label).track;const before=session().mutationRequests?.length||0;
 await q.send('Input.dispatchMouseEvent',{type:'mousePressed',x:track.left+track.width*ratio,y:track.top+track.height/2,button:'left',buttons:1,clickCount:1});await sleep(150);assert.equal(session().mutationRequests?.length||0,before,'dragging FPS is draft-only');
 await q.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:track.left+track.width*ratio,y:track.top+track.height/2,button:'left',buttons:0,clickCount:1});await poll(s=>s.sliders.find(s=>s.label===label)?.text.includes(expected+' FPS'));await sleep(150);const r=session().mutationRequests?.at(-1);assert.equal(r.command,'frame.setField');assert.equal(r.args.field,side+'Fps');assert.equal(r.args.value,String(expected));}
async function state(change){fs.writeFileSync(session().memoryStateRequestPath,JSON.stringify(change));await sleep(150);}
try {
 let list=await targets();c=await connect(list.find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);
 await c.evaluate(`(()=>{DFL.Navigation.OpenQuickAccessMenu(100019);return true;})()`);
 let target;for(let i=0;i<50;i++){target=(await targets()).find(t=>t.title.startsWith('QuickAccess'));if(target)break;await sleep(100);}
 if(!target)throw Error('Already-running Steam has no QAM window');q=await connect(target.webSocketDebuggerUrl);
 await c.evaluate(`(()=>{DFL.Navigation.CloseSideMenus();DFL.Navigation.OpenQuickAccessMenu(100019);return true;})()`);
 report.initial=await poll(s=>s.combos.length===11&&s.sliders.length===3);assert.equal(report.initial.panels,1);assert.ok(report.initial.sliders.some(s=>s.text.includes('插电锁帧 AC')&&s.text.includes('120 FPS')));assert.ok(!report.initial.sliders.some(s=>s.label==='电池锁帧 DC'));
 assert.ok(report.initial.combos.every(combo=>Math.abs(combo.rect.width-report.initial.combos[0].rect.width)<1));report.steps.push('actual current AC frame120 independent from performance mode, 11 equal-width dropdowns');save();
 for(const label of ['屏幕触摸板','YMCC呼出','专用按键','背部按键','锁帧上限']){const s=await open(label);down(label,s);await cancel(label);}assert.equal(session().mutationRequests?.length||0,0);report.steps.push('four primary global touchpad and frame ceiling menus expand down and cancel returns focus');
 await choose('YMCC呼出','右侧呼出');await choose('专用按键','只开启 Steam');await choose('背部按键','L5+R5');await sleep(150);assert.equal(session().hostCounts.touchpadSaves,3);assert.equal(session().hostCounts.saves,0);report.steps.push('global summon/special/rear menus saved three original touchpad patches, no EXE records');save();
 await fps('ac',.7,90);assert.equal(session().hostCounts.saves,1);assert.equal(session().hostCounts.frameApplies,1);report.steps.push('actual FPS drag no write until completion, commits90 to original EXE RTSS pair once');
 await choose('锁帧上限','60 FPS');await poll(s=>s.sliders.find(s=>s.label==='插电锁帧 AC')?.text.includes('60 FPS'));
 await choose('锁帧上限','不锁帧');await poll(s=>s.sliders.find(s=>s.label==='插电锁帧 AC')?.text.includes('不锁帧'));
 await choose('锁帧上限','120 FPS');await poll(s=>s.sliders.find(s=>s.label==='插电锁帧 AC')?.text.includes('60 FPS'));report.steps.push('frame ceiling clamp/unlimited/re-enable preserve independent remembered value');save();
 await choose('屏幕触摸板','单触摸板');await poll(s=>!!s.combos.find(e=>e.label==='触摸板映射')&&!s.combos.find(e=>e.label==='左侧映射'));await choose('触摸板映射','键盘 W / A / S / D');report.steps.push('single layout exposes original single mapping dropdown, no game custom touchpad write');
 await choose('屏幕触摸板','关闭');let s=await poll(s=>!s.combos.find(e=>e.label==='触摸板映射'));for(const label of ['屏幕触摸板','YMCC呼出','专用按键','背部按键'])assert.ok(s.combos.find(e=>e.label===label));report.steps.push('layout off keeps four global dropdowns and hides mappings');
 await state({powerSource:'dc'});s=await poll(s=>s.sliders.some(e=>e.label==='电池锁帧 DC')&&!s.sliders.some(e=>e.label==='插电锁帧 AC'));assert.ok(s.sliders.find(e=>e.label==='电池锁帧 DC').text.includes('60 FPS'));await fps('dc',.625,45);report.steps.push('event-driven memory DC switch shows only DC60, native slider commits independent DC45');
 await state({powerSource:'ac'});s=await poll(s=>s.sliders.some(e=>e.label==='插电锁帧 AC'));assert.ok(s.sliders.find(e=>e.label==='插电锁帧 AC').text.includes('60 FPS'));report.steps.push('return AC remembers60 and does not overwrite DC45');
 await state({game:null});await poll(s=>!s.combos.find(e=>e.label==='核心调度'));await choose('YMCC呼出','左侧呼出');report.steps.push('no game still allows global touchpads; no second EXE dedicated store');
 await sleep(150);const final=session();assert.equal(final.hostCounts.saves,5);assert.equal(final.hostCounts.frameApplies,5);assert.equal(final.hostCounts.touchpadSaves,7);assert.equal(final.hostCounts.fanSaves,0);report.hostCounts=final.hostCounts;report.mutations=final.mutationRequests;report.final=await q.evaluate(read);
 report.pluginSha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'PowerControl/decky/plugins/ymcc-sidebar/dist/index.js'))).digest('hex');assert.equal(report.pluginSha256,final.servedProductionScriptSha256);report.pass=true;save();console.log('Actual Steam frame/touchpad PASS '+report.steps.length);
} catch(error){report.failure=error.stack;save();throw error;} finally {q?.close();c?.close();}
