import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {root,task} from './fixtures/decky_task_paths.mjs';import {targets,connect} from './fixtures/decky_cdp.mjs';
const sessionName=process.env.YMCC_DECKY_UI_RUN_NAME||'MAINLINE17-NATIVE-UI-FINAL';if(!/^[A-Z0-9-]+$/.test(sessionName))throw Error('Session evidence name rejected');
const sessionFile=path.join(task,'validation/'+sessionName+'.json');
const before=JSON.parse(fs.readFileSync(sessionFile,'utf8'));assert.equal(before.hostCounts?.saves,0,'Use a fresh memory fixture for deterministic one-input validation');assert.equal(before.mutationRequests?.length||0,0);
const ts=await targets(),q=await connect(ts.find(t=>t.title.startsWith('QuickAccess')).webSocketDebuggerUrl),c=await connect(ts.find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);
const read=`(()=>{const rows=Array.from(document.querySelectorAll('.ymcc-decky-slider'));return {text:document.body.innerText,sliders:document.querySelectorAll('.ymcc-decky-sidebar [role=slider]').length,comboboxes:document.querySelectorAll('.ymcc-decky-sidebar [role=combobox]').length,controls:rows.map(e=>({label:e.innerText,value:e.querySelector('[role=slider]').getAttribute('aria-valuenow'),font:getComputedStyle(e.querySelector('span')).fontSize,padding:getComputedStyle(e).padding,rect:e.getBoundingClientRect().toJSON()})),notice:document.querySelector('[role=status]')?.innerText,noticeTop:document.querySelector('[role=status]')?.getBoundingClientRect().top,height:innerHeight};})()`;
const initial=await q.evaluate(read);console.log(JSON.stringify(initial,null,2));assert.equal(initial.sliders,7);assert.equal(initial.comboboxes,0);assert.ok(initial.controls.every(row=>row.font==='12px'));assert.ok(initial.controls.at(-1).rect.bottom<=initial.noticeTop+0.1);assert.ok(initial.controls.at(-1).rect.bottom<initial.height);
const rect=await q.evaluate(`(()=>{const row=Array.from(document.querySelectorAll('.ymcc-decky-slider')).find(e=>e.innerText.startsWith('核心调度'));return row.querySelector('.SliderTrack').getBoundingClientRect().toJSON();})()`);
for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x:rect.left+rect.width*3/5,y:rect.top+rect.height/2,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});
let selected;for(let i=0;i<40;i++){selected=await q.evaluate(read);if(selected.controls.find(row=>row.label.startsWith('核心调度'))?.label.includes('仅小核'))break;await new Promise(r=>setTimeout(r,100));}
assert.match(selected.controls.find(row=>row.label.startsWith('核心调度')).label,/仅小核/);assert.match(selected.notice,/已记忆|未宣称硬件|方案值/);
await c.evaluate(`(()=>{DFL.Navigation.CloseSideMenus();return true;})()`);await new Promise(r=>setTimeout(r,400));await c.evaluate(`(()=>{DFL.Navigation.OpenQuickAccessMenu(999);return true;})()`);
let reopened;for(let i=0;i<40;i++){reopened=await q.evaluate(read);if(reopened.controls.find(row=>row.label.startsWith('核心调度'))?.label.includes('仅小核'))break;await new Promise(r=>setTimeout(r,100));}
assert.match(reopened.controls.find(row=>row.label.startsWith('核心调度')).label,/仅小核/);
const image=await q.send('Page.captureScreenshot',{format:'png'});const screenshot=path.join(task,'validation/MAINLINE17-QAM-FINAL.png');fs.writeFileSync(screenshot,Buffer.from(image.data,'base64'));
const binding=await c.evaluate(`(()=>{const d=Object.getOwnPropertyDescriptor(window,'__YMCC_DECKY_MIRROR__');return {frozen:Object.isFrozen(d?.value),writable:d?.writable,configurable:d?.configurable};})()`);
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex'),session=JSON.parse(fs.readFileSync(sessionFile,'utf8'));const production=fs.readFileSync(path.join(root,'PowerControl/decky/plugins/ymcc-sidebar/dist/index.js')),served=fs.readFileSync(path.join(session.home,'plugins/ymcc-sidebar/dist/index.js'));assert.equal(hash(served),hash(production));
const report={sessionEvidence:sessionFile,memorySavesBeforeInput:before.hostCounts.saves,project:'YMCC Decky 侧边栏',stage:'Mainline17',actualSteam:true,actualDflWidgets:true,actualCdpMouseSelection:true,directMutationCallbackUsed:false,javascriptCredentialInjection:false,binding,productionJsBytes:production.length,productionJsSha256:hash(production),initial,selected,reopened,screenshot,physicalControllerTested:false,physicalHardwareWrites:0,realBusinessConfigWrites:0,productYmccExeExecuted:false};fs.writeFileSync(path.join(task,'validation/MAINLINE17-QAM-ACCEPTANCE.json'),JSON.stringify(report,null,2));console.log('REAL_NATIVE_SLIDER_ACCEPTANCE_PASS');q.close();c.close();
