import { task } from './fixtures/decky_task_paths.mjs';
// Thin adapter + real original store/lock/resident owner, with inert dependencies.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
import {root,load,functions,fixture,base,profile,seed,gamePolicyKey,gameDisplayName,main} from './fixtures/decky_game_memory_store.mjs';
const require=createRequire(path.join(root,'package.json')),ts=require('typescript');
const pureKey=load(fs.readFileSync(path.join(root,'src/bridge/gamePolicyHysteresis.ts'),'utf8'));
const actionSource=fs.readFileSync(path.join(root,'src/bridge/deckyGameActions.ts'),'utf8');
const {createGameMirrorActions,makeGameMirrorEntry,makeGameMirrorAdmission,gameMirrorIdentity}=load(actionSource,{'./gamePolicyHysteresis':pureKey});
const {ReadOnlyMirrorRelay}=load(fs.readFileSync(path.join(root,'src/bridge/deckyMirrorRelay.ts'),'utf8'),{'../../decky-plugin/src/steamRunningContext':load(fs.readFileSync(path.join(root,'decky-plugin/src/steamRunningContext.ts'),'utf8'))});
const plain=value=>JSON.parse(JSON.stringify(value));const flush=async()=>{for(let i=0;i<50;i++)await Promise.resolve();};
const defer=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const originalPanel=fs.readFileSync(path.join(root,'src/components/GameCustomProfilePanel.vue'),'utf8').split('<script setup lang="ts">')[1].split('</script>')[0];
const tree=ts.createSourceFile('panel.ts',originalPanel,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const names=['cloneProfile','isCorePolicyMode','isHyperThreadMode','isPadPersonaOverride','isGyroOverride','makeEntry'],options=['PAD_PERSONA_OPTIONS','GYRO_OVERRIDE_OPTIONS','GYRO_LEGACY_OPTIONS'];
const nodes=tree.statements.filter(n=>ts.isFunctionDeclaration(n)&&names.includes(n.name?.text)||ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>options.includes(d.name.getText(tree))));assert.equal(nodes.length,9);
const originalBuilder=load("const gameName={value:'Game'};\n"+nodes.map(n=>n.getText(tree)).join('\n')+'\nmodule.exports.makeEntry=makeEntry;').makeEntry;
function makeFixture(initial=seed(),override={}){
 const memory=fixture(initial),calls={power:0,load:0,schedule:0,save:0,close:0};
 const state={enabled:true,connected:true,game:{pid:101,name:'game.exe',title:'Game',path:'C:/Games/Game.exe',processCreated:'A',ts:0},power:{generation:1,phase:'ready',hardwareWritesAllowed:true},caps:{heterogeneous:true,smtAvailable:true},schedule:{version:2,configured:true,enabled:true,active:{ac:'balanced',dc:'eco'},profiles:{ac:{},dc:{}}}};
 for(const side of ['ac','dc'])for(const mode of ['eco','balanced','medium','performance','elite','extreme'])state.schedule.profiles[side][mode]={...base,tdpMax:side==='ac'?30+['eco','balanced','medium','performance','elite','extreme'].indexOf(mode)*3:10+['eco','balanced','medium','performance','elite','extreme'].indexOf(mode)*2,fpsTarget:side==='ac'?60:30};
 const deps={featureAllowed:()=>state.enabled,game:()=>state.game,label:gameDisplayName,power:async()=>{calls.power++;return structuredClone(state.power);},capabilities:()=>state.caps,acquire:memory.lock.tryAcquireQuickAction,
  load:async()=>{calls.load++;return memory.store.loadGameCustomConfig();},current:memory.store.getGameCustomConfig,schedule:async()=>{calls.schedule++;return structuredClone(state.schedule);},currentSchedule:()=>state.schedule,save:async config=>{calls.save++;await memory.store.saveGameCustomConfig(config);},closeJoyxoff:async()=>{calls.close++;return true;},...override};
 const action=createGameMirrorActions(deps);
 const context=()=>({generation:state.power.generation,revision:1,gameIdentity:gameMirrorIdentity(state.game),gameAdmission:makeGameMirrorAdmission(memory.view().entries[gamePolicyKey(state.game)],state.schedule),checkpoint:()=>{if(!state.connected)throw new Error('MIRROR_CONTEXT_EXPIRED');}});
 const run=(field,value,ctx=context())=>action.execute('game.setField',{field,value},ctx);
 return {memory,state,calls,deps,action,context,run};
}
const cases=[],details=[];async function check(name,fn){await fn();cases.push(name);}
await check('record construction matches original panel for new, active, disabled, snapshot and legacy input records',()=>{const f=makeFixture();for(const current of [undefined,profile(),{...profile(),enabled:false},{...profile(),acMode:undefined,dcMode:undefined},{...profile(),corePolicyMode:'only-small',hyperThreadPolicy:'off',padPersona:'steamdeck',gyroOverride:'on'}]){const modes={ac:'performance',dc:'eco'};assert.deepEqual(plain(makeGameMirrorEntry(current,f.state.schedule,modes,'Game')),plain(originalBuilder(current,f.state.schedule,modes)));}});
await check('new display name reuses original title cleaning and name fallback, not a raw Steam title',async()=>{const f=makeFixture({version:1,entries:{},rtss:{}});f.state.game={...f.state.game,title:'Example Game (Vulkan)'};await f.run('acMode','performance');assert.equal(f.memory.raw().entries['game.exe'].displayName,gameDisplayName(f.state.game));assert.equal(f.memory.raw().entries['game.exe'].displayName,'Example Game');});
await check('first explicit AC edit creates/enables only original EXE entry with original defaults and two remembered sides',async()=>{const f=makeFixture({version:1,entries:{},rtss:{}}),r=await f.run('acMode','performance');const entry=f.memory.raw().entries['game.exe'];assert.equal(entry.enabled,true);assert.equal(entry.acMode,'performance');assert.equal(entry.dcMode,'eco');assert.equal(entry.corePolicyMode,'big-small');assert.equal(entry.corePolicyEnabled,true);assert.equal(r.saved,true);assert.equal(r.applied,false);assert.equal(r.pending,true);assert.equal(f.calls.power,2);assert.deepEqual(Object.keys(f.memory.raw().entries),['game.exe']);assert.ok(!Object.hasOwn(entry,'steamAppId'));});
await check('DC change preserves original remembered AC mode, RTSS and other EXE entries',async()=>{const f=makeFixture(),priorRtss=plain(f.memory.view().rtss);await f.run('dcMode','extreme');const raw=f.memory.raw();assert.equal(raw.entries['game.exe'].acMode,'balanced');assert.equal(raw.entries['game.exe'].dcMode,'extreme');assert.deepEqual(raw.rtss,priorRtss);assert.equal(raw.entries['other.exe'].acMode,'balanced');});
await check('explicit edit enables disabled old record but preserves existing core/input choices',async()=>{const initial=seed();initial.entries['game.exe']={...profile(),enabled:false,corePolicyMode:'only-small',corePolicyEnabled:true,hyperThreadPolicy:'off',hyperThreadPolicyEnabled:true,padPersona:'elite',gyroOverride:'racing'};const f=makeFixture(initial);await f.run('acMode','performance');const entry=f.memory.raw().entries['game.exe'];assert.equal(entry.enabled,true);assert.equal(entry.corePolicyMode,'only-small');assert.equal(entry.hyperThreadPolicy,'off');assert.equal(entry.padPersona,'elite');assert.equal(entry.gyroOverride,'racing');});
await check('non-Steam EXE uses the same adapter and cannot inherit a Steam primary key',async()=>{const f=makeFixture();f.state.game={...f.state.game,path:'D:/GOG/Offline.exe',name:'Offline.exe'};await f.run('acMode','eco');assert.equal(f.memory.raw().entries['offline.exe'].acMode,'eco');assert.ok(!Object.hasOwn(f.memory.raw().entries,'480'));});
await check('existing shared original lock refuses mirror overlap before any read or owner call',async()=>{const f=makeFixture(),release=f.memory.lock.tryAcquireQuickAction('top-custom-profile-select-mode');await assert.rejects(f.run('acMode','eco'),/BUSY/);assert.deepEqual(f.calls,{power:0,load:0,schedule:0,save:0,close:0});release();});
await check('fresh load under original lock preserves a preceding panel save',async()=>{const f=makeFixture(),value=await f.memory.store.loadGameCustomConfig();value.entries['other.exe'].acMode='extreme';await f.memory.store.saveGameCustomConfig(value);await f.run('acMode','performance');assert.equal(f.memory.raw().entries['other.exe'].acMode,'extreme');});
await check('fresh global presets are used for unremembered sides, without a new follow resolver',async()=>{const f=makeFixture({version:1,entries:{},rtss:{}});f.state.schedule.active.dc='extreme';f.state.schedule.profiles.dc.extreme.tdpMax=17;await f.run('acMode','performance');const value=f.memory.raw().entries['game.exe'];assert.equal(value.dcMode,'extreme');assert.equal(value.dc.tdpMax,17);assert.ok(!Object.hasOwn(value,'inheritDc'));});
await check('unsafe fields, arbitrary values and profile-management requests fail before IO',async()=>{for(const [field,value] of [['steamId','480'],['__proto__','x'],['constructor','x'],['enabled','false'],['acMode','file:///unsafe'],['fanPreset','soft']]){const f=makeFixture();await assert.rejects(f.run(field,value));assert.equal(f.calls.load,0);assert.equal(f.calls.save,0);}});
await check('extra arguments and non-game command cannot reach original store',async()=>{const f=makeFixture();await assert.rejects(f.action.execute('shell.run',{field:'acMode',value:'eco'},f.context()));await assert.rejects(f.action.execute('game.setField',{field:'acMode',value:'eco',steamId:'480'},f.context()));assert.equal(f.calls.load,0);});
await check('missing or mismatched admitted identity fails before the original lock/store',async()=>{const f=makeFixture();for(const gameIdentity of [undefined,'',JSON.stringify(['game.exe','C:/X/Game.exe',101,'A'])])await assert.rejects(f.run('acMode','eco',{...f.context(),gameIdentity}),/IDENTITY_REQUIRED|TARGET_CHANGED/);assert.equal(f.calls.load,0);});
await check('PID reuse during fresh load cannot redirect a write to the new game',async()=>{const gate=defer(),f=makeFixture();f.deps.load=async()=>{await gate.promise;return f.memory.store.loadGameCustomConfig();};const task=f.run('acMode','eco');await flush();f.state.game={...f.state.game,processCreated:'B'};gate.resolve();await assert.rejects(task,/TARGET_CHANGED/);assert.equal(f.calls.save,0);assert.equal(f.memory.lock.isQuickActionBusy(),false);});
await check('caller mutation cannot renew the frozen admitted game identity',async()=>{const gate=defer(),f=makeFixture(),ctx=f.context();f.deps.load=async()=>{await gate.promise;return f.memory.store.loadGameCustomConfig();};const task=f.run('acMode','eco',ctx);await flush();f.state.game={...f.state.game,pid:202,path:'D:/Other.exe'};ctx.gameIdentity=gameMirrorIdentity(f.state.game);gate.resolve();await assert.rejects(task,/TARGET_CHANGED/);assert.equal(f.calls.save,0);});
await check('caller mutation cannot renew the frozen admitted power generation',async()=>{const gate=defer(),f=makeFixture(),ctx=f.context();f.deps.power=async()=>{await gate.promise;return structuredClone(f.state.power);};const task=f.run('acMode','eco',ctx);await flush();f.state.power.generation=2;ctx.generation=2;gate.resolve();await assert.rejects(task,/POWER_NOT_READY/);assert.equal(f.calls.load,0);});
await check('field/value primitives remain frozen while a fresh load is awaited',async()=>{const gate=defer(),f=makeFixture();f.deps.load=async()=>{await gate.promise;return f.memory.store.loadGameCustomConfig();};const args={field:'acMode',value:'performance'},task=f.action.execute('game.setField',args,f.context());await flush();args.field='padPersona';args.value='disabled';gate.resolve();await task;assert.equal(f.memory.raw().entries['game.exe'].acMode,'performance');assert.equal(f.memory.raw().entries['game.exe'].padPersona,'follow');});
await check('two concurrent intents cannot save twice through the same original lock',async()=>{const gate=defer(),f=makeFixture();f.deps.load=async()=>{await gate.promise;return f.memory.store.loadGameCustomConfig();};const first=f.run('acMode','performance');await flush();await assert.rejects(f.run('dcMode','extreme'),/BUSY/);gate.resolve();await first;assert.equal(f.calls.save,1);});
await check('pending power transition fails before configuration reads or writes',async()=>{const f=makeFixture();f.state.power.phase='pending';f.state.power.hardwareWritesAllowed=false;await assert.rejects(f.run('acMode','eco'),/POWER_NOT_READY/);assert.equal(f.calls.load,0);assert.equal(f.calls.save,0);});
await check('power change during schedule load prevents persistence',async()=>{const gate=defer(),f=makeFixture();f.deps.schedule=async()=>{await gate.promise;return structuredClone(f.state.schedule);};const task=f.run('acMode','performance');await flush();f.state.power.generation=2;gate.resolve();await assert.rejects(task,/POWER_NOT_READY/);assert.equal(f.calls.save,0);});
await check('feature disable or peer close during load prevents persistence and releases lock',async()=>{for(const flag of ['enabled','connected']){const gate=defer(),f=makeFixture();f.deps.load=async()=>{await gate.promise;return f.memory.store.loadGameCustomConfig();};const task=f.run('acMode','performance');await flush();f.state[flag]=false;gate.resolve();await assert.rejects(task,/TARGET_CHANGED|CONTEXT_EXPIRED/);assert.equal(f.calls.save,0);assert.equal(f.memory.lock.isQuickActionBusy(),false);}});
await check('missing/malformed private admission cannot reach the original file queue',async()=>{const f=makeFixture();for(const gameAdmission of [undefined,{}, {entry:0,schedule:'x'}, {entry:'x',schedule:null}])await assert.rejects(f.run('acMode','performance',{...f.context(),gameAdmission}),/ADMISSION_REQUIRED/);assert.equal(f.calls.load,0);assert.equal(f.calls.save,0);});
await check('mutable caller admission cannot renew an unseen EXE profile during fresh load',async()=>{const f=makeFixture(),gate=defer(),context=f.context();f.deps.load=async()=>{await gate.promise;return f.memory.store.loadGameCustomConfig();};const task=f.run('acMode','performance',context);await flush();const changed=f.memory.raw();changed.entries['game.exe'].corePolicyMode='only-small';changed.entries['game.exe'].corePolicyEnabled=true;f.memory.documents.set(main,JSON.stringify(changed));context.gameAdmission=makeGameMirrorAdmission(f.memory.view().entries['game.exe'],f.state.schedule);gate.resolve();await assert.rejects(task,/SOURCE_CHANGED/);assert.equal(f.calls.save,0);assert.equal(f.memory.lock.isQuickActionBusy(),false);});
await check('preset change while original schedule load awaits rejects rather than remembering unseen DC',async()=>{const f=makeFixture({version:1,entries:{},rtss:{}}),gate=defer(),context=f.context();f.deps.schedule=async()=>{await gate.promise;return structuredClone(f.state.schedule);};const task=f.run('acMode','performance',context);await flush();f.state.schedule.active.dc='extreme';context.gameAdmission.schedule=makeGameMirrorAdmission(undefined,f.state.schedule).schedule;gate.resolve();await assert.rejects(task,/SOURCE_CHANGED/);assert.equal(f.calls.save,0);});
await check('original background save during an awaited schedule cannot be overwritten by the old full map',async()=>{const f=makeFixture(),gate=defer();f.deps.schedule=async()=>{await gate.promise;return structuredClone(f.state.schedule);};const task=f.run('acMode','performance');await flush();const background=await f.memory.store.loadGameCustomConfig();background.entries['other.exe'].acMode='extreme';await f.memory.store.saveGameCustomConfig(background);gate.resolve();await assert.rejects(task,/SOURCE_CHANGED/);assert.equal(f.calls.save,0);assert.equal(f.memory.raw().entries['other.exe'].acMode,'extreme');});
await check('original legacy input-restore clearing during final power gate cannot be resurrected',async()=>{const initial=seed();initial.inputRestore={persona:'elite',buttonMappingEnabled:true,gyroEnabled:true,motionEnabled:true};const f=makeFixture(initial),gate=defer();let reads=0;f.deps.power=async()=>{if(++reads===2)await gate.promise;return structuredClone(f.state.power);};const task=f.run('acMode','performance');await flush();const current=await f.memory.store.loadGameCustomConfig();assert.ok(current.inputRestore);await f.memory.store.clearGameInputRestoreSnapshot(current.inputRestore);gate.resolve();await assert.rejects(task,/SOURCE_CHANGED/);assert.equal(f.memory.raw().inputRestore,undefined);assert.equal(f.calls.save,0);assert.equal(f.memory.lock.isQuickActionBusy(),false);});
await check('global change during final power await is rejected by the original display-cache guard',async()=>{const f=makeFixture(),gate=defer();let reads=0;f.deps.power=async()=>{if(++reads===2)await gate.promise;return structuredClone(f.state.power);};const task=f.run('acMode','performance');await flush();f.state.schedule.profiles.ac.performance.tdpMax=99;gate.resolve();await assert.rejects(task,/SOURCE_CHANGED/);assert.equal(f.calls.save,0);});
await check('scheme change during pre-JoyXoff power check prevents both process operation and save',async()=>{const f=makeFixture(),gate=defer();let reads=0;f.deps.power=async()=>{if(++reads===2)await gate.promise;return structuredClone(f.state.power);};const task=f.run('padPersona','steamdeck');await flush();f.state.schedule.active.dc='extreme';gate.resolve();await assert.rejects(task,/SOURCE_CHANGED/);assert.equal(f.calls.close,0);assert.equal(f.calls.save,0);});
await check('original document change during JoyXoff boundary cannot overwrite a background entry',async()=>{const f=makeFixture(),gate=defer();f.deps.closeJoyxoff=async()=>{await gate.promise;return false;};const task=f.run('padPersona','steamdeck');await flush();const background=await f.memory.store.loadGameCustomConfig();background.rtss['other.exe'].acFps=90;await f.memory.store.saveGameCustomConfig(background);gate.resolve();await assert.rejects(task,/SOURCE_CHANGED/);assert.equal(f.calls.save,0);assert.equal(f.memory.raw().rtss['other.exe'].acFps,90);});
await check('original save queue still determines commits once atomic save has started, without speculative rollback',async()=>{const f=makeFixture(),gate=defer();f.memory.holdNext(gate.promise);const task=f.run('acMode','performance');await flush();assert.equal(f.calls.save,1);f.state.connected=false;gate.resolve();assert.equal((await task).saved,true);assert.equal(f.memory.raw().entries['game.exe'].acMode,'performance');});
await check('save failure publishes no new original cache and allows a later intent',async()=>{const f=makeFixture();await f.memory.store.loadGameCustomConfig();f.memory.failNext();await assert.rejects(f.run('acMode','performance'),/memory-only/);assert.equal(f.memory.store.getGameCustomConfig().entries['game.exe'].acMode,'balanced');assert.equal(f.memory.lock.isQuickActionBusy(),false);await f.run('acMode','performance');assert.equal(f.memory.raw().entries['game.exe'].acMode,'performance');});
await check('capability denial refuses core/SMT fields; valid core choice derives original flags',async()=>{for(const [field,value,cap] of [['corePolicyMode','only-big','heterogeneous'],['hyperThreadPolicy','on','smtAvailable']]){const f=makeFixture();f.state.caps[cap]=false;await assert.rejects(f.run(field,value),/UNSUPPORTED/);assert.equal(f.calls.load,0);}const f=makeFixture();await f.run('corePolicyMode','only-small');assert.equal(f.memory.raw().entries['game.exe'].corePolicyEnabled,true);await f.run('corePolicyMode','default');assert.equal(f.memory.raw().entries['game.exe'].corePolicyEnabled,false);});
await check('same nondefault core/hyper value still derives an inactive old enable flag, matching original panel',async()=>{for(const [field,value,flag] of [['corePolicyMode','only-small','corePolicyEnabled'],['hyperThreadPolicy','off','hyperThreadPolicyEnabled']]){const initial=seed();initial.entries['game.exe'][field]=value;initial.entries['game.exe'][flag]=false;const f=makeFixture(initial);const result=await f.run(field,value);assert.equal(result.saved,true);assert.equal(f.memory.raw().entries['game.exe'][flag],true);}});
await check('reselecting native pad clears a stale gyro override even when the pad value itself is unchanged',async()=>{const initial=seed();initial.entries['game.exe'].padPersona='disabled';initial.entries['game.exe'].gyroOverride='racing';const f=makeFixture(initial);assert.equal((await f.run('padPersona','disabled')).saved,true);assert.equal(f.memory.raw().entries['game.exe'].gyroOverride,'follow');});
await check('native pad resets gyro override exactly as the original panel; locked gyro refuses edits',async()=>{const initial=seed();initial.entries['game.exe'].gyroOverride='racing';const f=makeFixture(initial);await f.run('padPersona','disabled');assert.equal(f.memory.raw().entries['game.exe'].gyroOverride,'follow');await assert.rejects(f.run('gyroOverride','fps'),/GYRO_LOCKED/);assert.equal(f.calls.save,1);});
await check('SteamDeck selection calls only the supplied original JoyXoff boundary before save, with soft-failure parity',async()=>{const f=makeFixture(),order=[];f.deps.closeJoyxoff=async()=>{order.push('close');throw new Error('original soft failure');};const save=f.deps.save;f.deps.save=async value=>{order.push('save');await save(value);};await f.run('padPersona','steamdeck');assert.deepEqual(order,['close','save']);assert.equal(f.memory.raw().entries['game.exe'].padPersona,'steamdeck');});
await check('same remembered active value is idempotent and does not reload presets or call owners',async()=>{const f=makeFixture(),r=await f.run('acMode','balanced');assert.equal(r.saved,false);assert.equal(r.applied,false);assert.equal(f.calls.schedule,0);assert.equal(f.calls.save,0);assert.equal(f.calls.close,0);assert.equal(f.calls.power,1);});
await check('display-only global and legacy sentinels never create or rewrite a record',async()=>{const f=makeFixture({version:1,entries:{},rtss:{}});assert.equal((await f.run('acMode','follow')).saved,false);assert.equal(f.calls.save,0);const initial=seed();delete initial.entries['game.exe'].acMode;const old=makeFixture(initial);assert.equal((await old.run('acMode','legacy')).saved,false);assert.equal(old.calls.save,0);});
await check('explicit legacy edit uses original panel snapshot-to-mode recipe, not invented per-field inheritance',async()=>{const initial=seed();delete initial.entries['game.exe'].acMode;delete initial.entries['game.exe'].dcMode;initial.entries['game.exe'].ac.tdpMax=25;initial.entries['game.exe'].dc.tdpMax=15;const f=makeFixture(initial),old=await f.memory.store.loadGameCustomConfig();const expected=originalBuilder(old.entries['game.exe'],f.state.schedule,{ac:'performance',dc:'eco'});await f.run('acMode','performance');assert.deepEqual(f.memory.raw().entries['game.exe'],plain(expected));});
await check('in-flight atomic commit after menu close is truthfully saved to frozen EXE, never redirected',async()=>{const f=makeFixture(),gate=defer();f.memory.holdNext(gate.promise);const task=f.run('acMode','performance');await flush();assert.equal(f.calls.save,1);f.state.connected=false;f.state.game={...f.state.game,pid:202,path:'D:/Other.exe'};gate.resolve();const outcome=await task;assert.equal(outcome.saved,true);assert.equal(outcome.applied,false);assert.equal(f.memory.raw().entries['game.exe'].acMode,'performance');assert.equal(f.memory.raw().entries['other.exe'].acMode,'balanced');assert.equal(f.memory.lock.isQuickActionBusy(),false);});
const runId='a'.repeat(32),peer={connection:'1',runId,connected:true};
function relayFixture(f,redirect=false){const replies=[];const relay=new ReadOnlyMirrorRelay({read:async()=>({gameAdmission:makeGameMirrorAdmission(f.memory.view().entries[gamePolicyKey(f.state.game)],f.state.schedule),generation:1,ready:true,actions:{game:true,fan:false},game:{label:'Game',identity:gameMirrorIdentity(f.state.game),fields:{}},fan:{supported:false,enabled:false,preset:'',choices:[]}}),observe:()=>()=>{},reply:async(_c,message)=>{replies.push(message);return true;},execute:(command,args,context)=>{if(redirect)f.state.game={...f.state.game,pid:202,path:'D:/New.exe'};return f.action.execute(command,args,context);}});return {relay,replies,open:()=>relay.request({...peer,request:{command:'snapshot',runId}}),request:()=>({...peer,request:{command:'game.setField',runId,id:'test:1',clientId:'test',sequence:1,generation:1,revision:1,identity:gameMirrorIdentity(f.state.game),args:{field:'acMode',value:'performance'}}})};}
await check('production relay carries admitted identity; late target switch cannot change the write owner',async()=>{const f=makeFixture(),r=relayFixture(f,true);await r.open();await r.relay.request(r.request());assert.equal(f.calls.save,0);assert.equal(r.replies.find(reply=>reply.type==='reply').ok,false);r.relay.dispose();});
await check('production relay caches a successful original save; lost ACK replay does not save or apply twice',async()=>{const f=makeFixture(),r=relayFixture(f);await r.open();const packet=r.request();await r.relay.request(packet);await flush();await r.relay.request(packet);assert.equal(f.calls.save,1);assert.equal(r.replies.filter(reply=>reply.type==='reply').length,2);assert.equal(r.replies.find(reply=>reply.type==='reply').result.saved,true);assert.equal(r.replies.find(reply=>reply.type==='reply').result.applied,false);r.relay.dispose();});
const ownerFrameModel=load(fs.readFileSync(path.join(root,'src/bridge/frameRateModel.ts'),'utf8'));
function ownerFixture(f){const timers=new Map(),calls=[],listeners=[];const owner=load(fs.readFileSync(path.join(root,'src/bridge/gamePolicyRuntime.ts'),'utf8')+'\nexport function debug(){return {active,epoch,running,dirty,appliedPerformance,appliedCore};}',{
 'vue':{watch:()=>()=>{}},'./powerSource':{powerSourceMode:{value:'ac'}},'./yeman':{detectPowerMode:async()=> 'ac'},'./autofloat':{setFloatRtssLinked:()=>{}},
 './frameRateLimits':{...ownerFrameModel,loadGlobalFrameRates:async()=>ownerFrameModel.frameRatePair({}),onFrameRatesChanged:()=>()=>{},applyIndependentFrameRates:async()=>true},
 './gamePolicyTarget':{getPolicyGame:()=>f.state.game,gamePolicyKey,isPolicyGameInitialized:()=>true,subscribePolicyGameStatus:callback=>{listeners.push(callback);callback(f.state.game);return()=>listeners.splice(listeners.indexOf(callback),1);}},
 './performanceSchedule':{loadGameCustomConfig:f.memory.store.loadGameCustomConfig,loadPerformanceSchedule:async()=>structuredClone(f.state.schedule),onGameCustomConfigChanged:f.memory.store.onGameCustomConfigChanged,onPerformanceScheduleChanged:()=>()=>{},resolveGameCustomProfiles:f.memory.store.resolveGameCustomProfiles,restorePerformanceScheduleIfConfigured:async()=>{const current=await f.memory.store.loadGameCustomConfig();calls.push(['performance',f.state.game.pid,f.memory.store.resolveGameCustomProfiles(current.entries[gamePolicyKey(f.state.game)],f.state.schedule).ac.tdpMax]);return true;}},
 './gameCorePolicy':{detectGameCorePolicy:async()=>f.state.caps,applyGameCorePolicy:async(target,mode,hyper)=>{calls.push(['core',target.pid,mode,hyper]);return {ok:true,applied:true};},clearGameCorePolicy:async()=>{calls.push(['clear']);return true;}},
 '@/scheduler':{registerScheduledTask:(name,interval,run)=>{timers.set(name,{interval,run});return()=>timers.delete(name);}},'./api':{powerLifecycle:{get:async()=>structuredClone(f.state.power)}},'./quickActionLock':f.memory.lock});
 return {owner,calls,timers,changed:()=>listeners.forEach(callback=>callback()),tick:async()=>{await timers.get('game-policy-runtime-retry').run();await flush();}};
}
await check('unchanged original resident owner applies saved mode once on its existing retry, without parallel mirror owner',async()=>{const f=makeFixture(),o=ownerFixture(f);o.owner.startGamePolicyRuntime();await flush();const before=o.calls.length;await f.run('acMode','performance');assert.equal(o.calls.length,before);assert.equal(o.timers.size,1);assert.equal(o.timers.get('game-policy-runtime-retry').interval,2000);await o.tick();assert.equal(o.calls.filter(call=>call[0]==='performance').length,2);await o.tick();assert.equal(o.calls.filter(call=>call[0]==='performance').length,2);details.push({originalOwnerCalls:o.calls,mirrorDirectHardwareCalls:0,addedRetryTimers:0});o.owner.stopGamePolicyRuntime();assert.equal(o.timers.size,0);});
await check('unchanged owner holds application during pending power then applies once after ready resume',async()=>{const f=makeFixture(),o=ownerFixture(f);o.owner.startGamePolicyRuntime();await flush();const before=o.calls.length;await f.run('acMode','performance');f.state.power.phase='pending';f.state.power.hardwareWritesAllowed=false;await o.tick();assert.equal(o.calls.length,before);f.state.power={generation:2,phase:'ready',hardwareWritesAllowed:true};await o.tick();assert.equal(o.calls.length,before+1);await o.tick();assert.equal(o.calls.length,before+1);o.owner.stopGamePolicyRuntime();});
await check('saved EXE profile is reconciled for the original current lease after PID reuse, never redirected by mirror',async()=>{const f=makeFixture(),o=ownerFixture(f);o.owner.startGamePolicyRuntime();await flush();await f.run('acMode','performance');const before=o.calls.length;f.state.game={...f.state.game,pid:202,processCreated:'B'};o.changed();await flush();await o.tick();const next=o.calls.slice(before).filter(call=>call[0]==='performance');assert.equal(next.length,1);assert.equal(next[0][1],202);assert.equal(f.memory.raw().entries['game.exe'].acMode,'performance');o.owner.stopGamePolicyRuntime();});
await check('input-only edit does not replay original performance or CPU affinity after reconciliation',async()=>{const f=makeFixture(),o=ownerFixture(f);o.owner.startGamePolicyRuntime();await flush();await f.run('acMode','performance');await o.tick();const before=o.calls.length;await f.run('padPersona','elite');await o.tick();assert.equal(o.calls.length,before);assert.equal(f.memory.raw().entries['game.exe'].padPersona,'elite');o.owner.stopGamePolicyRuntime();});
function inputFixture(f){
 const timers=new Map(),calls=[],listeners=[];
 const state={input:{schemaVersion:1,revision:1,outputTarget:{persona:'elite',buttonMappingEnabled:true,gyroEnabled:false},gyroMotion:{enabled:false,presets:{fps:{motionMode:'on',innerDeadzone:3}}},buttonMapping:{unchanged:true},gameOverride:null},failCas:0};
 const owner=load(fs.readFileSync(path.join(root,'src/bridge/gameInputOverride.ts'),'utf8'),{
 './gyroPresetModel':load(fs.readFileSync(path.join(root,'src/bridge/gyroPresetModel.ts'),'utf8')),
    '@/bridge/settingsRepository':{loadSettings:async()=>({input:structuredClone(state.input)}),compareAndSwapInputSettings:async(expected,patch,current)=>{calls.push({expected,patch:structuredClone(patch)});if(!current()||expected!==state.input.revision||state.failCas-->0)return {ok:false,value:structuredClone(state.input)};state.input={...state.input,...structuredClone(patch),revision:state.input.revision+1};return {ok:true,value:structuredClone(state.input)};}},
 '@/bridge/gamePolicyTarget':{getPolicyGame:()=>f.state.game,gamePolicyKey,isPolicyGameInitialized:()=>true,subscribePolicyGameStatus:callback=>{listeners.push(callback);callback(f.state.game);return()=>listeners.splice(listeners.indexOf(callback),1);}},
 '@/bridge/ipc':{invoke:async command=>{assert.equal(command,'input.gameOverride.session');return 'inert-session';}},
 '@/scheduler':{registerScheduledTask:(name,interval,run)=>{timers.set(name,{interval,run});return()=>timers.delete(name);}},
 '@/bridge/performanceSchedule':{loadGameCustomConfig:f.memory.store.loadGameCustomConfig,onGameCustomConfigChanged:f.memory.store.onGameCustomConfigChanged,clearGameInputRestoreSnapshot:()=>{throw new Error('Legacy restore is out of this fixture scope');}}});
 return {owner,state,calls,timers,changed:()=>listeners.forEach(callback=>callback()),tick:async()=>{await timers.get('game-input-overlay-retry').run();await flush();}};
}
await check('unchanged input owner consumes mirror pad/gyro saves as overlay without changing base settings',async()=>{const f=makeFixture(),o=inputFixture(f);o.owner.startGameInputOverrideWatch();await flush();const baseTarget=structuredClone(o.state.input.outputTarget),baseMotion=structuredClone(o.state.input.gyroMotion);await f.run('padPersona','steamdeck');await o.tick();assert.equal(o.state.input.gameOverride.outputTarget.persona,'steamdeck');await f.run('gyroOverride','fps');await o.tick();assert.equal(o.state.input.gameOverride.gyroMotion.preset,'fps');assert.equal(o.state.input.gameOverride.gyroMotion.innerDeadzone,3);assert.deepEqual(o.state.input.outputTarget,baseTarget);assert.deepEqual(o.state.input.gyroMotion,baseMotion);assert.equal(o.timers.size,1);assert.equal(o.timers.get('game-input-overlay-retry').interval,2000);o.owner.stopGameInputOverrideWatch();assert.equal(o.timers.size,0);});
await check('input native-pad choice removes virtual/gyro effect through the unchanged overlay owner',async()=>{const f=makeFixture(),o=inputFixture(f);o.owner.startGameInputOverrideWatch();await flush();await f.run('padPersona','disabled');await o.tick();assert.equal(o.state.input.gameOverride.outputTarget.persona,'disabled');assert.equal(o.state.input.gameOverride.outputTarget.gyroEnabled,false);assert.equal(o.state.input.gameOverride.gyroMotion.enabled,false);o.owner.stopGameInputOverrideWatch();});
await check('old input owner retries failed CAS on its existing timer, with no new mirror retry',async()=>{const f=makeFixture(),o=inputFixture(f);o.owner.startGameInputOverrideWatch();await flush();o.state.failCas=3;await f.run('padPersona','elite');await flush();assert.equal(o.state.input.gameOverride,null);await o.tick();assert.equal(o.state.input.gameOverride.outputTarget.persona,'elite');const committed=o.calls.length;await o.tick();assert.equal(o.calls.length,committed);o.owner.stopGameInputOverrideWatch();});
await check('input game exit removes only overlay; original base remains intact',async()=>{const f=makeFixture(),o=inputFixture(f);o.owner.startGameInputOverrideWatch();await flush();await f.run('gyroOverride','racing');await o.tick();assert.ok(o.state.input.gameOverride);const baseTarget=structuredClone(o.state.input.outputTarget);f.state.game=null;o.changed();await flush();await o.tick();assert.equal(o.state.input.gameOverride,null);assert.deepEqual(o.state.input.outputTarget,baseTarget);o.owner.stopGameInputOverrideWatch();});
await check('adapter adds no raw bridge/hardware API, configuration path, persistent SteamID or retry timer',()=>{for(const banned of ['setTdp(','applyGameCorePolicy(','clearGameCorePolicy(','invoke(','setInterval(','setTimeout(','writeTextFile','steamAppId','game-custom.json'])assert.ok(!actionSource.includes(banned),banned);});
const report={project:'YMCC Decky 侧边栏',stage:process.argv.includes('--stage14')?'Implementation14':process.argv.includes('--stage13')?'Implementation13':process.argv.includes('--stage12')?'Implementation12':process.argv.includes('--stage11')?'Implementation11':process.argv.includes('--stage10')?'Implementation10':'Implementation09',dateHongKong:'2026-10-09',cases:cases.length,results:cases,details,productionAdapterExecuted:true,originalStoreAndLockExecuted:true,originalResidentOwnerExecuted:true,originalInputOverlayOwnerExecuted:true,originalPanelBuilderParity:true,productionRelayExecuted:true,realBusinessFileWrites:0,physicalHardwareWrites:0,actualJoyXoffOperations:0,realSteam:false,ownerApplicationEvidence:'Original owner code with inert schedule/core adapters and manually pulsed original scheduler; original input overlay/CAS owner also executed with inert settings; actual native input/device acceptance remains untested',gameWriteHostWired:true};
fs.writeFileSync(path.resolve(task,process.argv.includes('--stage14')?'validation/GAME-ACTIONS-IMPLEMENTATION14.json':process.argv.includes('--stage13')?'validation/GAME-ACTIONS-IMPLEMENTATION13.json':process.argv.includes('--stage12')?'validation/GAME-ACTIONS-IMPLEMENTATION12.json':process.argv.includes('--stage11')?'validation/GAME-ACTIONS-IMPLEMENTATION11.json':process.argv.includes('--stage10')?'validation/GAME-ACTIONS-IMPLEMENTATION10.json':'validation/GAME-ACTIONS-IMPLEMENTATION09.json'),JSON.stringify(report,null,2));console.log(`Thin EXE mirror adapter tests passed: ${cases.length}`);
