// Actual DFL controls -> native broker -> original business adapters/owners, all device IO in memory.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {task} from './fixtures/decky_task_paths.mjs';import {targets,connect} from './fixtures/decky_cdp.mjs';
const file=path.join(task,'validation/'+process.env.YMCC_DECKY_UI_RUN_NAME+'.json'),out=path.join(task,'validation/GOAL27-EXTRA-OWNER-UI.json');
const session=()=>JSON.parse(fs.readFileSync(file,'utf8'));const report={actualSteam:true,actualDflControls:true,actualProductYmcc:false,businessOwners:'original with memory-only file/process/device boundaries',physicalHardwareWrites:0,realBusinessConfigWrites:0,steps:[]};const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2));const sleep=ms=>new Promise(r=>setTimeout(r,ms));let c,q;
const read=`(()=>{const p=document.querySelector('.ymcc-decky-sidebar'),r=e=>e.getBoundingClientRect().toJSON();return {text:p?.innerText,checks:Array.from(p?.querySelectorAll('[role=checkbox]')||[]).map(e=>({label:document.getElementById(e.getAttribute('aria-labelledby'))?.innerText,checked:e.getAttribute('aria-checked'),rect:r(e),disabled:e.classList.contains('Disabled')})),sliders:Array.from(p?.querySelectorAll('.ymcc-decky-slider')||[]).map(e=>({label:e.innerText.split(String.fromCharCode(10))[0],text:e.innerText,track:e.querySelector('.SliderTrack')?r(e.querySelector('.SliderTrack')):null}))};})()`;
async function poll(test){for(let i=0;i<100;i++){const s=await q.evaluate(read);if(test(s))return s;await sleep(100);}throw Error('Extra original-owner UI deadline '+JSON.stringify(await q.evaluate(read)));}
async function toggle(label,value){await q.evaluate(`(()=>{const e=Array.from(document.querySelectorAll('.ymcc-decky-sidebar [role=checkbox]')).find(e=>document.getElementById(e.getAttribute('aria-labelledby'))?.innerText===${JSON.stringify(label)});e?.scrollIntoView({block:'center'});return !!e;})()`);await sleep(100);const s=await q.evaluate(read),e=s.checks.find(e=>e.label===label);assert.ok(e,label);assert.equal(e.disabled,false,label+' must be genuinely supported by this memory owner');if(e.checked===String(value))return;for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x:e.rect.left+e.rect.width/2,y:e.rect.top+e.rect.height/2,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});await poll(s=>s.checks.find(e=>e.label===label)?.checked===String(value));}
try{
 const current=session();assert.equal(current.originalBusinessOwnersInMemory,true);const before={...current.hostCounts};const baseMutations=current.mutationRequests?.length||0;
 fs.writeFileSync(current.memoryStateRequestPath,JSON.stringify({game:'initial'}));await sleep(200);const list=await targets();c=await connect(list.find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);await c.evaluate(`DFL.Navigation.OpenQuickAccessMenu(100019);true`);await sleep(300);q=await connect((await targets()).find(t=>t.title.startsWith('QuickAccess')).webSocketDebuggerUrl);await poll(s=>s.checks.some(e=>e.label==='超线程')&&s.checks.some(e=>e.label==='LosslessScaling 插帧'));
 await toggle('超线程',true);report.steps.push('actual SMT toggle writes original EXE memory entry through the real native broker');
 await toggle('LosslessScaling 插帧',true);await toggle('LosslessScaling 插帧',false);report.steps.push('LS on/off reaches exact original quickapp owner: one original launch and one normal identity-checked closure, no XML/profile writes');
 await toggle('风扇控制（全局）',true);await q.evaluate(`(()=>{const e=Array.from(document.querySelectorAll('.ymcc-decky-slider')).find(e=>e.innerText.startsWith('风扇挡位（全局）'));e.scrollIntoView({block:'center'});return true;})()`);await sleep(100);const track=(await q.evaluate(read)).sliders.find(e=>e.label==='风扇挡位（全局）').track;assert.ok(track);for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x:track.left+track.width*.95,y:track.top+track.height/2,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});await poll(s=>s.sliders.find(e=>e.label==='风扇挡位（全局）')?.text.includes('暴力转速'));await toggle('风扇控制（全局）',false);report.steps.push('global Fan enable/preset/disable reaches original FanHostLifecycle with a no-IO adapter, never becomes an EXE setting');
 await sleep(200);const end=session();assert.equal(end.hostCounts.saves,before.saves+1);assert.equal(end.hostCounts.fanSaves,1);assert.equal(end.hostCounts.touchpadSaves,before.touchpadSaves);assert.equal(end.ownerStats.lossless.running,false);assert.equal(end.ownerStats.lossless.profileXmlUnchanged,true);assert.equal(end.ownerStats.lossless.events.filter(e=>e==='original-launch').length,1);assert.equal(end.ownerStats.lossless.events.filter(e=>e==='original-normal-close').length,1);assert.equal(end.ownerStats.fan.active,false);assert.equal(end.ownerStats.fan.preset,'aggressive');assert.equal(end.ownerStats.fan.leasePresent,false);assert.equal(end.ownerStats.fan.physicalHardwareWrites,0);
 report.counts=end.hostCounts;report.ownerStats=end.ownerStats;report.mutations=end.mutationRequests.slice(baseMutations);assert.equal(report.mutations.length,6);report.pass=true;save();console.log('Extra original-owner native UI PASS '+report.steps.length);
}catch(error){report.failure=error.stack;save();throw error;}finally{q?.close();c?.close();}
