// Real installed product only. Read/expand/cancel/reload, never select a business value.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {task} from './fixtures/decky_task_paths.mjs';import {targets,connect} from './fixtures/decky_cdp.mjs';
const deploy=JSON.parse(fs.readFileSync(path.join(task,'validation/PRODUCT-DEPLOYMENT.json'),'utf8').replace(/^\uFEFF/,''));assert.equal(deploy.stage,'started');
const pid=deploy.productPid,dataRoot=deploy.activePowerControlDirectory,log='C:/Users/DaVe/AppData/Local/YeManCC/decky-sidebar.log';
const configHash=()=>Object.fromEntries(['yeman-settings.json','game-custom.json'].filter(n=>fs.existsSync(path.join(dataRoot,n))).map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(path.join(dataRoot,n))).digest('hex')]));
const events=()=>fs.readFileSync(log,'utf8').split('\n').filter(Boolean).map(line=>JSON.parse(line)).filter(e=>e.processPid===pid);
const report={actualInstalledProduct:true,productPid:pid,actualSteam:true,actualNativeBootstrap:true,javascriptCredentialInjection:false,businessMutationsRequested:false,businessFilesBefore:configHash(),steps:[]};
const out=path.join(task,'validation/PRODUCT-SIX-MODULES-READONLY.json'),save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)),sleep=ms=>new Promise(r=>setTimeout(r,ms));let c,q;
const read=`(()=>{const panels=Array.from(document.querySelectorAll('.ymcc-decky-sidebar')),p=panels.find(e=>e.getBoundingClientRect().width>0),rect=e=>e.getBoundingClientRect().toJSON();return {visiblePanels:panels.filter(e=>e.getBoundingClientRect().width>0).length,retainedPanels:panels.length,modules:Array.from(p?.querySelectorAll('[data-ymcc-module]')||[]).map(e=>e.dataset.ymccModule),text:p?.innerText,combos:Array.from(p?.querySelectorAll('[role=combobox]')||[]).map(e=>({label:e.closest('.ymcc-anchored-dropdown')?.innerText.split(String.fromCharCode(10))[0],text:e.innerText,rect:rect(e),disabled:e.getAttribute('aria-disabled')==='true'||e.classList.contains('Disabled'),focus:e===document.activeElement})),list:p?.querySelector('[role=listbox]')?rect(p.querySelector('[role=listbox]')):null,tabs:Array.from(document.querySelectorAll('[role=tab]')).map(e=>{let f=e[Object.keys(e).find(k=>k.startsWith('__reactFiber$'))],key=null;for(let i=0;f&&i<20;i++,f=f.return)if(key===null&&f.key!=null)key=String(f.key);const icon=e.querySelector('[aria-label="YMCC 控制台"]');return {key,rect:rect(e),icon:icon?rect(icon):null,iconTag:icon?.tagName};})};})()`;
async function ui(){return q.evaluate(read,{awaitPromise:false});}
async function poll(fn){for(let i=0;i<80;i++){const s=await ui();if(fn(s))return s;await sleep(100);}throw Error('Installed QAM readiness deadline');}
function verify(s){assert.equal(s.visiblePanels,1);assert.equal(s.retainedPanels,1);assert.deepEqual(s.modules,['tdp','frames','fan','lossless','virtual','touchpads']);assert.doesNotMatch(s.text,/内存档位|测试 · 内存|尚未提供镜像连接|连接已中断|镜像身份无效|未提供镜像链接/);assert.equal(s.tabs.filter(t=>t.key==='100019').length,1);assert.equal(s.tabs.filter(t=>t.key==='999').length,1);const icon=s.tabs.find(t=>t.key==='100019');assert.equal(icon.iconTag?.toLowerCase(),'svg');assert.ok(Math.abs(icon.icon.top+icon.icon.height/2-icon.rect.top-icon.rect.height/2)<1);assert.ok(s.combos.every(e=>Math.abs(e.rect.width-s.combos[0].rect.width)<1));}
async function connectUi(){c?.close();q?.close();const list=await targets();c=await connect(list.find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);for(let i=0;i<100;i++){if(await c.evaluate(`typeof DFL!=='undefined'&&window.__TABS_HOOK_INSTANCE?.tabs?.filter(t=>t.id===100019).length===1&&!!window.__YMCC_DECKY_MIRROR__`))break;if(i===99)throw Error('Native product did not register console');await sleep(100);}await c.evaluate('DFL.Navigation.OpenQuickAccessMenu(100019);true');await sleep(250);q=await connect((await targets()).find(t=>t.title.startsWith('QuickAccess')).webSocketDebuggerUrl);}
try{
 await connectUi();report.initial=await poll(s=>s.modules.length===6&&s.combos.length>=6);verify(report.initial);assert.match(report.initial.text,/锁帧|TDP/);report.steps.push('Genuine installed product snapshot: one panel, all six modules, native centered SVG Y, uniform dropdown widths; no memory owner or missing-link notice');save();
 for(const item of report.initial.combos){if(item.disabled){report.steps.push(item.label+' retained with native unsupported disabled state');continue;}await q.evaluate(`Array.from(document.querySelectorAll('.ymcc-anchored-dropdown')).find(e=>e.innerText.split(String.fromCharCode(10))[0]===${JSON.stringify(item.label)})?.scrollIntoView({block:'center',behavior:'instant'});true`,{awaitPromise:false});await sleep(300);const state=await ui(),r=state.combos.find(e=>e.label===item.label).rect,x=r.left+r.width/2,y=r.top+r.height/2;assert.ok(y>=0&&y<await q.evaluate('innerHeight',{awaitPromise:false}));for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});const opened=await poll(s=>!!s.list),trigger=opened.combos.find(e=>e.label===item.label);assert.ok(opened.list.top>=trigger.rect.bottom-2);assert.ok(Math.abs(opened.list.width-trigger.rect.width)<1);for(const type of ['keyDown','keyUp'])await q.send('Input.dispatchKeyEvent',{type,key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await poll(s=>!s.list&&s.combos.find(e=>e.label===item.label)?.focus);report.steps.push(item.label+' actual dropdown opens below and Escape returns exact trigger without selection');save();}
 for(let i=0;i<3;i++){await c.evaluate('DFL.Navigation.CloseSideMenus();true');await sleep(200);await c.evaluate('DFL.Navigation.OpenQuickAccessMenu(100019);true');await sleep(250);verify(await ui());}report.steps.push('Three genuine product close/reopen cycles preserve controls and unique native tabs');
 await c.evaluate(`(async()=>{const l=window.DeckyPluginLoader,p=l.plugins.find(p=>p.name==='ymcc-sidebar');if(!p||l.reloadLock)throw Error('Native plugin reload unavailable');DFL.Navigation.CloseSideMenus();await l.importPlugin(p.name,p.version,p.loadType,true,10000);return true;})()`);await connectUi();report.afterPluginReload=await poll(s=>s.modules.length===6&&s.combos.length>=6);verify(report.afterPluginReload);report.steps.push('Native plugin-only reload preserves exactly one original Decky home and one fresh console; old duplicate-tab failure is not reproduced');save();
 // Context generations restart for a new Steam/CEF process. Verify a new native receipt after this reload, not a maximum across unrelated contexts.
 const beforeEventCount=events().length;q.close();q=null;await c.send('Page.reload',{ignoreCache:false});c.close();c=null;
 for(let i=0;i<100;i++){try{await connectUi();const s=await poll(s=>s.modules.length===6&&s.combos.length>=6);verify(s);report.afterSharedPageReload=s;break;}catch(e){c?.close();q?.close();c=q=null;if(i===99)throw e;await sleep(200);}}
 const current=events();assert.ok(current.some(e=>e.event==='runtime'&&e.launchMode==='verified-shell-primary'&&e.launchStage==='child-token-verified'));assert.ok(current.some(e=>e.event==='mirror-snapshot-queued'&&e.ready===true));assert.ok(current.slice(beforeEventCount).some(e=>e.event==='bootstrap-watch'&&e.bootstrapStage==='context-attached'&&e.contextGeneration>=1),'A fresh authenticated native attachment must follow the explicit shared-page reload');assert.ok(current.slice(beforeEventCount).some(e=>e.event==='mirror-snapshot-queued'&&e.ready===true),'Fresh real-owner snapshot must follow reload');report.steps.push('Same-process real shared-page reload automatically restores native authenticated product connection, fresh snapshot and all six modules');
 report.businessFilesAfter=configHash();assert.deepEqual(report.businessFilesAfter,report.businessFilesBefore,'Read-only acceptance must not change any user business configuration');report.nativeStages=current.filter(e=>['runtime','bootstrap-watch','mirror-snapshot-queued'].includes(e.event)).map(e=>({event:e.event,pid:e.pid,phase:e.phase,ready:e.ready,reason:e.reason,launchMode:e.launchMode,launchStage:e.launchStage,bootstrapStage:e.bootstrapStage,contextGeneration:e.contextGeneration}));report.pass=true;save();console.log('Installed six-module product readonly PASS '+report.steps.length);
}catch(error){report.failure=error.stack;report.businessFilesAfter=configHash();save();throw error;}finally{q?.close();c?.close();}
