// Exact production trailing-edge queue with a deterministic virtual clock.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {root,task} from './fixtures/decky_task_paths.mjs';import {load} from './fixtures/decky_game_memory_store.mjs';
const {PowerChoiceDebounce,POWER_CHOICE_DELAY_MS}=load(fs.readFileSync(path.join(root,'decky-plugin/src/powerChoiceDebounce.ts'),'utf8'));
const cases=[];const check=(name,fn)=>{fn();cases.push(name);};
function fixture(){let now=0,id=0;const timers=new Map(),sent=[];const choices=['eco','balanced','performance','extreme'].map(data=>({data,label:data}));
 const state={connected:true,busy:false,snapshot:{runId:'r',generation:1,revision:1,ready:true,powerSource:'ac',actions:{game:true},game:{identity:'game:101:A',fields:{acMode:{value:'balanced',supported:true,choices},dcMode:{value:'eco',supported:true,choices}}}}};
 const queue=new PowerChoiceDebounce({state:()=>state,send:choice=>{sent.push(choice);return Promise.resolve();},schedule:(action,delay)=>{timers.set(++id,{action,due:now+delay});return id;},cancel:id=>timers.delete(id)});
 const advance=ms=>{now+=ms;for(const [id,timer] of [...timers])if(timer.due<=now){timers.delete(id);timer.action();}};
 return {queue,state,timers,sent,advance,choose:value=>queue.choose('acMode',value,state.snapshot)};
}
check('delay is exactly 3000ms and no command/save is sent during 2999ms',()=>{const f=fixture();assert.equal(POWER_CHOICE_DELAY_MS,3000);f.choose('performance');f.advance(2999);assert.equal(f.sent.length,0);f.advance(1);assert.equal(f.sent.length,1);assert.equal(f.sent[0].value,'performance');assert.equal(f.queue.snapshot(),null);});
check('every intermediate change restarts the full delay; only the last choice sends once',()=>{const f=fixture();f.choose('performance');f.advance(2100);f.choose('extreme');f.advance(2999);assert.equal(f.sent.length,0);f.advance(1);assert.equal(f.sent.length,1);assert.equal(f.sent[0].value,'extreme');f.advance(10000);assert.equal(f.sent.length,1);});
check('returning to saved mode cancels pending, with zero commands',()=>{const f=fixture();f.choose('performance');f.choose('balanced');f.advance(5000);assert.equal(f.sent.length,0);assert.equal(f.timers.size,0);});
for(const changed of ['identity','runId','generation','revision','powerSource','ready','connected','busy','unsupported','no-action'])check('pending cancellation on '+changed,()=>{const f=fixture();f.choose('performance');if(changed==='identity')f.state.snapshot.game.identity='different';else if(['runId','generation','revision'].includes(changed))f.state.snapshot[changed]='changed';else if(changed==='powerSource')f.state.snapshot.powerSource='dc';else if(changed==='ready')f.state.snapshot.ready=false;else if(changed==='unsupported')f.state.snapshot.game.fields.acMode.supported=false;else if(changed==='no-action')f.state.snapshot.actions.game=false;else f.state[changed]=changed==='busy';f.queue.observe(f.state);f.advance(5000);assert.equal(f.sent.length,0);assert.equal(f.timers.size,0);});
check('final tick also validates identity even without a delivered event',()=>{const f=fixture();f.choose('performance');f.state.snapshot.game.identity='reused-pid';f.advance(3000);assert.equal(f.sent.length,0);});
check('invalid/global/display-only choices are not executable',()=>{const f=fixture();for(const value of ['bad','follow','legacy'])f.choose(value);assert.equal(f.timers.size,0);f.state.snapshot.game.fields.acMode.choices.push({data:'extreme',label:'off',disabled:true});f.state.snapshot.game.fields.acMode.choices=f.state.snapshot.game.fields.acMode.choices.filter(c=>c.data!=='extreme'||c.disabled);f.choose('extreme');assert.equal(f.timers.size,0);});
check('explicit close/dispose cancels ownership and listeners',()=>{const f=fixture();let updates=0;f.queue.subscribe(()=>updates++);f.choose('performance');f.queue.dispose();f.advance(3000);assert.equal(f.sent.length,0);assert.equal(f.timers.size,0);assert.equal(updates,2);});
fs.writeFileSync(path.join(task,'validation/MAINLINE22-POWER-DEBOUNCE.json'),JSON.stringify({cases:cases.length,results:cases,virtualClock:true,hardwareWrites:0},null,2));console.log('Power debounce PASS '+cases.length);
