// Complete production host/relay/global adapter with memory-only IO owners.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {createMirrorHostFixture} from './fixtures/decky_mirror_host_fixture.mjs';import {task} from './fixtures/decky_task_paths.mjs';
const runId='a'.repeat(32),peer={connection:'1',runId},cases=[];let sequence=0;const flush=async()=>{for(let i=0;i<120;i++)await Promise.resolve();};
async function fixture(){const f=await createMirrorHostFixture();f.state.game=null;f.ready();f.read=async()=>{f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'snapshot',runId}});await flush();return f.replies.at(-1).message.snapshot;};f.edit=async(field,value,expected)=>{const s=expected??await f.read(),n=++sequence;f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'global.setField',runId,clientId:'global',id:'global:'+n,sequence:n,generation:s.generation,revision:s.revision,identity:'',args:{field,value}}});await flush();return f.replies.findLast(r=>r.message.id==='global:'+n)?.message;};return f;}
async function check(name,fn){await fn();cases.push(name);}
await check('no-game real global schedule and persona publish without fake EXE or admission leak',async()=>{const f=await fixture(),s=await f.read();assert.equal(s.game,null);assert.equal(s.actions.global,true);assert.equal(s.global.fields.acMode.value,f.state.schedule.active.ac);assert.equal(s.global.fields.padPersona.value,'steamdeck');assert.ok(s.global.fields.acMode.choices.every(o=>o.label.includes('W')));assert.ok(!JSON.stringify(s).includes('controlAdmission'));assert.equal(f.counts.saves,0);f.stop();});
await check('global AC mode reaches original schedule entry only, no dedicated EXE or frame write',async()=>{const f=await fixture();const r=await f.edit('acMode','performance');assert.equal(r.ok,true);assert.equal(f.counts.globalPowerApplies,1);assert.equal(f.state.schedule.active.ac,'performance');assert.equal(f.counts.saves,0);assert.equal(f.counts.frameApplies,0);assert.equal(f.counts.globalFrameSaves,0);f.stop();});
await check('inactive power-side global mutation refused without writes',async()=>{const f=await fixture();f.state.powerSource='dc';const r=await f.edit('acMode','extreme');assert.equal(r.ok,false);assert.equal(f.counts.globalPowerApplies,0);f.stop();});
await check('global persona uses original revision CAS and does not create an EXE profile',async()=>{const f=await fixture();const r=await f.edit('padPersona','elite');assert.equal(r.ok,true);assert.equal(f.state.input.outputTarget.persona,'elite');assert.equal(f.state.input.outputTarget.buttonMappingEnabled,true);assert.equal(f.counts.inputSaves,1);assert.equal(f.counts.saves,0);assert.equal(r.result.applied,false);assert.equal(r.result.pending,true);f.stop();});
await check('native persona stops mapping and gyro through original coupled settings patch',async()=>{const f=await fixture();f.state.input.outputTarget.gyroEnabled=true;f.state.input.gyroMotion.enabled=true;assert.equal((await f.edit('padPersona','disabled')).ok,true);assert.equal(f.state.input.outputTarget.buttonMappingEnabled,false);assert.equal(f.state.input.outputTarget.gyroEnabled,false);assert.equal(f.state.input.gyroMotion.enabled,false);f.stop();});
await check('global on transition respects the original opt-out gyro link',async()=>{const f=await fixture();f.state.input.outputTarget={persona:'disabled',buttonMappingEnabled:false,gyroEnabled:false};f.state.input.gyroMotion={enabled:false,virtualPadLink:false};assert.equal((await f.edit('padPersona','elite')).ok,true);assert.equal(f.state.input.gyroMotion.enabled,false);assert.equal(f.state.input.outputTarget.gyroEnabled,false);f.stop();});
await check('foreign input edit after snapshot is rejected at private source validation',async()=>{const f=await fixture(),s=await f.read();f.state.input.revision++;assert.equal((await f.edit('padPersona','elite',s)).ok,false);assert.equal(f.counts.inputSaves,0);f.stop();});
await check('global packet cannot be used with a current confirmed game',async()=>{const f=await fixture(),s=await f.read();f.state.game={name:'Other',path:'C:/Other.exe',pid:123,processCreated:'other'};f.gameChanged();assert.equal((await f.edit('padPersona','elite',s)).ok,false);assert.equal(f.counts.inputSaves,0);assert.equal(f.counts.saves,0);f.stop();});
await check('power transition refuses both global entry points',async()=>{for(const field of ['padPersona','acMode']){const f=await fixture();f.state.power.phase='pending';f.state.power.hardwareWritesAllowed=false;assert.equal((await f.edit(field,field==='acMode'?'extreme':'elite')).ok,false);assert.equal(f.counts.inputSaves,0);assert.equal(f.counts.globalPowerApplies,0);f.stop();}});
await check('malformed values never reach original owners',async()=>{for(const [field,value] of [['padPersona','follow'],['tdpHack','999'],['acMode','follow']]){const f=await fixture();assert.equal((await f.edit(field,value)).ok,false);assert.equal(f.counts.inputSaves,0);assert.equal(f.counts.globalPowerApplies,0);f.stop();}});
fs.writeFileSync(path.join(task,'validation/GLOBAL-CONTROLS.json'),JSON.stringify({pass:true,cases:cases.length,results:cases,actualProductionHostRelayAdapter:true,memoryIoBoundaries:true,physicalHardwareWrites:0,realConfigWrites:0},null,2));console.log('Global controls PASS '+cases.length);
