// Gyro mirror intents through exact original EXE store, lock and overlay; all effects inert.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {root,load,fixture,seed,profile,functions} from './fixtures/decky_game_memory_store.mjs';import {task} from './fixtures/decky_task_paths.mjs';
const require=createRequire(path.join(root,'package.json')),ts=require('typescript');
const key=load(fs.readFileSync(path.join(root,'src/bridge/gamePolicyHysteresis.ts'),'utf8'));
const actions=load(fs.readFileSync(path.join(root,'src/bridge/deckyGameActions.ts'),'utf8'),{'./gamePolicyHysteresis':key});
const overlayText=fs.readFileSync(path.join(root,'src/bridge/gyroPresetModel.ts'),'utf8')+'\n'+fs.readFileSync(path.join(root,'src/bridge/gameInputOverride.ts'),'utf8'),tree=ts.createSourceFile('overlay.ts',overlayText,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const functionNames=['isGyroPresetKey','gyroMotionParamsForPreset','isPadPersonaOverride','isGyroOverride','buildGameInputOverlay'];const constantNames=['PAD_PERSONAS','GYRO_OVERRIDES','GYRO_PRESET_KEYS','GYRO_PRESET_DEFINING_FIELDS'];
const nodes=tree.statements.filter(n=>ts.isFunctionDeclaration(n)&&functionNames.includes(n.name?.text)||ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>constantNames.includes(d.name.getText(tree))));assert.equal(nodes.length,9);
const overlay=load(nodes.map(n=>n.getText(tree)).join('\n'));
const defaultsModule=fs.readFileSync(path.join(root,'src/bridge/deckyGyroDefaults.ts'),'utf8');const plain=value=>JSON.parse(JSON.stringify(value));
async function setup(previous={...profile(),gyroOverride:'fps'}){
 const initial=seed();initial.entries['game.exe']=previous;const memory=fixture(initial);await memory.store.loadGameCustomConfig();
 const state={game:{pid:101,path:'D:/Games/Game.exe',processCreated:'native-created',name:'Game.exe'},power:{generation:1,phase:'ready',hardwareWritesAllowed:true},input:{revision:1,outputTarget:{persona:'steamdeck',gyroEnabled:true},gyroMotion:{enabled:true,preset:'fps',presets:{racing:{motionMode:'on',motionInput:'joystick-steering',outputStick:'left',outputAxis:'x'}}}},schedule:{version:2,active:{ac:'balanced',dc:'eco'},profiles:{ac:{},dc:{}}}};
 for(const side of ['ac','dc'])for(const mode of ['eco','balanced','medium','performance','elite','extreme'])state.schedule.profiles[side][mode]={...profile()[side]};
 let saves=0,reads=0,closed=false;const shared=load(defaultsModule,{'./settingsRepository':{readSettingsSection:async section=>{assert.equal(section,'input');reads++;return structuredClone(state.input);}}});
 const deps={featureAllowed:()=>!closed,game:()=>state.game,label:()=> 'Game',power:async()=>structuredClone(state.power),capabilities:()=>({heterogeneous:true,smtAvailable:true}),acquire:memory.lock.tryAcquireQuickAction,load:memory.store.loadGameCustomConfig,current:memory.store.getGameCustomConfig,schedule:async()=>structuredClone(state.schedule),currentSchedule:()=>state.schedule,save:async config=>{saves++;await memory.store.saveGameCustomConfig(config);},closeJoyxoff:()=>{throw Error('Gyro must not close a process');},gyroDefaults:shared.readGameMirrorGyroDefaults};
 const action=actions.createGameMirrorActions(deps);
 const context=async()=>({generation:state.power.generation,revision:1,gameIdentity:actions.gameMirrorIdentity(state.game),gameAdmission:actions.makeGameMirrorAdmission(memory.view().entries['game.exe'],state.schedule,undefined,(await shared.readGameMirrorGyroDefaults()).source),checkpoint:()=>{if(closed)throw Error('closed');}});
 return {memory,state,deps,context,run:async(field,value,ctx)=>action.execute('game.setField',{field,value},ctx??await context()),record:()=>memory.raw().entries['game.exe'],saves:()=>saves,reads:()=>reads,close:()=>closed=true,shared};
}
const cases=[];async function check(name,fn){await fn();cases.push(name);console.log('PASS '+name);}
await check('original override value derives selected preset; no independent renderer settings table',async()=>{const f=await setup({...profile(),gyroOverride:'racing',gyroPreset:'fps'});assert.equal(f.memory.view().entries['game.exe'].gyroPreset,'racing');const d=await f.shared.readGameMirrorGyroDefaults();assert.equal(actions.readGameMirrorGyro(f.memory.view().entries['game.exe'],d).preset,'racing');assert.equal(f.saves(),0);});
await check('off saves the selected preset in the original EXE record and on restores it',async()=>{const f=await setup({...profile(),gyroOverride:'racing'});await f.run('gyroEnabled','off');assert.equal(f.record().gyroOverride,'off');assert.equal(f.record().gyroPreset,'racing');await f.run('gyroEnabled','on');assert.equal(f.record().gyroOverride,'racing');assert.equal(f.record().gyroPreset,'racing');assert.equal(f.saves(),2);});
await check('each of the original four choices sets only its original override/preset keys',async()=>{for(const preset of ['fps','racing','custom','steam']){const f=await setup();await f.run('gyroPreset',preset);assert.equal(f.record().gyroOverride,preset);assert.equal(f.memory.view().entries['game.exe'].gyroPreset,preset);assert.equal(f.record().enabled,true);assert.ok(!Object.hasOwn(f.record(),'gyroEnabled'));}});
await check('server refuses changing a preset while its gyro switch is off',async()=>{const f=await setup({...profile(),gyroOverride:'off',gyroPreset:'racing'});await assert.rejects(f.run('gyroPreset','steam'),/GYRO_DISABLED/);assert.equal(f.saves(),0);assert.equal(f.record().gyroPreset,'racing');});
await check('native-pad disabled rejects both gyro controls before any save',async()=>{for(const field of ['gyroEnabled','gyroPreset']){const f=await setup({...profile(),padPersona:'disabled'});await assert.rejects(f.run(field,field==='gyroEnabled'?'on':'fps'),/GYRO_LOCKED/);assert.equal(f.saves(),0);}});
await check('follow with an original disabled virtual pad cannot falsely enable or change gyro',async()=>{const f=await setup({...profile(),padPersona:'follow',gyroOverride:'follow'});f.state.input.outputTarget.persona='disabled';const global=await f.shared.readGameMirrorGyroDefaults();assert.equal(actions.readGameMirrorGyro(f.memory.view().entries['game.exe'],global).enabled,false);await assert.rejects(f.run('gyroEnabled','on'),/GYRO_LOCKED/);await assert.rejects(f.run('gyroPreset','racing'),/GYRO_LOCKED/);assert.equal(f.saves(),0);});
await check('malformed switch/preset choices never reach original save',async()=>{for(const [field,value] of [['gyroEnabled','follow'],['gyroEnabled','true'],['gyroPreset','on'],['gyroPreset','off'],['gyroPreset','invented']]){const f=await setup();await assert.rejects(f.run(field,value),/INVALID_FIELD/);assert.equal(f.saves(),0);}});
await check('follow shows the current original global preset rather than stale remembered EXE preset',async()=>{const f=await setup({...profile(),gyroOverride:'follow',gyroPreset:'racing'});f.state.input.gyroMotion.preset='steam';const view=actions.readGameMirrorGyro(f.memory.view().entries['game.exe'],await f.shared.readGameMirrorGyroDefaults());assert.equal(view.preset,'steam');assert.equal(view.enabled,true);});
await check('turning off an inherited global preset remembers that current original preset',async()=>{const f=await setup({...profile(),gyroOverride:'follow'});f.state.input.gyroMotion.preset='steam';await f.run('gyroEnabled','off');assert.equal(f.record().gyroPreset,'steam');assert.equal(f.record().gyroOverride,'off');});
await check('legacy on stays readable; explicit off/on retains original global preset',async()=>{const f=await setup({...profile(),gyroOverride:'on'});f.state.input.gyroMotion.preset='custom';await f.run('gyroEnabled','off');await f.run('gyroEnabled','on');assert.equal(f.record().gyroOverride,'custom');});
await check('a duplicate explicit on is a no-op, not a repeated config/hardware request',async()=>{const f=await setup();await f.run('gyroEnabled','on');assert.equal(f.saves(),0);});
await check('a displayed inherited same-preset choice explicitly remembers an EXE override',async()=>{const f=await setup({...profile(),gyroOverride:'follow'});await f.run('gyroPreset','fps');assert.equal(f.saves(),1);assert.equal(f.record().gyroOverride,'fps');});
await check('stale global preset or enabled state cannot be committed from an old menu',async()=>{for(const changed of ['preset','enabled']){const f=await setup({...profile(),gyroOverride:'follow'}),ctx=await f.context();if(changed==='preset')f.state.input.gyroMotion.preset='racing';else f.state.input.gyroMotion.enabled=false;await assert.rejects(f.run('gyroPreset','steam',ctx),/SOURCE_CHANGED/);assert.equal(f.saves(),0);}});
await check('unrelated input receipt/revision changes do not fabricate a global preset conflict',async()=>{const f=await setup(),ctx=await f.context();f.state.input.revision++;f.state.input.applyStatus='host-acknowledged';await f.run('gyroPreset','steam',ctx);assert.equal(f.saves(),1);});
await check('missing source admission refuses a gyro request rather than guessing defaults',async()=>{const f=await setup(),ctx=await f.context();delete ctx.gameAdmission.gyro;await assert.rejects(f.run('gyroPreset','racing',ctx),/SOURCE_REQUIRED/);assert.equal(f.saves(),0);});
await check('pending power and an admitted generation mismatch cannot save gyro controls',async()=>{for(const change of ['pending','generation']){const f=await setup(),ctx=await f.context();if(change==='pending')f.state.power.phase='pending';else f.state.power.generation++;await assert.rejects(f.run('gyroEnabled','off',ctx),/POWER_NOT_READY/);assert.equal(f.saves(),0);}});
await check('game PID/creation identity changes reject a captured menu',async()=>{const f=await setup(),ctx=await f.context();f.state.game.processCreated='reused';await assert.rejects(f.run('gyroPreset','racing',ctx),/TARGET_CHANGED/);assert.equal(f.saves(),0);});
await check('original shared quick-action lock serializes both gyro controls',async()=>{const f=await setup(),release=f.memory.lock.tryAcquireQuickAction('original-panel');await assert.rejects(f.run('gyroPreset','racing'),/BUSY/);assert.equal(f.saves(),0);release();await f.run('gyroPreset','racing');assert.equal(f.saves(),1);});
await check('global or document changes during the final defaults read are rejected before save',async()=>{const f=await setup(),ctx=await f.context();let calls=0;const original=f.deps.gyroDefaults;f.deps.gyroDefaults=async()=>{const value=await original();if(++calls===2)f.state.input.gyroMotion.preset='steam';return calls===2?original():value;};await assert.rejects(f.run('gyroPreset','racing',ctx),/SOURCE_CHANGED/);assert.equal(f.saves(),0);});
await check('power pending during final global-default read refuses the original gyro save',async()=>{const f=await setup(),ctx=await f.context();let calls=0;const original=f.deps.gyroDefaults;f.deps.gyroDefaults=async()=>{const value=await original();if(++calls===2)f.state.power.phase='pending';return value;};await assert.rejects(f.run('gyroPreset','racing',ctx),/POWER_NOT_READY/);assert.equal(f.saves(),0);});
await check('gyro edits preserve original AC/DC, CPU/core, pad and RTSS fields',async()=>{const f=await setup(),before=plain(f.memory.view().entries['game.exe']),rtss=plain(f.memory.view().rtss);await f.run('gyroPreset','racing');const after=f.record();for(const field of ['ac','dc','acMode','dcMode','corePolicyMode','hyperThreadPolicy','padPersona'])assert.deepEqual(after[field],before[field]);assert.deepEqual(plain(f.memory.raw().rtss),rtss);});
await check('original overlay applies all original presets; disabled gyro keeps global data unchanged',async()=>{for(const preset of ['fps','racing','custom','steam']){const f=await setup({...profile(),padPersona:'steamdeck',gyroOverride:preset}),before=JSON.stringify(f.state.input);const result=overlay.buildGameInputOverlay(f.state.input,f.memory.view().entries['game.exe'],'game-id','session-id');assert.equal(result.gyroMotion.preset,preset);assert.equal(result.outputTarget.gyroEnabled,true);assert.equal(result.gyroMotion.enabled,true);assert.equal(JSON.stringify(f.state.input),before);}const f=await setup({...profile(),gyroOverride:'off',gyroPreset:'racing'});const result=overlay.buildGameInputOverlay(f.state.input,f.memory.view().entries['game.exe'],'game-id','session-id');assert.equal(result.outputTarget.gyroEnabled,false);assert.equal(result.gyroMotion.enabled,false);});
await check('a preset survives original store reload and older records remain valid without migrations',async()=>{const f=await setup({...profile(),gyroOverride:'racing'});await f.run('gyroEnabled','off');const second=fixture(f.memory.raw());await second.store.loadGameCustomConfig();assert.equal(second.view().entries['game.exe'].gyroPreset,'racing');const old=fixture(seed());await old.store.loadGameCustomConfig();assert.equal(old.view().entries['game.exe'].gyroOverride,'follow');assert.ok(!old.calls.some(c=>c[0]==='write'));});
const report={stage:'Mainline21',cases:cases.length,results:cases,originalStoreLockOverlay:true,originalModelExtension:'optional gyroPreset in the existing EXE entry',separateSidebarStore:false,realConfigWrites:0,physicalHardwareWrites:0,actualSteam:false};fs.writeFileSync(path.join(task,'validation/MAINLINE21-GYRO-ACTIONS.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
