import { task } from './fixtures/decky_task_paths.mjs';
// Baseline and fixed examination of hidden fresh-state activation. Original
// store and exact production host, with ALL business documents held in memory.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {root,seed,profile,main} from './fixtures/decky_game_memory_store.mjs';import {createMirrorHostFixture} from './fixtures/decky_mirror_host_fixture.mjs';
const baseline=process.argv.includes('--baseline'),runId='a'.repeat(32),peer={connection:'1',runId,connected:true};const flush=async()=>{for(let i=0;i<120;i++)await Promise.resolve();};
async function opened(initial,warm=true){const f=await createMirrorHostFixture({initial,warm});f.ready();f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'snapshot',runId}});await flush();return f;}
const latest=f=>f.replies.filter(reply=>reply.message.type==='snapshot').at(-1)?.message.snapshot;
async function edit(f,snapshot,sequence=1){const before=f.replies.length;f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'game.setField',runId,id:`source:${sequence}`,clientId:'source',sequence,generation:snapshot.generation,revision:snapshot.revision,identity:snapshot.game?.identity,args:{field:'acMode',value:'performance'}}});await flush();return f.replies.slice(before).find(reply=>reply.message.type==='reply')?.message;}
const results=[];
const initial=seed();initial.entries['game.exe']={...profile(),enabled:false,corePolicyEnabled:true,corePolicyMode:'only-small',hyperThreadPolicyEnabled:true,hyperThreadPolicy:'off',padPersona:'disabled'};
const cold=await opened(initial,false),coldSnapshot=latest(cold),coldReply=await edit(cold,coldSnapshot);
results.push({case:'cold cache hides existing dormant profile',shownCore:coldSnapshot.game.fields.corePolicyMode.value,storedCoreAfter:cold.memory.raw().entries['game.exe'].corePolicyMode,replyOk:coldReply.ok,saves:cold.counts.saves,enabledAfter:cold.memory.raw().entries['game.exe'].enabled});
if(!baseline){assert.equal(coldReply.ok,false);assert.match(coldReply.error,/未保存.*不自动重试/);assert.equal(cold.counts.saves,0);assert.equal(cold.counts.joyxoff,0);assert.equal(cold.counts.schedule,1);const refreshed=latest(cold);assert.equal(refreshed.game.fields.corePolicyMode.value,'only-small');assert.ok(!refreshed.notice.includes('首次修改'));const accepted=await edit(cold,refreshed,2);assert.equal(accepted.ok,true);assert.equal(cold.counts.saves,1);}cold.stop();
const silent=await opened(seed()),shown=latest(silent),external=silent.memory.raw();external.entries['game.exe'].corePolicyEnabled=true;external.entries['game.exe'].corePolicyMode='only-small';silent.memory.documents.set(main,JSON.stringify(external));const silentReply=await edit(silent,shown);
results.push({case:'silent external EXE profile change',shownCore:shown.game.fields.corePolicyMode.value,storedCoreAfter:silent.memory.raw().entries['game.exe'].corePolicyMode,replyOk:silentReply.ok,saves:silent.counts.saves});
if(!baseline){assert.equal(silentReply.ok,false);assert.equal(silent.counts.saves,0);assert.equal(silent.counts.joyxoff,0);assert.equal(silent.counts.schedule,1);assert.equal(latest(silent).game.fields.corePolicyMode.value,'only-small');}silent.stop();
const schedule=await opened({version:1,entries:{},rtss:{}}),oldSchedule=latest(schedule);schedule.state.schedule.active.dc='extreme';schedule.state.schedule.profiles.dc.extreme.tdpMax=21;const scheduleReply=await edit(schedule,oldSchedule);
results.push({case:'silent global preset change',shownDc:oldSchedule.game.fields.dcMode.choices[0].label,storedDcAfter:schedule.memory.raw().entries['game.exe']?.dcMode,replyOk:scheduleReply.ok,saves:schedule.counts.saves});
if(!baseline){assert.equal(scheduleReply.ok,false);assert.equal(schedule.counts.saves,0);assert.equal(schedule.counts.schedule,2);assert.match(latest(schedule).game.fields.dcMode.choices[0].label,/极致性能.*21W/);const accepted=await edit(schedule,latest(schedule),2);assert.equal(accepted.ok,true);assert.equal(schedule.memory.raw().entries['game.exe'].dcMode,'extreme');}schedule.stop();
const report={project:'YMCC Decky 侧边栏',stage:'Implementation11',phase:baseline?'baseline':'fixed',results,actualSourceHost:true,originalStoreMemoryBacked:true,realBusinessFileWrites:0,physicalHardwareWrites:0,scope:'Does a user-visible revision protect the original profile and global presets that the user actually saw?'};
fs.writeFileSync(path.resolve(task,baseline?'validation/MIRROR-SOURCE-ADMISSION11-BASELINE.json':'validation/MIRROR-SOURCE-ADMISSION11-FIXED.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
