import { task } from './fixtures/decky_task_paths.mjs';
// Actual production host path with the real original memory-backed business store.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {root,base,profile,seed} from './fixtures/decky_game_memory_store.mjs';import {createMirrorHostFixture} from './fixtures/decky_mirror_host_fixture.mjs';
const flush=async()=>{for(let i=0;i<100;i++)await Promise.resolve();};const runId='a'.repeat(32),peer={connection:'1',runId,connected:true};const cases=[];
async function fixture(initial){const f=await createMirrorHostFixture({initial});let sequence=0;
 f.read=async()=>{f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'snapshot',runId}});await flush();return f.replies.filter(reply=>reply.message.type==='snapshot').at(-1)?.message.snapshot;};
 f.edit=async(field,value,snapshot)=>{const before=f.replies.length,snap=snapshot??await f.read();sequence++;f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'game.setField',runId,id:'host:'+sequence,clientId:'host',sequence,generation:snap.generation,revision:snap.revision,identity:snap.game?.identity,args:{field,value}}});await flush();return f.replies.slice(before).find(reply=>reply.message.type==='reply')?.message;};
 return f;
}
async function check(name,fn){await fn();cases.push(name);}
await check('host construction and ready-without-peer do not query power/capability/schedule or save',async()=>{const f=await fixture();assert.equal(f.counts.power,0);assert.equal(f.counts.saves,0);f.ready();await flush();assert.equal(f.counts.power,0);assert.equal(f.counts.capabilities,0);assert.equal(f.counts.schedule,0);assert.equal(f.counts.attaches,1);f.stop();});
await check('early snapshot fails ready without forcing owners or creating entries',async()=>{const f=await fixture();const snap=await f.read();assert.equal(snap.ready,false);assert.equal(f.counts.power,0);assert.equal(f.counts.saves,0);assert.deepEqual(f.memory.raw().entries,{});f.stop();});
await check('first ready snapshot shows global modes and original new core default before persistence',async()=>{const f=await fixture();f.ready();const snap=await f.read();assert.equal(snap.actions.game,true);assert.equal(snap.game.fields.acMode.value,'follow');assert.equal(snap.game.fields.corePolicyMode.value,'big-small');assert.ok(!snap.notice.includes('默认核心'));assert.equal(snap.powerSource,'ac');assert.ok(!snap.notice.includes('不是硬件回读'));assert.equal(f.counts.saves,0);assert.equal(f.counts.capabilities,1);assert.equal(f.counts.schedule,1);await f.read();assert.equal(f.counts.capabilities,1);assert.equal(f.counts.schedule,1);f.stop();});
await check('actual host first edit remembers and enables original EXE through adapter once',async()=>{const f=await fixture();f.ready();const snap=await f.read(),reply=await f.edit('acMode','performance',snap);assert.equal(reply.ok,true);assert.equal(reply.result.saved,true);assert.equal(reply.result.applied,false);assert.equal(reply.result.pending,true);const entry=f.memory.raw().entries['game.exe'];assert.equal(entry.enabled,true);assert.equal(entry.acMode,'performance');assert.equal(entry.dcMode,'eco');assert.equal(entry.corePolicyMode,snap.game.fields.corePolicyMode.value);assert.equal(entry.displayName,'Fixture Game');assert.equal(f.counts.saves,1);assert.equal(f.counts.fanSaves,0);f.stop();});
await check('all six original fields cross actual host and retain original schema',async()=>{const f=await fixture();f.ready();await f.read();for(const [field,value] of [['acMode','performance'],['dcMode','extreme'],['corePolicyMode','only-small'],['hyperThreadPolicy','off'],['padPersona','elite'],['gyroOverride','fps']]){const reply=await f.edit(field,value);assert.equal(reply.ok,true,field);assert.equal(reply.result.saved,true,field);}const entry=f.memory.raw().entries['game.exe'];assert.equal(entry.corePolicyEnabled,true);assert.equal(entry.hyperThreadPolicyEnabled,true);assert.equal(entry.padPersona,'elite');assert.equal(entry.gyroOverride,'fps');assert.equal(f.counts.saves,6);assert.ok(!Object.hasOwn(entry,'steamAppId'));f.stop();});
await check('dormant original choices are visible but read never activates them',async()=>{const initial=seed();initial.entries['game.exe']={...profile(),enabled:false,corePolicyMode:'only-small',corePolicyEnabled:true,hyperThreadPolicy:'off',hyperThreadPolicyEnabled:true,padPersona:'elite',gyroOverride:'racing'};const f=await fixture(initial);f.ready();const snap=await f.read();assert.equal(snap.game.fields.corePolicyMode.value,'only-small');assert.equal(snap.game.fields.padPersona.value,'elite');assert.ok(!snap.notice.includes('首次修改'));assert.equal(f.memory.raw().entries['game.exe'].enabled,false);assert.equal(f.counts.saves,0);const reply=await f.edit('dcMode','extreme',snap);assert.equal(reply.ok,true);assert.equal(f.memory.raw().entries['game.exe'].enabled,true);assert.equal(f.memory.raw().entries['game.exe'].gyroOverride,'racing');f.stop();});
await check('legacy snapshots display actual saved AC/DC with explicit original edit-conversion notice',async()=>{const initial=seed();delete initial.entries['game.exe'].acMode;delete initial.entries['game.exe'].dcMode;initial.entries['game.exe'].ac.tdpMax=25;initial.entries['game.exe'].dc.tdpMax=15;const f=await fixture(initial);f.ready();const snap=await f.read();assert.equal(snap.game.fields.acMode.value,'legacy');assert.match(snap.game.fields.acMode.choices.find(choice=>choice.data==='legacy').label,/25W/);assert.match(snap.game.fields.dcMode.choices.find(choice=>choice.data==='legacy').label,/15W/);assert.ok(!snap.notice.includes('以下为方案值'));assert.equal(f.counts.saves,0);f.stop();});
await check('unsupported core/SMT flags are mirrored and requests refused before save',async()=>{const f=await fixture();f.state.caps.heterogeneous=false;f.state.caps.smtAvailable=false;f.ready();let snap=await f.read();assert.equal(snap.game.fields.corePolicyMode.supported,false);assert.equal(snap.game.fields.hyperThreadPolicy.supported,false);for(const [field,value] of [['corePolicyMode','only-small'],['hyperThreadPolicy','on']]){const reply=await f.edit(field,value);assert.equal(reply.ok,false);}assert.equal(f.counts.saves,0);f.stop();});
await check('failed capability probe after resume clears old support and does not cause per-snapshot retries',async()=>{const f=await fixture();f.ready();const old=await f.read();assert.equal(old.game.fields.corePolicyMode.supported,true);f.state.power={...f.state.power,generation:2};f.state.caps=null;f.powerChanged();await flush();const fresh=await f.read();assert.equal(fresh.game.fields.corePolicyMode.supported,false);assert.equal(fresh.game.fields.hyperThreadPolicy.supported,false);assert.equal((await f.edit('corePolicyMode','only-small',fresh)).ok,false);const probes=f.counts.capabilities;await f.read();assert.equal(f.counts.capabilities,probes);assert.equal(f.counts.saves,0);f.stop();});
await check('native pad disables gyro field and actual host preserves coupled reset',async()=>{const f=await fixture();f.ready();await f.read();assert.equal((await f.edit('padPersona','disabled')).ok,true);const snap=await f.read();assert.equal(snap.game.fields.gyroOverride.supported,false);assert.equal(snap.game.fields.gyroOverride.value,'follow');assert.equal((await f.edit('gyroOverride','fps',snap)).ok,false);assert.equal(f.counts.saves,1);f.stop();});
await check('shared panel lock rejects once then recovers without a new busy observer or timer',async()=>{const f=await fixture();f.ready();const snap=await f.read(),release=f.memory.lock.tryAcquireQuickAction('top-custom-profile-select-mode');assert.equal(snap.actions.game,true);assert.equal((await f.edit('acMode','performance',snap)).ok,false);assert.equal(f.counts.saves,0);release();assert.equal((await f.edit('acMode','performance')).ok,true);assert.equal(f.counts.saves,1);f.stop();});
await check('pending/resumed power gates both UI-ready and stale accepted generation',async()=>{const f=await fixture();f.ready();const old=await f.read();f.state.power={...f.state.power,generation:2,phase:'pending',hardwareWritesAllowed:false};f.powerChanged(true);await flush();assert.equal((await f.read()).ready,false);assert.equal((await f.edit('acMode','performance',old)).ok,false);assert.equal(f.counts.saves,0);f.state.power={...f.state.power,phase:'ready',hardwareWritesAllowed:true};f.powerChanged();await flush();const fresh=await f.read();assert.equal(fresh.ready,true);assert.equal(fresh.generation,2);assert.equal((await f.edit('acMode','performance',fresh)).ok,true);assert.equal(f.counts.saves,1);f.stop();});
await check('game switch rejects old identity while non-Steam new target uses same EXE store',async()=>{const f=await fixture();f.ready();const old=await f.read();f.state.game={...f.state.game,pid:202,processCreated:'987654321',name:'Offline.exe',title:'Offline',path:'D:/GOG/Offline.exe'};f.gameChanged();await flush();assert.equal((await f.edit('acMode','performance',old)).ok,false);assert.equal(f.counts.saves,0);assert.equal((await f.edit('acMode','performance')).ok,true);assert.equal(f.memory.raw().entries['offline.exe'].enabled,true);assert.equal(f.memory.raw().entries['game.exe'],undefined);f.stop();});
await check('Steam metadata cannot provide a missing target and never persists an AppID',async()=>{const f=await fixture();f.state.game=null;f.ready();f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'snapshot',runId,steam:{availability:'observed',appId:'480',runningCount:1}}});await flush();const snap=await f.read();assert.equal(snap.game,null);assert.equal(snap.actions.game,false);assert.equal(snap.steam.appId,'480');assert.equal(f.counts.saves,0);f.stop();});
await check('host stop removes all event/observer bindings and cannot save through stale request',async()=>{const f=await fixture();f.ready();const snap=await f.read();f.stop();assert.deepEqual(f.observerStats(),{ipc:0,game:0,schedule:0,fan:0,watchers:0});f.emit('deckySidebar.mirrorRequest',{...peer,request:{command:'game.setField',runId,id:'late:1',clientId:'late',sequence:1,generation:1,revision:snap.revision,identity:snap.game.identity,args:{field:'acMode',value:'performance'}}});await flush();assert.equal(f.counts.saves,0);});
const report={project:'YMCC Decky 侧边栏',stage:process.argv.includes('--stage14')?'Implementation14':process.argv.includes('--stage13')?'Implementation13':process.argv.includes('--stage12')?'Implementation12':process.argv.includes('--stage11')?'Implementation11':'Implementation10',dateHongKong:'2026-10-09',cases:cases.length,results:cases,productionHostExecutedInVm:true,productionRelayAndAdapters:true,originalStoreLockNormalizer:true,actualWebView:false,actualSteam:false,actualHardwareWrites:0,realBusinessFileWrites:0,gameHostWired:true};fs.writeFileSync(path.resolve(task,process.argv.includes('--stage14')?'validation/MIRROR-HOST-IMPLEMENTATION14.json':process.argv.includes('--stage13')?'validation/MIRROR-HOST-IMPLEMENTATION13.json':process.argv.includes('--stage12')?'validation/MIRROR-HOST-IMPLEMENTATION12.json':process.argv.includes('--stage11')?'validation/MIRROR-HOST-IMPLEMENTATION11.json':'validation/MIRROR-HOST-IMPLEMENTATION10.json'),JSON.stringify(report,null,2));console.log(`Actual production mirror host inert checks passed: ${cases.length}`);
