// One real DFL checkbox failure through native Broker and exact original LS owner, strictly memory IO.
import fs from 'node:fs';import assert from 'node:assert/strict';import {targets,connect} from './fixtures/decky_cdp.mjs';
import path from 'node:path';import {task} from './fixtures/decky_task_paths.mjs';
const name=process.env.YMCC_DECKY_UI_RUN_NAME||'GOAL28-FAILURE-ROLLBACK';if(!/^[A-Z0-9-]+$/.test(name))throw Error('Session name rejected');const file=path.join(task,'validation',name+'.json'),out=path.join(task,'validation/TOGGLE-FAILURE-UI.json');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let c,q;const report={actualSteam:true,actualDfl:true,originalLosslessOwner:true,physicalHardwareWrites:0,realBusinessConfigWrites:0};
try{
 const s=JSON.parse(fs.readFileSync(file,'utf8'));const refusedBefore=s.ownerStats?.lossless?.events.filter(e=>e==='original-launch-refused').length??0;fs.writeFileSync(s.memoryStateRequestPath,JSON.stringify({losslessLaunchDenied:true}));await sleep(200);
 c=await connect((await targets()).find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);for(let i=0;i<100;i++){if(await c.evaluate(`window.__TABS_HOOK_INSTANCE?.tabs?.some(t=>t.id===100019)`))break;await sleep(100);}await c.evaluate(`DFL.Navigation.CloseSideMenus();DFL.Navigation.OpenQuickAccessMenu(100019);true`);await sleep(400);q=await connect((await targets()).find(t=>t.title.startsWith('QuickAccess')).webSocketDebuggerUrl);
 const read=`(()=>{const e=Array.from(document.querySelectorAll('.ymcc-decky-sidebar [role=checkbox]')).find(e=>document.getElementById(e.getAttribute('aria-labelledby'))?.innerText==='LosslessScaling 插帧');return {checked:e?.getAttribute('aria-checked'),rect:e?.getBoundingClientRect().toJSON(),notice:document.querySelector('.ymcc-decky-notice')?.innerText,focused:e===document.activeElement};})()`;
 for(let i=0;i<100;i++){if((await q.evaluate(read)).checked==='false')break;await sleep(100);}await q.evaluate(`(()=>{const e=Array.from(document.querySelectorAll('.ymcc-decky-sidebar [role=checkbox]')).find(e=>document.getElementById(e.getAttribute('aria-labelledby'))?.innerText==='LosslessScaling 插帧');e.scrollIntoView({block:'center'});return true;})()`);await sleep(100);report.before=await q.evaluate(read);assert.equal(report.before.checked,'false');const r=report.before.rect;
 for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x:r.left+r.width/2,y:r.top+r.height/2,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});
 for(let i=0;i<100;i++){const data=JSON.parse(fs.readFileSync(file,'utf8'));if((data.ownerStats?.lossless?.events.filter(e=>e==='original-launch-refused').length??0)>refusedBefore){report.after=await q.evaluate(read);break;}await sleep(100);}assert.ok(report.after,'exact original launch denial must be observed');await sleep(150);report.after=await q.evaluate(read);
 const end=JSON.parse(fs.readFileSync(file,'utf8'));report.ownerStats=end.ownerStats.lossless;report.mutations=end.mutationRequests;assert.equal(report.ownerStats.running,false);assert.ok(report.ownerStats.events.includes('original-launch-refused'));assert.equal(report.ownerStats.profileXmlUnchanged,true);
 report.pass=report.after.checked==='false'&&/未确认|失败/.test(report.after.notice);fs.writeFileSync(out,JSON.stringify(report,null,2));assert.ok(/未确认|失败/.test(report.after.notice),'failed owner error must survive the subsequent confirmed-state snapshot');assert.equal(report.after.checked,'false','failed native owner must rollback optimistic DFL checkbox to confirmed off');console.log('Failed-operation checkbox rollback PASS');
}catch(error){report.failure=error.stack;fs.writeFileSync(out,JSON.stringify(report,null,2));throw error;}finally{q?.close();c?.close();}
