// Exact current original FanHostLifecycle plus mirror, no real Host/device IO.
import assert from 'node:assert/strict';import fs from 'node:fs';
import {FanHostLifecycle,type FanHostLauncher} from '../src/bridge/fanHost';
import {isColdUnopenedFanHost} from '../src/bridge/fanSessionEvidence';
import {createFanMirrorActions} from '../src/bridge/deckyFanActions';
import {NoIoHost} from './fixtures/fan_no_io_host';
import type {FanPreset} from '../src/bridge/fanFeature';import type {PowerLifecycleState} from '../src/bridge/api';
const task=process.env.YMCC_DECKY_ARTIFACT_ROOT||'G:/YeManCC-Work/Build/Tasks/YMCC-Decky-Sidebar';
const curves={soft:[{tempC:0,dutyPercent:0},{tempC:40,dutyPercent:15},{tempC:70,dutyPercent:30},{tempC:100,dutyPercent:70}],balanced:[{tempC:0,dutyPercent:0},{tempC:40,dutyPercent:20},{tempC:70,dutyPercent:45},{tempC:100,dutyPercent:90}],aggressive:[{tempC:0,dutyPercent:0},{tempC:40,dutyPercent:30},{tempC:70,dutyPercent:75},{tempC:100,dutyPercent:100}]};
function fixture(shell='AwaitingControl',cachedActive=false){
 const host=new NoIoHost();host.stateName=shell;
 // The generic primary NoIoHost holds Stopped until Enable. For this cold
 // shell test use the ACTUAL engine's public Open/OpenEvents states: Open,
 // then Ready. This is test-only protocol projection, not production policy.
 const engineSource=fs.readFileSync('G:/YeManCC-Work/Mainline/YeManCC-source/YeManCC/FanLab/real-host/Program.cs','utf8');
 assert.ok(engineSource.includes('state.State = automaticResumeInProgress ? "Resuming" : "Open";'));
 assert.ok(engineSource.includes('state.State = automaticResumeInProgress ? "Resuming" : "Ready";'));
 const open=host.open.bind(host),events=host.openEvents.bind(host);
 host.open=async()=>{await open();host.stateName='Open';return host.snapshot();};
 host.openEvents=async()=>{await events();host.stateName='Ready';return host.snapshot();};
 let power:PowerLifecycleState={generation:2,phase:'ready',hardwareWritesAllowed:true,inputReady:true,resumeReady:true,hibernateAvailable:true};
 let active=cachedActive,preset:FanPreset='balanced',nativeReads=0,mirrorPowerReads=0,saves=0;let nativeOverride:(()=>Promise<PowerLifecycleState|null>)|null=null;
 const launcher:FanHostLauncher={start:async()=>({pid:944,executable:'inert-no-io-host.exe'}),stop:async()=>{}};
 const life=new FanHostLifecycle({enabled:true,launcher,adapter:host,heartbeatIntervalMs:5000,resumeWaitDeadlineMs:500,readNativePowerState:async()=>{nativeReads++;return nativeOverride?nativeOverride():power;}});
 life.setPowerGeneration(2);life.observePowerBoundary('suspending',2);life.observePowerBoundary('resuming',2);life.observePowerBoundary('resume-ready',2);
 const action=createFanMirrorActions({owner:life,enabled:()=>active,currentPreset:()=>preset,curve:name=>structuredClone(curves[name]),save:async(_nodes,name)=>{preset=name;saves++;},updateActive:value=>{active=value;},updateDuty:()=>{},power:async()=>{mirrorPowerReads++;return power;},featureAllowed:()=>true,uiBusy:()=>false,display:()=>{}});
 const execute=(command:'fan.setEnabled'|'fan.setPreset',args:Record<string,unknown>,generation=power.generation)=>action.execute(command,args,{generation,checkpoint:()=>{}});
 return {host,life,execute,stats:()=>({active,preset,nativeReads,mirrorPowerReads,saves,ownerIntent:life.hasControlIntent,ownerReady:life.controlReady,ownerState:life.state}),setPower:(value:PowerLifecycleState)=>power=value,native:(run:()=>Promise<PowerLifecycleState|null>)=>nativeOverride=run};
}
async function main(){
 if(process.argv.includes('--baseline')){const f=fixture('AwaitingControl',true);const outcome=await f.execute('fan.setEnabled',{enabled:true});const record={project:'YMCC Decky 侧边栏',stage:'Implementation12',phase:'baseline',outcome,hostCalls:[...f.host.calls],stats:f.stats(),actualOriginalOwner:true,physicalHardwareWrites:0,actualHostProcesses:0};fs.writeFileSync(task+'/validation/FAN-CACHED-ACTIVE12-BASELINE.json',JSON.stringify(record,null,2));await f.life.close();console.log(JSON.stringify(record));return;}
 const cases:string[]=[],details:unknown[]=[];const check=async(name:string,run:()=>Promise<void>|void)=>{console.log(`RUN_CASE=${name}`);await run();cases.push(name);};
 await check('cached UI active with no original owner does not report a fabricated applied no-op',async()=>{const f=fixture('AwaitingControl',true);try{assert.equal(f.life.hasControlIntent,false);const result=await f.execute('fan.setEnabled',{enabled:true});assert.equal(result.applied,true);assert.equal(f.host.calls.filter(c=>c==='enable').length,1);assert.equal(f.life.hasControlIntent,true);assert.equal(f.life.controlReady,true);details.push({cachedActiveTrueNativeReads:f.stats().nativeReads,mirrorPowerReads:f.stats().mirrorPowerReads,ownerCalls:[...f.host.calls]});}finally{await f.life.close();}});
 for(const shell of ['AwaitingControl','Stopped'])await check(`original unopened ${shell} Host created after prior sleep opens/enables once without phantom Resume`,async()=>{const f=fixture(shell);try{const result=await f.execute('fan.setEnabled',{enabled:true});assert.equal(result.applied,true);for(const op of ['open','events','acquire','enable'])assert.equal(f.host.calls.filter(c=>c===op).length,1,op);assert.equal(f.host.calls.includes('resume'),false);const lease=f.life.currentLease?.leaseId;assert.ok(lease);const before=f.host.calls.length;await f.execute('fan.setEnabled',{enabled:true});assert.equal(f.host.calls.length,before);await f.execute('fan.setPreset',{preset:'soft'});assert.equal(f.host.calls.filter(c=>c==='preset').length,1);assert.equal(f.host.calls.filter(c=>c==='enable').length,1);assert.equal(f.host.calls.includes('resume'),false);assert.equal(f.life.currentLease?.leaseId,lease);await f.execute('fan.setEnabled',{enabled:false});assert.equal(f.stats().active,false);assert.equal(f.life.currentLease,null);assert.ok(f.host.calls.includes('restore')&&f.host.calls.includes('release'));}finally{await f.life.close();}});
 await check('off-state preset is global save only, not cold HC start',async()=>{const f=fixture();try{const r=await f.execute('fan.setPreset',{preset:'aggressive'});assert.equal(r.saved,true);assert.equal(r.applied,false);assert.equal(f.host.calls.length,0);assert.equal(f.stats().saves,1);}finally{await f.life.close();}});
 await check('stale/pending mirror power refuses all original owner callbacks',async()=>{const f=fixture();try{await assert.rejects(f.execute('fan.setEnabled',{enabled:true},1),/POWER_NOT_READY/);assert.equal(f.host.calls.length,0);f.setPower({generation:3,phase:'suspending',hardwareWritesAllowed:false,inputReady:false,resumeReady:false,hibernateAvailable:true});await assert.rejects(f.execute('fan.setEnabled',{enabled:true},3),/POWER_NOT_READY/);assert.equal(f.host.calls.length,0);}finally{await f.life.close();}});
 await check('genuine sleep keeps the original resume owner and uses one new lease after its receipt',async()=>{const f=fixture();try{await f.execute('fan.setEnabled',{enabled:true});const oldLease=f.life.currentLease?.leaseId;f.setPower({generation:3,phase:'suspending',hardwareWritesAllowed:false,inputReady:false,resumeReady:false,hibernateAvailable:true});f.life.setPowerGeneration(3);f.life.observePowerBoundary('suspending',3);
 // Native HC SystemPending is an independent Host callback; the local owner
 // may already be Suspended and need no second HTTP suspend. Model its public
 // closed session/empty lease before the current original resume owner reopens.
 await f.host.suspend();f.host.lease=null;f.host.closed=true;await f.life.suspend();f.life.observePowerBoundary('resuming',3);f.life.observePowerBoundary('resume-ready',3);f.host.completeResume=true;f.setPower({generation:3,phase:'ready',hardwareWritesAllowed:true,inputReady:true,resumeReady:true,hibernateAvailable:true});const result=await f.execute('fan.setEnabled',{enabled:true});if(f.host.calls.filter(c=>c==='resume').length===0)fs.writeFileSync(task+'/validation/FAN-SUSPENDED-NOOP12-BASELINE.json',JSON.stringify({project:'YMCC Decky 侧边栏',stage:'Implementation12',result,stats:f.stats(),hostCalls:[...f.host.calls],actualOriginalOwner:true,physicalHardwareWrites:0},null,2));assert.equal(result.applied,true);assert.equal(f.host.calls.filter(c=>c==='resume').length,1);assert.equal(f.host.generation,3);assert.equal(f.host.attempt,1);assert.notEqual(f.life.currentLease?.leaseId,oldLease);assert.equal(f.host.calls.filter(c=>c==='enable').length,2);}finally{await f.life.close();}});
 for(const kind of ['pending','generation-changed'])await check('current original cold-open path refuses stale second native proof: '+kind,async()=>{const f=fixture();let probes=0;f.native(async()=>{probes++;return {generation:kind==='generation-changed'&&probes>1?3:2,phase:kind==='pending'&&probes>1?'suspending':'ready',hardwareWritesAllowed:!(kind==='pending'&&probes>1),inputReady:true,resumeReady:true,hibernateAvailable:true};});try{const result=await f.execute('fan.setEnabled',{enabled:true}).catch(()=>null);assert.ok(!result?.applied);assert.ok(probes>=2);assert.equal(f.host.calls.some(c=>['open','events','acquire','enable','preset'].includes(c)),false);}finally{await f.life.close();}});
 const base=new NoIoHost().snapshot();for(const patch of [{closeCalled:true},{openCalled:true},{openEventsCalled:true},{hardwareWritesObserved:true},{unknownState:true},{hcCloseCleanupPending:true},{lease:{leaseId:'other-owner'}},{powerOperationAttempt:1},{powerState:'Suspended'}])await check('cold predicate refuses '+Object.keys(patch)[0],()=>assert.equal(isColdUnopenedFanHost({...base,...patch}),false));
 await check('undefined Close proof cannot be treated as a never-opened original Host',()=>{const state={...base};delete state.closeCalled;assert.equal(isColdUnopenedFanHost(state),false);});
 await check('closed prior session cannot borrow cold-open shortcut or claim applied control',async()=>{const f=fixture('Stopped');f.host.closed=true;try{const result=await f.execute('fan.setEnabled',{enabled:true}).catch(()=>null);assert.ok(!result?.applied);assert.equal(f.host.calls.some(c=>['open','events','acquire','enable','preset'].includes(c)),false);assert.ok(f.host.calls.includes('resume'));}finally{await f.life.close();}});
 const record={project:'YMCC Decky 侧边栏',stage:'Implementation12',cases:cases.length,results:cases,details,actualCurrentOriginalFanLifecycle:true,actualEngineStateProjectionFromSource:true,originalSourcesChangedByMirror:false,inertAdapter:true,actualHostProcesses:0,realConfigWrites:0,physicalHardwareWrites:0};fs.writeFileSync(task+'/validation/FAN-REBASED-MIRROR-IMPLEMENTATION12.json',JSON.stringify(record,null,2));console.log(`Current original Fan lifecycle/cold mirror checks passed: ${cases.length}`);
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
