import { task } from './fixtures/decky_task_paths.mjs';
// Production relay and snapshot provider exercised with entirely fake owners/IO.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { createRequire } from 'node:module';
const root=path.resolve(import.meta.dirname,'..');const require=createRequire(path.join(root,'package.json'));const {transformSync}=require('esbuild');
function load(rel,modules={}){modules={...modules,'../../decky-plugin/src/steamRunningContext':loadContext()};const module={exports:{}};vm.runInNewContext(transformSync(fs.readFileSync(path.join(root,rel),'utf8'),{loader:'ts',format:'cjs'}).code,
{module,exports:module.exports,structuredClone,queueMicrotask,require:name=>{if(Object.hasOwn(modules,name))return modules[name];throw new Error(`Unmocked dependency: ${name}`);}});return module.exports;}
function loadContext(){const module={exports:{}};vm.runInNewContext(transformSync(fs.readFileSync(path.join(root,'decky-plugin/src/steamRunningContext.ts'),'utf8'),{loader:'ts',format:'cjs'}).code,{module,exports:module.exports});return module.exports;}
const {ReadOnlyMirrorRelay}=load('src/bridge/deckyMirrorRelay.ts');
const {createFanMirrorActions}=load('src/bridge/deckyFanActions.ts');
const cases=[];const runId='a'.repeat(32);const peer={connection:'1',runId,connected:true};
const data=(label='A')=>({generation:1,ready:false,game:{label,identity:'a.exe:101:A',fields:{}},fan:{supported:true,enabled:false,preset:'balanced',choices:[]},notice:'read-only'});
const flush=async()=>{for(let i=0;i<80;i++)await Promise.resolve();};
const defer=()=>{let resolve,reject;const promise=new Promise((y,n)=>{resolve=y;reject=n;});return {promise,resolve,reject};};
async function check(name,fn){await fn();cases.push({name,status:'passed'});}
function fixture(overrides={}){let reads=0,observes=0,stops=0;let invalidate;const replies=[];
const relay=new ReadOnlyMirrorRelay({read:async()=>{reads++;return data();},observe:fn=>{observes++;invalidate=fn;return()=>{stops++;};},reply:async(connection,message)=>{replies.push({connection,message});return true;},...overrides});
return {relay,replies,invalidate:()=>invalidate(),reads:()=>reads,observes:()=>observes,stops:()=>stops,request:()=>relay.request({...peer,request:{command:'snapshot',runId}})};}
await check('disabled/no-peer relay performs zero reads and observers',()=>{const f=fixture();assert.equal(f.reads(),0);assert.equal(f.observes(),0);f.relay.dispose();});
await check('authenticated peer attaches one observer set, no early read',()=>{const f=fixture();f.relay.connected(peer);f.relay.connected(peer);assert.equal(f.observes(),1);assert.equal(f.reads(),0);f.relay.dispose();});
await check('first demand reads once; unchanged refresh reuses current store result',async()=>{const f=fixture();f.relay.connected(peer);await f.request();await f.request();assert.equal(f.reads(),1);assert.equal(f.replies.length,2);assert.equal(f.replies[0].message.snapshot.revision,f.replies[1].message.snapshot.revision);f.relay.dispose();});
await check('concurrent snapshot requests share one read',async()=>{const f=fixture();await Promise.all([f.request(),f.request(),f.request()]);assert.equal(f.reads(),1);f.relay.dispose();});
await check('source events push one coalesced fresh read without timer',async()=>{const f=fixture();await f.request();f.invalidate();f.invalidate();f.invalidate();await flush();assert.equal(f.reads(),2);assert.equal(f.replies.at(-1).message.snapshot.revision,2);f.relay.dispose();});
await check('peer close unsubscribes and later source events do no work',async()=>{const f=fixture();await f.request();f.relay.connected({...peer,connected:false});assert.equal(f.stops(),1);f.invalidate();await flush();assert.equal(f.reads(),1);f.relay.dispose();});
await check('stale run/request ignored without provider IO',async()=>{const f=fixture();await f.relay.request({...peer,request:{command:'snapshot',runId:'b'.repeat(32)}});assert.equal(f.reads(),0);assert.equal(f.replies.length,0);f.relay.dispose();});
await check('all mutations fail read-only and never call read/mutation providers',async()=>{const f=fixture();f.relay.connected(peer);for(const command of ['game.setField','fan.setEnabled','fan.setPreset','shell.run'])await f.relay.request({...peer,request:{command,runId,id:command}});assert.equal(f.reads(),0);assert.equal(f.replies.length,4);assert.ok(f.replies.every(r=>r.message.ok===false));f.relay.dispose();});
await check('late source read after disconnect cannot publish',async()=>{const pending=defer();const f=fixture({read:()=>pending.promise});const request=f.request();f.relay.connected({...peer,connected:false});pending.resolve(data());await request;assert.equal(f.replies.length,0);f.relay.dispose();});
await check('different peer gets its own revision and old source completion rejected',async()=>{const pending=defer();let reads=0;const f=fixture({read:()=>++reads===1?pending.promise:Promise.resolve(data('B'))});const first=f.request();f.relay.connected({connection:'2',runId,connected:true});await f.relay.request({connection:'2',runId,request:{command:'snapshot',runId}});pending.resolve(data('A'));await first;assert.equal(f.replies.length,1);assert.equal(f.replies[0].connection,'2');assert.equal(f.replies[0].message.snapshot.game.label,'B');f.relay.dispose();});
await check('source changed during read prevents stale snapshot',async()=>{const pending=defer();let reads=0;const f=fixture({read:()=>++reads===1?pending.promise:Promise.resolve(data('B'))});f.relay.connected(peer);const request=f.request();f.invalidate();pending.resolve(data('A'));await request;await flush();assert.ok(f.replies.every(r=>r.message.snapshot.game.label==='B'));f.relay.dispose();});
await check('renderer reattach continues native revision sequence',async()=>{const f=fixture();f.relay.connected({...peer,revision:40});await f.request();assert.equal(f.replies[0].message.snapshot.revision,41);f.relay.dispose();});
await check('late attach metadata supersedes an initial low cached revision',async()=>{const f=fixture();await f.request();f.relay.connected({...peer,revision:50});await f.request();assert.equal(f.replies.at(-1).message.snapshot.revision,51);assert.equal(f.observes(),1);f.relay.dispose();});
await check('read failure is visible and never shows ready',async()=>{const f=fixture({read:async()=>{throw new Error('fake read failure');}});await f.request();assert.equal(f.replies[0].message.snapshot.ready,false);assert.match(f.replies[0].message.snapshot.notice,/读取失败/);f.relay.dispose();});
await check('failed native reply has no automatic resend or rejection leak',async()=>{let writes=0;const f=fixture({reply:async()=>{writes++;throw new Error('fake native gone');}});await f.request();await flush();assert.equal(writes,1);f.relay.dispose();});

// Execute the unchanged original resolver, not a second test-side interpretation.
const scheduleSource=fs.readFileSync(path.join(root,'src/bridge/performanceSchedule.ts'),'utf8');
const start=scheduleSource.indexOf('export function resolveGameCustomProfiles('),end=scheduleSource.indexOf('export function getCustomRtssFor(',start);
assert.ok(start>=0&&end>start);
const resolverModule={exports:{}};
vm.runInNewContext(transformSync("function isMode(value: unknown) { return ['eco','balanced','medium','performance','elite','extreme'].includes(value as string); }\n"+scheduleSource.slice(start,end),{loader:'ts',format:'cjs'}).code,{module:resolverModule,exports:resolverModule.exports});
const {resolveGameCustomProfiles}=resolverModule.exports;
const {gamePolicyKey}=load('src/bridge/gamePolicyHysteresis.ts');
const gameActions=load('src/bridge/deckyGameActions.ts',{'./gamePolicyHysteresis':{gamePolicyKey}});

function hostFixture(){const events=new Map();let nativeReads=0,configReads=0,topologyReads=0;const replies=[];let watchers=0;let scheduleListener;
const state={game:{pid:101,processCreated:'A',path:'C:/A/a.exe',name:'a.exe',title:'Game A'},entry:undefined,fanPreset:'balanced',fanEnabled:false};
const schedule={active:{ac:'balanced',dc:'eco'},profiles:{ac:{},dc:{}}};for(const side of ['ac','dc'])for(const mode of ['eco','balanced','medium','performance','elite','extreme'])schedule.profiles[side][mode]={tdpMax:side==='ac'?20:10,fpsTarget:60};
const frameModel=load('src/bridge/frameRateModel.ts');
const screens=load('src/bridge/screenTouchpads.ts',{'./ipc':{isNativeRuntime:false}});
const modules={
'./deckyFrameActions':load('src/bridge/deckyFrameActions.ts',{'./frameRateModel':frameModel,'./deckyGameActions':gameActions}),
'./deckyTouchpadActions':load('src/bridge/deckyTouchpadActions.ts',{'./screenTouchpads':screens}),
'./settingsRepository':{readSettingsSection:async()=>({outputTarget:{persona:'steamdeck',buttonMappingEnabled:true}})},
'./screenTouchpads':{...screens,screenTouchpadsGet:async()=>({...screens.screenTouchpadDefaults('steamdeck'),ok:true,available:true})},
'./frameRateLimits':{...frameModel,loadGlobalFrameRates:async()=>frameModel.frameRatePair({}),onFrameRatesChanged:()=>()=>{}},
'./deckySpeedActions':load('src/bridge/deckySpeedActions.ts',{'./deckyGameActions':gameActions}),
'./speedhack':{SPEED_PRESETS:[0.5,0.8,1,1.2,1.5,2,4,8],isMinecraftTarget:()=>false,getGameSpeedState:()=>null,onGameSpeedStateChanged:()=>()=>{},applyGameSpeed:()=>{throw Error('Snapshot must not apply speed');},clearGameSpeed:()=>{throw Error('Snapshot must not clear speed');}},
'./deckyGyroDefaults':{readGameMirrorGyroDefaults:async()=>({enabled:false,preset:'fps',source:'inert-global-gyro'})},
'./powerSource':{powerSourceMode:{value:'ac'},refreshPowerSourceSnapshot:async()=>{}},
'./losslessScaling':{readLosslessScaling:async()=>({profile:null,xml:'',reason:''}),losslessField:()=>({value:'off',supported:false,choices:[]}),onLosslessScalingChanged:()=>()=>{}},
'vue':{watch:()=>{watchers++;return()=>watchers--;}},
'./ipc':{on:(event,fn)=>{events.set(event,fn);return()=>events.delete(event);},invoke:async(command,args)=>{if(command==='deckySidebar.mirrorAttach')return {connected:false};if(command==='deckySidebar.mirrorReply'){replies.push(args.message);return true;}throw new Error('Unexpected native mutation');}},
'./api':{powerLifecycle:{get:async()=>{nativeReads++;return {generation:1,phase:'ready',hardwareWritesAllowed:true};}}},
'./gamePolicyTarget':{getPolicyGame:()=>state.game,gamePolicyKey,subscribePolicyGameStatus:()=>()=>{}},
'./performanceSchedule':{resolveGameCustomProfiles,getGameCustomConfig:()=>({entries:state.entry?{[gamePolicyKey(state.game)]:state.entry}:{}}),loadPerformanceSchedule:async()=>{configReads++;return structuredClone(schedule);},onGameCustomConfigChanged:()=>()=>{},onPerformanceScheduleChanged:fn=>{scheduleListener=fn;return()=>{};}},
'./gameCorePolicy':{detectGameCorePolicy:async()=>{topologyReads++;return {heterogeneous:false,smtAvailable:true};}},
'./deckyFanActions':{createFanMirrorActions},
'./deckyGameActions':gameActions,'./gamedetect':{detectedGameName:game=>game?.title||game?.name||''},
'./quickActionLock':{tryAcquireQuickAction:()=>{throw new Error('Snapshot fixture never acquires a mutation lock');}},'./gameproc':{closeJoyxoffIfRunning:()=>{throw new Error('Snapshot fixture never operates a process');}},
'./deckyFanDisplay':{observeFanMirrorDisplay:()=>{},isFanMirrorUiBusy:()=>false,onFanMirrorUiGate:()=>()=>{}},
'./fanFeature':{FAN_IMPORT_ENABLED:true,FAN_FORCE_PREVIEW:false,fanFeatureEnabled:{value:true},fanControlActive:{get value(){return state.fanEnabled;}},getFanFeatureSettings:()=>({preset:state.fanPreset})},
'./fanHost':{fanHostLifecycle:{controlReady:true}},'./deckyMirrorRelay':{ReadOnlyMirrorRelay}};
const host=load('src/bridge/deckyMirrorHost.ts',modules).startDeckyMirrorHost();
const read=async()=>{await events.get('deckySidebar.mirrorRequest')?.({...peer,request:{command:'snapshot',runId}});await flush();return replies.at(-1)?.snapshot;};
return {host,state,read,replies,events,schedule,scheduleChanged:()=>scheduleListener(structuredClone(schedule)),counts:()=>({nativeReads,configReads,topologyReads,watchers})};}
await check('observer setup failure is contained, no read or leaked peer',async()=>{const f=fixture({observe:()=>{throw new Error('fake observer failed');}});f.relay.connected(peer);await f.request();assert.equal(f.reads(),0);assert.equal(f.replies.length,0);f.relay.dispose();});
await check('explicit Steam runtime observation is delivered only in-memory',async()=>{let observation;const f=fixture({observeSteam:value=>{observation=value;return true;}});await f.relay.request({...peer,request:{command:'snapshot',runId,steam:{availability:'observed',appId:'480',gameId:'18446744073709551615',runningCount:1}}});assert.equal(observation.appId,'480');assert.equal(observation.gameId,'18446744073709551615');assert.equal(f.reads(),1);f.relay.dispose();});
await check('invalid Steam identity packet cannot enter source observer/read',async()=>{let observes=0;const f=fixture({observeSteam:()=>{observes++;return true;}});await f.relay.request({...peer,request:{command:'snapshot',runId,steam:{availability:'observed',appId:'480',exe:'wrong.exe'}}});assert.equal(observes,0);assert.equal(f.reads(),0);f.relay.dispose();});
await check('host initialization does not query state or write user data',()=>{const f=hostFixture();assert.equal(f.counts().nativeReads,0);assert.equal(f.counts().configReads,0);assert.equal(f.counts().watchers,0);f.host.stop();});
await check('early connection cannot force normal business startup',async()=>{const f=hostFixture();const snap=await f.read();assert.equal(snap.ready,false);assert.equal(f.counts().nativeReads,0);assert.equal(f.counts().configReads,0);f.host.stop();});
await check('no dedicated entry mirrors global AC/DC combination details',async()=>{const f=hostFixture();f.host.ready();const snap=await f.read();assert.equal(snap.game.fields.acMode.value,'follow');assert.match(snap.game.fields.acMode.choices[1].label,/20W/);assert.equal(snap.fan.preset,'balanced');assert.equal(snap.ready,true);assert.equal(snap.actions.game,true);assert.equal(snap.actions.fan,true);assert.equal(f.counts().nativeReads,1);assert.equal(f.counts().configReads,1);f.host.stop();});
await check('global change reuses supplied schedule rather than duplicate file read',async()=>{const f=hostFixture();f.host.ready();await f.read();f.schedule.active.ac='extreme';f.scheduleChanged();await flush();const latest=f.replies.at(-1).snapshot;assert.match(latest.game.fields.acMode.choices[0].label,/极致性能/);assert.equal(f.counts().configReads,1);assert.equal(f.counts().topologyReads,1);f.host.stop();});
await check('legacy dedicated snapshot is not falsely labeled global inheritance',async()=>{const f=hostFixture();f.state.entry={enabled:true,displayName:'Old',ac:{tdpMax:25,fpsTarget:50},dc:{tdpMax:12,fpsTarget:0},padPersona:'follow',gyroOverride:'on'};f.host.ready();const snap=await f.read();assert.equal(snap.game.fields.acMode.value,'legacy');assert.match(snap.game.fields.acMode.choices.find(o=>o.data==='legacy').label,/25W/);assert.match(snap.game.fields.dcMode.choices.find(o=>o.data==='legacy').label,/12W/);assert.ok(snap.game.fields.gyroOverride.choices.some(o=>o.data==='on'));f.host.stop();});
await check('global fan and capability gates are mirrored, not recreated',async()=>{const f=hostFixture();f.state.fanPreset='aggressive';f.state.fanEnabled=true;f.host.ready();const snap=await f.read();assert.equal(snap.fan.enabled,true);assert.equal(snap.fan.preset,'aggressive');assert.equal(snap.game.fields.corePolicyMode.supported,false);assert.equal(snap.game.fields.hyperThreadPolicy.supported,true);f.host.stop();});
await check('disabled dedicated record does not become enabled just by read',async()=>{const f=hostFixture();f.state.entry={enabled:false,acMode:'extreme',dcMode:'extreme'};f.host.ready();const snap=await f.read();assert.equal(snap.game.fields.acMode.value,'extreme');assert.ok(!snap.notice.includes('首次修改'));assert.equal(f.state.entry.enabled,false);f.host.stop();});
await check('runtime Steam identity is supplemental and never creates a remembered EXE entry',async()=>{const f=hostFixture();f.host.ready();f.events.get('deckySidebar.mirrorRequest')({...peer,request:{command:'snapshot',runId,steam:{availability:'observed',appId:'480',runningCount:1}}});await flush();const snap=f.replies.at(-1).snapshot;assert.equal(snap.steam.appId,'480');assert.equal(snap.actions.game,true);assert.equal(f.state.entry,undefined);f.host.stop();});
await check('Steam context cannot rekey an EXE entry or alter target identity',async()=>{const f=hostFixture();f.state.entry={enabled:true,acMode:'performance',dcMode:'eco'};f.host.ready();const first=await f.read();for(const appId of ['480','570']){f.events.get('deckySidebar.mirrorRequest')({...peer,request:{command:'snapshot',runId,steam:{availability:'observed',appId,runningCount:1}}});await flush();const latest=f.replies.at(-1).snapshot;assert.equal(latest.steam.appId,appId);assert.equal(latest.game.identity,first.game.identity);assert.equal(latest.game.fields.acMode.value,'performance');assert.equal(latest.actions.game,true);}assert.ok(!Object.hasOwn(f.state.entry,'steamAppId'));f.host.stop();});
await check('non-Steam EXE mirrors the same fields without requiring an AppID',async()=>{const f=hostFixture();f.state.game={pid:202,processCreated:'B',path:'D:/GOG/Offline.exe',name:'Offline.exe',title:'Offline game'};f.state.entry={enabled:true,acMode:'extreme',dcMode:'eco'};f.host.ready();const snap=await f.read();assert.equal(snap.steam.availability,'unavailable');assert.match(snap.game.identity,/offline\.exe/);assert.equal(snap.game.fields.acMode.value,'extreme');assert.equal(snap.actions.game,true);f.host.stop();});
await check('new dedicated core default is visible before any edit without creating a record',async()=>{const f=hostFixture();f.host.ready();const snap=await f.read();assert.equal(snap.game.fields.corePolicyMode.value,'big-small');assert.ok(!snap.notice.includes('默认核心'));assert.equal(f.state.entry,undefined);f.host.stop();});
await check('Steam observation alone never creates a game target or enables game actions',async()=>{const f=hostFixture();f.state.game=null;f.host.ready();f.events.get('deckySidebar.mirrorRequest')({...peer,request:{command:'snapshot',runId,steam:{availability:'observed',appId:'480',runningCount:1}}});await flush();const snap=f.replies.at(-1).snapshot;assert.equal(snap.game,null);assert.equal(snap.actions.game,false);assert.equal(f.state.entry,undefined);f.host.stop();});
await check('remembered record exposes only real modes and snapshot sentinel, not a false global inheritance action',async()=>{const f=hostFixture();f.state.entry={enabled:false,acMode:'extreme',dcMode:'eco',corePolicyMode:'only-small',hyperThreadPolicy:'off'};f.host.ready();const snap=await f.read();assert.equal(snap.game.fields.corePolicyMode.value,'only-small');assert.equal(snap.game.fields.hyperThreadPolicy.value,'off');assert.ok(!snap.game.fields.acMode.choices.some(option=>option.data==='follow'));assert.equal(f.state.entry.enabled,false);f.host.stop();});
await check('host stop releases all subscriptions, no fan stop/leases',async()=>{const f=hostFixture();f.host.ready();await f.read();f.host.stop();assert.equal(f.counts().watchers,0);assert.equal(f.events.size,0);});
fs.writeFileSync(path.resolve(task,'validation/READONLY-RELAY-SELFTEST.json'),JSON.stringify({project:'YMCC Decky 侧边栏',cases:cases.length,results:cases,realHardware:false,userConfigWrites:false,sourceUnderTest:['deckyMirrorRelay.ts','deckyMirrorHost.ts']},null,2));console.log(`Read-only relay/provider tests passed: ${cases.length}`);
