// Local Steam UI with actual DFL mouse/key dispatch; explicit memory business owners.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {root,task} from './fixtures/decky_task_paths.mjs';import {targets,connect} from './fixtures/decky_cdp.mjs';
const sessionName=process.env.YMCC_DECKY_UI_RUN_NAME||'MAINLINE22-REAL-UI-R6';if(!/^[A-Z0-9-]+$/.test(sessionName))throw Error('Session name rejected');
const verifyFirstDefault=process.env.YMCC_DECKY_UI_VERIFY_FIRST_DEFAULT==='1';
const session=path.join(task,'validation/'+sessionName+'.json'),out=path.join(task,'validation/MAINLINE22-REAL-UI-ACCEPTANCE.json');
const report={actualSteam:true,actualDflControls:true,businessData:'memory fixture',realProductYmcc:false,realConfigWrites:0,hardwareWrites:0,physicalControllerTested:false,steps:[]};
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)),sleep=ms=>new Promise(r=>setTimeout(r,ms));let q,c;
const read=`(()=>{const panels=Array.from(document.querySelectorAll('.ymcc-decky-sidebar'));const panel=panels.find(e=>e.getBoundingClientRect().width>0)||panels[0];const rect=e=>e.getBoundingClientRect().toJSON();return {panels:panels.length,text:panel?.innerText,combos:Array.from(panel?.querySelectorAll('[role=combobox]')||[]).map(e=>({label:e.closest('.ymcc-anchored-dropdown')?.innerText.split('\\n')[0],text:e.innerText,rect:rect(e),disabled:e.getAttribute('aria-disabled'),focus:e===document.activeElement})),options:Array.from(panel?.querySelectorAll('[role=option]')||[]).map(e=>({text:e.innerText,rect:rect(e),disabled:e.getAttribute('aria-disabled'),focus:e===document.activeElement})),list:panel?.querySelector('[role=listbox]')?rect(panel.querySelector('[role=listbox]')):null,checks:Array.from(panel?.querySelectorAll('[role=checkbox]')||[]).map(e=>({label:document.getElementById(e.getAttribute('aria-labelledby'))?.innerText,rect:rect(e),checked:e.getAttribute('aria-checked')})),sliders:Array.from(panel?.querySelectorAll('[role=slider]')||[]).map(e=>({text:e.closest('.ymcc-decky-slider')?.innerText,rect:rect(e),value:e.getAttribute('aria-valuenow'),max:e.getAttribute('aria-valuemax')})),active:document.activeElement?.getAttribute('role')};})()`;
async function poll(predicate){for(let i=0;i<60;i++){const s=await q.evaluate(read);if(predicate(s))return s;await sleep(100);}throw Error('QAM condition timeout: '+JSON.stringify(await q.evaluate(read)));}
async function mouse(rect){assert.ok(rect&&rect.width>0);const x=rect.left+rect.width/2,y=rect.top+rect.height/2;for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x,y,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});}
async function key(key,code=key){for(const type of ['keyDown','keyUp'])await q.send('Input.dispatchKeyEvent',{type,key,code,windowsVirtualKeyCode:key==='Escape'?27:key==='ArrowRight'?39:key==='ArrowLeft'?37:undefined});}
async function open(label){await q.evaluate(`(()=>{const e=Array.from(document.querySelectorAll('.ymcc-anchored-dropdown')).find(e=>e.innerText.split(String.fromCharCode(10))[0]===${JSON.stringify(label)});e?.scrollIntoView({block:'center'});return !!e;})()`);await sleep(100);const state=await q.evaluate(read),combo=state.combos.find(e=>e.label===label);assert.ok(combo,label);await mouse(combo.rect);return poll(s=>!!s.list);}
async function cancel(label){await key('Escape');const state=await poll(s=>!s.list&&s.combos.find(e=>e.label===label)?.focus);assert.equal(state.combos.find(e=>e.label===label).focus,true,'focus returns to '+label);return state;}
async function choose(label,option){let state=await open(label);const index=state.options.findIndex(e=>e.text===option);assert.ok(index>=0);await q.evaluate(`document.querySelectorAll('.ymcc-anchored-options [role=option]')[${index}].scrollIntoView({block:'nearest'});true`);state=await q.evaluate(read);await mouse(state.options[index].rect);return poll(s=>!s.list&&s.combos.find(e=>e.label===label)?.text===option);}
function verifyDown(label,state){const trigger=state.combos.find(e=>e.label===label);assert.ok(state.list.top>=trigger.rect.bottom-2,`${label} not down: ${state.list.top} vs ${trigger.rect.bottom}`);assert.ok(Math.abs(state.list.left-trigger.rect.left)<1,'menu and trigger left edges aligned');assert.ok(Math.abs(state.list.right-trigger.rect.right)<1,'menu and trigger right edges aligned');assert.ok(Math.abs(state.list.width-trigger.rect.width)<1,'menu and trigger widths identical');report.steps.push(label+' expanded below same QAM trigger');}
try {
 const list=await targets();c=await connect(list.find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);q=await connect(list.find(t=>t.title.startsWith('QuickAccess')).webSocketDebuggerUrl);
 await c.evaluate(`(()=>{DFL.Navigation.CloseSideMenus();DFL.Navigation.OpenQuickAccessMenu(100019);return true;})()`);
 report.initial=await poll(s=>s.combos.length>=4&&s.sliders.length>=2&&s.checks.length===4&&s.combos.some(e=>e.label==='核心调度'));
 assert.ok(report.initial.combos.every(combo=>Math.abs(combo.rect.width-report.initial.combos[0].rect.width)<1),'all dropdown triggers same width');assert.ok(report.initial.combos.every(combo=>Math.abs(combo.rect.left-report.initial.combos[0].rect.left)<1),'all dropdown triggers same left edge');report.steps.push('all dropdown widths and edges uniform');
 assert.equal(report.initial.panels,1,'one direct console, no duplicate native array panels');assert.match(report.initial.text,/LosslessScaling 插帧/);assert.ok(!report.initial.text.includes('小黄鸭'));save();
 let state=await open('核心调度');verifyDown('核心调度',state);assert.equal(state.options[0].text,'大核为主');assert.equal(state.options.at(-1).text,'仅小核');report.coreOpen=state;await cancel('核心调度');report.steps.push('core cancellation returns actual DOM focus, zero mutation');save();
 state=await open('虚拟手柄');verifyDown('虚拟手柄',state);assert.equal(state.options.find(e=>e.text==='全局方案').disabled,'true');await cancel('虚拟手柄');assert.equal(JSON.parse(fs.readFileSync(session)).mutationRequests?.length||0,0);report.steps.push('default Global is visibly disabled and never written');
 if(verifyFirstDefault){state=await choose('核心调度','大核为主');await sleep(150);assert.equal(JSON.parse(fs.readFileSync(session)).hostCounts.saves,1);assert.ok(!state.text.includes('全局方案'));report.steps.push('same displayed first core default explicitly remembers entire EXE profile');save();}
 state=await choose('核心调度','仅大核');assert.ok(!state.text.includes('全局方案'));report.afterDedicated=state;report.steps.push('first core save creates whole dedicated input selection and removes Global choices');save();
 const gyro=state.checks.find(e=>e.label==='陀螺仪');assert.equal(gyro.checked,'false');await mouse(gyro.rect);await poll(s=>s.checks.find(e=>e.label==='陀螺仪')?.checked==='true');
 state=await open('陀螺仪预设');verifyDown('陀螺仪预设',state);assert.deepEqual(state.options.map(e=>e.text),['FPS射击','赛车','自定义','Steam']);report.gyroOpen=state;await cancel('陀螺仪预设');report.steps.push('gyro four options downward, Escape focus return');save();
 state=await choose('陀螺仪预设','赛车');report.steps.push('actual gyro selection updates original memory EXE field');
 state=await open('游戏变速');verifyDown('游戏变速',state);assert.deepEqual(state.options.map(e=>e.text),['0.5×','0.8×','1×','1.2×','1.5×','2×','4×','8×']);report.speedOpen=state;await cancel('游戏变速');
 state=await choose('游戏变速','1.5×');report.steps.push('speed original owner applies 1.5× with no profile save');save();
 // Native slider keys exercise the production debounce, rather than directly calling React props.
 state=await q.evaluate(read);await q.evaluate(`document.querySelector('.ymcc-decky-sidebar .ymcc-decky-slider').scrollIntoView({block:'center'});true`);await sleep(100);const track=await q.evaluate(`document.querySelector('.ymcc-decky-sidebar .SliderTrack').getBoundingClientRect().toJSON()`);const movePower=async ratio=>{for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x:track.left+track.width*ratio,y:track.top+track.height/2,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});};
 const initialMutations=(JSON.parse(fs.readFileSync(session)).mutationRequests||[]).length;
 await movePower(.6);await sleep(1600);await movePower(.8);await sleep(1400);state=await q.evaluate(read);assert.match(state.text,/停止切换 3 秒/);assert.equal((JSON.parse(fs.readFileSync(session)).mutationRequests||[]).length,initialMutations);await sleep(1800);
 await poll(s=>!s.text.includes('停止切换 3 秒'));const after=JSON.parse(fs.readFileSync(session));assert.equal(after.mutationRequests.length,initialMutations+1);assert.equal(after.mutationRequests.at(-1).args.field,'acMode');assert.equal(after.hostCounts.saves,verifyFirstDefault?5:4);assert.equal(after.hostCounts.speedApply,1);assert.equal(after.hostCounts.fanSaves,0);report.hostCounts=after.hostCounts;report.mutations=after.mutationRequests;report.steps.push('two native power moves restarted 3s wait, one final AC write only');
 report.final=await q.evaluate(read);report.pass=true;report.pluginSha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'PowerControl/decky/plugins/ymcc-sidebar/dist/index.js'))).digest('hex');assert.equal(report.pluginSha256,after.servedProductionScriptSha256);save();
 console.log('Actual Steam console22 acceptance PASS '+report.steps.length);
} catch(error){report.failure=error.stack;save();throw error;} finally {q?.close();c?.close();}
