// Actual installed YMCC -> native broker -> current Steam/DFL. Read-only menus/cancel/reload only.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {task} from './fixtures/decky_task_paths.mjs';import {targets,connect} from './fixtures/decky_cdp.mjs';
const log='C:/Users/DaVe/AppData/Local/YeManCC/decky-sidebar.log';
const root='G:/YeManCC-Work/Mainline/Temp/ai-cpu-bundle-R11-rebuild/PowerControl';
const configNames=['game-custom.json','yeman-settings.json'];const hashConfigs=()=>Object.fromEntries(configNames.filter(n=>fs.existsSync(path.join(root,n))).map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,n))).digest('hex')]));
const report={actualProductYmcc:true,actualSteam:true,actualDflControls:true,mutationsRequested:false,credentialsRecorded:false,steamRestarted:false,steps:[],businessFilesBefore:hashConfigs()};
const output=path.join(task,'validation/ACTUAL-PRODUCT-READONLY-ACCEPTANCE.json'),save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let c,q;
const read=`(()=>{const all=Array.from(document.querySelectorAll('.ymcc-decky-sidebar')),visible=all.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0;}),p=visible[0],r=e=>e.getBoundingClientRect().toJSON();return {panels:visible.length,retainedHiddenPanels:all.length-visible.length,text:p?.innerText,combos:Array.from(p?.querySelectorAll('[role=combobox]')||[]).map(e=>({label:e.closest('.ymcc-anchored-dropdown')?.innerText.split(String.fromCharCode(10))[0],text:e.innerText,rect:r(e),disabled:e.getAttribute('aria-disabled')==='true'||e.classList.contains('Disabled'),focus:e===document.activeElement})),list:p?.querySelector('[role=listbox]')?r(p.querySelector('[role=listbox]')):null};})()`;
async function poll(fn){for(let i=0;i<100;i++){const s=await q.evaluate(read);if(fn(s))return s;await sleep(100);}throw Error('Actual installed panel deadline');}
async function connectUi(){c?.close();q?.close();const list=await targets();c=await connect(list.find(t=>t.title==='SharedJSContext').webSocketDebuggerUrl);for(let i=0;i<100;i++){if(await c.evaluate(`Array.isArray(window.__TABS_HOOK_INSTANCE?.tabs)&&window.__TABS_HOOK_INSTANCE.tabs.some(t=>t.id===100019)&&!!window.__YMCC_DECKY_MIRROR__`))break;if(i===99)throw Error('Registered native console tab readiness deadline');await sleep(100);}await c.evaluate(`DFL.Navigation.OpenQuickAccessMenu(100019);true`);await sleep(350);const current=await targets();q=await connect(current.find(t=>t.title.startsWith('QuickAccess')).webSocketDebuggerUrl);}
try{
 await connectUi();const first=await poll(s=>s.panels===1&&s.combos.length===5);assert.match(first.text,/插电锁帧 AC/);assert.match(first.text,/触摸板（全局）/);assert.doesNotMatch(first.text,/尚未提供镜像连接|连接已中断|镜像身份无效/);
 assert.ok(first.combos.every(e=>Math.abs(e.rect.width-first.combos[0].rect.width)<1));assert.ok(first.combos.every(e=>Math.abs(e.rect.left-first.combos[0].rect.left)<1));report.steps.push('installed product snapshot renders once, independent current AC FPS and four global touchpad menus with uniform widths');
 for(const label of ['锁帧上限','屏幕触摸板','YMCC呼出','专用按键','背部按键']){
  await q.evaluate(`(()=>{const e=Array.from(document.querySelectorAll('.ymcc-anchored-dropdown')).find(e=>e.innerText.split(String.fromCharCode(10))[0]===${JSON.stringify(label)});e.scrollIntoView({block:'center'});return true;})()`);await sleep(100);const current=await q.evaluate(read),rect=current.combos.find(e=>e.label===label).rect;
  for(const type of ['mousePressed','mouseReleased'])await q.send('Input.dispatchMouseEvent',{type,x:rect.left+rect.width/2,y:rect.top+rect.height/2,button:'left',buttons:type==='mousePressed'?1:0,clickCount:1});
  if(current.combos.find(e=>e.label===label).disabled===true){assert.ok(['专用按键','背部按键'].includes(label),'supported global controls must remain actionable');await sleep(150);assert.equal((await q.evaluate(read)).list,null);report.steps.push(label+' is unsupported in the current real persona and refuses activation without a mutation');continue;}
  const opened=await poll(s=>!!s.list),trigger=opened.combos.find(e=>e.label===label);assert.ok(opened.list.top>=trigger.rect.bottom-2);assert.ok(Math.abs(opened.list.left-trigger.rect.left)<1);assert.ok(Math.abs(opened.list.width-trigger.rect.width)<1);
  for(const type of ['keyDown','keyUp'])await q.send('Input.dispatchKeyEvent',{type,key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await poll(s=>!s.list&&s.combos.find(e=>e.label===label)?.focus);report.steps.push(label+' expands down/aligned and Escape returns actual DOM focus without selecting');
 }
 await c.evaluate(`DFL.Navigation.CloseSideMenus();true`);await sleep(300);await c.evaluate(`DFL.Navigation.OpenQuickAccessMenu(100019);true`);await poll(s=>s.panels===1&&s.combos.length===5);report.steps.push('hide/reopen reconnects to the installed product with one console panel');
 const before=fs.readFileSync(log,'utf8').split(String.fromCharCode(10)).filter(Boolean).map(s=>JSON.parse(s));const deploymentFile=['PRODUCT-RESTORED29.json','PRODUCT-RESTORED28.json','PRODUCT-RESTORED27.json','PRODUCT-DEPLOYMENT.json'].map(name=>path.join(task,'validation',name)).find(file=>fs.existsSync(file));if(!deploymentFile)throw Error('Product deployment evidence missing for current task');const deployment=JSON.parse(fs.readFileSync(deploymentFile,'utf8').replace(/^\uFEFF/,''));report.deploymentEvidence=path.basename(deploymentFile);const pid=deployment.productPid??deployment.newPid;
 const generation=Math.max(...before.filter(e=>e.processPid===pid&&e.event==='bootstrap-watch').map(e=>e.contextGeneration||0));
 q.close();q=null;await c.send('Page.reload',{ignoreCache:false});c.close();c=null;
 for(let i=0;i<100;i++){await sleep(100);try{const list=await targets();const t=list.find(t=>t.title==='SharedJSContext');if(!t)continue;const d=await connect(t.webSocketDebuggerUrl);try{if(await d.evaluate(`typeof DFL!=='undefined'&&typeof DFL.Navigation?.OpenQuickAccessMenu==='function'&&!!window.__YMCC_DECKY_MIRROR__&&window.__TABS_HOOK_INSTANCE?.tabs?.some(t=>t.id===100019)`))break;}finally{d.close();}}catch{}if(i===99)throw Error('Actual shared-page reload readiness deadline');}
 await connectUi();report.afterReload=await poll(s=>s.panels===1&&s.combos.length===5);report.steps.push('actual same-process shared-page reload automatically restores bootstrap and installed-product snapshot without JavaScript credential injection');
 const events=fs.readFileSync(log,'utf8').split(String.fromCharCode(10)).filter(Boolean).map(s=>JSON.parse(s)).filter(e=>e.processPid===pid);assert.ok(events.some(e=>e.event==='bootstrap-watch'&&e.bootstrapStage==='context-attached'&&e.contextGeneration>generation));assert.ok(events.some(e=>e.event==='mirror-snapshot-queued'&&e.ready===true));assert.ok(events.some(e=>e.event==='runtime'&&e.launchMode==='verified-shell-primary'&&e.launchStage==='child-token-verified'));
 report.nativeEvidence=events.filter(e=>['bootstrap-watch','mirror-peer','mirror-snapshot-queued','runtime'].includes(e.event)).map(e=>({event:e.event,pid:e.pid,phase:e.phase,bootstrapStage:e.bootstrapStage,contextGeneration:e.contextGeneration,connected:e.connected,ready:e.ready,launchMode:e.launchMode,launchStage:e.launchStage}));
 try{const image=await q.send('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(path.join(task,'validation/ACTUAL-PRODUCT-AFTER-RELOAD.png'),Buffer.from(image.data,'base64'));report.screenshotCaptured=true;}catch(error){report.screenshotCaptured=false;report.screenshotFailure=error.message;}
 report.businessFilesAfter=hashConfigs();assert.deepEqual(report.businessFilesAfter,report.businessFilesBefore);report.pass=true;save();console.log('Installed product read-only/reload acceptance PASS '+report.steps.length);
}catch(error){report.failure=error.stack;save();throw error;}finally{q?.close();c?.close();}
