// Exercise white-list deployment/rollback only in fresh scratch directories.
// Product processes and executables are never launched. Process guard/locks are
// mocked inside disposable PowerShell subprocesses where explicitly noted.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
const repo=process.cwd(),pointer=JSON.parse(fs.readFileSync(path.resolve(repo,'../../../_scratch/global-cache-config-audit-20261006/current-frozen-candidate.json'),'utf8'));
const root=path.join(pointer.path,'deploy-fixtures-'+Date.now());fs.mkdirSync(root,{recursive:true});
const script=path.join(repo,'tools/global_cache_config_deploy.ps1');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const managed=['assets/existing.css','assets/new.js','YeManCC.exe','CustomSteamLibrary/CustomSteamLibrary.exe','CustomSteamLibrary/SteamArtworkLab.exe','CustomSteamLibrary/package-manifest.json','index.html'];
const protectedPaths=['app.config.json','version.json','user-settings.json','assets/old-unmanaged.js','Xinput1_4.dll','CustomSteamLibrary/data/config/library-config.json','CustomSteamLibrary/logs/user.log'];
let number=0;const cases=[];
function fixture(){const dir=path.join(root,String(++number)),install=path.join(dir,'install'),payload=path.join(dir,'payload');const write=(base,p,s)=>{const f=path.join(base,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,s);};const files=managed.map((p,i)=>{const before=i===1?null:Buffer.from('old '+p),next=Buffer.from('new '+p);if(before)write(install,p,before);write(payload,p,next);return{path:p,sha256:hash(next),bytes:next.length,installedPresent:!!before,expectedInstalledSha256:before?hash(before):null};});for(const p of protectedPaths)write(install,p,p==='version.json'?'{"version":"0.0.33"}':'protected '+p);const manifest=path.join(dir,'manifest.json'),plan={status:'FIXTURE_READY',version:'0.0.33',overlayDirectory:payload,files};fs.writeFileSync(manifest,JSON.stringify(plan));return{dir,install,payload,manifest,plan,original:new Map([...managed,...protectedPaths].map(p=>[p,fs.existsSync(path.join(install,p))?fs.readFileSync(path.join(install,p)):null]))};}
function run(f,mode='Apply',extra=[],prefix=''){let command,args;if(prefix){const text=prefix+`;try { & '${script.replaceAll("'","''")}' -Mode '${mode}' -Manifest '${f.manifest}' -InstallRoot '${f.install}' ${extra.map(x=>`'${x}'`).join(' ')}; exit $LASTEXITCODE } finally { if($global:fixtureLock){$global:fixtureLock.Dispose()} }`;command='powershell.exe';args=['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',text];}else{command='powershell.exe';args=['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script,'-Mode',mode,'-Manifest',f.manifest,'-InstallRoot',f.install,...extra];}return spawnSync(command,args,{encoding:'utf8',windowsHide:true});}
function unchanged(f,paths=[...managed,...protectedPaths]){for(const p of paths){const now=fs.existsSync(path.join(f.install,p))?fs.readFileSync(path.join(f.install,p)):null;assert.deepEqual(now,f.original.get(p),p);}}
function backup(f){const dirs=fs.readdirSync(f.install).filter(p=>p.startsWith('.global-config-repair-backup-'));assert.equal(dirs.length,1);return path.join(f.install,dirs[0]);}
function passed(r){assert.equal(r.status,0,r.stderr||r.stdout);}
function rejected(r){assert.notEqual(r.status,0,'operation unexpectedly succeeded');}
function savePlan(f){fs.writeFileSync(f.manifest,JSON.stringify(f.plan));}
function check(name,fn){try{fn();cases.push({name,ok:true});console.log('PASS',name);}catch(e){cases.push({name,ok:false,error:e.message});console.log('FAIL',name,e.message.slice(0,450));}}
check('validate is read-only and preserves every sentinel',()=>{const f=fixture();passed(run(f,'Validate'));unchanged(f);assert(!fs.readdirSync(f.install).some(p=>p.startsWith('.global-config-repair-backup-')));});
check('Windows PowerShell reads BOM-less UTF-8 version notes without changing settings',()=>{const f=fixture();const version=Buffer.from(JSON.stringify({version:'0.0.33',notes:'主线功能与升级器规则更新；子程序继续位于原目录。'}));fs.writeFileSync(path.join(f.install,'version.json'),version);f.original.set('version.json',version);passed(run(f,'Validate'));unchanged(f);assert(!fs.readdirSync(f.install).some(p=>p.startsWith('.global-config-repair-backup-')));});
check('UTF-8 manifest paths and rollback journal round-trip Unicode bytes',()=>{const f=fixture(),p='assets/中文 Ω.css',before=Buffer.from('旧配置字节'),next=Buffer.from('新资源字节');for(const[base,bytes]of[[f.install,before],[f.payload,next]]){fs.mkdirSync(path.dirname(path.join(base,p)),{recursive:true});fs.writeFileSync(path.join(base,p),bytes)}f.original.set(p,before);f.plan.files.push({path:p,sha256:hash(next),bytes:next.length,installedPresent:true,expectedInstalledSha256:hash(before)});f.plan.notes='白名单更新；不修改设置。';savePlan(f);passed(run(f));assert.deepEqual(fs.readFileSync(path.join(f.install,p)),next);unchanged(f,protectedPaths);passed(run(f,'Rollback',['-BackupRoot',backup(f)]));unchanged(f,[...managed,...protectedPaths,p]);});
check('complete patch commits matching files and preserves unknown/config/input paths',()=>{const f=fixture();passed(run(f));for(const x of f.plan.files)assert.equal(hash(fs.readFileSync(path.join(f.install,x.path))),x.sha256);unchanged(f,protectedPaths);const b=backup(f);const journal=JSON.parse(fs.readFileSync(path.join(b,'deployment-journal.json'),'utf8'));assert.equal(journal.status,'committed');assert.equal(journal.files.at(-1).path,'index.html');for(const x of f.plan.files.filter(x=>x.installedPresent))assert.equal(hash(fs.readFileSync(path.join(b,'files',x.path))),x.expectedInstalledSha256);});
check('explicit rollback restores prior bytes and removes only verified added assets',()=>{const f=fixture();passed(run(f));passed(run(f,'Rollback',['-BackupRoot',backup(f)]));unchanged(f);});
check('failure after first activation rolls back all bytes',()=>{const f=fixture();rejected(run(f,'Apply',['-FixtureFaultAfter','1']));unchanged(f);const j=JSON.parse(fs.readFileSync(path.join(backup(f),'deployment-journal.json'),'utf8'));assert.equal(j.status,'rolled-back');assert.equal(j.activatedCount,1);assert.match(j.failure,/Fixture-injected/);});
check('failure after executable activation rolls back without configuration reset',()=>{const f=fixture();rejected(run(f,'Apply',['-FixtureFaultAfter','6']));unchanged(f);const j=JSON.parse(fs.readFileSync(path.join(backup(f),'deployment-journal.json'),'utf8'));assert.equal(j.status,'rolled-back');assert.equal(j.activatedCount,6);assert.match(j.failure,/Fixture-injected/);});
check('corrupt payload is rejected before backup or target writes',()=>{const f=fixture();fs.writeFileSync(path.join(f.payload,'assets/new.js'),'corrupt');rejected(run(f));unchanged(f);assert(!fs.readdirSync(f.install).some(p=>p.startsWith('.global-config-repair-backup-')));});
check('concurrent installed identity change is retained, not overwritten',()=>{const f=fixture();fs.writeFileSync(path.join(f.install,'YeManCC.exe'),'newer external build');f.original.set('YeManCC.exe',Buffer.from('newer external build'));rejected(run(f));unchanged(f);});
check('rollback refuses an unknown newer entry-point modification',()=>{const f=fixture();passed(run(f));fs.writeFileSync(path.join(f.install,'index.html'),'newer unrelated index');rejected(run(f,'Rollback',['-BackupRoot',backup(f)]));assert.equal(fs.readFileSync(path.join(f.install,'index.html'),'utf8'),'newer unrelated index');unchanged(f,protectedPaths);});
check('path traversal and user config are not deployment paths',()=>{const f=fixture();f.plan.files.push({...f.plan.files[0],path:'../escaped.json'});savePlan(f);rejected(run(f));unchanged(f);const g=fixture();g.plan.files.push({...g.plan.files[0],path:'app.config.json'});savePlan(g);rejected(run(g));unchanged(g);});
check('superseded candidate cannot be applied',()=>{const f=fixture();f.plan.status='SUPERSEDED_DO_NOT_INSTALL';savePlan(f);rejected(run(f));unchanged(f);});
check('existing version mismatch and incomplete main/child pairing are rejected',()=>{const f=fixture();f.plan.version='0.0.99';savePlan(f);rejected(run(f));unchanged(f);const g=fixture();g.plan.files=g.plan.files.filter(x=>x.path!=='CustomSteamLibrary/SteamArtworkLab.exe');savePlan(g);rejected(run(g));unchanged(g);});
check('mocked live product blocks deployment without launching a real process',()=>{const f=fixture();const prefix=`function global:Get-Process {param($Name,$ErrorAction) [pscustomobject]@{ProcessName='YeManCC';Id=98765}}`;rejected(run(f,'Apply',[],prefix));unchanged(f);});
check('real Windows entry-point sharing lock rolls back prior activations',()=>{const f=fixture();const target=path.join(f.install,'index.html');const prefix=`$global:fixtureCalls=0;function global:Get-Process {param($Name,$ErrorAction) $global:fixtureCalls++;if($global:fixtureCalls -eq 3){$global:fixtureLock=[IO.File]::Open('${target}',[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read)}}`;rejected(run(f,'Apply',[],prefix));unchanged(f);assert.equal(JSON.parse(fs.readFileSync(path.join(backup(f),'deployment-journal.json'),'utf8')).status,'rolled-back');});
const report={passed:cases.filter(c=>c.ok).length,failed:cases.filter(c=>!c.ok).length,cases,fixtureRoot:root,realProductStartedOrStopped:false,installedDirectoryWritten:false};fs.writeFileSync(pointer.path+'/tests/deployment-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed,fixtureRoot:root},null,2));if(report.failed)process.exitCode=1;
