// Real two-row widget AND actual dedicated-profile component, all native IO mocked.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createServer} from 'node:http';import {createHash} from 'node:crypto';
const root=process.cwd(),req=createRequire(path.join(root,'package.json')),{build}=req('esbuild'),{parse,compileScript,compileStyle}=req('vue/compiler-sfc');
const {chromium}=createRequire('C:/Users/DaVe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/_frame-ui.cjs')('playwright');
const out=path.resolve(process.env.YEMAN_FRAME_RATE_TEST_OUT || '../../Build/Validation/independent-frame-rates-20261009','browser');fs.mkdirSync(out,{recursive:true});
const styles=[],cases=[],images=[],errors=[];
const mocks={
 '@/bridge/frameRateLimits':`import {frameRatePair,frameRateSetting,dedicatedFrameRatePair,dedicatedFrameRateRecord} from './src/bridge/frameRateModel.ts';export {frameRatePair,dedicatedFrameRatePair,dedicatedFrameRateRecord};const f=()=>window.__fixture;const listeners=new Set();export async function loadGlobalFrameRates(){return frameRatePair(f().global)};export function onFrameRatesChanged(cb){listeners.add(cb);return ()=>listeners.delete(cb)};export async function saveGlobalFrameRate(side,value){if(f().failGlobal)throw Error('save failed');f().global[side]=frameRateSetting(value);f().globalWrites.push({side,value:structuredClone(value)});for(const cb of listeners)cb(frameRatePair(f().global));return frameRatePair(f().global)};export async function applyIndependentFrameRates(){const fixture=f(),entry=fixture.custom.entries['a.exe'];const pair=entry?.enabled?dedicatedFrameRatePair(fixture.custom.rtss['a.exe'],frameRatePair(fixture.global)):frameRatePair(fixture.global);fixture.applied.push(pair[fixture.side].fps);return true;}`,
 '@/bridge/yeman':`export const FPS_CEILINGS=[0,30,60,90,120,200,300],FPS_MIN=20;export async function detectPowerMode(){return window.__fixture.side};`,
 '@/bridge/performanceSchedule':`import {frameRatePair,dedicatedFrameRateRecord} from './src/bridge/frameRateModel.ts';const f=()=>window.__fixture,listeners=new Set();export async function loadGameCustomConfig(){return structuredClone(f().custom)};export async function loadPerformanceSchedule(){return structuredClone(f().schedule)};export function onPerformanceScheduleChanged(cb){listeners.add(cb);return ()=>listeners.delete(cb)};export function resolveGameCustomProfiles(entry,schedule){return {ac:entry.acMode?schedule.profiles.ac[entry.acMode]:entry.ac,dc:entry.dcMode?schedule.profiles.dc[entry.dcMode]:entry.dc}};export async function saveGameCustomConfig(next){if(f().failCustom)throw Error('save failed');const committed=JSON.parse(JSON.stringify(next));for(const key of Object.keys(committed.entries))if(!committed.rtss[key])committed.rtss[key]=dedicatedFrameRateRecord(frameRatePair({}));f().custom=committed;f().customWrites.push(JSON.parse(JSON.stringify(committed)));};export async function applyGameCustomProfiles(ac,dc,target,frames){f().performanceWrites.push({ac,dc,target,frames});return true};export async function applyPerformanceScheduleForCurrentPower(){f().performanceWrites.push('restore');return true};`,
 '@/bridge/autofloat':`export const FLOAT_PROFILES={eco:{min:1000,max:2000},bal:{min:1400,max:2800},balance:{min:1400,max:2800},balanced:{min:1400,max:2800},perf:{min:1800,max:3400},aggressive:{min:2000,max:4000}};export const getTdpTarget=(max,strategy)=>max;`,
 '@/bridge/powerSource':`import {ref} from 'vue';export const powerSourceMode=ref('ac');`,
 '@/bridge/ipc':`export function on(event,cb){const f=window.__fixture;(f.events[event]??=new Set()).add(cb);return ()=>f.events[event].delete(cb)};`,
 '@/bridge/gamedetect':`export const detectedGameName=game=>game?.name || '';`,
 '@/bridge/quickActionLock':`export function tryAcquireQuickAction(){return ()=>{}};`,
 '@/bridge/gameproc':`export async function closeJoyxoffIfRunning(){window.__fixture.joyCloses++;}`,
 '@/bridge/gameCorePolicy':`export async function detectGameCorePolicy(){return {heterogeneous:true,smtAvailable:true,efficiencyClasses:[0,1]}};export async function applyGameCorePolicy(){window.__fixture.coreWrites++;return {ok:true,applied:true}};export async function clearGameCorePolicy(){window.__fixture.coreWrites++;return true;}`,
};
const result=await build({stdin:{resolveDir:root,loader:'ts',contents:`import {createApp,defineComponent,h} from 'vue';import Global from './src/components/RtssFrameLimit.vue';import Dedicated from './src/components/GameCustomProfilePanel.vue';
 const modes=['eco','balanced','medium','performance','elite','extreme'];const profiles=Object.fromEntries(modes.map((mode,i)=>[mode,{cpuPreset:'turbo',coreMode:'big',tdpMax:12+i*4,fpsTarget:30+i*40,cpuTarget:'none',tdpStrategy:'none'}]));
 window.__fixture={events:{},side:'ac',global:{ac:{fps:120,ceiling:120,lastFps:120},dc:{fps:60,ceiling:60,lastFps:60}},custom:{version:1,entries:{'a.exe':{displayName:'Test Game',enabled:true,acMode:'balanced',dcMode:'eco',ac:profiles.balanced,dc:profiles.eco,padPersona:'follow',gyroOverride:'follow'}},rtss:{'a.exe':{enabled:true,acFps:85,dcFps:45,acCeiling:90,dcCeiling:60,acLastFps:85,dcLastFps:45,future:'KEEP'}}},schedule:{enabled:true,configured:true,active:{ac:'balanced',dc:'eco'},profiles:{ac:profiles,dc:profiles}},globalWrites:[],customWrites:[],performanceWrites:[],applied:[],coreWrites:0,joyCloses:0,status:{}};
 const game={pid:101,processCreated:'1001',path:'R:/memory/a.exe',name:'Test Game'};let app;window.__mount=()=>{app=createApp(defineComponent({setup(){return()=>h('div',{},[h('h2','性能调度'),h(Global),h('h2','专用配置'),h(Dedicated,{game,open:true,onStatus:value=>window.__fixture.status=value})])}}));app.mount('#app')};window.__unmount=()=>app.unmount();window.__mount();`},bundle:true,write:false,platform:'browser',format:'iife',alias:{'@':path.join(root,'src')},define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'fixture',setup(b){b.onResolve({filter:/.*/},args=>args.path in mocks?{path:args.path,namespace:'fixture'}:undefined);b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:mocks[args.path],loader:'ts',resolveDir:root}));b.onLoad({filter:/\.vue$/},args=>{const {descriptor,errors}=parse(fs.readFileSync(args.path,'utf8'),{filename:args.path});assert.deepEqual(errors,[]);const id='data-v-'+createHash('sha256').update(args.path).digest('hex').slice(0,8);const component=compileScript(descriptor,{id,inlineTemplate:true});for(const style of descriptor.styles){const css=compileStyle({source:style.content,filename:args.path,id,scoped:style.scoped});assert.deepEqual(css.errors,[]);styles.push(css.code)}return {contents:component.content.replace('export default','const _component=')+'\n_component.__scopeId='+JSON.stringify(id)+';export default _component;',loader:'ts',resolveDir:path.dirname(args.path)}})}}]});
const css=fs.readFileSync('src/styles/tokens.css','utf8')+'\n'+styles.join('\n');
const html='<!doctype html><meta charset="utf-8"><style>'+css+'\nbody{margin:0;background:var(--bg-solid);color:var(--text);font-family:system-ui}#app{max-width:720px;box-sizing:border-box;margin:auto;padding:14px}.card{border:1px solid var(--border);border-radius:var(--radius);background:var(--bg-panel);margin-bottom:12px}h2{font-size:14px;margin:15px 0 10px}</style><main id="app"></main><script src="/fixture.js"></script>';
const server=createServer((request,response)=>{response.setHeader('Content-Type',request.url==='/fixture.js'?'text/javascript':'text/html; charset=utf-8');response.end(request.url==='/fixture.js'?result.outputFiles[0].text:html)});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
async function choose(page,label,option){await page.getByRole('button',{name:label,exact:true}).click();await page.getByRole('option',{name:option,exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));}
try{browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:720,height:1160}});page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message)});page.on('console',m=>{if(m.type()==='error')console.error('BROWSER',m.text())});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.querySelector('.rtss-frame-limit input')?.value==='120');
 const global=page.locator('.rtss-frame-limit');assert.equal(await global.locator('.switch').count(),0);assert.equal(await global.locator('input[type=range]').count(),2);assert.equal(await global.locator('.dd-trigger').count(),2);assert.equal(await page.evaluate(()=>window.__fixture.globalWrites.length+window.__fixture.customWrites.length),0);
 cases.push('Global FPS renders exactly two slider/dropdown rows, no switch, and mount performs no saves');
 await choose(page,'电池锁帧上限','不锁帧');assert.equal(await page.evaluate(()=>window.__fixture.global.dc.fps),0);assert.equal(await global.locator('input').nth(1).isDisabled(),true);assert.equal(await page.evaluate(()=>window.__fixture.global.ac.fps),120);
 await global.locator('input').first().focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>window.__fixture.global.ac.fps===110);assert.equal(await page.evaluate(()=>window.__fixture.global.dc.fps),0);
 await choose(page,'插电锁帧上限','不锁帧');await choose(page,'插电锁帧上限','200 FPS');assert.equal(await page.evaluate(()=>window.__fixture.global.ac.fps),110);
 cases.push('AC/DC changes and zero/re-enable remain independent, restoring last nonzero value through dropdown only');
 await page.locator('.custom-top-head').click();await page.waitForSelector('.dedicated-frame-limits');const dedicated=page.locator('.dedicated-frame-limits');assert.equal(await dedicated.locator('input').count(),2);assert.equal(await dedicated.locator('.dd-trigger').count(),2);assert.deepEqual(await dedicated.locator('input').evaluateAll(nodes=>nodes.map(n=>n.value)),['85','45']);assert.equal(await dedicated.locator('.switch').count(),0);
 await page.evaluate(()=>window.__fixture.failGlobal=true);const savedAc=await global.locator('input').first().inputValue();await global.locator('input').first().focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>document.querySelector('.frame-error')?.textContent.includes('锁帧保存失败'));assert.equal(await global.locator('input').first().inputValue(),savedAc);assert.equal(await page.evaluate(()=>window.__fixture.global.ac.fps),Number(savedAc));await page.evaluate(()=>window.__fixture.failGlobal=false);await choose(page,'插电锁帧上限','200 FPS');assert.equal(await global.locator('.frame-error').count(),0);
 cases.push('Global failed save restores saved sides/slider and a subsequent save clears the error');
 assert.equal(await page.locator('.custom-top-body').innerText().then(text=>text.includes('核心线程控制')),false);
 cases.push('Actual dedicated submenu exposes the same two-row controls using its own per-game values');
 const before=await page.evaluate(()=>({global:structuredClone(window.__fixture.global),entry:structuredClone(window.__fixture.custom.entries['a.exe']),performance:window.__fixture.performanceWrites.length,core:window.__fixture.coreWrites}));
 await dedicated.locator('input').nth(1).focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>window.__fixture.custom.rtss['a.exe'].dcFps===35);
 assert.deepEqual(await page.evaluate(()=>window.__fixture.global),before.global);assert.equal(await page.evaluate(()=>window.__fixture.custom.rtss['a.exe'].future),'KEEP');assert.deepEqual(await page.evaluate(()=>window.__fixture.custom.entries['a.exe']),before.entry);assert.equal(await page.evaluate(()=>window.__fixture.performanceWrites.length),before.performance);assert.equal(await page.evaluate(()=>window.__fixture.coreWrites),before.core);
 cases.push('Dedicated FPS-only save changes neither global values nor performance/core/input settings');
 await choose(page,'专用插电锁帧上限','不锁帧');assert.equal(await page.evaluate(()=>window.__fixture.custom.rtss['a.exe'].acFps),0);assert.equal(await page.evaluate(()=>window.__fixture.custom.rtss['a.exe'].dcFps),35);assert.equal(await page.evaluate(()=>window.__fixture.applied.at(-1)),0);
 cases.push('Dedicated AC no-lock applies zero without disabling its performance owner or changing DC');
 const fpsRecord=await page.evaluate(()=>structuredClone(window.__fixture.custom.rtss['a.exe']));await page.getByRole('button',{name:'AC 专属性能档位',exact:true}).click();await page.getByRole('option').filter({hasText:'极致性能'}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));await page.waitForFunction(()=>window.__fixture.custom.entries['a.exe'].acMode==='extreme');
 assert.deepEqual(await page.evaluate(()=>window.__fixture.custom.rtss['a.exe']),fpsRecord);assert.equal(await dedicated.locator('input').first().inputValue(),'0');assert.equal(await page.evaluate(()=>window.__fixture.performanceWrites.at(-1).frames.ac.fps),0);assert.equal(await page.evaluate(()=>window.__fixture.performanceWrites.at(-1).frames.dc.fps),35);
 cases.push('Changing dedicated performance combination preserves independent FPS and passes its own pair to optimizer');
 const dc=page.getByRole('button',{name:'专用电池锁帧上限',exact:true});await dc.locator('..').dispatchEvent('gp:dropdown-open');await page.waitForSelector('.dd-menu');await dc.locator('..').evaluate(n=>n.dispatchEvent(new CustomEvent('gp:dropdown-nav',{bubbles:true,cancelable:true,detail:{dir:1}})));await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.querySelector('.dd-menu'));assert.equal(await dc.evaluate(n=>document.activeElement===n),true);
 cases.push('Shared dropdown supports actual controller open/nav/confirm and restores focus in dedicated submenu');
 await page.evaluate(()=>window.__fixture.failCustom=true);const currentDc=await dedicated.locator('input').nth(1).inputValue();await dedicated.locator('input').nth(1).focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>window.__fixture.status.error?.includes('帧率保存失败'));assert.equal(await dedicated.locator('input').nth(1).inputValue(),currentDc);await page.evaluate(()=>window.__fixture.failCustom=false);
 cases.push('Dedicated failed save reloads previous FPS instead of showing unsaved slider value');
 await page.locator('[data-gp-custom-actions] button').first().click();await page.waitForFunction(()=>window.__fixture.custom.entries['a.exe'].enabled===false);assert.equal(await page.evaluate(()=>window.__fixture.applied.at(-1)),110);assert.deepEqual(await page.evaluate(()=>window.__fixture.global),before.global);
 cases.push('Disabling dedicated configuration restores global AC FPS without erasing either saved pair');
 for(const width of [720,580,420]){await page.setViewportSize({width,height:1160});await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  for(const selector of ['.rtss-frame-limit','.dedicated-frame-limits']){const rects=await page.locator(selector+' .frame-rate-controls .dd-trigger').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().x));assert(Math.abs(rects[0]-rects[1])<1);}
  const boxes=await page.locator('[data-gp-group="custom-core-policy"] .dd-trigger, [data-gp-group="custom-input-override"] .dd-trigger').evaluateAll(nodes=>nodes.map(n=>({x:n.getBoundingClientRect().x,width:n.getBoundingClientRect().width})));assert.equal(boxes.length,4);for(let col=0;col<2;col++){assert(Math.abs(boxes[col].x-boxes[col+2].x)<1);assert(Math.abs(boxes[col].width-boxes[col+2].width)<1);}
  const file=path.join(out,'frame-rate-pairs-'+width+'.png');await page.screenshot({path:file,fullPage:true});images.push(file);cases.push('Global/dedicated AC/DC dropdowns align within 1px with no horizontal overflow at '+width+'px');
 }
 cases.push('Core/thread heading is absent and both dropdown columns align with the two input dropdowns at all widths');
 await page.evaluate(()=>{window.__unmount();window.__fixture.global={};window.__fixture.custom={version:1,entries:{},rtss:{}};window.__fixture.status={};window.__mount()});await page.waitForFunction(()=>document.querySelector('.rtss-frame-limit input')?.value==='120');assert.deepEqual(await global.locator('input').evaluateAll(nodes=>nodes.map(n=>n.value)),['120','60']);await page.locator('.custom-top-head').click();await page.waitForSelector('.dedicated-frame-limits');await page.waitForFunction(()=>window.__fixture.custom.rtss['a.exe']?.dcFps===60);assert.deepEqual(await dedicated.locator('input').evaluateAll(nodes=>nodes.map(n=>n.value)),['120','60']);
 cases.push('Fresh global and newly created dedicated controls both render the locked 120/60 presets');
 for(const width of [720,580,420]){await page.setViewportSize({width,height:1160});await page.waitForTimeout(80);const file=path.join(out,'frame-rate-presets-'+width+'.png');await page.screenshot({path:file,fullPage:true});images.push(file)}
 await page.evaluate(()=>{window.__unmount();window.__fixture.global={ac:{fps:90,ceiling:90,lastFps:90},dc:{fps:35,ceiling:60,lastFps:35}};window.__fixture.custom={version:1,entries:{},rtss:{}};window.__mount()});await page.waitForFunction(()=>document.querySelector('.rtss-frame-limit input')?.value==='90');await page.locator('.custom-top-head').click();await page.waitForFunction(()=>window.__fixture.custom.rtss['a.exe']?.dcFps===60);assert.deepEqual(await dedicated.locator('input').evaluateAll(nodes=>nodes.map(n=>n.value)),['120','60']);assert.deepEqual(await global.locator('input').evaluateAll(nodes=>nodes.map(n=>n.value)),['90','35']);
 cases.push('New dedicated pair uses its own 120/60 preset rather than inheriting user-edited global 90/35');
 await page.evaluate(()=>window.__unmount());assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>Object.values(window.__fixture.events).reduce((total,set)=>total+set.size,0)),0);
 cases.push('Unmount clears subscriptions and all real controls render without browser errors');
 const report={suite:'Independent AC/DC frame controls browser',passed:cases.length,cases,images,pageErrors:errors,scope:'Real widget/dedicated Vue components/Dropdown/Slider/focus, mocked native IO, zero installed settings changes'};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){if(browser){for(const page of browser.contexts().flatMap(c=>c.pages())){console.error(await page.evaluate(()=>({error:document.querySelector('.custom-top-panel')?.textContent,fixture:window.__fixture})));await page.screenshot({path:path.join(out,'failure.png'),fullPage:true})}}throw error;}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
