// Production frame model/service/runtime with memory-only native/storage boundaries.
import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import path from 'node:path';import {createRequire} from 'node:module';
const req=createRequire(path.join(process.cwd(),'package.json')),{transformSync}=req('esbuild'),vue=req('vue');
const cases=[],out=path.resolve(process.env.YEMAN_FRAME_RATE_TEST_OUT || '../../Build/Validation/independent-frame-rates-20261009');fs.mkdirSync(out,{recursive:true});
function evaluate(text,imports={},globals={}){const module={exports:{}};vm.runInNewContext(transformSync(text,{loader:'ts',format:'cjs'}).code,{module,exports:module.exports,console,structuredClone,require(name){if(name==='vue')return vue;if(name in imports)return imports[name];throw Error('unexpected dependency '+name)},...globals});return module.exports;}
const model=evaluate(fs.readFileSync('src/bridge/frameRateModel.ts','utf8'));
const settingsModel=evaluate(req('esbuild').buildSync({entryPoints:['src/bridge/settingsRepository.ts'],bundle:true,write:false,platform:'node',format:'cjs',external:['vue']}).outputFiles[0].text);
let prefs={rtss:{future:'KEEP'},tdp:{fpsLimit:75,tdpMax:27,future:'TDP'},performanceSchedule:{}},generation=1,mode='ac',game=null,initialized=true,phase='ready',actual=75,failWrite=false,failReload=false,reliablePower=true,readHook=null,storeHook=null;
let custom={entries:{},rtss:{}},schedule={configured:true,enabled:true,active:{ac:'balanced',dc:'balanced'},profiles:{ac:{balanced:{cpuPreset:'turbo',tdpMax:25,fpsTarget:30}},dc:{balanced:{cpuPreset:'balanced',tdpMax:12,fpsTarget:120}}}};
let optimizer={enabled:false,target:90};const trace={writes:[],rtss:[],targets:[],performance:[],cores:[],phaseReads:0,powerReads:0,rtssReads:0};
const source=vue.ref('ac'),gameListeners=new Set(),customListeners=new Set(),scheduleListeners=new Set(),tasks=new Map();
const repository={getSettingsGeneration:()=>generation,assertSettingsGeneration:expected=>{if(expected!==generation)throw Error('generation-changed')},async readSettingsSection(key){if(storeHook){const hook=storeHook;storeHook=null;await hook()}return structuredClone(prefs[key]||{})},async saveSettingsSection(key,patch,expected){repository.assertSettingsGeneration(expected);prefs[key]={...prefs[key],...structuredClone(patch)};trace.writes.push({key,patch:structuredClone(patch)})}};
const target={getPolicyGame:()=>game,isPolicyGameInitialized:()=>initialized,gamePolicyKey:g=>g?g.path.split(/[\/]/).at(-1).toLowerCase():'',subscribePolicyGameStatus(cb){gameListeners.add(cb);cb(game);return()=>gameListeners.delete(cb)}};
const float={getFloatInfo:()=>({...optimizer}),setFloatRtssLinked:()=>{},async setFloatTarget(fps){optimizer.target=fps;trace.targets.push(fps)}};
const yeman={async detectPowerModeReliable(){trace.powerReads++;return reliablePower?mode:null},async detectPowerMode(){trace.powerReads++;return mode},async readRtssLimit(){trace.rtssReads++;if(readHook){const hook=readHook;readHook=null;await hook()}return actual},async setRtssLimit(fps,current){if(current&&!current())return;if(failWrite)throw Error('simulated-RTSS-write-failure');actual=fps;trace.rtss.push(fps);if(failReload)throw Error('simulated-live-reload-failure')}};
const api={powerLifecycle:{async get(){trace.phaseReads++;return {phase,hardwareWritesAllowed:phase==='ready'}}}};
const perf={async loadGameCustomConfig(){return structuredClone(custom)},async loadPerformanceSchedule(){return structuredClone(schedule)},resolveGameCustomProfiles:entry=>({ac:entry.acMode?schedule.profiles.ac[entry.acMode]:entry.ac,dc:entry.dcMode?schedule.profiles.dc[entry.dcMode]:entry.dc}),onGameCustomConfigChanged(cb){customListeners.add(cb);return()=>customListeners.delete(cb)},onPerformanceScheduleChanged(cb){scheduleListeners.add(cb);return()=>scheduleListeners.delete(cb)},async restorePerformanceScheduleIfConfigured(){trace.performance.push(game?.pid||null);return 'auto'}};
const limits=evaluate(fs.readFileSync('src/bridge/frameRateLimits.ts','utf8'),{'./settingsRepository':repository,'./yeman':yeman,'./gamePolicyTarget':target,'./frameRateModel':model,'./performanceSchedule':perf,'./autofloat':float,'./api':api,'./powerSource':{powerSourceMode:source}});
const runtime=evaluate(fs.readFileSync('src/bridge/gamePolicyRuntime.ts','utf8'),{'./powerSource':{powerSourceMode:source},'./yeman':yeman,'./frameRateLimits':limits,'./autofloat':float,'./gamePolicyTarget':target,'./performanceSchedule':perf,'@/scheduler':{registerScheduledTask(name,ms,run){tasks.set(name,{ms,run});return()=>tasks.delete(name)}},'./api':api,'./quickActionLock':{isQuickActionBusy:()=>false},'./gameCorePolicy':{detectGameCorePolicy:async()=>({heterogeneous:false,smtAvailable:false}),applyGameCorePolicy:async()=>({ok:true,applied:true}),clearGameCorePolicy:async()=>{trace.cores.push('clear');return true}}});
async function flush(){for(let i=0;i<120;i++){await Promise.resolve();await vue.nextTick();}}
async function check(name,run){await run();cases.push(name)}
function resetTrace(){for(const key of ['writes','rtss','targets','performance','cores'])trace[key]=[]}
function rates(ac,dc){return model.frameRatePair({},ac,dc)}
function record(ac,dc){return model.dedicatedFrameRateRecord(rates(ac,dc))}
await check('Fresh model, actual settings defaults and global read all use locked AC 120/DC 60 without saving',async()=>{const before=prefs;const pair=model.frameRatePair({});assert.equal(pair.ac.fps,120);assert.equal(pair.dc.fps,60);const fresh=settingsModel.normalizeSettings({});assert.equal(fresh.rtss.frameRates.ac.fps,120);assert.equal(fresh.rtss.frameRates.dc.fps,60);prefs=fresh;generation++;resetTrace();const loaded=await limits.loadGlobalFrameRates();assert.equal(loaded.ac.fps,120);assert.equal(loaded.dc.fps,60);assert.equal(trace.writes.length,0);prefs=before;generation++});
await check('New presets do not hide explicit legacy scalar zero/120 or old profile FPS; saved independent values win',()=>{for(const fps of [0,120,75]){const legacy=settingsModel.normalizeSettings({tdp:{fpsLimit:fps}});assert.equal(legacy.tdp.fpsLimit,fps);assert.equal(legacy.rtss.frameRates,undefined)}const prior=settingsModel.normalizeSettings({performanceSchedule:{profiles:{dc:{eco:{fpsTarget:35}}}}});assert.equal(prior.rtss.frameRates,undefined);const saved=settingsModel.normalizeSettings({tdp:{fpsLimit:75},rtss:{frameRates:rates(85,45),future:'KEEP'}});assert.equal(saved.rtss.frameRates.ac.fps,85);assert.equal(saved.rtss.frameRates.dc.fps,45);assert.equal(saved.rtss.future,'KEEP');const partial=settingsModel.normalizeSettings({rtss:{frameRates:{ac:{fps:90,ceiling:120,lastFps:90}}}});assert.equal(partial.rtss.frameRates.ac.fps,90);assert.equal(partial.rtss.frameRates.dc.fps,60)});
await check('Production dedicated save seeds a new entry at 120/60 even when global is 90/35 and retains an existing pair',async()=>{const text=fs.readFileSync('src/bridge/performanceSchedule.ts','utf8'),start=text.indexOf('export async function saveGameCustomConfig('),end=text.indexOf('/** Legacy migration clears',start),saved=[];const save=evaluate(text.slice(start,end),{}, {ensureGlobalFrameRates:async()=>rates(90,35),normalizeGameCustom:value=>structuredClone(value),...model,gameCustomWriteQueue:Promise.resolve(),gameCustomCache:null,fs:{exists:async()=>false},GAME_CUSTOM_PATH:'memory-only',writeStandaloneGameCustom:async value=>saved.push(structuredClone(value)),notifyGameCustomConfigChanged(){}}).saveGameCustomConfig;await save({version:1,entries:{'new.exe':{}},rtss:{}});assert.equal(saved[0].rtss['new.exe'].acFps,120);assert.equal(saved[0].rtss['new.exe'].dcFps,60);await save({version:1,entries:{'old.exe':{}},rtss:{'old.exe':record(85,45)}});assert.equal(saved[1].rtss['old.exe'].acFps,85);assert.equal(saved[1].rtss['old.exe'].dcFps,45)});
await check('Legacy single FPS scalar migrates read-only into two modes without erasing TDP/unknown data',async()=>{const pair=await limits.loadGlobalFrameRates();assert.equal(pair.ac.fps,75);assert.equal(pair.dc.fps,75);assert.equal(trace.writes.length,0);await limits.saveGlobalFrameRate('ac',110);assert.equal((await limits.loadGlobalFrameRates()).dc.fps,75);assert.equal(prefs.rtss.future,'KEEP');assert.equal(prefs.tdp.fpsLimit,75);assert.equal(prefs.tdp.tdpMax,27)});
await check('Concurrent AC/DC saves serialize without losing either side',async()=>{await Promise.all([limits.saveGlobalFrameRate('ac',120),limits.saveGlobalFrameRate('dc',60)]);const pair=await limits.loadGlobalFrameRates();assert.equal(pair.ac.fps,120);assert.equal(pair.dc.fps,60)});
await check('Zero disables a side but preserves its last nonzero FPS and the other side',async()=>{await limits.saveGlobalFrameRate('dc',{fps:0,lastFps:60,ceiling:0});const pair=await limits.loadGlobalFrameRates();assert.equal(pair.dc.fps,0);assert.equal(pair.dc.lastFps,60);assert.equal(pair.dc.ceiling,0);assert.equal(pair.ac.fps,120)});
await check('Independent ceiling persists even when actual FPS is lower',async()=>{await limits.saveGlobalFrameRate('ac',{fps:110,lastFps:110,ceiling:300});assert.equal((await limits.loadGlobalFrameRates()).ac.ceiling,300)});
await check('Queued submissions snapshot their own value rather than a later caller mutation',async()=>{const submitted={fps:110,ceiling:300,lastFps:110};const save=limits.saveGlobalFrameRate('ac',submitted);submitted.fps=299;submitted.ceiling=300;await save;assert.equal((await limits.loadGlobalFrameRates()).ac.fps,110)});
await check('Old per-side active combination values migrate once then no longer follow mode changes',async()=>{generation++;prefs={rtss:{},tdp:{fpsLimit:99},performanceSchedule:{enabled:true,active:{ac:'eco',dc:'extreme'},profiles:{ac:{eco:{fpsTarget:30}},dc:{extreme:{fpsTarget:120}}}}};const pair=await limits.ensureGlobalFrameRates();assert.equal(pair.ac.fps,30);assert.equal(pair.dc.fps,120);prefs.performanceSchedule.profiles.ac.eco.fpsTarget=250;assert.equal((await limits.loadGlobalFrameRates()).ac.fps,30)});
await check('Legacy dedicated profile FPS migrates into RTSS map, explicit map wins on subsequent mode edits',async()=>{
 const text=fs.readFileSync('src/bridge/performanceSchedule.ts','utf8'),start=text.indexOf('function normalizeGameCustom(value:'),end=text.indexOf('type GameCustomConfigListener',start);
 const snippet=text.slice(start,end);const migrate=evaluate(snippet+'\nexport {normalizeGameCustom};',{}, {defaultPerformanceScheduleConfig:()=>({profiles:{ac:{performance:{fpsTarget:60}}}}),normalizeCustomProfile:(value)=>value,...model}).normalizeGameCustom;
 const original={entries:{'A.exe':{ac:{fpsTarget:50},dc:{fpsTarget:70}}},rtss:{}};
 const converted=migrate(original);assert.equal(converted.rtss['a.exe'].acFps,50);assert.equal(converted.rtss['a.exe'].dcFps,70);converted.entries['a.exe'].ac.fpsTarget=300;converted.rtss['a.exe'].future='KEEP';assert.equal(migrate(converted).rtss['a.exe'].acFps,50);assert.equal(migrate(converted).rtss['a.exe'].future,'KEEP');converted.rtss['a.exe'].dcFps=999;assert.equal(migrate(converted).rtss['a.exe'].dcFps,300);
});
await check('Global FPS applies actual DC side, including zero, without CPU/profile writes',async()=>{await limits.saveGlobalFrameRate('ac',110);await limits.saveGlobalFrameRate('dc',0);game=null;mode='dc';source.value='dc';actual=120;resetTrace();assert(await limits.applyIndependentFrameRates());assert.equal(actual,0);assert.deepEqual(trace.performance,[]);assert.deepEqual(trace.cores,[])});
const A={pid:101,processCreated:'A-1',path:'R:/memory/a.exe'},B={pid:202,processCreated:'B-1',path:'R:/memory/b.exe'};
custom={entries:{'a.exe':{enabled:true,ac:{cpuPreset:'turbo',tdpMax:25,fpsTarget:30},dc:{cpuPreset:'balanced',tdpMax:12,fpsTarget:250}},'b.exe':{enabled:true,ac:{cpuPreset:'turbo',tdpMax:26},dc:{cpuPreset:'balanced',tdpMax:10}}},rtss:{'a.exe':record(85,45),'b.exe':record(96,36)}};
await check('Dedicated FPS uses its own AC/DC map, never inherited profile FPS or global record',async()=>{game=A;mode='ac';source.value='ac';actual=110;resetTrace();assert(await limits.applyIndependentFrameRates());assert.equal(actual,85);assert.equal(prefs.rtss.frameRates.ac.fps,110);custom.entries['a.exe'].ac.fpsTarget=300;assert.equal((await limits.effectiveFrameRates()).pair.ac.fps,85)});
await check('Disabling dedicated owner and game exit restore global values even in manual performance mode',async()=>{custom.entries['a.exe'].enabled=false;await limits.applyIndependentFrameRates();assert.equal(actual,110);custom.entries['a.exe'].enabled=true;await limits.applyIndependentFrameRates();game=null;await limits.applyIndependentFrameRates();assert.equal(actual,110)});
await check('Read-only/unchanged FPS reconciliation does not reload RTSS',async()=>{resetTrace();assert(await limits.applyIndependentFrameRates());assert.deepEqual(trace.rtss,[]);assert.deepEqual(trace.targets,[])});
await check('Recording a noncurrent power-side value does not apply it to current output',async()=>{resetTrace();mode='ac';source.value='ac';await limits.saveGlobalFrameRate('dc',40);await limits.applyIndependentFrameRates();assert.equal(actual,110);assert.deepEqual(trace.rtss,[])});
await check('Native power gate and uninitialized game policy defer hardware changes',async()=>{actual=10;phase='resuming';assert.equal(await limits.applyIndependentFrameRates(),false);assert.equal(actual,10);phase='ready';initialized=false;assert.equal(await limits.applyIndependentFrameRates(),false);initialized=true});
await check('Unknown power status defers independent RTSS changes instead of defaulting to AC',async()=>{const before=actual;reliablePower=false;resetTrace();assert.equal(await limits.applyIndependentFrameRates(),false);assert.equal(actual,before);assert.deepEqual(trace.rtss,[]);reliablePower=true});
await check('Failed live reload is retried even after disk Limit already equals the saved target',async()=>{game=null;mode='ac';source.value='ac';actual=10;resetTrace();failReload=true;await assert.rejects(limits.applyIndependentFrameRates());assert.equal(actual,110);failReload=false;assert(await limits.applyIndependentFrameRates());assert.deepEqual(trace.rtss,[110,110])});
await check('Power changes during RTSS read cancel stale side before file write',async()=>{game=null;mode='ac';source.value='ac';actual=10;resetTrace();readHook=async()=>{mode='dc';source.value='dc'};assert.equal(await limits.applyIndependentFrameRates(),false);assert.deepEqual(trace.rtss,[]);await limits.applyIndependentFrameRates();assert.equal(actual,40)});
await check('Game PID reuse/switch during queued read cannot replay old dedicated cap',async()=>{game=A;mode='ac';source.value='ac';actual=10;resetTrace();readHook=async()=>{game=B};assert.equal(await limits.applyIndependentFrameRates(),false);assert.deepEqual(trace.rtss,[]);await limits.applyIndependentFrameRates();assert.equal(actual,96)});
await check('Save failure keeps both prior independent modes and other feature fields',async()=>{const before=JSON.stringify(prefs);const previous=repository.saveSettingsSection;repository.saveSettingsSection=async()=>{throw Error('write-failed')};await assert.rejects(limits.saveGlobalFrameRate('ac',200));repository.saveSettingsSection=previous;assert.equal(JSON.stringify(prefs),before)});
await check('Queued old-generation save cannot contaminate a reset/new settings directory',async()=>{const before=JSON.stringify(prefs);const request=limits.saveGlobalFrameRate('ac',220);generation++;await assert.rejects(request);assert.equal(JSON.stringify(prefs),before)});
custom.entries['a.exe'].acMode='balanced';custom.entries['a.exe'].dcMode='balanced';game=A;mode='ac';source.value='ac';actual=85;phase='ready';runtime.startGamePolicyRuntime();await flush();
await check('Existing resident policy has one original retry task and remains event-driven for frame changes',async()=>{assert.equal(tasks.size,1);assert.equal(tasks.get('game-policy-runtime-retry').ms,2000);await flush()});
await check('Performance combo edits reapply CPU/TDP owner but never write unchanged independent FPS',async()=>{resetTrace();schedule.profiles.ac.balanced.tdpMax=28;schedule.profiles.ac.balanced.fpsTarget=300;for(const cb of scheduleListeners)cb(schedule);await flush();assert.equal(trace.performance.length,1);assert.deepEqual(trace.rtss,[]);assert.equal(actual,85)});
await check('Frame-only dedicated edit never replays CPU/TDP/core policies',async()=>{resetTrace();custom.rtss['a.exe'].acFps=100;for(const cb of customListeners)cb(custom);await flush();assert.equal(actual,100);assert.deepEqual(trace.performance,[]);assert.deepEqual(trace.cores,[])});
await check('AC/DC native notification swaps cap once without a background power poll',async()=>{resetTrace();mode='dc';source.value='dc';await flush();assert.equal(actual,45);assert.deepEqual(trace.rtss,[45]);assert.deepEqual(trace.performance,[])});
await check('Dedicated exit restores global DC cap even when global performance is manual',async()=>{schedule.enabled=false;game=null;for(const cb of gameListeners)cb(game);await flush();assert.equal(actual,40)});
await check('Idle original retry loop does not query power, native gate or RTSS after successful application',async()=>{const before={phase:trace.phaseReads,power:trace.powerReads,rtss:trace.rtssReads};for(let i=0;i<100;i++)await tasks.get('game-policy-runtime-retry').run();assert.deepEqual({phase:trace.phaseReads,power:trace.powerReads,rtss:trace.rtssReads},before)});
await check('Stopping resident owner removes power/frame subscriptions and the original retry task',async()=>{runtime.stopGamePolicyRuntime();assert.equal(tasks.size,0);resetTrace();mode='ac';source.value='ac';for(const cb of customListeners)cb(custom);await flush();assert.deepEqual(trace.rtss,[])});
await check('Restarting the resident owner rechecks RTSS rather than reusing a stopped-session receipt',async()=>{mode='dc';source.value='dc';actual=299;resetTrace();runtime.startGamePolicyRuntime();await flush();assert.equal(actual,40);assert.deepEqual(trace.rtss,[40]);runtime.stopGamePolicyRuntime();assert.equal(tasks.size,0)});
const editor=fs.readFileSync('src/views/PerformanceScheduleView.vue','utf8'),pair=fs.readFileSync('src/components/FrameRatePair.vue','utf8'),widget=fs.readFileSync('src/components/RtssFrameLimit.vue','utf8'),app=fs.readFileSync('src/App.vue','utf8'),perfText=fs.readFileSync('src/bridge/performanceSchedule.ts','utf8');
await check('Source contract removes profile FPS editors/gates/toggle and old AC-only startup replay',()=>{assert(!editor.includes('editingDraft.fpsTarget'));assert(!editor.includes('fpsCeiling'));assert(!widget.includes('Toggle'));assert(!widget.includes('autoMode'));assert(!app.includes('applyRtssLimitConfig'));assert(pair.includes("value===0?'不锁帧'"));assert(perfText.includes('const optimizationTarget = independent.fps || independent.lastFps'));assert(!perfText.includes('hasFpsFloatTarget'));});
const report={suite:'Independent frame-rate production service/runtime',passed:cases.length,cases,scope:'Actual TypeScript model/service/runtime and legacy normalizer; storage/native/hardware are memory-only'};fs.writeFileSync(path.join(out,'service-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
