// Exact original quickapp owner under inert file/process boundaries, plus real LS list read-only.
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {createRequire} from 'node:module';
import {root,task} from './fixtures/decky_task_paths.mjs';
const require=createRequire(path.join(root,'package.json')),{transformSync}=require('esbuild');
const source=fs.readFileSync(path.join(root,'src/bridge/quickapp.ts'),'utf8');
function load(text,modules={}){const module={exports:{}};vm.runInNewContext(transformSync(text,{loader:'ts',format:'cjs'}).code,{module,exports:module.exports,structuredClone,console,Uint8Array,btoa:value=>Buffer.from(value,'binary').toString('base64'),require:name=>{if(!(name in modules))throw Error('Unexpected import '+name);return modules[name];}});return module.exports;}
const profiles=load(fs.readFileSync(path.join(root,'src/bridge/losslessProfiles.ts'),'utf8'));
const profile=(title,p,enabled=true)=>`    <Profile><Title>${title}</Title><Path>${p}</Path><AutoScale>${enabled}</AutoScale><ScalingType>FSR</ScalingType><FrameGeneration>LSFG3</FrameGeneration></Profile>`;
const xml=`<Settings><Unknown>retained</Unknown>\n  <GameProfiles>\n${profile('A','D:\\Games\\a.exe')}\n${profile('B','D:\\Games\\b.exe')}\n  </GameProfiles>\n</Settings>`;
const observedScripts=new Set();
const file='Q:\\LocalData\\Lossless Scaling\\Settings.xml',exe='C:\\SOFT\\Lossless.Scaling\\LosslessScaling.exe';
function fixture(options={}){
 const files=new Map([[file,options.xml??xml],[exe,'locked-asset']]);const events=[];let running=!!options.running,stamp='123',liveXml=options.liveXml;const hooks={closeDenied:!!options.closeDenied,backupDenied:false,sourceChange:false,startDenied:false,observeUnknown:false};let title='A',button='缩放';
 const api={fs:{exists:async p=>files.has(p),readTextFile:async p=>{if(!files.has(p))throw Error('missing fixture '+p);return files.get(p);},writeTextFileAtomic:async(p,text)=>{events.push('write:'+p);if(p.endsWith('.ymccbak')&&hooks.backupDenied)throw Error('backup denied');if(p===file&&running)throw Error('SHARING_VIOLATION_RUNNING_LS');files.set(p,text);if(p.endsWith('.ymccbak')&&hooks.sourceChange)files.set(file,xml.replace('retained','external-update'));}},
 registry:{read:async()=>null},proc:{findExact:async p=>({found:p===exe&&running,pid:running?71:0}),identity:async pid=>({valid:running&&pid===71,pid,processCreated:stamp,path:exe})},
 shell:{execute:async(p,args)=>{events.push('launch:'+JSON.stringify(args));if(hooks.startDenied)return false;running=true;title=args.includes('-auto')?'A':title;button=args.includes('-auto')?'取消缩放':button;return true;},run:async(p,args)=>{if(args.includes('Write-Output $env:LOCALAPPDATA'))return {exitCode:0,stdout:'Q:\\LocalData',stderr:''};const script=args.includes('-EncodedCommand')?Buffer.from(args.at(-1),'base64').toString('utf16le'):args.join(' ');if(args.includes('-EncodedCommand'))observedScripts.add(script);if(script.includes('CloseMainWindow')){events.push('normal-close');assert.match(script,/StartTime.*ToFileTimeUtc/);assert.match(script,/CloseMainWindow/);if(hooks.closeDenied)return {exitCode:1,stdout:'',stderr:'close to tray'};running=false;if(liveXml)files.set(file,liveXml);return {exitCode:0,stdout:'',stderr:''};}if(script.includes('原开启动作不重发')){events.push('bounded-start-observation');return {exitCode:0,stdout:'',stderr:''};}if(script.includes('UIAutomationClient')){events.push('status-readonly');assert.ok(!script.includes('.Invoke('));if(hooks.observeUnknown)return {exitCode:1,stdout:'',stderr:'UIA denied'};return {exitCode:0,stdout:JSON.stringify({title,button}),stderr:''};}throw Error('Unexpected actual shell operation');}}};
 const owner=load(source+'\nexport const unsafeImportForRegression=ensureLsProfileUnlocked;',{'./api':api,'./losslessProfiles':profiles,'./gamedetect':{}});
 return {owner,files,events,hooks,running:()=>running,observe:(t,b)=>{title=t;button=b;}};
}
const results=[];async function check(name,action){await action();results.push(name);console.log('PASS '+name);}
await check('baseline locked-file failure reproduced inside the exact unguarded original import body',async()=>{const f=fixture({running:true});await assert.rejects(f.owner.unsafeImportForRegression('D:\\Games\\c.exe'),/SHARING_VIOLATION/);assert.equal(f.files.get(file),xml);});
await check('fixed original import closes LS before fresh read/write and restores its app once',async()=>{const f=fixture({running:true});await f.owner.ensureLsProfile('D:\\Games\\c.exe');assert.equal(f.running(),true);assert.equal(f.events.filter(e=>e==='normal-close').length,1);assert.equal(f.events.filter(e=>e.startsWith('launch:')).length,1);assert.ok(f.events.indexOf('normal-close')<f.events.indexOf('write:'+file));const parsed=profiles.parseLsProfiles(f.files.get(file));assert.deepEqual(Array.from(parsed,p=>p.title),['A','B','c.exe']);assert.match(f.files.get(file),/<Unknown>retained<\/Unknown>/);});
await check('LS final in-memory save is read after normal close, not overwritten by the earlier snapshot',async()=>{const newer=xml.replace('retained','latest-live-save'),f=fixture({running:true,liveXml:newer});await f.owner.ensureLsProfile('D:\\Games\\c.exe');assert.match(f.files.get(file),/latest-live-save/);assert.equal(f.files.get(file+'.ymccbak'),newer);});
await check('closed LS import keeps it closed and does not launch an unrelated scaling session',async()=>{const f=fixture();await f.owner.ensureLsProfile('D:\\Games\\c.exe');assert.equal(f.running(),false);assert.equal(f.events.filter(e=>e==='normal-close'||e.startsWith('launch:')).length,0);});
await check('refused normal closure does not force-kill LS or touch either original file',async()=>{const f=fixture({running:true,closeDenied:true});await assert.rejects(f.owner.ensureLsProfile('D:\\Games\\c.exe'),/close to tray/);assert.equal(f.files.get(file),xml);assert.equal(f.files.has(file+'.ymccbak'),false);assert.equal(f.running(),true);});
await check('backup failure preserves main and restores the original LS app',async()=>{const f=fixture({running:true});f.hooks.backupDenied=true;await assert.rejects(f.owner.ensureLsProfile('D:\\Games\\c.exe'),/backup denied/);assert.equal(f.files.get(file),xml);assert.equal(f.running(),true);});
await check('a source change after backup is rejected before original-file replacement',async()=>{const f=fixture({running:true});f.hooks.sourceChange=true;await assert.rejects(f.owner.ensureLsProfile('D:\\Games\\c.exe'),/配置已变化/);assert.match(f.files.get(file),/external-update/);assert.ok(!f.events.includes('write:'+file));assert.equal(f.running(),true);});
await check('malformed XML fails before closing the live LS process or replacing its backup',async()=>{const f=fixture({running:true,xml:'<broken>'});f.files.set(file+'.ymccbak','known-good');await assert.rejects(f.owner.ensureLsProfile('D:\\Games\\c.exe'),/格式/);assert.deepEqual(f.events,[]);assert.equal(f.files.get(file+'.ymccbak'),'known-good');assert.equal(f.running(),true);});
await check('AutoScale true does not mean actual running/scaling when LS is closed',async()=>{const f=fixture();const state=await f.owner.getLosslessGameState('D:\\Games\\a.exe');assert.equal(state.profile.enabled,true);assert.equal(state.enabled,false);assert.equal(state.running,false);assert.deepEqual(f.events,[]);});
await check('readonly actual LS selected-profile and stop-button observation identifies this EXE only',async()=>{const f=fixture({running:true});f.observe('A','取消缩放');assert.equal((await f.owner.getLosslessGameState('D:\\Games\\a.exe')).enabled,true);assert.equal((await f.owner.getLosslessGameState('D:\\Games\\b.exe')).enabled,false);assert.ok(f.events.every(e=>e==='status-readonly'));});
await check('unreadable actual status is unknown and never fabricated as hardware off/on',async()=>{const f=fixture({running:true});f.hooks.observeUnknown=true;assert.equal((await f.owner.getLosslessGameState('D:\\Games\\a.exe')).enabled,null);});
await check('original on uses the existing -path/-auto launch route with no profile reset',async()=>{const f=fixture();const result=await f.owner.oneClickFrameGen('D:\\Games\\a.exe');assert.equal(result.alreadyHadProfile,true);assert.equal(f.files.get(file),xml);assert.match(f.events[0],/"-path","D:\\\\Games\\\\a\.exe","-auto"/);});
await check('shared original on confirms its read-only receipt after one launch, without replay or XML writes',async()=>{const f=fixture();const result=await f.owner.setLosslessScalingEnabled('D:\\Games\\a.exe',true);assert.equal(result.confirmed,true);assert.equal(f.events.filter(e=>e.startsWith('launch:')).length,1);assert.equal(f.files.get(file),xml);assert.ok(f.events.includes('bounded-start-observation'));});
await check('original launch refusal is visible rather than a false success',async()=>{const f=fixture();f.hooks.startDenied=true;await assert.rejects(f.owner.oneClickFrameGen('D:\\Games\\a.exe'),/启动请求失败/);});
await check('original off closes only the actual selected EXE session and writes no profiles',async()=>{const f=fixture({running:true});f.observe('A','取消缩放');const result=await f.owner.setLosslessScalingEnabled('D:\\Games\\a.exe',false);assert.equal(result.confirmed,true);assert.equal(f.running(),false);assert.equal(f.files.get(file),xml);assert.ok(!f.events.some(e=>e.startsWith('write:')));});
await check('original off refuses another EXE session and keeps LS running',async()=>{const f=fixture({running:true});f.observe('B','取消缩放');await assert.rejects(f.owner.stopLosslessScaling('D:\\Games\\a.exe'),/另一 EXE/);assert.equal(f.running(),true);assert.ok(!f.events.includes('normal-close'));});
await check('existing generated EXE list is required; missing match never creates a sidebar preset',async()=>{const f=fixture();const state=await f.owner.getLosslessGameState('D:\\Games\\missing.exe');assert.equal(state.profile,null);assert.equal(f.files.get(file),xml);assert.deepEqual(f.events,[]);});
await check('same-name matching is case-insensitive, exact-path first, and ambiguous duplicates fail closed',()=>{const list=profiles.parseLsProfiles(xml);assert.equal(profiles.matchLsProfile(list,'d:/games/A.EXE').title,'A');assert.equal(profiles.matchLsProfile(list,'Q:/Moved/a.exe').title,'A');const duplicate=profiles.parseLsProfiles(xml.replace('</GameProfiles>',profile('A2','Q:\\Other\\a.exe')+'</GameProfiles>'));assert.equal(profiles.matchLsProfile(duplicate,'D:/Games/a.exe').title,'A');assert.throws(()=>profiles.matchLsProfile(duplicate,'Z:/Other/a.exe'),/同名 EXE/);});
await check('mirror delegates only to shared original YMCC owner, and both original views use that same entry',async()=>{
 const game={pid:101,processCreated:'native-created',path:'D:\\Games\\a.exe'};let current=game,calls=0,released=0;
 const key={gameMirrorIdentity:g=>g?JSON.stringify(g):''},shared={getLosslessGameState:async()=>({xml,profile:{path:game.path},enabled:false}),setLosslessScalingEnabled:async(p,on,checkpoint)=>{checkpoint();assert.equal(p,game.path);assert.equal(on,true);calls++;return {confirmed:true,notice:'original-owner'};},onLosslessScalingChanged:()=>()=>{}};
 const adapter=load(fs.readFileSync(path.join(root,'src/bridge/losslessScaling.ts'),'utf8'),{'./api':{powerLifecycle:{get:async()=>({generation:1,phase:'ready',hardwareWritesAllowed:true})}},'./quickapp':shared,'./gamePolicyTarget':{getPolicyGame:()=>current},'./deckyGameActions':key,'./quickActionLock':{tryAcquireQuickAction:()=>()=>released++}});
 const context={gameIdentity:JSON.stringify(game),gameAdmission:{lossless:xml},generation:1,checkpoint:()=>{}};assert.equal((await adapter.setLosslessFromMirror({field:'losslessScaling',value:'on'},context)).applied,true);assert.equal(calls,1);assert.equal(released,1);
 current={...game,pid:102};await assert.rejects(adapter.setLosslessFromMirror({field:'losslessScaling',value:'on'},context),/UNCONFIRMED/);assert.equal(calls,1);
 const thin=fs.readFileSync(path.join(root,'src/bridge/losslessScaling.ts'),'utf8');for(const token of ['shell.run','shell.execute','writeTextFile','AutoScale>','UIAutomationClient','InvokePattern'])assert.ok(!thin.includes(token),token);
 for(const p of ['src/components/GameQuickActions.vue','src/views/QuickAppView.vue'])assert.ok(fs.readFileSync(path.join(root,p),'utf8').includes('setLosslessScalingEnabled'));
});
const scriptDir=path.join(task,'Build/LS-Owner-Scripts');fs.mkdirSync(scriptDir,{recursive:true});for(const [index,script] of [...observedScripts].entries())fs.writeFileSync(path.join(scriptDir,'ls-owner-'+index+'.ps1'),script);
// The user's two real imports are only read here. No applications or games are launched.
const actualPath=path.join(process.env.LOCALAPPDATA,'Lossless Scaling/Settings.xml'),bytes=fs.readFileSync(actualPath),hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const actual=profiles.parseLsProfiles(bytes.toString('utf8')),realGames=actual.filter(p=>p.path);
if(process.argv.includes('--require-two-real-exes')){assert.equal(realGames.length,2);for(const key of ['cyberpunk2077.exe','warno.exe'])assert.ok(realGames.some(p=>profiles.lsExeKey(p.path)===key));}assert.equal(hash(fs.readFileSync(actualPath)),hash(bytes));
const report={stage:'Mainline20',cases:results.length,results,exactOriginalOwnerExecuted:true,sideEffectBoundaries:'inert memory fs/process/shell; not live YMCC acceptance',realListReadOnly:{path:actualPath,sha256:hash(bytes),profiles:actual.length,exeEntries:realGames.map(p=>({title:p.title,path:p.path,autoScale:p.enabled}))},actualProductYmccExecuted:false,actualLSControlActions:0,realSettingsWrites:0,realGameLaunches:0};
fs.writeFileSync(path.join(task,'validation/MAINLINE20-LOSSLESS-OWNER.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
