// Real RTSS page, FPS component, Dropdown/Slider/Toggle/focus; native IO is memory-only.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createServer} from 'node:http';import {createHash} from 'node:crypto';
const root=process.cwd(),req=createRequire(path.join(root,'package.json'));
const {build}=req('esbuild'),{parse,compileScript,compileStyle}=req('vue/compiler-sfc');
const runtime='C:/Users/DaVe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=createRequire(path.join(runtime,'_monitor-steam.cjs'))('playwright');
const out=path.resolve(root,'../../Build/Validation/monitor-steam-settings-20261009/browser');fs.mkdirSync(out,{recursive:true});
const cases=[],images=[],errors=[],styles=[];
const rtss=fs.readFileSync('src/views/RtssView.vue','utf8'),schedule=fs.readFileSync('src/views/PerformanceScheduleView.vue','utf8'),router=fs.readFileSync('src/router.ts','utf8');
assert(!rtss.includes('title="FPS 锁帧"'));assert(!rtss.includes('RTSS 锁定帧率上限'));assert(schedule.includes('<RtssFrameLimit />'));assert(router.includes("name: 'rtss', title: '监控'"));
const mocks={
 '@/bridge/frameRateLimits':`import {frameRatePair,frameRateSetting} from './src/bridge/frameRateModel.ts';export {frameRatePair};const listeners=new Set();export async function loadGlobalFrameRates(){return frameRatePair(window.__fixture.frames)};export function onFrameRatesChanged(cb){listeners.add(cb);return ()=>listeners.delete(cb)};export async function saveGlobalFrameRate(side,value){const f=window.__fixture;f.frames[side]=frameRateSetting(value);f.fpsWrites.push({side,...f.frames[side]});for(const cb of listeners)cb(frameRatePair(f.frames));return frameRatePair(f.frames)};export async function applyIndependentFrameRates(){const f=window.__fixture;f.limit=f.frames.ac.fps;f.limitWrites.push(f.limit);return true;}`,
 '@/bridge/yeman':`const f=()=>window.__fixture;export const FPS_MIN=20,FPS_CEILINGS=[0,30,60,90,120,200,300],RTSS_ZOOM_MIN=1,RTSS_ZOOM_MAX=12,BOOT_RTSS_TASK='rtss',BOOT_MIRROR_CHANGED_EVENT='boot-mirror';
 export async function rtssRunning(){return f().rtss;}export async function monitorOn(){return f().monitor;}export async function toggleRtss(v){f().rtss=v;f().rtssWrites.push(v);}export async function readOverlayLayout(){return 'YeManOBS-W-1.ovl'};export async function setOverlayLayout(v){f().monitor=v!=='off';f().overlayWrites.push(v);return {mode:'live'}};export async function readRtssZoom(){return 5};export async function setRtssZoom(v){f().zoomWrites.push(v)};export async function readBootRtssState(){return false};export async function toggleBootRtss(v){return v};export async function taskExists(){return false};export async function toggleTask(n,v){return v};
 export async function readRtssLimit(){f().limitReads++;return f().limit};export async function setRtssLimit(v){f().limit=v;f().limitWrites.push(v)};export async function readFps(){return 120};export async function saveFps(mode,v){f().fpsWrites.push(v)};`,
 '@/bridge/gamedetect':`export async function detectGame(){return null};export function clearGameCache(){}`,
 '@/bridge/settingsRepository':`export async function readSettingsSection(){return {autoEnable:{mode:window.__fixture.autoMode}}}`,
 '@/bridge/uiLifecycle':`export function onUiVisibilityChange(){return ()=>{}}`,
 '@/bridge/ipc':`export function on(event,cb){const f=window.__fixture;(f.events[event]??=new Set()).add(cb);return ()=>f.events[event].delete(cb)};export async function invoke(command,args){const f=window.__fixture;f.calls.push({command,args});if(command==='steam.settings.get')return structuredClone(f.steam);if(command==='steam.settings.set'){if(f.fail)return {ok:false,available:true,pending:false,reason:'write-failed'};Object.assign(f.steam,args.monitor);f.steam.pending=f.defer;f.steam.restartRequired=f.defer;f.steam.via=f.defer?'deferred':'live';return structuredClone(f.steam)}throw Error(command)}`,
};
const result=await build({stdin:{resolveDir:root,loader:'ts',contents:`import {createApp,defineComponent,h,ref} from 'vue';import Monitor from './src/views/RtssView.vue';import Fps from './src/components/RtssFrameLimit.vue';
 window.__fixture={events:{},calls:[],rtss:true,monitor:true,limit:120,limitReads:0,frames:{ac:{fps:120,ceiling:120,lastFps:120},dc:{fps:60,ceiling:60,lastFps:60}},autoMode:'never',rtssWrites:[],overlayWrites:[],zoomWrites:[],limitWrites:[],fpsWrites:[],steam:{ok:true,available:true,pending:false,position:1,detail:1,scale:.8,saturation:1,opacity:1}};
 let app;window.__mount=()=>{app=createApp(defineComponent({setup(){return()=>h('div',{},[h(Monitor),h('div',{'class':'schedule-fixture'},[h('h2','性能调度'),h(Fps)])])}}));app.mount('#app')};window.__unmount=()=>app.unmount();window.__mount();`},bundle:true,write:false,format:'iife',platform:'browser',alias:{'@':path.join(root,'src')},define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'mock',setup(b){
 b.onResolve({filter:/.*/},args=>{if(args.path in mocks)return {path:args.path,namespace:'fixture'};if(args.path==='./ipc' && args.importer.endsWith('steamSettings.ts'))return {path:'@/bridge/ipc',namespace:'fixture'};});
 b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:mocks[args.path],loader:'ts',resolveDir:root}));
 b.onLoad({filter:/\.vue$/},args=>{const {descriptor,errors}=parse(fs.readFileSync(args.path,'utf8'),{filename:args.path});assert.deepEqual(errors,[]);const id='data-v-'+createHash('sha256').update(args.path).digest('hex').slice(0,8);const c=compileScript(descriptor,{id,inlineTemplate:true});for(const style of descriptor.styles){const css=compileStyle({source:style.content,filename:args.path,id,scoped:style.scoped});assert.deepEqual(css.errors,[]);styles.push(css.code);}return {contents:c.content.replace('export default','const _component=')+'\n_component.__scopeId='+JSON.stringify(id)+';export default _component;',loader:'ts',resolveDir:path.dirname(args.path)};});
}}]});
const css=fs.readFileSync('src/styles/tokens.css','utf8')+'\n'+styles.join('\n');
const html='<!doctype html><meta charset="utf-8"><style>'+css+'\nbody{margin:0;background:var(--bg-solid);font-family:system-ui;color:var(--text)}#app{max-width:720px;margin:auto;padding:14px;box-sizing:border-box}.card{background:var(--bg-panel);border:1px solid var(--border);border-radius:var(--radius);padding:12px 14px;margin-bottom:10px}.schedule-fixture h2{font-size:14px}</style><main id="app"></main><script src="/fixture.js"></script>';
const server=createServer((r,res)=>{res.setHeader('Content-Type',r.url==='/fixture.js'?'text/javascript':'text/html; charset=utf-8');res.end(r.url==='/fixture.js'?result.outputFiles[0].text:html)});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:720,height:1120}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 await page.waitForFunction(()=>document.querySelector('.steam-monitor .dd-trigger:not(:disabled)') && document.querySelector('.rtss-frame-limit input[type=range]'));
 assert.equal(await page.locator('.page .state-card').count(),0);assert.equal(await page.locator('.page .rtss-frame-limit').count(),0);
 assert.equal(await page.locator('.monitor-template-head .switch').count(),2);assert.equal(await page.locator('.steam-monitor input[type=range]').count(),3);
 assert.equal(await page.evaluate(()=>window.__fixture.calls.filter(x=>x.command.endsWith('.set')).length),0);assert.equal(await page.evaluate(()=>window.__fixture.limitWrites.length),0);
 cases.push('Monitor page removes old FPS state/limit bubble; two real switches align right of template; mount is read-only');
 const position=page.getByRole('button',{name:'Steam监控位置',exact:true}),detail=page.getByRole('button',{name:'性能详情等级',exact:true});
 await position.click();assert.deepEqual((await page.getByRole('option').allTextContents()).map(s=>s.trim()),['关闭监控','左上角','顶部居中','右上角','右下角','底部居中','左下角']);await page.getByRole('option',{name:'顶部居中',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));
 await page.waitForFunction(()=>window.__fixture.steam.position===5);assert.equal(await page.evaluate(()=>window.__fixture.calls.at(-1).args.monitor.position),5);
 await detail.click();assert.deepEqual((await page.getByRole('option').allTextContents()).map(s=>s.trim()),['FPS 单个值','FPS 详情','FPS详情、CPU及GPU利用率','FPS、CPU、GPU和RAM完整详情']);await page.getByRole('option',{name:'FPS、CPU、GPU和RAM完整详情',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));await page.waitForFunction(()=>window.__fixture.steam.detail===4);
 cases.push('Real YMCC dropdowns expose exactly seven native-position and four Steam-detail options with correct enum mapping');
 const sliders=page.locator('.steam-monitor input[type=range]');assert.deepEqual(await sliders.evaluateAll(nodes=>nodes.map(n=>[n.min,n.max,n.step])),[['20','140','10'],['0','100','10'],['0','100','10']]);
 await sliders.nth(0).focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>Math.abs(window.__fixture.steam.scale-.9)<1e-6);
 await sliders.nth(1).focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>Math.abs(window.__fixture.steam.saturation-.9)<1e-6);
 await sliders.nth(2).focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>Math.abs(window.__fixture.steam.opacity-.9)<1e-6);
 assert.deepEqual(await page.evaluate(()=>window.__fixture.calls.filter(x=>x.command==='steam.settings.set').slice(-3).map(x=>Object.keys(x.args.monitor))),[['scale'],['saturation'],['opacity']]);
 cases.push('All three sliders use Steam ranges/step and existing keyboard/gamepad increments; each commit only changes its own scalar');
 await position.locator('..').dispatchEvent('gp:dropdown-open');await page.waitForSelector('.dd-menu');assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('dd-option')),true);
 await position.locator('..').evaluate(n=>n.dispatchEvent(new CustomEvent('gp:dropdown-nav',{bubbles:true,cancelable:true,detail:{dir:1}})));await page.keyboard.press('Enter');await page.waitForFunction(()=>window.__fixture.steam.position===2);await page.waitForFunction(()=>!document.querySelector('.dd-menu'));

 await detail.locator('..').dispatchEvent('gp:dropdown-open');await page.waitForSelector('.dd-menu');await page.evaluate(()=>window.dispatchEvent(new Event('ipc:gamepad-back',{cancelable:true})));await page.waitForFunction(()=>!document.querySelector('.dd-menu'));
 assert.equal(await detail.evaluate(n=>document.activeElement===n),true);
 cases.push('Actual gamepad dropdown open/nav/confirm/back events work and return focus to original trigger');
 await page.locator('.monitor-template-switches .switch').nth(0).click();assert.deepEqual(await page.evaluate(()=>window.__fixture.rtssWrites),[false]);await page.locator('.monitor-template-switches .switch').nth(1).click();assert.deepEqual(await page.evaluate(()=>window.__fixture.overlayWrites),['off']);
 cases.push('Relocated RTSS/monitor switches invoke their original safe handlers, not new process or monitoring logic');
 await page.evaluate(()=>window.__fixture.defer=true);await position.click();await page.getByRole('option',{name:'左下角',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));await page.waitForFunction(()=>document.querySelector('.steam-monitor-status').textContent.includes('退出并重新开启 Steam'));
 cases.push('Deferred Steam writes explicitly show restart requirement without claiming live success');
 await page.evaluate(()=>{window.__fixture.fail=true;window.__fixture.defer=false});await detail.click();await page.getByRole('option',{name:'FPS 详情',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));await page.waitForFunction(()=>document.querySelector('.steam-monitor-status').textContent.includes('保存失败'));
 cases.push('Failed Steam write has visible failure feedback; reading/failed commits do not change unrelated settings');
 assert.equal(await page.locator('.rtss-frame-limit .switch').count(),0);
 const ac=page.getByRole('button',{name:'插电锁帧上限',exact:true}),dc=page.getByRole('button',{name:'电池锁帧上限',exact:true});
 await dc.click();await page.getByRole('option',{name:'不锁帧',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));
 await page.waitForFunction(()=>window.__fixture.frames.dc.fps===0);assert.equal(await page.evaluate(()=>window.__fixture.frames.ac.fps),120);
 await ac.click();await page.getByRole('option',{name:'不锁帧',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));
 await page.waitForFunction(()=>window.__fixture.frames.ac.fps===0);assert.equal(await page.locator('.rtss-frame-limit input[type=range]').count(),2);
 await ac.click();await page.getByRole('option',{name:'200 FPS',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));
 await page.waitForFunction(()=>window.__fixture.frames.ac.fps===120);const fpsInput=page.locator('.rtss-frame-limit input[type=range]').first();await fpsInput.focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>window.__fixture.limit<120);
 assert.equal(await page.evaluate(()=>window.__fixture.frames.dc.fps),0);
 cases.push('Independent AC/DC frame rows have no toggle; dropdown zero disables and nonzero re-enables only selected power side');
 await page.evaluate(()=>{window.__fixture.fail=false;window.__fixture.defer=false});await detail.click();await page.getByRole('option',{name:'FPS、CPU、GPU和RAM完整详情',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.dd-menu'));
 await page.locator('.monitor-template-switches .switch').nth(0).click();await page.locator('.monitor-template-switches .switch').nth(1).click();
 for(const width of [720,580,420]){await page.setViewportSize({width,height:1120});await page.waitForTimeout(80);
  const rects=await page.locator('.steam-monitor-selects .dd-trigger').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {y:r.y,h:r.height,w:r.width}}));assert(Math.abs(rects[0].y-rects[1].y)<1);assert(Math.abs(rects[0].h-rects[1].h)<1);assert(Math.abs(rects[0].w-rects[1].w)<1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const head=await page.locator('.monitor-template-head').evaluate(n=>{const t=n.querySelector('h3').getBoundingClientRect();return [...n.querySelectorAll('.switch')].map(s=>{const r=s.getBoundingClientRect();return Math.abs((r.y+r.height/2)-(t.y+t.height/2))})});assert(head.every(v=>v<1));
  cases.push('Dropdown/switch rows have matching horizontal alignment and no overflow at '+width+'px');const file=path.join(out,'monitor-steam-'+width+'.png');await page.screenshot({path:file,fullPage:true});images.push(file);
 }
 await page.evaluate(()=>window.__unmount());assert.equal(await page.evaluate(()=>Object.values(window.__fixture.events).reduce((n,set)=>n+set.size,0)),0);assert.deepEqual(errors,[]);
 cases.push('Unmount clears native subscriptions; no page errors or real settings/hardware touched');
 const report={suite:'Monitor/Steam UI browser',passed:cases.length,cases,images,pageErrors:errors,scope:'Actual production Vue components and controls; IPC/process/settings mocked; no Steam instance or user settings changed'};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){console.error('UI test error',error);if(browser){const pages=browser.contexts().flatMap(c=>c.pages());for(const page of pages){console.error(await page.evaluate(()=>({menus:[...document.querySelectorAll('.dd-menu')].map(n=>n.textContent),active:document.activeElement?.outerHTML,fixture:{calls:window.__fixture.calls,steam:window.__fixture.steam}})));await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});}}throw error;}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
