#ifdef YMCC_VENDOR_R15
static bool oemVendorTaskQuery(const std::wstring& name,OemVendorTaskFacts& facts){facts={};auto it=tasks.find(name);if(it==tasks.end())return true;if(it->second.deny){SetLastError(ERROR_ACCESS_DENIED);return false;}facts={true,it->second.enabled,it->second.running};return true;}
static bool oemVendorTaskSet(const std::wstring& name,bool enabled,bool stop,bool run){auto it=tasks.find(name);if(it==tasks.end()){SetLastError(ERROR_FILE_NOT_FOUND);return false;}auto& t=it->second;if(t.setFail){SetLastError(ERROR_ACCESS_DENIED);return false;}t.enabled=enabled;++taskMutations;if(stop&&!t.stuck)t.running=false;if(run){t.running=true;++taskStarts;}return true;}
static bool oemVendorProcessesStop(const std::vector<std::wstring>& names,unsigned long long epoch){++processCalls;if(processFail)return false;for(const auto& n:names)if(oemVendorStackIntentCurrent(epoch)&&std::find(processes.begin(),processes.end(),n)!=processes.end())stoppedProcesses.push_back(n);return true;}
#endif
static int cases=0,failed=0;
static void check(bool ok,const char* text){++cases;std::cout<<(ok?"PASS ":"FAIL ")<<text<<"\n";if(!ok)++failed;}
static bool state(const char* text){return std::any_of(logs.begin(),logs.end(),[&](const auto& x){return x.value("state","")==text;});}
static void reset(){services.clear();logs.clear();jobs.clear();journal.clear();tasks.clear();processes.clear();stoppedProcesses.clear();onPersist={};journalExists=false;journalFail=scmFail=queueFail=processFail=false;mutationCount=stops=starts=taskMutations=taskStarts=processCalls=0;g_exitRequested=false;tick=1;g_oemVendorServiceLeases.clear();g_oemVendorStackLoaded=false;g_oemVendorStackJournalValid=true;g_oemVendorStackWanted=false;g_oemVendorStackOpQueued=false;g_oemVendorStackRequested=1;g_oemVendorStackCompleted=0;g_machineIdentity.family=YmccFamily::AsusRogAlly;g_machineIdentity.deviceClass="HandheldCompanion.Devices.ROGAlly";SetLastError(0);
#ifdef YMCC_VENDOR_R15
 g_oemVendorTaskLeases.clear();g_oemVendorStackIntentSeen=false;g_oemVendorStackStartupRecovered=false;g_oemVendorStackIntentFamily=YmccFamily::Unknown;g_oemVendorStackAttempts=0;g_oemVendorStackRetryAt=0;
#endif
}
static void seed(){
 if(g_machineIdentity.family==YmccFamily::MsiClaw)g_machineIdentity.deviceClass="HandheldCompanion.Devices.ClawA1M";
 else if(g_machineIdentity.family==YmccFamily::LenovoLegionGo)g_machineIdentity.deviceClass="HandheldCompanion.Devices.LegionGoTablet";
 else if(g_machineIdentity.family==YmccFamily::ZotacGamingZone)g_machineIdentity.deviceClass="HandheldCompanion.Devices.GamingZone";
 for(const auto& n:oemVendorServiceNamesForFamily(g_machineIdentity.family))services[n]={};}
static void drain(){size_t n=0;while(!jobs.empty()&&++n<32){auto f=std::move(jobs.front());jobs.erase(jobs.begin());f();}check(n<32,"serial queue remains bounded");}
int main(){
 reset();seed();oemVendorStackRequest(true);drain();check(stops==3,"ROG all three HC services stopped");check(state("applied"),"aggregate service readback success");check(g_oemVendorServiceLeases.size()==3,"durable original service facts");
 oemVendorStackRequest(true);drain();check(starts==0,"unchanged takeover never briefly restarts Armoury Crate");check(stops==3,"unchanged takeover performs no redundant stop");oemVendorStackRestore("exit");check(starts==3&&g_oemVendorServiceLeases.empty(),"normal exit restores originals and clears debt");
 reset();seed();services.begin()->second.stopDelay=3000;oemVendorStackRequest(true);drain();check(state("applied"),"realistic 3-second service stop is not lost at old 2-second deadline");
 reset();seed();services.begin()->second.state=SERVICE_START_PENDING;services.begin()->second.settleAt=1001;oemVendorStackRequest(true);drain();check(stops==3&&state("applied"),"START_PENDING stabilizes before takeover instead of permanent skip");
 reset();seed();services.begin()->second.stopFail=true;oemVendorStackRequest(true);drain();check(!state("applied")&&state("apply-failed"),"failed stop never claims applied");check(g_oemVendorServiceLeases.size()==3,"failed stop retains original fact");services.begin()->second.stopFail=false;tick+=1000;oemVendorStackSchedule();drain();check(state("applied"),"transient failed stop retried on existing refresh");check(starts==0,"retry does not restore/restart already acquired services");
 reset();seed();services.begin()->second.stuck=true;oemVendorStackRequest(true);drain();check(!state("applied"),"stuck service never claims suppression");check(tick<=10051,"service wait remains bounded at ten seconds");
 reset();seed();journalFail=true;oemVendorStackRequest(true);drain();check(mutationCount==0&&stops==0,"write-ahead lease failure prevents all SCM mutations");
 reset();seed();services.begin()->second.deny=true;oemVendorStackRequest(true);drain();check(!state("applied"),"unreadable service forbids aggregate success");
 reset();seed();services.begin()->second.state=SERVICE_STOPPED;oemVendorStackRequest(true);drain();oemVendorStackRestore("exit");check(starts==2,"original stopped service is never newly started");
 reset();seed();services.begin()->second.type=SERVICE_DISABLED;services.begin()->second.state=SERVICE_STOPPED;oemVendorStackRequest(true);drain();check(stops==2&&mutationCount==2,"already-disabled/stopped service receives no mutation and no invented lease");oemVendorStackRestore("exit");check(services.begin()->second.type==SERVICE_DISABLED&&services.begin()->second.state==SERVICE_STOPPED,"pre-existing disabled policy survives restoration");
 reset();seed();services.begin()->second.type=SERVICE_DISABLED;oemVendorStackRequest(true);drain();check(stops==2&&!state("applied"),"disabled-but-running unqualified original remains explicit hold");
 reset();seed();oemVendorStackRequest(true);drain();services.begin()->second.configFail=true;oemVendorStackRestore("exit");check(g_oemVendorServiceLeases.size()==1,"restore failure retains debt");check(json::parse(journal)["services"].size()==1,"restore failure remains durable");services.begin()->second.configFail=false;oemVendorStackRestore("retry");check(g_oemVendorServiceLeases.empty(),"later recovery discharges failed restoration");
 reset();seed();oemVendorStackRequest(true);drain();services.begin()->second.type=SERVICE_DEMAND_START;oemVendorStackRestore("exit");check(services.begin()->second.type==SERVICE_DEMAND_START&&!g_oemVendorServiceLeases.empty(),"third-party start policy is not overwritten");
 reset();seed();oemVendorStackRequest(true);drain();journalFail=true;oemVendorStackRestore("exit");check(g_oemVendorServiceLeases.size()==3,"failed journal commit cannot erase in-memory recovery debt");journalFail=false;oemVendorStackRestore("retry");check(g_oemVendorServiceLeases.empty(),"recovery debt commits on later successful write");
 reset();seed();journalExists=true;journal="{broken";oemVendorStackRequest(true);drain();check(stops==0&&state("recovery-held"),"corrupt journal holds all writes");
 reset();seed();journalExists=true;journal=json({{"schema",1},{"family",static_cast<int>(g_machineIdentity.family)},{"services",json::array({{{"name","UnrelatedService"},{"originalStartType",2},{"wasRunning",true}}})}}).dump();oemVendorStackRequest(true);drain();check(mutationCount==0&&state("recovery-held"),"unbound service in recovery journal rejected");
 reset();seed();queueFail=true;oemVendorStackRequest(true);check(jobs.empty()&&!g_oemVendorStackOpQueued,"queue refusal releases publication ownership");queueFail=false;oemVendorStackSchedule();drain();check(stops==3,"rejected publication can use existing refresh retry");
 reset();seed();oemVendorStackRequest(true);g_exitRequested=true;drain();check(mutationCount==0,"queued job after exit never disables");
 reset();seed();oemVendorStackRequest(true);oemVendorStackRequest(false);drain();check(mutationCount==0,"latest rule clear beats queued takeover");
 reset();seed();oemVendorStackRequest(true);drain();oemVendorStackRequest(false);drain();check(starts==3&&g_oemVendorServiceLeases.empty(),"cleared or disabled executable rules return manufacturer control");
 reset();seed();onPersist=[]{oemVendorStackRequest(false);};oemVendorStackRequest(true);drain();check(stops==0,"rule clear during durable write fences remaining stop operations");
 reset();seed();scmFail=true;oemVendorStackRequest(true);drain();check(!state("applied")&&state("apply-failed"),"SCM access failure remains observable");
 reset();g_machineIdentity.family=YmccFamily::Gpd;oemVendorStackRequest(true);drain();check(stops==0,"no services inferred for generic GPD family");
#ifdef YMCC_VENDOR_R15
 reset();seed();g_machineIdentity.deviceClass="HandheldCompanion.Devices.AsusDevice";oemVendorStackRequest(true);drain();check(stops==0&&mutationCount==0,"generic ASUS fallback cannot acquire ROG manufacturer services");
 reset();seed();services.begin()->second.state=SERVICE_PAUSED;oemVendorStackRequest(true);drain();check(state("applied"),"paused service can be stopped under its durable original-state lease");oemVendorStackRestore("exit");check(services.begin()->second.state==SERVICE_PAUSED,"original paused service is restored to Paused not silently promoted to Running");
 reset();seed();services.begin()->second.stopFail=true;oemVendorStackRequest(true);drain();for(int i=0;i<6;++i){tick+=30000;oemVendorStackSchedule();drain();}check(state("retry-exhausted")&&g_oemVendorStackAttempts==3,"per-intent retry budget exhausts with failure not success");const int oldStops=stops;tick+=30000;oemVendorStackRequest(true);drain();check(stops==oldStops,"unchanged failed intent does not become a permanent poller");
 reset();seed();oemVendorStackRequest(true);drain();auto& s=services.begin()->second;s.type=SERVICE_DEMAND_START;s.stopFail=true;g_oemVendorStackCompleted=0;oemVendorStackSchedule();drain();check(s.type==SERVICE_DEMAND_START,"retry respects externally changed start policy");
 reset();seed();oemVendorStackRequest(true);drain();auto oldJournal=json::parse(journal);oldJournal["schema"]=1;oldJournal.erase("tasks");journal=oldJournal.dump();g_oemVendorServiceLeases.clear();g_oemVendorStackLoaded=false;check(oemVendorStackRestoreLocked("schema1-recovery"),"R13 schema1 service journal remains recoverable");
 for(const auto fam:{YmccFamily::LenovoLegionGo,YmccFamily::MsiClaw,YmccFamily::ZotacGamingZone}){
  reset();g_machineIdentity.family=fam;seed();for(const auto& n:oemVendorTaskNamesForFamily(fam))tasks[n]={};processes=oemVendorProcessNamesForFamily(fam);processes.push_back(L"UnrelatedProcess");oemVendorStackRequest(true);drain();check(state("applied"),"HC manufacturer stack service/task/process paths all admitted");check(stoppedProcesses.size()==oemVendorProcessNamesForFamily(fam).size(),"only exact HC process allowlist stopped in memory boundary");for(const auto& [n,t]:tasks)check(!t.enabled&&!t.running,"MSI scheduled task disabled and terminal");oemVendorStackRequest(false);drain();check(g_oemVendorServiceLeases.empty()&&g_oemVendorTaskLeases.empty(),"family restore commits all service/task debt");for(const auto& [n,t]:tasks)check(t.enabled&&t.running,"MSI original enabled/running task restored");
 }
 reset();g_machineIdentity.family=YmccFamily::MsiClaw;seed();tasks[L"MSI_Center_M_Server"]={false,false};oemVendorStackRequest(true);drain();check(taskMutations==0&&g_oemVendorTaskLeases.empty(),"pre-disabled task is not owned or modified");oemVendorStackRestore("exit");check(!tasks.begin()->second.enabled&&taskStarts==0,"pre-disabled task not enabled or started on return");
 reset();g_machineIdentity.family=YmccFamily::MsiClaw;seed();tasks[L"MSI_Center_M_Server"]={};journalFail=true;oemVendorStackRequest(true);drain();check(taskMutations==0&&mutationCount==0&&stoppedProcesses.empty(),"task write-ahead failure blocks every mutation");
 reset();g_machineIdentity.family=YmccFamily::MsiClaw;seed();tasks[L"MSI_Center_M_Server"]={};tasks.begin()->second.stuck=true;oemVendorStackRequest(true);drain();check(!state("applied")&&state("task-disable-failed"),"task stop without terminal state cannot claim success");
 reset();g_machineIdentity.family=YmccFamily::MsiClaw;seed();tasks[L"MSI_Center_M_Server"]={};oemVendorStackRequest(true);drain();tasks.begin()->second.setFail=true;oemVendorStackRestore("exit");check(g_oemVendorTaskLeases.size()==1,"failed task restoration remains debt");
 reset();g_machineIdentity.family=YmccFamily::MsiClaw;seed();tasks[L"MSI_Center_M_Server"]={};tasks.begin()->second.deny=true;oemVendorStackRequest(true);drain();check(!state("applied"),"task access denied is not capability absence");
 reset();g_machineIdentity.family=YmccFamily::LenovoLegionGo;seed();processFail=true;oemVendorStackRequest(true);drain();check(!state("applied"),"failed manufacturer-process stop blocks aggregate success");
 reset();seed();check(oemVendorTaskNamesForFamily(g_machineIdentity.family).empty()&&oemVendorProcessNamesForFamily(g_machineIdentity.family).empty(),"no ROG task/process names guessed beyond HC source");
 reset();g_machineIdentity.family=YmccFamily::MsiClaw;seed();journalExists=true;journal=json({{"schema",2},{"family",static_cast<int>(g_machineIdentity.family)},{"services",json::array()},{"tasks",json::array({{{"name","ArbitraryTask"},{"wasEnabled",true},{"wasRunning",true}}})}}).dump();oemVendorStackRequest(true);drain();check(taskMutations==0&&mutationCount==0&&state("recovery-held"),"foreign task journal cannot direct arbitrary TaskScheduler writes");
#endif
 std::cout<<"cases="<<cases<<" failures="<<failed<<" hardwareCalls=0 RESULT="<<(failed?"FAIL":"PASS")<<"\n";return failed?1:0;
}
