import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const header=process.env.YMCC_VENDOR_PROCESS_HEADER || path.join(root,'native/oem_vendor_stack.h');
const source=fs.readFileSync(header,'utf8');
const start=source.indexOf('static bool oemVendorProcessMatches(');
const end=source.indexOf('\n#else',start);
assert(start>=0&&end>start,'Production process methods must exist');
const block=source.slice(start,end);
const out=path.resolve(process.env.YMCC_VENDOR_PROCESS_OUT || path.join(root,'../../Build/Validation/oem-vendor-process'));
fs.mkdirSync(out,{recursive:true});
const fixture=fs.readFileSync(path.join(root,'tools/oem_vendor_process_selftest.cpp'),'utf8').replace('/* PRODUCTION_PROCESS_METHODS */',block);
const cpp=path.join(out,'vendor-process.fixture.cpp'),exe=path.join(out,'vendor-process.fixture.exe'),batch=path.join(out,'compile.cmd');
fs.writeFileSync(cpp,fixture);
fs.writeFileSync(batch,'@echo off\r\ncall "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat" >nul\r\ncl /nologo /std:c++20 /utf-8 /EHsc /MT /O2 /I"'+path.join(root,'deps/json')+'" "'+cpp+'" /Fo"'+path.join(out,'fixture.obj')+'" /Fe"'+exe+'"\r\nexit /b %errorlevel%\r\n');
const build=spawnSync('cmd.exe',['/d','/c',batch],{cwd:out,encoding:'utf8'});
fs.writeFileSync(path.join(out,'build.log'),(build.stdout||'')+(build.stderr||''));assert.equal(build.status,0,'Production process fixture must compile');
const run=spawnSync(exe,[],{cwd:out,encoding:'utf8'});
const output=(run.stdout||'')+(run.stderr||'');fs.writeFileSync(path.join(out,'results.txt'),output);process.stdout.write(output);
fs.writeFileSync(path.join(out,'source-binding.json'),JSON.stringify({header,headerSha256:createHash('sha256').update(source).digest('hex'),productionMethodsSha256:createHash('sha256').update(block).digest('hex'),fixtureSha256:createHash('sha256').update(fixture).digest('hex'),memoryWin32Boundaries:true,liveMutations:0,exitCode:run.status},null,2)+'\n');
assert.equal(run.status,0,'Vendor process regression');
