// Real api.ts + ipc.ts + repository startup boundary. All native requests are
// denied except memory-only settings/FS fixtures; no product/hardware is started.
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const root=process.cwd(),require=createRequire(path.join(root,'package.json')),{build}=require('esbuild');
const compiled=await build({stdin:{contents:`export * as repo from './src/bridge/settingsRepository';export { StartupWorkBarrier } from './src/robust/startupReadiness';`,resolveDir:root,loader:'ts'},bundle:true,write:false,format:'cjs',platform:'browser',define:{'process.env.NODE_ENV':'"production"'}});
const key=p=>String(p).replaceAll('/','\\').replace(/\\+$/,'').toLowerCase();
async function fixture(dir='G:\\fixture-override\\PowerControl'){
 const fx={dir,file:dir+'\\yeman-settings.json',calls:[],files:new Map(),locationHook:null,readFailure:false,writes:[],renames:[]};let receiver;
 const reply=(id,value,error)=>receiver({data:error?{id,error:String(error.message||error)}:{id,result:value}});
 const webview={addEventListener(type,fn){assert.equal(type,'message');receiver=fn},postMessage(message){fx.calls.push(message);queueMicrotask(async()=>{try{const{cmd,args,id}=message;let value;if(cmd==='settings.location')value=fx.locationHook?await fx.locationHook():{directory:fx.dir,file:fx.file,backup:fx.file+'.bak'};else if(cmd==='settings.read'||cmd==='settings.write'){if(key(args.path)!==key(fx.file))throw Error('Invalid unified settings path');if(cmd==='settings.read'){if(fx.readFailure)throw Error('fixture read I/O failure');const raw=fx.files.get(key(args.path));value={stamp:raw===undefined?'missing':raw,unchanged:raw!==undefined&&raw===args.stamp,content:raw??''}}else{const raw=args.content;fx.files.set(key(args.path),raw);fx.writes.push(args);value=args.baseline?{ok:true,content:raw}:true}}else if(cmd==='fs.rename'){const from=key(args.from??args.src),to=key(args.to??args.dst);if(!fx.files.has(from))throw Error('rename source missing');fx.files.set(to,fx.files.get(from));fx.files.delete(from);fx.renames.push(args);value=true}else if(cmd==='fs.exists')value=fx.files.has(key(args.path));else if(cmd==='fs.readTextFile'){if(!fx.files.has(key(args.path)))throw Error('missing fixture');value=fx.files.get(key(args.path))}else throw Error('Forbidden native request '+cmd);reply(id,value)}catch(e){reply(message.id,null,e)}})}};
 const module={exports:{}},context={module,exports:module.exports,console,setTimeout,clearTimeout,queueMicrotask,structuredClone,TextEncoder,TextDecoder,window:{chrome:{webview},dispatchEvent(){return true},addEventListener(){},removeEventListener(){}},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init?.detail}},document:{},process:{env:{NODE_ENV:'production'}}};
 vm.runInNewContext(compiled.outputFiles[0].text,context,{filename:'actual-settings-ipc-startup.cjs'});
 const repo=module.exports.repo,initial=repo.normalizeSettings({tdp:{tdpMax:37},performanceSchedule:{enabled:false},input:{revision:12},future:{preserve:true}});fx.files.set(key(fx.file),JSON.stringify(initial));return{fx,repo,initial,Barrier:module.exports.StartupWorkBarrier};
}
const cases=[];async function check(name,fn){try{await fn();cases.push({name,ok:true});console.log('PASS '+name)}catch(e){cases.push({name,ok:false,error:e.message});console.log('FAIL '+name+': '+e.message)}}
const ticks=async()=>{for(let i=0;i<15;i++)await Promise.resolve()};
await check('native override startup resolves real wire location before schedule readiness',async()=>{const f=await fixture();const barrier=new f.Barrier();await barrier.track(()=>f.repo.readSettingsSection('performanceSchedule'));assert.equal(await barrier.settle(),true);assert.equal(key(f.repo.SETTINGS_FILE),key(f.fx.file));assert.equal(f.fx.calls[0].cmd,'settings.location');assert.equal(f.fx.writes.length,0);assert(!f.fx.calls.some(c=>c.args.path?.startsWith('C:\\SOFT')))});
await check('default installed directory still loads without rewriting healthy settings',async()=>{const f=await fixture('C:\\SOFT\\YeMan\\PowerControl');assert.equal((await f.repo.loadSettings()).tdp.tdpMax,37);assert.equal(f.fx.calls[0].cmd,'settings.location');assert.equal(f.fx.writes.length,0)});
await check('first queued save uses discovered directory, not submission-time default alias',async()=>{const f=await fixture();await f.repo.saveSettingsSection('ui',{theme:'red-black'});assert.equal(key(f.fx.writes[0].path),key(f.fx.file));assert.equal(JSON.parse(f.fx.files.get(key(f.fx.file))).tdp.tdpMax,37);assert.equal(JSON.parse(f.fx.files.get(key(f.fx.file))).future.preserve,true)});
await check('initial shared CAS uses canonical directory before raw disk revision read',async()=>{const f=await fixture();const input=f.initial.input;const result=await f.repo.compareAndSwapInputSettings(input.revision,{...input,revision:input.revision+1});assert.equal(result.ok,true);assert(f.fx.calls.filter(c=>c.cmd==='fs.readTextFile').every(c=>key(c.args.path)===key(f.fx.file)))});
await check('failed location discovery does not read/write defaults and can retry',async()=>{const f=await fixture();let n=0;f.fx.locationHook=()=>{if(++n===1)throw Error('location I/O unavailable');return{directory:f.fx.dir,file:f.fx.file}};await assert.rejects(f.repo.loadSettings(),/location I\/O/);assert(f.fx.calls.every(c=>c.cmd==='settings.location'));assert.equal((await f.repo.loadSettings()).tdp.tdpMax,37);assert.equal(n,2)});
await check('malformed or mismatched native location blocks file access',async()=>{for(const value of [{directory:'relative',file:'relative\\yeman-settings.json'},{directory:'G:\\allowed',file:'G:\\other\\yeman-settings.json'}]){const f=await fixture();f.fx.locationHook=()=>value;await assert.rejects(f.repo.loadSettings(),/配置位置|settings location/i);assert(f.fx.calls.every(c=>c.cmd==='settings.location'))}});
await check('coalesced cold readers share discovery but own independent snapshots',async()=>{const f=await fixture();const[a,b]=await Promise.all([f.repo.loadSettings(),f.repo.loadSettings()]);a.tdp.tdpMax=199;assert.equal(b.tdp.tdpMax,37);assert.equal(f.fx.calls.filter(c=>c.cmd==='settings.location').length,1)});
await check('explicit directory switch cancels late initial discovery',async()=>{const f=await fixture();let release;const original={directory:f.fx.dir,file:f.fx.file};f.fx.locationHook=()=>new Promise(r=>{release=r});const p=f.repo.loadSettings();await ticks();assert.equal(typeof release,'function');f.repo.setSettingsDirectory('Q:\\manual-fixture');f.fx.dir='Q:\\manual-fixture';f.fx.file=f.fx.dir+'\\yeman-settings.json';f.fx.files.set(key(f.fx.file),JSON.stringify(f.initial));release(original);await assert.rejects(p,/目录已切换|旧请求已取消/);assert.equal((await f.repo.loadSettings()).tdp.tdpMax,37);assert.equal(key(f.repo.SETTINGS_FILE),key(f.fx.file))});
await check('post-discovery file I/O failure never falls back to a different root',async()=>{const f=await fixture();f.fx.readFailure=true;await assert.rejects(f.repo.loadSettings(),/I\/O/);assert.equal(f.fx.writes.length,0);f.fx.readFailure=false;assert.equal((await f.repo.loadSettings()).tdp.tdpMax,37);assert.equal(f.fx.calls.filter(c=>c.cmd==='settings.location').length,1)});
await check('initial discovery keeps queued module generation valid',async()=>{const f=await fixture();const generation=f.repo.getSettingsGeneration();await f.repo.saveSettingsSection('sleep',{keep:true},generation);assert.equal(f.repo.getSettingsGeneration(),generation);assert.equal(f.fx.writes.length,1)});
await check('replacement and mutator queues both bind canonical path before first write',async()=>{for(const op of ['replace','update']){const f=await fixture();if(op==='replace')await f.repo.replaceSettingsSection('sleep',{onlyOwned:true});else await f.repo.updateSettings(s=>{s.sleep.onlyOwned=true});assert.equal(key(f.fx.writes[0].path),key(f.fx.file))}});
await check('explicit isolated adapters never discover or overwrite native directory',async()=>{const f=await fixture();f.repo.setSettingsDirectory(f.fx.dir);await f.repo.loadSettings();assert.equal(f.fx.calls.filter(c=>c.cmd==='settings.location').length,0)});
await check('legacy schema 0 migrates without losing unrelated/protected settings',async()=>{const f=await fixture();const old={...f.initial,schemaVersion:0};f.fx.files.set(key(f.fx.file),JSON.stringify(old));const loaded=await f.repo.loadSettings();assert.equal(loaded.schemaVersion,1);assert.equal(loaded.future.preserve,true);assert.equal(loaded.input.revision,12);assert.equal(f.fx.writes.length,1)});
await check('unsupported schema is retained and never silently downgraded or cleared',async()=>{const f=await fixture();const raw=JSON.stringify({...f.initial,schemaVersion:99});f.fx.files.set(key(f.fx.file),raw);await assert.rejects(f.repo.loadSettings(),/配置版本 99/);assert.equal(f.fx.writes.length,0);assert.equal(f.fx.files.get(key(f.fx.file)),raw)});

await check('existing corrupt or empty main without a valid backup requires explicit recovery',async()=>{for(const raw of ['{broken','', '[]']){const f=await fixture();f.fx.files.set(key(f.fx.file),raw);await assert.rejects(f.repo.loadSettings(),/损坏|无法解析/);assert.equal(f.fx.writes.length,0);assert.equal(f.fx.renames.length,0);assert.equal(f.fx.files.get(key(f.fx.file)),raw)}});
await check('both corrupt files remain byte-identical until user explicitly recovers',async()=>{const f=await fixture();f.fx.files.set(key(f.fx.file),'{broken-main');f.fx.files.set(key(f.fx.file+'.bak'),'{broken-backup');await assert.rejects(f.repo.loadSettings(),/损坏|无法解析/);assert.equal(f.fx.writes.length,0);assert.equal(f.fx.renames.length,0);assert.equal(f.fx.files.get(key(f.fx.file+'.bak')),'{broken-backup')});
await check('unsupported backup schema is not used or archived even if main is corrupt',async()=>{const f=await fixture();f.fx.files.set(key(f.fx.file),'{broken-main');const raw=JSON.stringify({...f.initial,schemaVersion:99});f.fx.files.set(key(f.fx.file+'.bak'),raw);await assert.rejects(f.repo.loadSettings(),/配置版本 99/);assert.equal(f.fx.writes.length,0);assert.equal(f.fx.renames.length,0);assert.equal(f.fx.files.get(key(f.fx.file)),'{broken-main');assert.equal(f.fx.files.get(key(f.fx.file+'.bak')),raw)});
await check('missing main does not erase an existing invalid backup',async()=>{const f=await fixture();f.fx.files.delete(key(f.fx.file));f.fx.files.set(key(f.fx.file+'.bak'),'{broken-backup');await assert.rejects(f.repo.loadSettings(),/损坏|无法解析/);assert.equal(f.fx.writes.length,0);assert.equal(f.fx.renames.length,0);assert.equal(f.fx.files.get(key(f.fx.file+'.bak')),'{broken-backup')});
await check('genuine first-run absence can still initialize defaults automatically',async()=>{const f=await fixture();f.fx.files.clear();const loaded=await f.repo.loadSettings();assert.equal(loaded.schemaVersion,1);assert.equal(f.fx.writes.length,1);assert.equal(key(f.fx.writes[0].path),key(f.fx.file));assert.equal(f.fx.renames.length,0)});
await check('compatible backup can restore protected and unknown data while archiving corrupt main',async()=>{const f=await fixture();f.fx.files.set(key(f.fx.file),'{broken-main');const raw=JSON.stringify(f.initial);f.fx.files.set(key(f.fx.file+'.bak'),raw);const loaded=await f.repo.loadSettings();assert.equal(loaded.tdp.tdpMax,37);assert.equal(loaded.input.revision,12);assert.equal(loaded.future.preserve,true);assert.equal(f.fx.writes.length,1);assert.equal(f.fx.renames.length,1);assert([...f.fx.files.values()].includes('{broken-main'));assert.equal(f.fx.files.get(key(f.fx.file+'.bak')),raw)});
await check('unknown non-numeric or fractional schema is not silently downgraded',async()=>{for(const schemaVersion of ['future',1.5,-1]){const f=await fixture();const raw=JSON.stringify({...f.initial,schemaVersion});f.fx.files.set(key(f.fx.file),raw);await assert.rejects(f.repo.loadSettings(),/配置版本/);assert.equal(f.fx.writes.length,0);assert.equal(f.fx.files.get(key(f.fx.file)),raw)}});
await check('shared CAS refuses an unsupported root schema rather than bypassing startup guard',async()=>{const f=await fixture();const raw=JSON.stringify({...f.initial,schemaVersion:99});f.fx.files.set(key(f.fx.file),raw);await assert.rejects(f.repo.compareAndSwapInputSettings(f.initial.input.revision,f.initial.input),/配置版本 99/);assert.equal(f.fx.writes.length,0);assert.equal(f.fx.files.get(key(f.fx.file)),raw)});
const report={passed:cases.filter(c=>c.ok).length,failed:cases.filter(c=>!c.ok).length,cases,apiAndIpcMocked:false,nativeServicesMemoryOnly:true,realSettingsWritten:false,hardwareOperations:false};console.log(JSON.stringify(report,null,2));if(process.env.YMCC_STARTUP_PATH_REPORT)fs.writeFileSync(process.env.YMCC_STARTUP_PATH_REPORT,JSON.stringify(report,null,2)+'\n');if(report.failed)process.exitCode=1;
