<#
.SYNOPSIS
  Real-machine acceptance probe for the HC sleep/wake four-domain parity
  (GYRO DATA LINKAGE / SLEEP / GYRO WAKE / CONTROLLER WAKE).

  Run AFTER deploying the YeManCC build to C:\SOFT\YeMan\YeManCC. The probe
  is read-only: it inspects the native lifecycle logs generated by the app.

  Evidence sources:
    - %LOCALAPPDATA%\YeManCC\input-capture.jsonl  (sensor-suspend / sensor-resume / sample)
    - C:\SOFT\YeMan\PowerControl\Sleep\sleep-facts.log (power/lifecycle transaction facts)
    - %LOCALAPPDATA%\YeManCC\native-lifecycle.log (resume-ready / power.resumed)

  Forward/reverse checks written per gap (G1 long-sleep 3s grace, G3 joystick
  wake re-sleep, sensor chain across wake, controller-wake classification).
  Exit 0 = all evidence found; exit 1 = at least one check failed/missing.
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $false)][string]$LocalAppData = (Join-Path $env:LOCALAPPDATA 'YeManCC'),
  [Parameter(Mandatory = $false)][string]$SleepDir = 'C:\SOFT\YeMan\PowerControl\Sleep',
  [Parameter(Mandatory = $true)][ValidateSet('sleep-short', 'sleep-long', 'controller-wake',
      'sensor-chain', 'all')][string]$Probe
)

$ErrorActionPreference = 'Stop'
$InputCapture = Join-Path $LocalAppData 'input-capture.jsonl'
$FactsLog = Join-Path $SleepDir 'sleep-facts.log'
$LifecycleLog = Join-Path $LocalAppData 'native-lifecycle.log'

$files = @{ InputCapture = $InputCapture; FactsLog = $FactsLog; LifecycleLog = $LifecycleLog }
foreach ($entry in $files.GetEnumerator()) {
  if (!(Test-Path -LiteralPath $entry.Value -PathType Leaf)) {
    Write-Warning "Missing evidence file: $($entry.Key) -> $($entry.Value)"
  }
}

$results = [System.Collections.Generic.List[string]]::new()
function Record([string]$check, [bool]$ok, [string]$detail) {
  $results.Add(($(if ($ok) { 'PASS' } else { 'FAIL' }) + " | $check | $detail"))
  if (!$ok) { Write-Warning "FAIL: $check | $detail" }
}

# ── G1 reverse guard: short sleep must NOT show long-sleep grace ──────────
if ($Probe -in @('sleep-short', 'all') -and (Test-Path -LiteralPath $FactsLog)) {
  $facts = Get-Content -LiteralPath $FactsLog -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
  $grace = ([regex]::Matches($facts, '"event"\s*:\s*"long-sleep-resume-grace"')).Count
  Record 'G1 short-sleep no-grace' ($grace -eq 0) "long-sleep-resume-grace occurrences left over: $grace (should be 0 for a short sleep)"
}

# ── G1 forward: long sleep (>=30min) MUST produce one grace receipt ───────
if ($Probe -in @('sleep-long', 'all') -and (Test-Path -LiteralPath $FactsLog)) {
  $facts = Get-Content -LiteralPath $FactsLog -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
  $m = [regex]::Match($facts, '"event"\s*:\s*"long-sleep-resume-grace"[^}]*"generation"\s*:\s*(\d+)')
  Record 'G1 long-sleep grace receipt' $m.Success 'expected one long-sleep-resume-grace fact with generation'
  if ($m.Success) {
    $gen = $m.Groups[1].Value
    $graceMs = [regex]::Match($facts, '"event"\s*:\s*"long-sleep-resume-grace"[^}]*"delayMs"\s*:\s*(\d+)')
    Record 'G1 delay 3000ms' ($graceMs.Success -and $graceMs.Groups[1].Value -eq '3000') "delayMs matched: $($graceMs.Groups[1].Value)"
    Record 'G1 once-per-generation' (([regex]::Matches($facts, '"event"\s*:\s*"long-sleep-resume-grace"[^}]*"generation"\s*:\s*' + $gen)).Count -eq 1) "grace per generation $gen"
  }
}

# ── G3 controller-wake classification: 507 Reason=7 must be recorded ──────
if ($Probe -in @('controller-wake', 'all') -and (Test-Path -LiteralPath $FactsLog)) {
  $facts = Get-Content -LiteralPath $FactsLog -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
  $s0 = [regex]::Match($facts, '"event"\s*:\s*"s0-wake-message"[^}]*"reason"\s*:\s*(\d+)')
  Record 'G3 s0-wake-message present' $s0.Success 's0-wake-message fact with reason'
  if ($s0.Success) {
    $reason = $s0.Groups[1].Value
    Record 'G3 reason=7 joystick' ($reason -eq '7') "s0 wake reason recorded: $reason (expected 7 for controller wake)"
  }
  $joystick = [regex]::Match($facts, '"event"\s*:\s*"external-device-wake-evaluated"[^}]*"resleepEnabled"\s*:\s*(true|false)')
  Record 'G3 resleep evaluation occurred' $joystick.Success 'external-device-wake-evaluated fact'
}

# ── Sensor chain across wake: suspend before resume, samples after resume ──
if ($Probe -in @('sensor-chain', 'all') -and (Test-Path -LiteralPath $InputCapture)) {
  $recs = Get-Content -LiteralPath $InputCapture -Encoding UTF8 -ErrorAction SilentlyContinue |
    ForEach-Object { try { $_ | ConvertFrom-Json } catch { $null } }
  $sus = @($recs | Where-Object { $_.kind -eq 'sensor-suspend' })
  $res = @($recs | Where-Object { $_.kind -eq 'sensor-resume' })
  $samples = @($recs | Where-Object { $_.kind -eq 'sample' })
  Record 'sensor-suspend seen' ($sus.Count -gt 0) "count=$($sus.Count)"
  Record 'sensor-resume seen' ($res.Count -gt 0) "count=$($res.Count)"
  if ($sus.Count -gt 0 -and $res.Count -gt 0) {
    $firstResume = $res[0].t
    $lastSuspend = $sus[-1].t
    Record 'suspend precedes resume' ($lastSuspend -le $firstResume) "lastSuspend=$lastSuspend firstResume=$firstResume"
  }
  $recent = @($samples | Where-Object { $_.t -gt $firstResume })
  Record 'samples after resume' ($recent.Count -gt 0) "count=$($recent.Count) (gyro data linkage resumed)"
}

# ── Lifecycle: resume-ready + power.resumed receipts ──────────────────────
if ($Probe -eq 'all') {
  $lc = Get-Content -LiteralPath $LifecycleLog -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
  if ($lc) {
    Record 'resume-ready lifecycle fact' ($lc -match 'power-resume-ready|power\.resume-ready|RESUME_READY') 'lifecycle contains resume-ready'
    Record 'resumed transaction fact' ($lc -match 'power\.resumed|power-resumed') 'lifecycle contains resumed'
  } else {
    Record 'resume-ready lifecycle fact' $false 'lifecycle log empty/missing'
  }
}

$fails = @($results | Where-Object { $_ -like 'FAIL*' })
Write-Host ''
$results | ForEach-Object { Write-Host $_ }
Write-Host ''
if ($fails.Count -gt 0) {
  Write-Host "RESULT: $($fails.Count) FAIL, $($results.Count - $fails.Count) PASS" -ForegroundColor Red
  exit 1
}
Write-Host "RESULT: ALL PASS ($($results.Count))" -ForegroundColor Green
exit 0